### ISSUE TITLE
FormBuilderInput.TYPE_TEXT validates as FormBuilderInput.TYPE_EMAIL

### ISSUE THREAD

**Issue by ckildgypmk** [danvick/flutter_form_builder#1]

**Comment by danvick** [comment]
Thanks for your input @ckildgypmk. I admire how brave you are, trying this package while in version 0.0.1 ;-). I'll be releasing v1.0.0 soon. 
Stay tuned.
Cheers!

**Comment by danvick** [comment]
Closed in v1.0.0
