### ISSUE TITLE
How to supress error messages from TYPE_EMAIL and TYPE_PASSWORD until input finished being entered?

### ISSUE THREAD

**Issue by JesseRMeyer** [danvick/flutter_form_builder#10]
The default behavior is to inform the user that their inputs are invalid as soon as they begin entering their information. This means that every user will see that their email address is not valid until they have almost finished typing it all in. This is inappropriate -- the error should only show when they have finished imputing their information.

So can this default behavior be changed? Or how can I suppress the messages until I deem it is necessary?

**Comment by danvick** [comment]
You could remove `autovalidate` parameter for `FormBuilder` or alternatively set it to `false`.
