### ISSUE TITLE
A FormBuilderLocalizations delegate that supports the ro locale was not found.

### ISSUE THREAD

**Issue by alexcontra** [danvick/flutter_form_builder#1000]
I'm working with an app and I want to have 'en' & 'ro' locales supported by my app, when I integrated the FormBuilder in my app I used to see this warning and I've tried to solve this issue, but I guess it will be better to open this issue to add 'ro' locale to this package.
![Screenshot 2022-03-24 at 15 33 08](https://user-images.githubusercontent.com/59314040/163111608-dda6682c-df67-4d9a-b4e8-732232540204.png)

**Comment by danvick** [comment]
Hi @alexcontra,

We currently don't have Romanian language support for FormBuilderValidators. Localization of the package depends on community support - where individuals in the community help us translate the package into their local languages.

I would encourage you to help us translate the package into your language [using these instructions](https://github.com/danvick/flutter_form_builder/blob/master/packages/form_builder_validators/README.md#localizing-messages) - thus helping yourself and other Romanian language users.

**Comment by alexcontra** [comment]
@danvick I've integrated the translations for Romanian language.
