### ISSUE TITLE
Custom Validation

### ISSUE THREAD

**Issue by muezz** [danvick/flutter_form_builder#1002]
This is more of a request for guidance than a technical issue.

Is it possible, either with `flutter_form_builder` or `form_builder_validators`, to have two dropdown fields where if one item is chosen in the first field and in the second field, you get validation error that says that both values cannot be same?

This error should obviously go away automatically if another option is chosen or the field is cleared.

**Comment by danvick** [comment]
Hi @muezz, 

This should be possible!

Please check out [conditional validation](https://pub.dev/packages/flutter_form_builder#conditional-validation) section of the documentation.

**Comment by muezz** [comment]
Thanks for the reply @danvick 

I did not know this was possible. I assumed that the `validator` only took `FormBuilderValidators` as its argument. I will close this issue/question now.

**Comment by muezz** [comment]
@danvick I replied without trying this first. Although this works, I am coming across one issue so far. If I try the method you showed, I cannot keep using the existing validators like `FormBuilderValidators.required`. Is there a way to work around this?
