### ISSUE TITLE
It looks that the flutter_form_builder is not compatible with fluent-ui.

### ISSUE THREAD

**Issue by step4u** [danvick/flutter_form_builder#1004]
I've tried to use flutter_form_builder FormBuilderTextField in fluent-ui ScaffoldPage.
But I encountered below errors.
It looks the FormBuilderTextField is not compatible with fluent-ui.
Is there any way to fix this?
Or do you have any plan to make it compatible with fluent-ui?

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═════════════════════════════
The following assertion was thrown building TextField(controller:
TextEditingController#efe72(TextEditingValue(text: ┤├, selection: TextSelection.invalid, composing:
TextRange(start: -1, end: -1))), focusNode: FocusNode#8c09b(full_name), enabled: true, decoration:
InputDecoration(labelText: "Full Name"), enableSuggestions: false, dirty, dependencies:
[UnmanagedRestorationScope, MediaQuery], state: _TextFieldState#8aae9):
No Material widget found.
TextField widgets require a Material widget ancestor.
In material design, most widgets are conceptually "printed" on a sheet of material. In Flutter's
material library, that material is represented by the Material widget. It is the Material widget
that renders ink splashes, for instance. Because of this, many material library widgets require that
there be a Material widget in the tree above them.
To introduce a Material widget, you can either directly include one, or use a widget that contains
Material itself, such as a Card, Dialog, Drawer, or Scaffold.
The specific widget that could not find a Material ancestor was:
  TextField
The ancestors of this widget were:
  ...
  FormBuilderTextField
  Column
  _FocusMarker
  Focus
  _FocusTraversalGroupMarker
  ...
The relevant error-causing widget was:
  FormBuilderTextField
FormBuilderTextField:file:///D:/develop/workspace/flutter/mathspace/lib/view/counsel_view.dart:62:13
When the exception was thrown, this was the stack:
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
packages/flutter/src/material/debug.dart 29:7                                                                              <fn>
packages/flutter/src/material/debug.dart 49:12                                                                             debugCheckHasMaterial
packages/flutter/src/material/text_field.dart 1115:12                                                                      build
packages/flutter/src/widgets/framework.dart 4870:27                                                                        build
packages/flutter/src/widgets/framework.dart 4754:15                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4928:11                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                         [_firstBuild]
packages/flutter/src/widgets/framework.dart 4919:11                                                                        [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                         mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4928:11                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                         [_firstBuild]
packages/flutter/src/widgets/framework.dart 4919:11                                                                        [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                         mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 6422:36                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 6433:32                                                                        mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                         [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                         mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4928:11                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                         [_firstBuild]
packages/flutter/src/widgets/framework.dart 4919:11                                                                        [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                         mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                         [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                         mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4928:11                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                         [_firstBuild]
packages/flutter/src/widgets/framework.dart 4919:11                                                                        [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                         mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                         [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                         mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4928:11                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                         [_firstBuild]
packages/flutter/src/widgets/framework.dart 4919:11                                                                        [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                         mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4928:11                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                         [_firstBuild]
packages/flutter/src/widgets/framework.dart 4919:11                                                                        [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                         mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4928:11                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                         [_firstBuild]
packages/flutter/src/widgets/framework.dart 4919:11                                                                        [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                         mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 6284:14                                                                        mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                         [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                         mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                         [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                         mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 6422:36                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 6433:32                                                                        mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 6284:14                                                                        mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 6284:14                                                                        mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                         [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                         mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                         [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                         mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 6422:36                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 6433:32                                                                        mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                         [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                         mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 6284:14                                                                        mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 6284:14                                                                        mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 6284:14                                                                        mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4928:11                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                         [_firstBuild]
packages/flutter/src/widgets/framework.dart 4919:11                                                                        [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                         mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 6284:14                                                                        mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                         [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                         mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                         [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                         mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                        inflateWidget
packages/flutter/src/widgets/framework.dart 3524:20                                                                        updateChild
packages/flutter/src/widgets/framework.dart 6291:14                                                                        update
packages/flutter/src/widgets/framework.dart 3501:14                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4928:11                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4960:5                                                                         update
packages/flutter/src/widgets/framework.dart 3501:14                                                                        updateChild
packages/flutter/src/widgets/framework.dart 6291:14                                                                        update
packages/flutter/src/widgets/framework.dart 3501:14                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4834:5                                                                         update
packages/flutter/src/widgets/framework.dart 3501:14                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4928:11                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4960:5                                                                         update
packages/flutter/src/widgets/framework.dart 3501:14                                                                        updateChild
packages/flutter/src/widgets/framework.dart 6291:14                                                                        update
packages/flutter/src/widgets/framework.dart 3501:14                                                                        updateChild
packages/flutter/src/widgets/framework.dart 6291:14                                                                        update
packages/flutter/src/widgets/framework.dart 3501:14                                                                        updateChild
packages/flutter/src/widgets/framework.dart 6291:14                                                                        update
packages/flutter/src/widgets/framework.dart 3501:14                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 5108:5                                                                         update
packages/flutter/src/widgets/framework.dart 3501:14                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4928:11                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4960:5                                                                         update
packages/flutter/src/widgets/framework.dart 3501:14                                                                        updateChild
packages/flutter/src/widgets/framework.dart 5787:32                                                                        updateChildren
packages/flutter/src/widgets/framework.dart 6445:17                                                                        update
packages/flutter/src/widgets/framework.dart 3501:14                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 5108:5                                                                         update
packages/flutter/src/widgets/framework.dart 3501:14                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 5108:5                                                                         update
packages/flutter/src/widgets/framework.dart 3501:14                                                                        updateChild
packages/flutter/src/widgets/framework.dart 6291:14                                                                        update
packages/flutter/src/widgets/framework.dart 3501:14                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4834:5                                                                         update
packages/flutter/src/widgets/framework.dart 3501:14                                                                        updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                        performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                         rebuild
packages/flutter/src/widgets/framework.dart 4834:5                                                                         update
packages/flutter/src/widgets/framework.dart 3501:14                                                                        updateChild
packages/flutter/src/widgets/layout_builder.dart 138:18                                                                    layoutCallback
packages/flutter/src/widgets/framework.dart 2600:19                                                                        buildScope
packages/flutter/src/widgets/layout_builder.dart 156:5                                                                     [_layout]
packages/flutter/src/rendering/object.dart 1997:59                                                                         <fn>
packages/flutter/src/rendering/object.dart 918:15                                                                          [_enableMutationsToDirtySubtrees]
packages/flutter/src/rendering/object.dart 1997:7                                                                          invokeLayoutCallback
packages/flutter/src/widgets/layout_builder.dart 230:7                                                                     rebuildIfNecessary
packages/flutter/src/widgets/layout_builder.dart 319:5                                                                     performLayout
packages/flutter/src/rendering/object.dart 1731:7                                                                          [_layoutWithoutResize]
packages/flutter/src/rendering/object.dart 887:17                                                                          flushLayout
packages/flutter/src/rendering/binding.dart 497:19                                                                         drawFrame
packages/flutter/src/widgets/binding.dart 883:13                                                                           drawFrame
packages/flutter/src/rendering/binding.dart 363:5                                                                          [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1144:15                                                                        [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1081:9                                                                         handleDrawFrame
packages/flutter/src/scheduler/binding.dart 995:5                                                                          [_handleDrawFrame]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 1011:13           invoke
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 159:5             invokeOnDrawFrame
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/initialization.dart 128:45                 <fn>
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: No Material widget found.
Another exception was thrown: No Material widget found.
Another exception was thrown: No Material widget found.
Another exception was thrown: No Material widget found.
Another exception was thrown: A RenderFlex overflowed by 499183 pixels on the bottom.
Application finished.
Exited (sigterm)

**Comment by danvick** [comment]
FormBuilder's `FormBuilderTextField` makes use of Flutter's `TextFormField` widget, which is a Material component (makes use of Material Design System).

I'm assuming in Fluent UI, you are using `FluentApp` instead of `MaterialApp` as your root widget, which will not work for any widget that depends on the Material design system. 

I'd suggest making a `FormBuilderField` out of Fluent-UI's TextBox instead of `FormBuilderTextField`.

**Comment by step4u** [comment]
> Can be close this issue?

Got it.

**Comment by step4u** [comment]
> FormBuilder's `FormBuilderTextField` makes use of Flutter's `TextFormField` widget, which is a Material component (makes use of Material Design System).
> 
> I'm assuming in Fluent UI, you are using `FluentApp` instead of `MaterialApp` as your root widget, which will not work for any widget that depends on the Material design system.
> 
> I'd suggest making a `FormBuilderField` out of Fluent-UI's TextBox instead of `FormBuilderTextField`.

I got it. Thanks.
