### ISSUE TITLE
handle null value from formbuilderTextfield

### ISSUE THREAD

**Issue by YouSour** [danvick/flutter_form_builder#1008]
hi , i would like to know the right way how to handle null value from formbuilderTextfield , thank in advance .

**Comment by danvick** [comment]
What exactly do you mean by 'handle'? If you need only non-null values from FormBuilderTextField, you may consider using 
a valueTransformer to transform the null to say an empty string.

**Comment by YouSour** [comment]
@danvick what i mean 
Example: i have 2 textfields (**name** [required] and **bio** [optional]) if i don't input anything to bio textfield, i want get data from Form builder like this 
`{name: 'jhon'} `

**Comment by danvick** [comment]
I'd advise massaging the data by yourself otherwise in case you need changes to the returned map.

Or maybe create a PR if possible.

**Comment by YouSour** [comment]
@danvick thank you, solved
