### ISSUE TITLE
programmatically set value on form builder textfield 

### ISSUE THREAD

**Issue by YouSour** [danvick/flutter_form_builder#1012]
hi , i'm doing auto generated Id to set on form builder textfield every time i press on submit button, it will generated a new id , how can i programmatically set a new id that generated on form builder textfield?
i tried this `_formKey.currentState.fields['autoId'].didChange('$autoId');` it isn't work for me

**Comment by WilliamCunhaCardoso** [comment]
Let me see if I understood your scenario

You have a field with a name/id like
FormBuilderField(name: 'first_id');

Then, on pressing a button, you generate a second id, without generating a new field?
So, you are trying to update the aforementioned field using the new id? Expecting something like:
FormBuilderField(name: 'second_id');
?

At this time, it seems the field with new id is not registered in the form. But, may I ask you, why are you changing the id of a field?

**Comment by YouSour** [comment]
@WilliamCunhaCardoso it isn't what i want , i didn't want to change name of the field i need to change the value

**Comment by danvick** [comment]
I haven't been able to reproduce your error. This works for me:

```Dart
FormBuilder(
  key: _formBuilderKey,
  child: FormBuilderTextField(
    name: 'text',
    decoration: const InputDecoration(labelText: 'Text'),
  ),
),
ElevatedButton(
  onPressed: () {
    _formBuilderKey.currentState!.fields['text']
        ?.didChange('New value');
  },
  child: const Text('Change value'),
),
```

**Comment by danvick** [comment]
Kindly confirm that the name of the attribute you are referencing in _formKey.currentState.fields[*] matches the `name` attribute of the `FormBuilderTextField`

**Comment by YouSour** [comment]
@danvick solved by `TextEditingController`
