### ISSUE TITLE
search box in FormBuilderSearchableDropdown not exist in version 8.0.0?

### ISSUE THREAD

**Issue by huongtran84** [danvick/flutter_form_builder#1022]
aftar I upgrade to 8.0.0 I have not seen search box in FormBuilderSearchableDropdown.how do I show it again?

**Comment by danvick** [comment]
Kindly note that the API for [dropdown_search](https://pub.dev/packages/dropdown_search) has changed in the recent versions that are compatible with Flutter 3.

Please refer to the package on what has changed.

**Comment by huongtran84** [comment]
I got it

**Comment by TomTom101** [comment]
@huongtran84 Can you tell what needs to be done to show the search box? Thank you!

**Comment by syahrezafauzi** [comment]
FormBuilderSearchableDropdown(
	items: _items,
	popupProps: PopupProps.menu(showSearchBox: true)
)
