### ISSUE TITLE
There is error in build time due to isFilteredOnline

### ISSUE THREAD

**Issue by ashim-kr-saha** [danvick/flutter_form_builder#1023]
`/Users/ashim/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:173:15: Error: No named parameter with the name 'isFilteredOnline'.
              isFilteredOnline: isFilteredOnline,`

[Reason of this error](https://github.com/salim-lachdhaf/searchable_dropdown/commit/4da39123e03024e1362dd0f1a2d3d935524b03ed#diff-8905c8a5d0a1f4f37a23ac082cf564a7a34799a608ad86628f7eb3e6fe750d56L62)

**Comment by ducdac** [comment]
@ashim-kr-saha downgrade dropdown_search 4.0.1 to 4.0.0

**Comment by Orlyga01** [comment]
After flutter upgrade to 3 and form_builder_extra_fields to 8.0.1 I'm experiencing a similar problem, which was not solved after downgrading dropdown_search to 4.0.0
`/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:173:15: Error: No named parameter with the name 'isFilteredOnline'.
              isFilteredOnline: isFilteredOnline,
  /C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/dropdown_search-4.0.1/lib/dropdown_search.dart:143:3: Context: Found this candidate, but the arguments don't match.
  DropdownSearch({`

**Comment by ashim-kr-saha** [comment]
Yes. It works with 8.1.0
