### ISSUE TITLE
Flutter can't compile after upgrade to flutter 3 and flutter_form_builder to latest version

### ISSUE THREAD

**Issue by Orlyga01** [danvick/flutter_form_builder#1024]
After flutter upgrade to 3 and form_builder_extra_fields to 8.0.1 I'm experiencing a similar problem, which was not solved after downgrading dropdown_search to 4.0.0
`/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:28:9: Error: Type 'DropdownSearchBuilder' not found.
  final DropdownSearchBuilder<T>? dropdownBuilder;
        ^^^^^^^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:31:9: Error: Type 'DropdownSearchBuilderMultiSelection' not found.
  final DropdownSearchBuilderMultiSelection<T>? dropdownBuilderMultiSelection;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:34:9: Error: Type 'DropdownSearchItemAsString' not found.
  final DropdownSearchItemAsString<T>? itemAsString;

        ^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:37:9: Error: Type 'DropdownSearchFilterFn' not found.
  final DropdownSearchFilterFn<T>? filterFn;
        ^^^^^^^^^^^^^^^^^^^^^^

/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:40:9: Error: Type 'DropdownSearchCompareFn' not found.
  final DropdownSearchCompareFn<T>? compareFn;
        ^^^^^^^^^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:60:9: Error: Type 'BeforeChange' not found.

  final BeforeChange<T>? onBeforeChange;
        ^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:63:9: Error: Type 'BeforeChangeMultiSelection' not found.

  final BeforeChangeMultiSelection<T>? onBeforeChangeMultiSelection;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:69:9: Error: Type 'OnItemAdded' not found.
  final OnItemAdded<T>? popupOnItemAdded;
        ^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:72:9: Error: Type 'OnItemRemoved' not found.
  final OnItemRemoved<T>? popupOnItemRemoved;
        ^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:75:9: Error: Type 'DropdownSearchPopupItemBuilder' not found.
  final DropdownSearchPopupItemBuilder<T>? popupSelectionWidget;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:78:9: Error: Type 'ValidationMultiSelectionBuilder' not found.
  final ValidationMultiSelectionBuilder<T?>?
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:82:9: Error: Type 'ValidationMultiSelectionBuilder' not found.
  final ValidationMultiSelectionBuilder<T>? popupCustomMultiSelectionWidget;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:85:9: Error: Type 'DropdownSearchOnFind' not found.
  final DropdownSearchOnFind<T>? asyncItems;
        ^^^^^^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:87:9: Error: Type 'PopupProps' not found.
  final PopupProps<T> popupProps;
        ^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:90:9: Error: Type 'IconButtonProps' not found.
  final IconButtonProps? clearButtonProps;
        ^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:96:9: Error: Type 'IconButtonProps' not found.
  final IconButtonProps? dropdownButtonProps;
        ^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:131:29: Error: Couldn't find constructor 'PopupProps.menu'.
    this.popupProps = const PopupProps.menu(),
                            ^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:28:9: Error: 'DropdownSearchBuilder' isn't a type.
  final DropdownSearchBuilder<T>? dropdownBuilder;
        ^^^^^^^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:31:9: Error: 'DropdownSearchBuilderMultiSelection' isn't a type.
  final DropdownSearchBuilderMultiSelection<T>? dropdownBuilderMultiSelection;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:34:9: Error: 'DropdownSearchItemAsString' isn't a type.
  final DropdownSearchItemAsString<T>? itemAsString;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:37:9: Error: 'DropdownSearchFilterFn' isn't a type.
  final DropdownSearchFilterFn<T>? filterFn;
        ^^^^^^^^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:40:9: Error: 'DropdownSearchCompareFn' isn't a type.
  final DropdownSearchCompareFn<T>? compareFn;
        ^^^^^^^^^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:60:9: Error: 'BeforeChange' isn't a type.
  final BeforeChange<T>? onBeforeChange;
        ^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:63:9: Error: 'BeforeChangeMultiSelection' isn't a type.
  final BeforeChangeMultiSelection<T>? onBeforeChangeMultiSelection;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:69:9: Error: 'OnItemAdded' isn't a type.
  final OnItemAdded<T>? popupOnItemAdded;
        ^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:72:9: Error: 'OnItemRemoved' isn't a type.
  final OnItemRemoved<T>? popupOnItemRemoved;
        ^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:75:9: Error: 'DropdownSearchPopupItemBuilder' isn't a type.
  final DropdownSearchPopupItemBuilder<T>? popupSelectionWidget;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:78:9: Error: 'ValidationMultiSelectionBuilder' isn't a type.
  final ValidationMultiSelectionBuilder<T?>?
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:82:9: Error: 'ValidationMultiSelectionBuilder' isn't a type.
  final ValidationMultiSelectionBuilder<T>? popupCustomMultiSelectionWidget;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:85:9: Error: 'DropdownSearchOnFind' isn't a type.
  final DropdownSearchOnFind<T>? asyncItems;
        ^^^^^^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:87:9: Error: 'PopupProps' isn't a type.

  final PopupProps<T> popupProps;
        ^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:90:9: Error: 'IconButtonProps' isn't a type.
  final IconButtonProps? clearButtonProps;
        ^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:96:9: Error: 'IconButtonProps' isn't a type.
  final IconButtonProps? dropdownButtonProps;
        ^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:172:15: Error: No named parameter with the name 'isFilteredOnline'.
              isFilteredOnline: isFilteredOnline,
              ^^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/dropdown_search-4.0.1/lib/dropdown_search.dart:143:3: Context: Found this candidate, but the arguments don't match.
  DropdownSearch({
  ^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\ngplayground\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\ngplayground\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 23s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)`
When I set dropdown_serach to 4.0.1 this is what I get:
`/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/form_builder_extra_fields-8.0.1/lib/src/fields/form_builder_searchable_dropdown.dart:173:15: Error: No named parameter with the name 'isFilteredOnline'.
              isFilteredOnline: isFilteredOnline,
              ^^^^^^^^^^^^^^^^
/C:/ngplayground/flutter/.pub-cache/hosted/pub.dartlang.org/dropdown_search-4.0.1/lib/dropdown_search.dart:143:3: Context: Found this candidate, but the arguments don't match.
  DropdownSearch({
  ^^^^^^^^^^^^^^`

**Comment by danvick** [comment]
Let me know if this works out

**Comment by Orlyga01** [comment]
Yes it did - Thank you!

**Comment by WilliamCunhaCardoso** [comment]
> Yes it did - Thank you!

Closing issue since the author answered it has been resolved. Thanks for your report!
