### ISSUE TITLE
[flutter_form_builder][BUG] Error: No named parameter with the name 'anchorPoint'

### ISSUE THREAD

**Issue by SalahAdDin** [danvick/flutter_form_builder#1028]
We recently updated this package as we released there were a new version.

Now, trying to compiled the project and test it, we are getting this error:
```
Running Gradle task 'assembleDebug'...
../../.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-7.2.0/lib/src/fields/form_builder_date_time_picker.dart:355:7: Error: No named parameter with the name 'anchorPoint'.
      anchorPoint: widget.anchorPoint,
      ^^^^^^^^^^^
/opt/flutter/packages/flutter/lib/src/material/date_picker.dart:133:19: Context: Found this candidate, but the arguments don't match.
Future<DateTime?> showDatePicker({
                  ^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-7.2.0/lib/src/fields/form_builder_date_time_picker.dart:373:7: Error: No named parameter with the name 'anchorPoint'.
      anchorPoint: widget.anchorPoint,
      ^^^^^^^^^^^
/opt/flutter/packages/flutter/lib/src/material/time_picker.dart:2413:20: Context: Found this candidate, but the arguments don't match.
Future<TimeOfDay?> showTimePicker({
                   ^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script '/opt/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/opt/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 50s
Exception: Gradle task assembleDebug failed with exit code 1

```

What's the problem?

```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.10.5, on Manjaro Linux 5.15.38-1-MANJARO, locale en_GB.UTF-8)
    • Flutter version 2.10.5 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (hace 5 semanas), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/mehmeth/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Android Studio (version 2021.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 67.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (2 available)
    • MI 9 (mobile) • da22004 • android-arm64  • Android 10 (API 29)
    • Chrome (web)  • chrome  • web-javascript • Chromium 101.0.4951.64 Manjaro Linux

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by SalahAdDin** [comment]
@danvick [It seems you added that option to the widget](https://github.com/danvick/flutter_form_builder/commit/c5addf00c577deed25326c9ca895f09f92fb732d) but you didn't add it to the functions for **Date** and **Time** pickers.

**Comment by SalahAdDin** [comment]
@danvick [It seems you added that option to the widget](https://github.com/danvick/flutter_form_builder/commit/c5addf00c577deed25326c9ca895f09f92fb732d) but you didn't add it to the functions for **Date** and **Time** pickers.

**Comment by josephkoroma01** [comment]
How did you solve this issue? I am facing the same problem here.

**Comment by SalahAdDin** [comment]
> How did you solve this issue? I am facing the same problem here.

You have two ways: you can't downgrade this package or you can remove all code lines with `anchorPoint` as and argument.

**Comment by danvick** [comment]
Downgrade the package to pre 7.2 if you're not on Flutter 3 yet

**Comment by josephkoroma01** [comment]
I

> Downgrade the package to pre 7.2 if you're not on Flutter 3 yet

I am already on Flutter 3.  But I am trying @SalahAdDin suggestion soon

**Comment by mdeandrea-mrmilu** [comment]
If 7.2 is a version with breaking changes, it should be explicit in the changelog

**Comment by SalahAdDin** [comment]
> If 7.2 is a version with breaking changes, it should be explicit in the changelog

I guess the breaking changes are related to the new Flutter version.

**Comment by fongfiafia** [comment]
您好，来件已收到，我会尽快给您回复。

**Comment by milkyway044** [comment]
+1

**Comment by GenPingYuan** [comment]
Please fix this problem quickly, it will really 3Q

**Comment by SalahAdDin** [comment]
> Please fix this problem quickly, it will really 3Q

It seems to be related to  Flutter 3, i recommend to downgrade it.

**Comment by WilliamCunhaCardoso** [comment]
Remove `^` from `form_builder` packages in `pubspec`, then run pub get again. It will help.

**Comment by deandreamatias** [comment]
- With Flutter < 3.0.0, need use package version 7.1.1 and below
- With Flutter >= 3.0.0, need use package version 7.2.0 and hereinafter

This is the solution to this error. Unfortunately this breaking change should be manage otherwise, but with new versions we try that this breaking changes don't happens again or would be more gradatives and clear.

Some collaborators work to improvements in this repo to avoid situations like this. You can see here #1038 

For now, this issue will be closed
