### ISSUE TITLE
Date picker is automatically shown once again on click of ok button

### ISSUE THREAD

**Issue by krishnakirana** [danvick/flutter_form_builder#103]

**Comment by danvick** [comment]
Hi @krishnakirana,
Could you kindly clarify your issue.

**Comment by danvick** [comment]
KIndly confirm that this issue is fixed in version 3.5.0

**Comment by katlego-alphains** [comment]
Hi

I am having the same issue.

It seems that there is still an instance of the datepicker running when I click OK, although on the Form in the background you can very clearly see that the date HAS been set. 

I tried using Navigator.pop(context) but there has been no luck with this. I hope this clarifies the above a little better. 

Thanks in advance.

**Comment by danvick** [comment]
This issue was fixed as of version 3.5.2. Thanks for your contribution guys.
