### ISSUE TITLE
FormBuilderRangeSlider should not require an initialValue

### ISSUE THREAD

**Issue by grundid** [danvick/flutter_form_builder#1046]
As most form fields FormBuilderRangeSlider should not require to define an initialValue during creation of the widget. The initialValue can come from FormBuilder.initialValue.

**Comment by deandreamatias** [comment]
Basically, change this property to nullable https://github.com/danvick/flutter_form_builder/blob/1fbdda779166d91ead010878884a2bae5605f5d9/packages/flutter_form_builder/lib/src/fields/form_builder_range_slider.dart#L113

**Comment by grundid** [comment]
Exactly. Do you need a PR for this?

**Comment by danvick** [comment]
The reason why `initialValue` was made to be required is that Flutter's `RangeSlider` widget's `values` attribute is required. 

But we since made the default initialValue to take the bounds of the range, the attribute can be made nullable.

**Comment by danvick** [comment]
We'd appreciate a PR @grundid. Thanks
