### ISSUE TITLE
initial value on FormBuilderFilterChip() by FormBuilder()

### ISSUE THREAD

**Issue by YouSour** [danvick/flutter_form_builder#1052]
## Environment

**Package name: flutter_form_builder**  

## Describe your question
hi , i'm trying to initial value on FormBuilderFilterChip() by FormBuilder(), it doesn't work , but if i initial value on FormBuilderFilterChip() directly it works, please check it

**Comment by deandreamatias** [comment]
Hi @YouSour 
This situation is more like a bug.
Can you be share this info please

- **Package version:**
- **Platform:**
- **Device information:**
- A sample code

Thanks

**Comment by YouSour** [comment]
@deandreamatias nvm, i'm happy to help 😄
