### ISSUE TITLE
Error: No named parameter with the name 'anchorPoint'

### ISSUE THREAD

**Issue by tailn804** [danvick/flutter_form_builder#1055]
## Environment

**Package name:**  flutter_form_builder
**Package version:**  ^7.3.0
**Platform:** Web
**Flutter information:** Flutter 2.10.5

## Images   
<img width="1209" alt="Screen Shot 2022-06-23 at 09 44 07" src="https://user-images.githubusercontent.com/104020709/175196052-6ce17ace-dedc-492a-ba70-ce01a0fd0be1.png">

**Comment by deandreamatias** [comment]
Duplicated from #1028 
Take a look in [this comment](https://github.com/danvick/flutter_form_builder/issues/1028#issuecomment-1156025018) to solution and explication
