### ISSUE TITLE
FormBuilderCustomField does not provide the option to set initialValue 

### ISSUE THREAD

**Issue by kapilnarula** [danvick/flutter_form_builder#106]
FormBuilderCustomField does not provide the option to set initialValue. This is a critical need of many applications.
Would truly appreciate a quick fix.

**Comment by danvick** [comment]
Hi @kapilnarula,
Thank for your contribution to this package. 

That seems to have been a bit of an oversight on my part. Kindly try out v3.3.4 which has a fix for that.

Alternatively, you could still add `initialValue` to the `FormField` class of `formField` attribute
