### ISSUE TITLE
alwaysUse24HourFormat:true is not working on FormBuilderDateTimePicker.

### ISSUE THREAD

**Issue by yeasin50** [danvick/flutter_form_builder#1068]
## Environment

**Package name:**  flutter_form_builder
**Package version:**  7.3.1
**Platform:**  Web
**Device information:**  Google Chrome

## Description
I've used `alwaysUse24HourFormat: true`  and `timePickerInitialEntryMode: TimePickerEntryMode.input,`  inside `FormBuilderDateTimePicker`  in order to take 24h format time by user type. But It shows invalid time error.

**Expected behavior:** 
By using ` alwaysUse24HourFormat: true,` I think  it should be able to take 24hour format time by user input.

**Current behavior:**
![image](https://user-images.githubusercontent.com/46500228/176667807-d68b6873-6dec-45a3-9c24-4f2781927808.png)

## Steps to reproduce

 ```dart
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';

void main() {
  runApp(const MaterialApp(
    debugShowCheckedModeBanner: false,
    home: HomePage(),
  ));
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final _formKey = GlobalKey<FormBuilderState>();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Column(
      children: [
        FormBuilder(
          key: _formKey,
          child: Column(
            children: [
              FormBuilderDateTimePicker(
                name: 'name',
                initialValue: DateTime.now(),
                initialDate: DateTime.now(),
                initialEntryMode: DatePickerEntryMode.input,
                alwaysUse24HourFormat: true,
                timePickerInitialEntryMode: TimePickerEntryMode.input,
                decoration: const InputDecoration(
                  labelText: 'Appointment Time',
                ),
                initialTime: const TimeOfDay(hour: 14, minute: 0),
              ),
            ],
          ),
        )
      ],
    ));
  }
}
```

I was following [this](https://stackoverflow.com/q/72814475/10157127) question, but I am not able to find any use case of `alwaysUse24HourFormat` inside `form_builder_date_time_picker.dart`

**Comment by deandreamatias** [comment]
Duplicated from #826
