### ISSUE TITLE
Support disabled attribute in the field control

### ISSUE THREAD

**Issue by huzhiren** [danvick/flutter_form_builder#11]
Sometimes you need to disable certain fields based on other field's value.

**Comment by danvick** [comment]
This idea is in the works.
Thank you for your feedback.

Cheers

**Comment by danvick** [comment]
Closed by release v1.4.0. We'll use `readonly: true` on either the controls or entire form

**Comment by SogoGolf** [comment]
ive not been able to disable any of these controls. was this fixed/added or is it still on the todo list ?
