### ISSUE TITLE
FormBuilderCheckboxList error onTap : UnmodifiableListBase.add

### ISSUE THREAD

**Issue by dzluppin** [danvick/flutter_form_builder#112]
Hey, this plugin is actually a life saver. But I have a problem when using FormBuilderCheckboxList inside FutureBuilder. All checkbox not work when clicked.

Here's my code : 

> FutureBuilder(
> builder: (BuildContext context, AsyncSnapshot<List<ArtMasterV>> snapshot) {
>                     if (snapshot.hasData) {
>                       return FormBuilderCheckboxList(
>                         attribute: 'artCategory',
>                         leadingInput: true,
>                         options: snapshot.data
>                             .where((test) => test.tipe)
>                             .map((dt) => FormBuilderFieldOption(value: dt.id.id, label: dt.title))
>                             .toList(),
>                       );
>                     } else if (snapshot.hasError) {
>                       return Center(
>                         child: Text(snapshot.error),
>                       );
>                     }
>                     return Center(
>                       child: ListTile(
>                         leading: CircularProgressIndicator(),
>                         title: Text('Loading Category...'),
>                       ),
>                     );
>                   },
>                   future: _bloc.categoryByARTType(widget.form.tipe, widget.form.objectObserv),
>                 )

Then, when i click some checkbox, flutter throw this error :

> `flutter: Unsupported operation: Cannot add to an unmodifiable list
> flutter: 
> Handler: "onTap"
> Recognizer: TapGestureRecognizer#3f16e
> flutter: 
> #0      UnmodifiableListBase.add (dart:_internal/list.dart:114:5)
> #1      _FormBuilderCheckboxListState._checkbox.<anonymous closure> (package:flutter_form_builder/src/fields/form_builder_checkbox_list.dart:78:27)`

* ps : I don't know how to write code in issue submission so i used quote instead. Sorry.

**Comment by danvick** [comment]
Hi @dzluppin,
Thanks for making this known. 
A fix is in the works and will be published in a few.

Your feedback is much appreciated.

**Comment by danvick** [comment]
Kindly confirm that this bug has been addressed in `v3.4.0`.
Feel free to reopen this issue if not.
