### ISSUE TITLE
NoSuchMethodError using DateTimePicker with v.3.4.0

### ISSUE THREAD

**Issue by mattf80** [danvick/flutter_form_builder#114]
I just upgraded to `v3.4.0` but now when using the FormBuilderDateTimePicker as per the docs:

```
          FormBuilderDateTimePicker(
            attribute: "date",
            inputType: InputType.date,
            format: DateFormat("yyyy-MM-dd"),
            decoration:
                InputDecoration(labelText: "Appointment Time"),
          ),
```

It throws an error:

> NoSuchMethodError: The getter 'weekday' was called on null. 
> Receiver: null
> Tried calling weekday

My code was unchanged from upgrading to 3.4.0 so has something changed in the latest release?

**Comment by danvick** [comment]
Could you kindly post the whole stacktrace

**Comment by mattf80** [comment]
I/flutter ( 7950): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 7950): The following NoSuchMethodError was thrown building _FormScope:
I/flutter ( 7950): The getter 'weekday' was called on null.
I/flutter ( 7950): Receiver: null
I/flutter ( 7950): Tried calling: weekday
I/flutter ( 7950):
I/flutter ( 7950): When the exception was thrown, this was the stack:
[38;5;244mI/flutter ( 7950): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:50:5)[39;49m
[38;5;248mI/flutter ( 7950): #1      _DateFormatPatternField.formatDayOfWeek[39;49m
[38;5;248mI/flutter ( 7950): #2      _DateFormatPatternField.formatField[39;49m
[38;5;248mI/flutter ( 7950): #3      _DateFormatPatternField.format[39;49m
[38;5;248mI/flutter ( 7950): #4      DateFormat.format.<anonymous closure>[39;49m
[38;5;244mI/flutter ( 7950): #5      List.forEach  (dart:core-patch/growable_array.dart:278:8)[39;49m
[38;5;248mI/flutter ( 7950): #6      DateFormat.format[39;49m
[38;5;248mI/flutter ( 7950): #7      _FormBuilderDateTimePickerState.initState[39;49m
[38;5;244mI/flutter ( 7950): #8      StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #9      ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #10     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #11     MultiChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #12     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #13     Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #14     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #15     Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #16     ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #17     ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #18     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #19     Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #20     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #21     Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #22     ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #23     StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #24     ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #25     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #26     Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #27     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #28     Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #29     ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #30     StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #31     ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #32     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #33     Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #34     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #35     Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #36     ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #37     StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #38     ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #39     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #40     Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #41     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #42     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #43     Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #44     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #45     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #46     Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #47     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #48     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #49     Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #50     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #51     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #52     Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #53     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #54     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #55     Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #56     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #57     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #58     Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #59     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #60     Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #61     ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #62     StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #63     ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #64     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #65     Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #66     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #67     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #68     Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #69     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #70     Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #71     ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #72     ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #73     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #74     Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #75     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #76     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #77     Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #78     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #79     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #80     Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #81     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #82     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #83     Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #84     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #85     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #86     Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #87     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #88     Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #89     ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #90     ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #91     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #92     Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #93     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #94     Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #95     ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #96     StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #97     ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #98     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #99     Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #100    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #101    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #102    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #103    StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #104    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #105    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #106    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #107    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #108    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #109    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #110    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #111    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #112    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #113    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #114    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #115    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #116    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #117    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #118    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #119    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #120    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #121    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #122    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #123    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #124    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #125    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #126    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #127    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #128    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #129    ParentDataElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #130    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #131    MultiChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #132    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #133    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #134    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #135    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #136    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #137    StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #138    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #139    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #140    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #141    ComponentElement.performRebuild[39;49m
V/InputMethodManager( 7950): Starting input: tba=android.view.inputmethod.EditorInfo@e88fa15 nm : com.frowemetheus.expense_master_app ic=io.flutter.plugin.editing.InputConnectionAdaptor@dc3112a
I/InputMethodManager( 7950): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport( 7950): Input channel constructed: fd=94
D/InputTransport( 7950): Input channel destroyed: fd=112
D/InputMethodManager( 7950): ISS - flag : 0Pid : 7950 view : com.frowemetheus.expense_master_app
D/ViewRootImpl@c10a706[MainActivity]( 7950): MSG_RESIZED: ci=Rect(0, 96 - 0, 1128) vi=Rect(0, 96 - 0, 1128) or=1
D/ViewRootImpl@c10a706[MainActivity]( 7950): Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x1 surface={isValid=true 495832121856} surfaceGenerationChanged=false
[38;5;244mI/flutter ( 7950): #142    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #143    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #144    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #145    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #146    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #147    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #148    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #149    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #150    StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #151    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #152    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #153    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #154    SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #155    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #156    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #157    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #158    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #159    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #160    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #161    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #162    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #163    SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #164    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #165    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #166    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #167    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #168    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #169    StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #170    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #171    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #172    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #173    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #174    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #175    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #176    StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #177    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #178    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #179    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #180    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #181    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #182    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #183    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #184    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #185    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #186    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #187    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #188    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #189    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #190    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #191    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #192    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #193    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #194    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #195    StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #196    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #197    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #198    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #199    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #200    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #201    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #202    StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #203    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #204    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #205    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #206    SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #207    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #208    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #209    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #210    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #211    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #212    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #213    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #214    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #215    SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #216    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #217    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #218    SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #219    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #220    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #221    SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #222    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #223    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #224    SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #225    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #226    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #227    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #228    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #229    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #230    StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #231    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #232    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #233    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #234    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #235    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #236    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #237    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #238    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #239    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #240    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #241    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #242    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #243    StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #244    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #245    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #246    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #247    SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #248    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #249    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #250    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #251    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #252    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #253    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #254    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #255    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #256    SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #257    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #258    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #259    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #260    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #261    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #262    StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #263    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #264    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #265    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #266    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #267    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #268    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #269    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #270    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #271    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #272    SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #273    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #274    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #275    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #276    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #277    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #278    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #279    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #280    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #281    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #282    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #283    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #284    StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #285    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #286    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #287    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #288    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #289    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #290    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #291    StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 7950): #292    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 7950): #293    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 7950): #294    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #295    RenderObjectElement.updateChildren[39;49m
[38;5;244mI/flutter ( 7950): #296    MultiChildRenderObjectElement.update[39;49m
[38;5;244mI/flutter ( 7950): #297    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #298    _TheatreElement.update[39;49m
[38;5;244mI/flutter ( 7950): #299    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #300    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #301    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #302    StatefulElement.update[39;49m
[38;5;244mI/flutter ( 7950): #303    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #304    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #305    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #306    ProxyElement.update[39;49m
[38;5;244mI/flutter ( 7950): #307    _InheritedNotifierElement.update[39;49m
[38;5;244mI/flutter ( 7950): #308    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #309    SingleChildRenderObjectElement.update[39;49m
[38;5;244mI/flutter ( 7950): #310    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #311    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #312    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #313    StatefulElement.update[39;49m
[38;5;244mI/flutter ( 7950): #314    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #315    SingleChildRenderObjectElement.update[39;49m
[38;5;244mI/flutter ( 7950): #316    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #317    SingleChildRenderObjectElement.update[39;49m
[38;5;244mI/flutter ( 7950): #318    Element.updateChild[39;49m
[38;5;244mI/flutter ( 7950): #319    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 7950): #320    Element.rebuild[39;49m
[38;5;244mI/flutter ( 7950): #321    BuildOwner.buildScope[39;49m
[38;5;244mI/flutter ( 7950): #322    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame[39;49m
[38;5;244mI/flutter ( 7950): #323    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback[39;49m
[38;5;244mI/flutter ( 7950): #324    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback[39;49m
[38;5;244mI/flutter ( 7950): #325    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame[39;49m
[38;5;244mI/flutter ( 7950): #326    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame[39;49m
[38;5;244mI/flutter ( 7950): #330    _invoke  (dart:ui/hooks.dart:236:10)[39;49m
[38;5;244mI/flutter ( 7950): #331    _drawFrame  (dart:ui/hooks.dart:194:3)[39;49m
I/flutter ( 7950): (elided 3 frames from package dart:async)
I/flutter ( 7950): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 7950): Another exception was thrown: NoSuchMethodError: The getter 'weekday' was called on null.

**Comment by danvick** [comment]
Thanks for catching this early.
v3.4.1 is live with the fix.

Cheers!

**Comment by mattf80** [comment]
Confirmed as fixed, thanks for doing it so quickly!
