### ISSUE TITLE
initialDate Value Not Being Used

### ISSUE THREAD

**Issue by runedrune** [danvick/flutter_form_builder#116]
To test I used these values:

```
    FormBuilderDateTimePicker(
    firstDate: DateTime.now(),
    initialDate: DateTime.now().add(Duration(days: 30)),
```

By my understanding the calendar should start from the firstDate (Aug 23rd) which it does. But it should open up one month later (Sept 23rd) but it shows August 23rd when it opens up. Am I doing something wrong? On v3.4.1.

```
[✓] Flutter (Channel dev, v1.9.3, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.37.1)
[✓] Connected device (1 available)

• No issues found!
```

EDIT: Looks like it was reported and fixed before. But I don't think it was fixed then.

**Comment by runedrune** [comment]
Duplicate of #108

**Comment by danvick** [comment]
Hi @runedrune,
To set the initial value of the field, use `initialValue`.

The `initialDate` attribute was meant to be used as the default date in DatePicker dialog. It will soon be deprecated and removed as it causes confusion.

**Comment by runedrune** [comment]
Hey @danvick,
Thanks for the reply. I have initialValue set but when I open the datepicker dialog it default to DateTime.now(). That's why I was trying to set initialDate.

Like if I set initialValue to September 6th 2020 and then click the datepicker, it'll open on today's date and then you have to navigate all the way to Sept 6th 2020.

**Comment by danvick** [comment]
I'm aware of this and have worked on the issue. Will be fixed in the next release coming very soon

**Comment by runedrune** [comment]
Oh awesome. Thanks.

**Comment by danvick** [comment]
Hi @runedrune,
Version 3.5.0 is out. Contains fix for this.
Kindly confirm that the issue is fixed.

**Comment by runedrune** [comment]
Hey @danvick 
It's actually not working at all now. After I select date and time, it shows the picker again. And after I select it again, it closes and the date and time doesn't get set.

**Comment by danvick** [comment]
Thanks for the feedback, let me check it out.

**Comment by danvick** [comment]
I'm unable to reproduce - but I see you are using a later version of Flutter on dev Channel.
I'll try testing with that.

**Comment by runedrune** [comment]
@danvick I'm actually not using that version of flutter anymore. I changed to the stable branch.

**Comment by danvick** [comment]
Could you kindly open this on a separate issue. Thanks in advance.

**Comment by runedrune** [comment]
Done.
