### ISSUE TITLE
Only Show 1 Form at a Time with OnChange Not Working & Not Saving

### ISSUE THREAD

**Issue by CedYF** [danvick/flutter_form_builder#117]
I have a list of 3 FormBuilderRadio.

I only want to show one a time so I'm wrapping them in a visibility widget.

But when I use the onChange function to change the visibility, it doesn't save the value of the Radio that the user selected.

the onChange seems to replace saving the value...

Is there anyway to fix this?

**Comment by danvick** [comment]
Hi,
The form value is usually saved when the `save()` function is called. 
You could invoke the save function within your onChange so that the value is committed.

**Comment by danvick** [comment]
> Hi,
> The form value is usually saved when the `save()` function is called.
> You could invoke the save function within your onChange so that the value is committed.

Hi @CedYF,
Has this been of any help? Should we close this issue?
