### ISSUE TITLE
How to add onChanged to DropDownlist? crash happening in dropdown

### ISSUE THREAD

**Issue by neenabastin123** [danvick/flutter_form_builder#119]
I/flutter ( 5339): 'package:flutter/src/material/dropdown.dart': Failed assertion: line 608 pos 15: 'items == null ||
I/flutter ( 5339): items.isEmpty || value == null || items.where((DropdownMenuItem<T> item) => item.value ==
I/flutter ( 5339): value).length == 1': is not true.

**Comment by danvick** [comment]
Hi @neenabastin123 / @dhsont,
This assertion is not part of the package, rather in Flutter. This shows that your initial value for the Dropdown is not part of the list of options you've provided as `DropdownMenuItem`s.

Feel free to reopen this issue if you feel that this issue has been wrongly closed.
