### ISSUE TITLE
DateTimePicker show up twice

### ISSUE THREAD

**Issue by wiseideal** [danvick/flutter_form_builder#125]
just updated ver 3.5.0 found this issure, when click at the datetime field, picker dialog show up for two times.Same code works fine under 3.4.1

**Comment by danvick** [comment]
Hi @wiseideal,
Kindly use v3.5.1 which has a fix for the issue.

**Comment by wiseideal** [comment]
/Users/wiseideal/Documents/flutter/bin/flutter --no-color packages get
Running "flutter pub get" in hello_flutter...                   
Because hello_flutter depends on flutter_form_builder 3.5.1 which doesn't match any versions, version solving failed.
pub get failed (1)


I cant find this version
