### ISSUE TITLE
Updated App asserts FormBuilderDateTimePicker 

### ISSUE THREAD

**Issue by jamiethain** [danvick/flutter_form_builder#127]
On at least version 3.50 update the field firstDate now must be initialized or the field asserts! 

This is a new change, and I think firstDate should just default to 01/01/0001. 

> 
 '!initialDate.isBefore(firstDate)': initialDate must be on or after firstDate

**Comment by danvick** [comment]
Well noted @jamiethain. 

I, however, doubt if this is a new change the `firstDate` for now defaults to start of the year 1900 and `lastDate` defaults to the year 2100.

As a temporary measure, kindly set the `firstDate` to fit your needs.

**Comment by jamiethain** [comment]
This is a relatively new change it was not this way as of 3.4.1 which is the last version I used. 

I had done an update and was demoing it did an Assert that was not there before. I fixed it in like five seconds with a workaround, no issue, but I posted it so you would know.
