### ISSUE TITLE
Slider can be positioned so .0000000000001 appears. 

### ISSUE THREAD

**Issue by jamiethain** [danvick/flutter_form_builder#128]
Writing a controller for the slider it can be positioned where .999999999999 or .0000000001 appears. 

Did a work around to call a function that does round. 
```

  void _setValue(val)
  {
    num valNumber =  num.parse(val.toString());
    valNumber = valNumber.round();
    _valController.text = valNumber.toString();  
  }
```
![Screen Shot 2019-09-03 at 2 10 46 PM](https://user-images.githubusercontent.com/52176376/64197869-1f0d0600-ce55-11e9-8075-740e79619e99.png)

One fix should be to add universal round. (not tested)  

```
number universalRound (num number){
  numDecimals = (number - number.toInt()).toString.length().clamp(0,10); 
  divisor = 10 ^ numDecimals; 

  // multiply by number of decimals add .5 then round then divide by the number of decimals and throw away the remainder. 
  number = (((number * divisor) + .5).round()) ~/ divisor) ;
return number; 

Something like that ... 
```

**Comment by danvick** [comment]
Hello @jamiethain,
KIndly use `divisions` attribute to set the number of divisions on the slider to avoid decimals if you don't need them.

**Comment by jamiethain** [comment]
The divisors is already set at 200. It is not giving me a decimal point, it
is giving me 15 decimal points...

FormBuilderSlider(
                      attribute: "slider",
                      validators: [FormBuilderValidators.min(6)],
                      onChanged: (val){
                           // _bidController.text = val;
                                _setBidValue(val);
                            },
                      min: 0.0,
                      max: 10000.0,
                      initialValue: 200.0,
                      divisions: 200,
                      activeColor: Colors.red,
                      inactiveColor: Colors.pink[100],
                      decoration: InputDecoration(
                        labelText: "Bid in Elan",
                      ),
                    ),
