### ISSUE TITLE
How to display error border without error text?

### ISSUE THREAD

**Issue by lee-40square** [danvick/flutter_form_builder#132]
I'd like to be able to show the error border without showing any error text. When I do something like 
```
 validators: [
    FormBuilderValidators.required(errorText: null),
  ],
```
the error border no longer works.

**Comment by danvick** [comment]
Hi @lee-40square,
I'm afraid that's not how Flutter's `FormField` works. A null value for `errorText` essentially means that validation is successful and a String means validation has failed.

I, however, get your point - currently, the feature to hide the validation error is not present. This may be considered in the next major version.

**Comment by atiqsamtia** [comment]
@lee-40square, for now, you can use an empty string for the errorText
```
 validators: [
    FormBuilderValidators.required(errorText: ''),
  ],
```

**Comment by danvick** [comment]
> @lee-40square, for now, you can use an empty string for the errorText
> 
> ```
>  validators: [
>     FormBuilderValidators.required(errorText: ''),
>   ],
> ```

This will have to work for now.
