### ISSUE TITLE
Multiple Drop down Select

### ISSUE THREAD

**Issue by nousath** [danvick/flutter_form_builder#133]
Dear team,
           if possible create Multiple Drop down Select ?

**Comment by danvick** [comment]
Hi @nousath,
Do you mean a DropDown where you can select multiple values? 
If so, then kindly have a look at `FormBuilderChipsInput` which does something similar.

**Comment by nousath** [comment]
okay bro thank you...

i Love it is package

**Comment by nousath** [comment]
i have one more question how to set new initialvalue in fields

**Comment by danvick** [comment]
> okay bro thank you...
> 
> i Love it is package

I'm glad you love it.

**Comment by danvick** [comment]
> i have one more question how to set new initialvalue in fields after load

That's currently impossible in Flutter currently, you'll have to rebuild the Form to change the `initialValue`s
