### ISSUE TITLE
Problem FormBuilderValidators.required

### ISSUE THREAD

**Issue by cmregazzo** [danvick/flutter_form_builder#137]
Good Morning,
I have a problem.
When using auto validate = true, and I have FormBuilderValidators.required validation, when the screen loads, the FormBuilderValidators.required error message is already triggered.

Is there any way to trigger validation only when you start typing in the field, or when you trigger saveAndValidate, keeping autovalidate = true?

Thank you very much and congratulations for your work.

Cristian Regazzo

**Comment by danvick** [comment]
Hi @cmregazzo,
I'm afraid this is the default behavior of Flutter `Form`. I'm working to have it fixed in the next version of the package. 

Thanks for your patience.

**Comment by cmregazzo** [comment]
Good night, 

Thank you very much for the prompt reply. 

Sorry for the inconvenience, but would you have a forecast for such an improvement? 

Thanks. 

Cristian Regazzo

**Comment by cmregazzo** [comment]
Good night,

Thank you very much for the prompt reply.

Sorry for the inconvenience, but would you have a forecast for such an improvement?

Thanks.

Cristian Regazzo

**Comment by cmregazzo** [comment]
Good afternoon danvick,

Verify that the Issue has ended.

What was the solution adopted to solve the problem mentioned in it?

Thanks.

Cristian Regazzo
