### ISSUE TITLE
Is it possible to have a hidden field or a display field?

### ISSUE THREAD

**Issue by wyxcoder** [danvick/flutter_form_builder#139]
I want to show a Total somewhere, for example, I have two Select and a summary to show the total of the two selected value, like

horizontalSelect 1 (attribute:a) => 20
horizontalSelect 2 (attribute:b) => 30
The total is 50

How can I have a widget to show the three line, the ideal way is have a third form field with attribute c and value set to 50, so when I submt, I can submit value like
{ "a":20, "b":30", "c":50}

Thanks

**Comment by danvick** [comment]
Hi @wyxcoder,
You could build your own custom `FormBuilderField` for this scenario.
Kindly refer [here](https://github.com/danvick/flutter_form_builder#building-your-own-custom-field) on how to construct a custom field

**Comment by atiqsamtia** [comment]
The Easy way would be to add a TextField with readOnly flag to true.
```
FormBuilderTextField(
            readOnly: true,
            attribute: "c",
            decoration: InputDecoration(labelText: "Total"),
          ),
```
