### ISSUE TITLE
Can not change field value in form

### ISSUE THREAD

**Issue by huzhiren** [danvick/flutter_form_builder#14]
There is no way to change the field value once they are created, I have create a form with fields initially, then some user interaction will change the status, but all the fields remain the same regardless that I call setState(), in the build function I can see the status data have been changed.

Looking into source code, it looks like the field control state is not recreated and is associated with the attribute as key.

**Comment by danvick** [comment]
Noted. Working on that.
Sorry for the late response.

**Comment by huzhiren** [comment]
The field widgets are stateful widgets, so you can't change the state from the parent widget, I think a callback would serve this purpose.

**Comment by danvick** [comment]
Yes. Kindly use a `StatefulWidget`. 

This is a known issue with stateless widget but I haven't given it much priority since in most cases the form is used within a stateful widget in order to collect data after submission.

Thanks for your contribution, I'll find time to look into it.

**Comment by 926** [comment]
@danvick thank but it is already in a StatefulWidget.
Please look at screenshot below
Would a video be of any help ?
![Screen Shot 2019-04-24 at 12 29 38](https://user-images.githubusercontent.com/14161798/56659491-cd759300-668c-11e9-8c9c-35e84a1d43ca.png)
