### ISSUE TITLE
How to set value of another field?

### ISSUE THREAD

**Issue by wyxcoder** [danvick/flutter_form_builder#140]
Seems didChange works for dropdown, but not TextField, looks like the code doesn't handle to set text on the controller

**Comment by sidharthpatnaik** [comment]
Any idea how to work on TextFields ?

**Comment by danvick** [comment]
Hi @wyxcoder 
Currently, this feature is not working so well. We can change the underlying value of a field using `FormField.didChange` but for most fields, the change won't propagate to the UI.

I'm planning to have this feature fully functional in the next major version (4.0.0) which will be an overhaul of the package.

**Comment by sidharthpatnaik** [comment]
My use case is with FutureBuilder, and with FutureBuilder if I use setstate(), it just reloads, is there any other way i can set the value in TextField ?

**Comment by danvick** [comment]
For a TextField, the best option is to use a TextEditing controller to set its value programmatically.
