### ISSUE TITLE
Can't instantiate FormBuilderTypeAhead with custom controller

### ISSUE THREAD

**Issue by taigfs** [danvick/flutter_form_builder#144]
I'm trying to build a instance of FormBuilderTypeAhead with a custom controller, but it breaks at `flutter_form_builder/src/fields/form_builder_typeahead.dart:173:32`. 

Apparently the package is not initializing the variable `_typeAheadController` if a custom controller is provided.

My code is as follows:

    

    var _controller = TextEditingController(text: "");

    return FormBuilderTypeAhead(
      attribute: "city",
      controller: _controller,
      decoration: InputDecoration(
        hintText: 'City',
        labelText: 'City',
      ),
      itemBuilder: (context, suggestion) {
        return ListTile(
          title: Text(suggestion.label),
        );
      },
      transitionBuilder: (context, suggestionsBox, controller) {
        return suggestionsBox;
      },
      selectionToTextTransformer: (MOption suggestion) {
        return suggestion.toString();
      },
      suggestionsCallback: (pattern) async {
        var s = CitiesService.getOptions(pattern);
        s.add(MOption(label: 'Create $pattern...', value: -1));
        return s;
      },
      onSuggestionSelected: (suggestion) {
        print(suggestion.toString());
      },
    );

**Comment by sidharthpatnaik** [comment]
Is there any workaround for the same ?

**Comment by sidharthpatnaik** [comment]
> Is there any workaround for the same ?

Apparently there is a patch, in _selectionToTextTransformer_ attribute
`selectionToTextTransformer: (dynamic val) {
        //you can update the controller manually here (controller.text = val.toString())
        return val.toString();
      },`
