### ISSUE TITLE
FormDropDownBuilder clear option

### ISSUE THREAD

**Issue by rodrigobastosv** [danvick/flutter_form_builder#148]
Is there a way to clear the current selected option?

I think this is necessary since right now i don't think you can clear the field after choosing an option.

**Comment by yaskawabr** [comment]
Good Morning,

I have the same problem.

When you already have an item selected in FormBuilderDropdown, and set a new list, an error is generated in the APP.

Therefore, before setting the new list, you would have to clear the current list.

But I didn't find an option either.

Unfortunately the author of lib is no longer answering our questions.

Cristian Regazzo

**Comment by danvick** [comment]
Hi @rodrigobastosv / @yaskawabr 
Sorry for the late response. 
I think clearing the currently selected option is a good suggestion and I'll incorporate it ASAP.

As for changing setting a new list to a Dropdown, as suggested by @yaskawabr , Flutter doesn't offer an easy option for this as the whole widget has to rebuild.

**Comment by dannycortesv** [comment]
Also needing this, thanks for the support
