### ISSUE TITLE
Key attribute not available.

### ISSUE THREAD

**Issue by feijodev** [danvick/flutter_form_builder#151]
While writing integration tests I ended up falling into a problem.

There is a recommendation to select elements using their key, but FormBuilderTextField does not allow a custom key.

Is there any way you can set the key in the future?

**Comment by danvick** [comment]
Hi @feijodev,
Currently, there's no way of doing that. What would be the possible reason for us to consider such a scenario?

**Comment by feijodev** [comment]
Today, I decided to use a manager detector by placing the key on a label and setting the focus without input when receiving a click.

I saw that there are other ways around this.

But writing an e2e test is easier.
