### ISSUE TITLE
Settings keys on field widgets

### ISSUE THREAD

**Issue by tjarvstrand** [danvick/flutter_form_builder#155]
Hi! I'm quite new to flutter but Is there any way it would be possible to set predictable value keys on the underlying form field widgets? At the moment, as far as I can tell, it is not possible to locate the widgets in integration testing with flutter_driver.

If this sounds like an acceptable idea, I could take a stab at a PR

**Comment by danvick** [comment]
Hello @tjarvstrand,
Sounds like a great idea. A PR will be much appreciated!
