### ISSUE TITLE
Specifying an integer in min or max results in error from slider

### ISSUE THREAD

**Issue by jamiethain** [danvick/flutter_form_builder#156]
Form_Builder_Slider min and max values are of type num. 

If you pass these values an integer instead of a double, then Slider blows up and creates an error that int is not of subtype of double. 

In Slider min and max are defined as double and therefore likely should match the types. I did update my local version of form_builder_slider.  I sent this to you in email. 

Also I added a parameter to form builder slider for wholeNumbersOnly or something of that effect that displays only integer values and passes integers values below the slider bar. 

Anyway the displaying of 700.00000001 issue is actually in the slider code from Flutter.

**Comment by danvick** [comment]
Thanks for your contribution @jamiethain. I'll have that fixed ASAP

**Comment by danvick** [comment]
The error: "int is not of subtype of double" is an error that should have been fixed in the latest versions of Dart. Can I kindly have the output of your `flutter doctor` from your PC?

**Comment by jamiethain** [comment]
Sure, i have since upgraded everything, like about 3 days ago so I'm not
sure it will help.


It would be my suggestion when building controls on top of controls to pass
the same types as the underlying control unless there is some practical
reason not too.

The way to reproduce the error in my machine in the sample slider set the
min to 0 instead of 0.0 and it blew up immediately.

Also it took me about 4 hours to figure out why slider was displaying
700.00000001 it was because 10,000 / 700 mod (increment) value math Flutter
is doing is producing a rounding error.

I've got too much on to write it up more meaningful than that...

Jamie

**Comment by danvick** [comment]
Noted. The underlying type for Flutter's Slider is `double` and I've since had it reverted. 
Thanks for your help.

**Comment by jamiethain** [comment]
Dan,

Have you looked at my whole numbers only edition and are you going to keep
that in future controls.

the reason I stuck that in there is to be a workaround for the modulus math
problem with the double overflow on the underlying control.

It also looks quite a bit better on my screen that is says 700 not 700.00
something or even on any of the other screens when you set the number to
0.0 that is what displayed as a minimum giving the user the thought that
3.1 might be one of the options.

Whole numbers only displays 0 even if the min is set to zero point zero.

Jamie

**Comment by danvick** [comment]
I've noticed that I may have been going about this the wrong way and that may be the reason you may be having issues. 

The default Flutter Slider doesn't display values by default. The min, max, and current values being displayed under the Slider are my own creation so that the user can see the values.

I'll look for a better way to format the values but converting it to integer only for all users of the package may not be the best idea.

**Comment by jamiethain** [comment]
Dan,

My code doesn't convert it to integer it just displays that I put as whole
numbers did you look at my coat it's just a little wrap around your display

**Comment by jamiethain** [comment]
Dan,

I sent you code directly to your gmail account danvick@gmail.com.

Jamie

**Comment by danvick** [comment]
Sorry, my email is danvickmiller@gmail.com.

**Comment by jamiethain** [comment]
Dan,

That is where I sent it maybe google gobbled it because it is code.

**Comment by danvick** [comment]
Hi Jamie,
I really like your implementation. 

I'm, however, planning to give the user the liberty of formatting the number using the `NumberFormat` class for internationalization reasons - since some countries use dot (.) instead of comma (,) as a number separator.
The user will also be able to limit the number of decimal places.

Thanks very much for your contribution.

**Comment by jamiethain** [comment]
Dan,

Thanks no problem at all, i appreciate your forms, easy to use.

Flutter people seam to want to do big chains of complex things, your forms
are awesome

I do like the Q and D US option as default :)
