### ISSUE TITLE
Fields auto clear

### ISSUE THREAD

**Issue by DevTard** [danvick/flutter_form_builder#158]
If you have a long form with a ListView the fields clear themselves as you scroll.
See video here:
https://drive.google.com/file/d/1sV_bmsBiA_xUu_kMvBZNc8gSQRtwU6em/view?usp=sharing

**Comment by DevTard** [comment]
Changing it to a list view with a column inside fixed the issue

**Comment by alvinvin00** [comment]
can u please elaborate what did u do to your form?
