### ISSUE TITLE
FormBuilder initialValue is not taken into account for FormBuilderSwitch

### ISSUE THREAD

**Issue by Sigfrodr** [danvick/flutter_form_builder#159]
This works:
`FormBuilderSwitch(
                attribute: 'theme',
                initialValue: userPreferences.darkTheme,
                activeColor: SecondaryColor,
                label: Text("Thème sombre"),
                decoration: InputDecoration(
                  icon: Icon(FontAwesome.getIconData('moon-o')),
                  border: InputBorder.none,
                ))`

But this don't:
` FormBuilder( key: _fbKey,
          initialValue: {
            'theme': userPreferences.darkTheme,
          },
          autovalidate: false,
              FormBuilderSwitch(
                attribute: 'theme',
                activeColor: SecondaryColor,
                label: Text("Thème sombre"),
                decoration: InputDecoration(
                  icon: Icon(FontAwesome.getIconData('moon-o')),
                  border: InputBorder.none,
                ))`

**Comment by danvick** [comment]
Hi @Sigfrodr,
Thanks for bringing this to my attention. I'm working on a fix.

**Comment by danvick** [comment]
Kindly have a look at v3.6.0 from pub, it contains a fix for this.

Cheers!
