### ISSUE TITLE
[suggestion] The InputDecorator of FormBuilderCheckboxList, FormBuilderRadio, FormBuilderSegmentedControl need to be changed.

### ISSUE THREAD

**Issue by lightlitebug** [danvick/flutter_form_builder#160]
Currently, the InputDecorator of FormBuilderCheckboxList, FormBuilderRadio,  and FormBuilderSegmentedControl's border is set to `InputBorder.none` and `contentPadding` is set to `EdgeInsets.only(top: 10.0, bottom: 0.0)`.
Because of this, `border: OutlineInputBorder()` is not working.
For all other widgets, giving `border: OutlineInputBorder()` work fine.

By changing the packages setting from
```
return InputDecorator(
  decoration: widget.decoration.copyWith(
     enabled: !_readOnly,
     errorText: field.errorText,
     contentPadding: EdgeInsets.only(top: 10.0, bottom: 0.0),
     border: InputBorder.none,
),
```
to
```
return InputDecorator(
  decoration: widget.decoration.copyWith(
    enabled: !_readOnly,
    errorText: field.errorText,
    contentPadding: EdgeInsets.only(top: 10.0, left: 12.0, bottom: 0.0),
),
```
I could get the desired result.
Why set `border` to` InputBorder.none`? Are there any reasons?

This is my screen capture after removing border: InputBorder.none and setting contentPadding: EdgeInsets.only(top: 10.0, left: 12.0, bottom: 0.0).

<img width="573" alt="스크린샷 2019-10-29 오전 12 31 51" src="https://user-images.githubusercontent.com/53779146/67692566-ad2fe380-f9e3-11e9-8cc8-ff5287b7463a.png">

I think there is no reason to set `border` to` InputBorder.none`.

**Comment by danvick** [comment]
Hi @lightlitebug,
Your feedback is much appreciated.

**Comment by danvick** [comment]
The reason for doing this was simply because I didn't like the spaces created around the fields. 
I realize that this may have been ill-advised. 

In the next release, I'll have `contentPadding` and `border` attributes removed from the library so that the developer decides how that goes.

Cheers!

**Comment by lightlitebug** [comment]
It's my pleasure.
I really love your package.

Thank you

2019년 11월 3일 (일) 오후 8:03, Danvick Miller <notifications@github.com>님이 작성:

**Comment by danvick** [comment]
Kindly check out v3.6.0. Let me know if there's anything to add. 
Meanwhile, I'm closing this.

Cheers! Thanks for the love.
