### ISSUE TITLE
Validation idiom

### ISSUE THREAD

**Issue by awhitford** [danvick/flutter_form_builder#161]
I have seen both strategies for validation:
```dart
                if (_formKey.currentState.validate()) {
                  _formKey.currentState.save();
                  // Do whatever...
                }
```
or
```dart
                if (_formKey.currentState.saveAndValidate()) {
                  // Do whatever...
                }
```
The latter looks nicer since it is one call, but the logic seems to save and then validate while the first version validates and then saves.

Is there a preferred idiom?  Does each apply to different situations?  Shouldn't one validate before saving?

**Comment by danvick** [comment]
There isn't much difference. I created the second method since most people were forgetting to call `save()` hence end up with an empty form. It's also just cooler, one function call and you're done

**Comment by awhitford** [comment]
Does it matter if you _validate, then save_ vs _save, then validate_?  I am keen to adopt the simpler `saveAndValidate`, but is there anything I should be looking out for?

**Comment by danvick** [comment]
I don't think so.
