### ISSUE TITLE
add `flutter_hook` support.

### ISSUE THREAD

**Issue by yuzurih4** [danvick/flutter_form_builder#166]
I hope you don't mind if I would like to request for [flutter_hook](https://pub.dev/packages/flutter_hooks) out-of-the-box support.

currently the idea is

```dart
GlobalKey<FormBuilderState> useFormBuilder() =>
    useState(GlobalKey<FormBuilderState>()).value;
```

example usage:

```dart
class SetupProfile extends HookWidget {
  @override
  Widget buildWidget(BuildContext context) {
    final _formKey = useFormBuilder();
    return FormBuilder(
      key: _formKey,
      child: ...restOfTheForm
    )
  }
}
```

**Comment by danvick** [comment]
Hi @yuzurih4,
Your suggestion seems like a sound idea. 

However, this may come as a disadvantage to users of the package who wouldn't want to use or are not conversant with the `flutter_hooks` library.

Is there a reason why you think it would be a good idea to have `flutter_hooks` come baked into this package? Especially given that from the example given it's not much of a hassle to implement it within your own code.

If we have more people asking for this feature, I would consider having it supported out of box.

**Comment by yuzurih4** [comment]
It is of course not really a must have features, but it just give an optional usage for those who use hook and those who dont :) but I think since this one is depends on demand (which I think it maybe not since the popularity is not high), I’m closing this.

**Comment by danvick** [comment]
Okay. But the feedback much appreciated though.
Keep 'em coming.

Cheers!

**Comment by yuzurih4** [comment]
I will :) and will try to help out anywhere I can.
