### ISSUE TITLE
ChipsInput in 1.5.2 is causing issues with onChipTapped

### ISSUE THREAD

**Issue by ibosev** [danvick/flutter_form_builder#168]
Installing flutter_form_builder: ^3.6.0, it came with flutter_chips_input - version 1.5.2

I get the following error:

```Error: No named parameter with the name 'onChipTapped'.
          onChipTapped: widget.onChipTapped,
          ^^^^^^^^^^^^
```

Perhaps this one relates to [this ](https://github.com/danvick/flutter_chips_input/issues/22
) issue in flutter_chips_input.

Please advise what to do to make forms work.

**Comment by danvick** [comment]
Hi @ibosev,
Thanks for the heads-up. I'm pushing an update to sort that out
