### ISSUE TITLE
DateTime field keyboard issue

### ISSUE THREAD

**Issue by Reprevise** [danvick/flutter_form_builder#169]
When I click into the DateTime field in my form many times, eventually, the arrow in the bottom left makes goes down believing there's a keyboard there. When I click my X in the top left of the screen, I have a dialog that comes up and when I press a button, it calls `Navigator.pop()` twice so that it removes the dialog and goes back to the previous page. However, when I get to that page, the DateTime field shows up on my screen. When I click "Cancel", my editor pauses on an exception and when I tell it to continue a couple of times, it spits out this error.

> E/flutter ( 6866): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'didChange' was called on null.
E/flutter ( 6866): Receiver: null
E/flutter ( 6866): Tried calling: didChange(null)
E/flutter ( 6866): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 6866): #1      _FormBuilderDateTimePickerState._onShowPicker 
package:flutter_form_builder/…/fields/form_builder_date_time_picker.dart:343
E/flutter ( 6866): <asynchronous suspension>
E/flutter ( 6866): #2      _DateTimeFieldState.requestUpdate 
package:datetime_picker_formfield/datetime_picker_formfield.dart:287
E/flutter ( 6866): <asynchronous suspension>

When I press the down-facing arrow, it acts as though there's nothing there and it keeps popping the screen like usual. However, nothing I do fixes it unless I go into the form and the keyboard appears. When I get rid of the keyboard by pressing that arrow, it returns to it's normal position.

This screenshot shows the arrow in the bottom left pointing down signaling a keyboard or something else:
![Screenshot_1573312605](https://user-images.githubusercontent.com/25782944/68530825-1532d380-02da-11ea-91e6-daf9a5aa8728.png)

**Comment by danvick** [comment]
Should have been closed by v3.10.0. Feel free to reopen if not.
