### ISSUE TITLE
I18N and i10n

### ISSUE THREAD

**Issue by ghost** [danvick/flutter_form_builder#17]
This is an awesome package for speeding up mundane data pumping apps.

What's your thoughts on i18n ( language translation ) and i10n ( datatime, currency, etc ) formatting 

I am using a pure JSON i18n approach which I a bit different from the standard approach so that the JSON files are more reusable.
Then using simple getText calls to get the translations.
If there is datatime or currency then I wrap the getText to also pass in the datetime or currency in, then get the translated text and then replace the datetime and currency with the real value formatted to the correct local.

I don't do any of the codegen of dart code to wrap the translation as I found it just does not properly support i10n use cases. Too many edge cases.

You still get type checking with getText because you can run a simple AST style checker to walk the dart code and check your keys are there in the JSON files for every language. 

I am also not using dart to do the translation workflow.
Instead just use golang so it reusable I'm lots of things.
This is all used at design time.

Then just getText at runtime.

Thoughts ??? Useful for form builder ??

**Comment by danvick** [comment]
Seems useful. 
There are lots of issues and improvements to be done in the current version, I was planning of doing a v2 which will be a complete rewrite - maybe you should get involved. You seem more experienced than me :-).

**Comment by gedw99** [comment]
Yeah I am happy to get more involved.

Maybe if you write down what and why for V2 somewhere to get the ball rolling.

I have a few ideas myself for other things needed for a form builder than just i18n too.
Printing and pdf
Cross platform ( mobile and desktop )
Grpc for server to flutter communication for rpc.
Events system between server and flutter as well as event bus between flutter components.
Html --> flutter forms. Basically a JSON serialisation of forms layout. Useful for web and flutter apps all using dart

**Comment by gedw99** [comment]
@danvick Hey I am working on different aspects of this. If you get time to scribble some roadmap notes down it will help.

Currently working on i18n and i10n and it working with validation messages

**Comment by danvick** [comment]
Hi @gedw99, 
Sorry for taking this long before getting back to you on this. 

You'd be glad to know that I have been working on improving the plugin before incorporating your much needed brilliant ideas. 
Now check out a branch named ***[version3](https://github.com/danvick/flutter_form_builder/tree/version3)*** which is a complete rewrite of the codebase and I think will close most of the current issues raised. 

I'm planning to release this version within the next two weeks, and I'd be glad to have you have a look before then. The documentation for this version is not currently not complete but feel free to poke around and advise as we plan for these suggestions.

Cheers

**Comment by gedw99** [comment]
Awesome will hit the V3 branch tonight

**Comment by danvick** [comment]
That would be great!

I've already published a beta version on pub and I'm getting some awesome feedback and suggestions already. I'm eagerly waiting for yours.

**Comment by danvick** [comment]
Hi all,
This issue is being worked on in Version 4 which is [still in the works](https://pub.dev/packages/flutter_form_builder/versions/4.0.0-alpha.5). Kindly test it out and let's have the feedback. Help in translating the `FormBuilderValidator` `errorText`s is needed. I'll include the guide to contributing to the readme soon.

**Comment by danvick** [comment]
I'm closing thiis because we now have i18n support in ^4.0.0
