### ISSUE TITLE
No named parameter with the name 'onChipTapped'

### ISSUE THREAD

**Issue by nest-don** [danvick/flutter_form_builder#170]
Hello, 

Please look at the bug below.

/Volumes/Extra/Projects/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.5.3/lib/src/fields/form_builder_chips_input.dart:108:13: Error: No named parameter with the name 'onChipTapped'.
            onChipTapped: widget.onChipTapped,
            ^^^^^^^^^^^^
/Volumes/Extra/Projects/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.6.0/lib/src/chips_input.dart:12:3: Context: Found this candidate, but the arguments don't match.
  ChipsInput({
  ^
FAILURE: Build failed with an exception.

**Comment by danvick** [comment]
Hi @nest-don,
Could you kindly upgrade to v3.6.1 instead on v3.5.3.

**Comment by nest-don** [comment]
Thank you.
