### ISSUE TITLE
The Text form field freezes the entire app

### ISSUE THREAD

**Issue by nest-don** [danvick/flutter_form_builder#172]
The sample program provided "Age" numeric field input does not work.

This sample -> https://github.com/danvick/flutter_form_builder/tree/master/example/lib

It freezes the entire program.

**Comment by danvick** [comment]
Hi @nest-don,
I'm unable to reproduce this. Are you getting any errors? 

Anyone having the same issue?

**Comment by nest-don** [comment]
Hello,  
Are you able to type a value into the age field?

**Comment by danvick** [comment]
Hi @nest-don,
Do we still have this issue?

**Comment by danvick** [comment]
Closed due to inactivity.
