### ISSUE TITLE
The method 'saveAndValidate' was called on null.

### ISSUE THREAD

**Issue by irwinOT** [danvick/flutter_form_builder#174]
showDialog(
            barrierDismissible: false,
            context: context,
            builder: (BuildContext context) {
              return AlertDialog(
                actions: <Widget>[
                  MaterialButton(
                    child: Text("Guardar"),
                    onPressed: () {
                      if (_formKey.currentState.saveAndValidate()) {
                        Navigator.pop(context);
                        print(_formKey.currentState.value );
                      }
                    },
                  ),
                  MaterialButton(
                    child: Text("Cancelar"),
                    onPressed: () {
                      Navigator.pop(context);
                      _auth.signOut();
                    },
                  ),
                ],
                content:
                    FormBuilder(
                      initialValue: {
                        'accept_terms': true,
                      },
                      key: _formKey,
                      autovalidate: true,
                      child: SingleChildScrollView(
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          children: <Widget>[
                            FormBuilderTextField(
                              attribute: "name",
                              decoration: InputDecoration(labelText: "Nombre"),
                              validators: [
                                FormBuilderValidators.required(),
                                FormBuilderValidators.minLength(5),
                              ],
                            ),
                            FormBuilderTextField(
                              attribute: "cedula",
                              decoration:
                                  InputDecoration(labelText: "No. Cédula"),
                              keyboardType: TextInputType.number,
                              validators: [
                                FormBuilderValidators.required(
                                  errorText: "Ingrese la cédula (10 números)",
                                ),
                                FormBuilderValidators.minLength(10,
                                    errorText: "Debe contener 10 dígitos."),
                                FormBuilderValidators.maxLength(10,
                                    errorText: "Debe contener 10 dígitos."),
                              ],
                            ),
                            FormBuilderTextField(
                              attribute: "phone",
                              decoration: InputDecoration(
                                  labelText: "Celular", hintText: "0996123456"),
                              keyboardType: TextInputType.number,
                              validators: [
                                FormBuilderValidators.required(),
                                FormBuilderValidators.numeric(
                                    errorText:
                                        "Ingrese un número celular sin letras."),
                                FormBuilderValidators.minLength(10,
                                    errorText: "Debe contener 10 dígitos."),
                                FormBuilderValidators.maxLength(10,
                                    errorText: "Debe contener 10 dígitos."),
                              ],
                            ),
                            FormBuilderDropdown(
                              attribute: "gender",
                              decoration: InputDecoration(labelText: "Género"),
                              // initialValue: 'Male',
                              hint: Text('Seleccione género'),
                              validators: [FormBuilderValidators.required()],
                              items: ['Masculino', 'Femenino', 'Otro']
                                  .map((gender) => DropdownMenuItem(
                                      value: gender, child: Text("$gender")))
                                  .toList(),
                            ),
                            FormBuilderCheckbox(
                              attribute: 'accept_terms',
                              label: Text("Acepto términos y condiciones."),
                              validators: [
                                FormBuilderValidators.requiredTrue(
                                  errorText:
                                      "Usted debe aceptar términos y condiciones de uso para continuar.",
                                ),
                              ],
                            ),
                          ],
                        ),
                      ),
                    ),
              );
            });

**Comment by danvick** [comment]
Make sure you've declared and initialized your `_formKey` as shown in the [example](https://github.com/danvick/flutter_form_builder#example)

**Comment by irwinOT** [comment]
> Make sure you've declared and initialized your `_formKey` as shown in the [example](https://github.com/danvick/flutter_form_builder#example)

already declared: final _formKey = GlobalKey<FormBuilderState>();

**Comment by danvick** [comment]
I've failed to reproduce your error. If you haven't already solved this, kindly share more of your code - preferably formatted for us to be able to assist easily
