### ISSUE TITLE
[Feature Request] Different DateTime Picker to include

### ISSUE THREAD

**Issue by EricPreventa** [danvick/flutter_form_builder#176]
Looking to add in a DOB picker. The current date time picker is a little cumbersome to use for just selecting years that go way back. This is much easier to use and add.

https://github.com/Realank/flutter_datetime_picker

**Comment by danvick** [comment]
Hi @EricPreventa,
Thanks for your suggestion. I will consider adding this to the upcoming v4 of the package.

There are some inherent problems with the current version that needed to be fixed in order to make maintenance of this package a bit easy since I've been fighting bugs every day.
