### ISSUE TITLE
[feature request] filter/choice chip form builder

### ISSUE THREAD

**Issue by VOIDCRUSHER** [danvick/flutter_form_builder#186]
Oftentimes in mobile applications, we have the same use case for a radio buttons and checkbox lists but would like to make more efficient use of the available screen space. In these cases, we might use a fixed set of filter chips to replace a checkbox list and a fixed set of choice chips to replace a busy radio button or segmented control bar. 

This would a request for a FormBuilderFilterChip and FormBuilderChoiceChip classes with the same form behavior as FormBuilderCheckBoxList and FormBuilderRadio but as a wrapped set of chips constructed from a set of FormBuilderFieldOptions.

**Comment by danvick** [comment]
Yeah, I'm aware of this. I was planning to have something close to [multiselect_formfield](https://pub.dev/packages/multiselect_formfield)

**Comment by VOIDCRUSHER** [comment]
I'm on the fence about multiselect_formfield because while it does compress the form input for display, it also forces the end user to work with a drop list, limiting usability past 12 options. I have a FormBuilderChoiceChip and FormBuilderFilterChip that I'm currently working with. I can submit a PR if you'd like to take a look at it.

**Comment by danvick** [comment]
A PR's much welcome.

**Comment by VOIDCRUSHER** [comment]
#196 Is available for feedback
