### ISSUE TITLE
Add option to allow to use 'Wrap' widget for FormBuilderCheckboxList 

### ISSUE THREAD

**Issue by magillus** [danvick/flutter_form_builder#188]
One of my use cases is that the form have multi selection on wide area.
With using current implementation there is a lot of space between label and checkbox, using [Wrap widget](https://api.flutter.dev/flutter/widgets/Wrap-class.html) and forcing child (checkbox with label) widget to have set width would make it look like expandable table of check boxes.

**Comment by danvick** [comment]
Hello @magillus,
I'm aware of the space issue and I'm working on fixing that without breaking changes, I'm be making such improvements to the next major version of the package.

In the meantime, I'd advise setting `leadingInput` to `true` so that the Checkbox is next to the label.

**Comment by magillus** [comment]
Thank you for great package. 
If I had little more spare time I would contribute PR, for now just using local change of Wrap and static width of checkboxes.

thx for tip on `leadingInput`
