### ISSUE TITLE
The new version depends on an old version of intl 

### ISSUE THREAD

**Issue by jamiethain** [danvick/flutter_form_builder#189]
Dan, 

Can you add the latest package or broaden the constraint. 

--------------------------------------------------------------------------------------------------

Because flmobile depends on flutter_form_builder ^3.7.1 which depends on intl ^0.15.8, intl ^0.15.8 is required.

So, because flmobile depends on intl ^0.16.0, version solving failed.

**Comment by danvick** [comment]
Kindly resolve with `dependency_overrides`.

**Comment by danvick** [comment]
There has been a bit of an outcry and a lot of issues raised because of this. My plan is to have it to be the latest version in the next major version. 

I've been answering new issues raised, every.

**Comment by jamiethain** [comment]
Danvick/Flutter_form_builder

Remember we all appreciate your effort into to simplifying this whole
chaotic form process on Flutter. I know I do for sure.

I did the override that worked for me.

Jamie
