### ISSUE TITLE
Scroll to Error

### ISSUE THREAD

**Issue by ghost** [danvick/flutter_form_builder#19]
This is looking amazing. Great work !!

One thing i noticed is that on a large form ( like the example ) if you press submit at the bottom and there is an error, the user has to scroll up to find it.

It might be possible to scroll to the first error automatically ? No sure how flutter supports this. I know there was lots of talk about Tabbing through fields.
https://medium.com/flutterpub/flutter-keyboard-actions-and-next-focus-field-3260dc4c694
- looks like maybe it is fixed & supported now  :)

Also on a Tablet, where the classic layout is the List on the left and the Form on the right, have to test the scroll to error also to make sure it works.

**Comment by danvick** [comment]
Seems useful. It's an issue I've noticed myself.
Thanks for your contribution.

**Comment by gedw99** [comment]
@danvickI found the solution: https://flutter.io/docs/cookbook/forms/focus

It works with the keyboard, but also is programatic and designed for the exact use case of a validation error and needing to scroll the screen to the text field with the error :)

Looks like an easy one to fix.

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
