### ISSUE TITLE
FormBuilderStepper broken on previously required integer values.

### ISSUE THREAD

**Issue by VOIDCRUSHER** [danvick/flutter_form_builder#195]
In 3.7.1.,  FormBuilderStepper now requires double values to in min, max, step values. Immediately prior to this, only integer values were allowed so upgrading to the latest version breaks all prior instantiations of FormBuilderStepper. I believe this to be a critical bug that should be fixed immediately.

**Comment by danvick** [comment]
I believe this is fixed in 3.7.1. The bug was in 3.7.0. Kindly confirm this

**Comment by VOIDCRUSHER** [comment]
Seems to work now. Thanks.
