### ISSUE TITLE
typeahead FormBuilder forces selectionToTextTransformer to be String type

### ISSUE THREAD

**Issue by JohnKuan** [danvick/flutter_form_builder#197]
Hi @danvick, its been awhile. 

I just noticed that you have made this change to line 115 of FormBuilderTypeAhead

`_initialText = (widget.selectionToTextTransformer != null)
        ? widget.selectionToTextTransformer(_initialValue ?? '')
        : _initialValue?.toString() ?? '';`

I am afraid this invalidates the dynamic type <T> of the form builder as `_initialValue ?? ''` forces the supplied selectionToTextTransformer to accept typed String regardless of the type of the initialValue.

**Comment by danvick** [comment]
Hi @JohnKuan,
Kindly note that here we are just setting the `_initialText` to feed it to the `TextEditingController` of the TypeAhead.

Also, note that the final value of a TypeAhead will always be a string and that's how the package is set  to work.

**Comment by awhitford** [comment]
This is a duplicate (see #319 and #244); PR #320 resolves this properly.

**Comment by awhitford** [comment]
Closing because fix is part of **3.11.1**.
