### ISSUE TITLE
load form from firestore document ?

### ISSUE THREAD

**Issue by antoniosap** [danvick/flutter_form_builder#198]
Form data from firestore is empty.
Some idea / example for loading data ?
writing form data is OK.

```
...
  Widget _showUserPage(BuildContext context) {
    _userRead();

    return Column(
        children: <Widget>[
          FormBuilder(
            key: _fbKey,
            autovalidate: true,
            initialValue: {
              'RagSoc': widget.RagSoc,
              'ResDom': widget.ResDom,
              'CFPiva': widget.CFPiva,
              'Ubicaz': widget.Ubicaz,
              'Autorz': widget.Autorz,
              'AutorzDate': widget.AutorzDate,
            },
            child: Column(
                children: <Widget>[
...
```

```
  void _userRead() async {
    await Firestore.instance
        .collection('USERS')
        .document(widget.userId)
        .get()
        .then((DocumentSnapshot ds) {
      if (ds.exists) {
        widget.RagSoc = ds.data['RagSoc'].toString();
        widget.ResDom = ds.data['ResDom'].toString();
        widget.CFPiva = ds.data['CFPiva'].toString();
        widget.Ubicaz = ds.data['Ubicaz'].toString();
        widget.Autorz = ds.data['Autorz'].toString();
        widget.AutorzDate = ds.data['AutorzDate'].toString();
      }
    });
  }
```

**Comment by yarmel** [comment]
My working example 
===
void _getData(id) async {
    try {
      await repository.getHabitById(id).then((result) {
        initData = result.toJson();
      });
    } catch (e) {
      print(e);
    } finally {
      setState(() {
        isLoaded = true;
      });
    }
  }

  Widget _buildForm() {
    switch (action) {
      case "update":
        return FormBuilder(
          key: _habitKey,
          initialValue: isLoaded == true ? initData : {},
          autovalidate: false,
          child: Expanded(
            child: isLoaded == true ? HabitForm() : Container(),
          ),
        );
        break;
      default:
        return FormBuilder(
          key: _habitKey,
          initialValue: {},
          autovalidate: false,
          child: Expanded(
            child: HabitForm(),
          ),
        );
    }
  }
