### ISSUE TITLE
Accept `errorText` as callback and pass validation parameters to the callback function

### ISSUE THREAD

**Issue by e200** [danvick/flutter_form_builder#199]
Accept `errorText` as callback and pass validation parameters to the callback function so people can dynamically return a different text error message with the required values.

```dart
FormBuilderTextField(
       attribute: 'last_name',
       maxLines: 1,
       decoration: InputDecoration(labelText: 'Último nome'),
       validators: [
            FormBuilderValidators.minLength(
                     3,
                     errorText: (value, minLength) {
                          return `${value} must be greater then ${minLength}`;
                     },
             ],
       ),
)
```

**Comment by danvick** [comment]
Hi @e200,
This sounds like a nice idea. 

However, it would be a bit challenging to pull off on this package based on the implementation of  `FormFieldValidator`.

**Comment by e200** [comment]
:(

**Comment by danvick** [comment]
I know. I'm sorry. 

PR welcome though. Or get some votes on the issue.
