### ISSUE TITLE
Is there a way to check dropdown attribute selected value on change?

### ISSUE THREAD

**Issue by ckildgypmk** [danvick/flutter_form_builder#2]

**Comment by danvick** [comment]
Not currently. 
Could you kindly suggest the possible application/need for this behaviour.

**Comment by ckildgypmk** [comment]
For example I use dropdown menu to display regions that i get from api, when user selected his region I'm getting available city's in that region.

**Comment by danvick** [comment]
Hmmm. That would be quite helpful. I'll be willing to start planning for it in near-future releases

**Comment by huzhiren** [comment]
@danvick  Please add formData as parameter in onChanged() callback, so we can check if value change?

instead of:
  @override
  Widget build(BuildContext context) {
    return Form(
      key: _formKey,
      onChanged: widget.onChanged,

do this:
  @override
  Widget build(BuildContext context) {
    return Form(
      key: _formKey,
      onChanged: () { widget.onChanged(formData) },

**Comment by danvick** [comment]
Thanks @huzhiren. You're the best

**Comment by huzhiren** [comment]
Awesome, thanks.

**Comment by danvick** [comment]
@ckildgypmk I'm aware that the current solution may not fully solve the problem but we'll have an `onChanged()` function attached to each `FormInput` in the coming releases so that one can react to only the changes one is interested in.

**Comment by huzhiren** [comment]
Yes, when you try to dynamically update the dropdown options when the other filed changed, I got his error, weird:

Error caught by widgets library, thrown building FormField<dynamic>-[<'followupTask'>](dirty, state: FormFieldState<dynamic>#01d28).
'package:flutter/src/material/dropdown.dart': Failed assertion: line 514 pos 15: 'items == null || value == null || items.where((DropdownMenuItem<T> item) => item.value == value).length == 1': is not true.
#2      new DropdownButton (package:flutter/src/material/dropdown.dart:514:15)
#3      _FormBuilderState.formControlsToForm.<anonymous closure> (package:flutter_form_builder/src/form_builder.dart:244:24)
#4      FormFieldState.build (package:flutter/src/widgets/form.dart)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3787:27)

**Comment by danvick** [comment]
As of version 3.0.0, each field has an `onChanged` callback.
