### ISSUE TITLE
Does the slider builder work correctly?

### ISSUE THREAD

**Issue by f9n** [danvick/flutter_form_builder#20]
When I slided the example slider in the [example app]((https://github.com/danvick/flutter_form_builder/tree/master/example)), it did not work correctly. It didn't refresh current value of slider in ui. But it works correctly in `onChanged` and `onSubmit` events.

**Comment by danvick** [comment]
Noted. Thanks for your contribution

**Comment by danvick** [comment]
Should be fixed as of v1.3.5
