### ISSUE TITLE
intl version

### ISSUE THREAD

**Issue by malikdoksoz** [danvick/flutter_form_builder#204]
Can you update intl 16.0.

> Because flutter_form_builder 3.7.2 depends on intl ^0.15.8 and no versions of flutter_form_builder match >3.7.2 <4.0.0, flutter_form_builder ^3.7.2 requires intl ^0.15.8.

**Comment by matheusrezende** [comment]
@malikdoksoz I already created a pull request for it. https://github.com/danvick/flutter_form_builder/pull/207

**Comment by itsMatoosh** [comment]
Using this in your pubspec.yaml will fix the issue until an official patch is released:

    flutter_form_builder:
        git:
          url: https://github.com/danvick/flutter_form_builder.git
          ref: 4597ffb6e1695ad00a7aa10ac0f3634549d60280
