### ISSUE TITLE
Add Feature DateTimePicker with String for initialValue

### ISSUE THREAD

**Issue by ekasetiawans** [danvick/flutter_form_builder#208]
Add feature to convert String into DateTime.
Currently, valueTransformer only convert DateTime into String and executed onSave. But I want same way to convert String into DateTime as initialValue.

for example:

```
Map<String, dynamic> data = {
   "birthday" : "1990-12-23 08:00:00",
};

...
FormBuilder(
  initialValue: data,
  child: Column(
    children : [
        FormBuilderDateTimePicker(
             attribute: "birthday", // will throws error, because birthday value is not a subtype of DateTime
        ),
    ],
  ),
),
...
```

**Comment by isojtouano** [comment]
You can use DateTime.parse(*String here*)

**Comment by danvick** [comment]
Hi @ekasetiawans, 
I'll consider this in later versions of the package, in the meantime, kindly consider using @isojtouano's suggestion.

**Comment by ekasetiawans** [comment]
> Hi @ekasetiawans,
> I'll consider this in later versions of the package, in the meantime, kindly consider using @isojtouano's suggestion.

Hi @danvick thankyou very much

**Comment by danvick** [comment]
Because of Dart's type-safety feature, it would be much of a hassle to make this happen. We'll therefore stick to the suggested solution.
