### ISSUE TITLE
DateTimePicker readOnly property not consistent with datetime_picker_formfield

### ISSUE THREAD

**Issue by RedTech64** [danvick/flutter_form_builder#210]
When using the `FormBuilderDateTimePicker`, the keyboard jumps up and closes when the date picker shows. After looking at the DateTimePicker from `datetime_picker_formfield`, it looks like if `readOnly` is true, then this issue should be resolved. However, due to the way `FormBuilderDateTimePicker` is written, if `readOnly` is true, then enabled is set to false, which disables the whole widget. While I believe this keyboard issue is the fault of `datetime_picker_formfield`, there should be more control of making only the keyboard read-only, and the whole widget read-only.

**Comment by Ayman-Kortobaa** [comment]
Are there any workarounds or news for this issue?
I am having the same issue right now stopping me from using the package in production.
