### ISSUE TITLE
locale: Locale('zh') in FormBuilderDateTimePicker doesn't work.

### ISSUE THREAD

**Issue by allonli** [danvick/flutter_form_builder#212]
When I set the options  InputType.both and locale: Locale('zh') ,  right.
But when I set the options  InputType.date and locale: Locale('zh'), doesn't work.

**Comment by danvick** [comment]
Could you kindly consider raising the issue on the [datetime_picker_formfield repository](https://github.com/jifalops/datetime_picker_formfield) on which this package depends.

**Comment by danvick** [comment]
Hi @allonli,
Were you able to resolve this? If not kindly check out v3.9.0 and let us know if this was resolved.
