### ISSUE TITLE
FormBuilderChipsInput 

### ISSUE THREAD

**Issue by tanmaypandharipande** [danvick/flutter_form_builder#213]
Not able to set the data into chipsBuilder after returning from route. Can you help out with the FormBuilderChipsInput which on click goes to another route and on response gets the data and fills in form of Chips. Current Code 

> FormBuilderChipsInput(
                                            attribute: "ABC",
                                            decoration: InputDecoration(
                                                contentPadding:
                                                    EdgeInsets.all(8),
                                                labelText: "Label"),
                                            validators: [],
                                            initialValue:
                                                widget.values,
                                            chipBuilder: (context, state,
                                                selectedOptions) {
                                              return InputChip(
                                                deleteIcon: Icon(null),
                                                elevation: 5,
                                                key: ObjectKey(selectedOptions),
                                                label: Text(
                                                    selectedOptions.toString()),
                                                onDeleted: () {
                                                  state.deleteChip(
                                                      selectedOptions);
                                                },
                                                materialTapTargetSize:
                                                    MaterialTapTargetSize
                                                        .shrinkWrap,
                                              );
                                            })

So in this case if I setState the widget.values then the FormBuilderChipsInput isn't updating, I am purposely taking another bool to manage the thing, which I don't want to do. Any another way?

**Comment by danvick** [comment]
This issue should be fixed. Feel free to reopen if not
