### ISSUE TITLE
DateTimePicker keyboard  visible

### ISSUE THREAD

**Issue by AlexEAA** [danvick/flutter_form_builder#221]
When choosing a date or time, the keyboard is visible, someone solved the problem?? with datetime_picker_formfield this was not

**Comment by lkloon123** [comment]
got this problem too

**Comment by danvick** [comment]
Hi @AlexEAA, @lkloon123 
Do we still have this issue in the latest version of this package? I'm unable to reproduce this currently

**Comment by Ayman-Kortobaa** [comment]
Hello, @danvick.
I am having this issue with the latest version of the package.
