### ISSUE TITLE
Using PageView with Flutter_Form_Builder

### ISSUE THREAD

**Issue by CedYF** [danvick/flutter_form_builder#222]
Hi, is there any way to implement pageview?

When I try I keep getting this error:
The following assertion was thrown during performResize():
flutter: Horizontal viewport was given unbounded height.

Any examples would be great

**Comment by CedYF** [comment]
I've managed to make progress by using a PageView.builder

**Comment by digitalindiaapps** [comment]
hi @CedYF 
i have implemented flutter form builder with page view. I had done it for paid project so for security reason i dont able to share screenshot. if you want then i can share structure Code..
mail me at dafdaprakash@gmail.com

**Comment by CedYF** [comment]
Messaged, thanks!

**Comment by danvick** [comment]
Hi @CedYF,
Were you able to solve this issue?

**Comment by Dennis-Mwea** [comment]
@danvick Tried to use page view with the package. My problem is that inputs lose their values when page index is changed.

**Comment by Dennis-Mwea** [comment]
Figured it out.

**Comment by WilliamCunhaCardoso** [comment]
> Figured it out.

Then close, please.

**Comment by danielweil** [comment]
> Figured it out.

Can you share your solution?
Thanks!

**Comment by hareendranmg** [comment]
> Figured it out.

Please share the solution.

**Comment by yasirraku** [comment]
Thankful if someone could please share the solution.

**Comment by WilliamCunhaCardoso** [comment]
Maybe wrapping PageView with a FormBuilder. It is complicated to understand without any code to test
