### ISSUE TITLE
FormBuilderTypeAhead - selecting suggestion does not fill field in web

### ISSUE THREAD

**Issue by renahan** [danvick/flutter_form_builder#223]
I'm wanting to use the FormBuilderTypeAhead while developing an app that will primarily be for the web. I found that when selecting a suggestion it does not fill the field. Fortunately, this does work in Android. Have not verified iOS.

**Comment by jocelyngirard** [comment]
The `FormBuilderTypeAhead` component depend on `flutter_typeahead` library, this one has an issue with the `onSuggestionSelected` callback on web platform.

A workaround is available here : https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/151#issuecomment-590934761
