### ISSUE TITLE
datepicker that support mutilple language ? 

### ISSUE THREAD

**Issue by zozeei** [danvick/flutter_form_builder#224]

**Comment by zozeei** [comment]
example https://pub.dev/packages/flutter_rounded_date_picker#-readme-tab-

**Comment by RodolfoSilva** [comment]
You need to initialize localizations in your application.

```
MaterialApp(
    localizationsDelegates: [
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
    ],
    supportedLocales: [
          const Locale('en', 'US'), // English
          const Locale('th', 'TH'), // Thai
    ],
)
```

I believe this is related with this issue: #99

**Comment by RodolfoSilva** [comment]
@zozeei if you have any problem with flutter_localizations you can follow this guide:

https://www.youtube.com/watch?v=Nn6kle_DThM

**Comment by zozeei** [comment]
@RodolfoSilva  thank you

**Comment by RodolfoSilva** [comment]
@zozeei 😜, can you close this issue?
