### ISSUE TITLE
FormBuilderTextField not take "obscureText: true" to hide password field

### ISSUE THREAD

**Issue by marqueetest** [danvick/flutter_form_builder#226]
i using flutter_form_builder: ^3.7.3.
and I use this "obscure text: true" to hide the password field in FormBuilderTextField.
flutter compiler give an error:-
"Obscured fields cannot be multiline.
'package:flutter/src/material/text_form_field.dart':
Failed assertion: line 149 pos 15: '!obscureText || maxLines == 1' "

**Comment by RodolfoSilva** [comment]
@marqueetest you need to pass this attribute: `maxLines: 1`

This error was introduced in flutter 1.12

close #226

**Comment by Cretezy** [comment]
Could we default to `maxLines: 1` when `obsureText` is set? This feels like a easily fixable default.
