### ISSUE TITLE
Version constraints with flutter_localizations ,how fixed?

### ISSUE THREAD

**Issue by Jasoneng2017** [danvick/flutter_form_builder#227]
Because no versions of flutter_form_builder match >3.7.3 <4.0.0 and flutter_form_builder 3.7.3 depends on intl ^0.16.1, flutter_form_builder ^3.7.3 requires intl ^0.16.1.

And because every version of flutter_localizations from sdk depends on intl 0.16.0, flutter_form_builder ^3.7.3 is incompatible with flutter_localizations from sdk.
So, because dvmg_app depends on both flutter_localizations any from sdk and flutter_form_builder ^3.7.3, version solving failed.
pub get failed (1; So, because dvmg_app depends on both flutter_localizations any from sdk and flutter_form_builder ^3.7.3, version solving failed.)

**Comment by liugangnhm** [comment]
@Jasoneng2017  how do you fix this? i got the same issue

**Comment by liugangnhm** [comment]
> @Jasoneng2017 how do you fix this? i got the same issue

```yaml
dependency_overrides:
  intl: 0.16.0
```

fixed me!

**Comment by Jasoneng2017** [comment]
dependency_overrides:
  intl: ^0.16.0
 try this!!!!

**Comment by Jasoneng2017** [comment]
> > @Jasoneng2017 how do you fix this? i got the same issue
> 
> ```yaml
> dependency_overrides:
>   intl: 0.16.0
> ```
> 
> fixed me!

dependency_overrides:
  intl: ^0.16.0
 try this!!!
