### ISSUE TITLE
Unable to use flutter_form_builder

### ISSUE THREAD

**Issue by Spepardy** [danvick/flutter_form_builder#228]
I get the error below immediately I add **final GlobalKey<FormBuilderState> _senderDetailsFormKey = GlobalKey<FormBuilderState>();** to my code and hot reload it.

Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.7.3/lib/src/form_builder.dart:25:15: Error: The method 'findAncestorStateOfType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'findAncestorStateOfType'.
      context.findAncestorStateOfType<FormBuilderState>();
              ^^^^^^^^^^^^^^^^^^^^^^^

Below is my code

`import 'package:flutter/material.dart';
import '../../globals.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';

class SenderDetails extends StatefulWidget {
  @override
  _SenderDetailsState createState() => _SenderDetailsState();
}

class _SenderDetailsState extends State<SenderDetails> {
  final GlobalKey<FormBuilderState> _senderDetailsFormKey = GlobalKey<FormBuilderState>();

  @override
  void initState() {
    super.initState();
    userId = "9";
  }
  @override
  Widget build(BuildContext context) {
    return Form(
      //key: _signInFormKey,
      child: Column(
        //mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: <Widget>[
          Center(child: Text("This will be the sender's detail page " + userId),),
        ],
      ),
    );
  }
}
`

**Comment by timeappkz** [comment]
i have this error too

**Comment by Hellomik2002** [comment]
The same error

**Comment by danvick** [comment]
Hi @Spepardy,
It looks from the code that you are using Flutter's vanilla `Form` widget instead of `FormBuilder` widget from this package.

**Comment by danvick** [comment]
Kindly try to run the example app that comes with the package and let us know if you are still facing the issue

**Comment by Spepardy** [comment]
The error shows up immediately I import the package even without using it to create any form.
Only this line of code gives that error:
import 'package:flutter_form_builder/flutter_form_builder.dart';

**Comment by danvick** [comment]
What's your Flutter version? Or your result of `flutter doctor`

**Comment by Spepardy** [comment]
My flutter version is : Flutter 1.9.1+hotfix.4


My flutter doctor output is;
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.17134.1246], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.42.1)
[√] Connected device (1 available)

• No issues found!

**Comment by danvick** [comment]
I'm afraid your version of Flutter is a bit old. The current version of stable Flutter is `1.12.x`.

**Comment by Spepardy** [comment]
Okay thank you.
But then I tried using earlier versions of the flutter_form_builder like 3.0.0 which were released in April, 2019 which is prior to my version which was released in September, 2019 but still didn't work.

**Comment by danvick** [comment]
I wouldn't really advocate for using older versions since there are many issues in the package we've fixed since then. 

But, you could try using 3.7.2 since it was the last version before the change you're refering to was introduced.

**Comment by Spepardy** [comment]
Okay, thank you very much.
But then I tried that too but couldn't fix the problem. I think the only solution will be to upgrade my flutter version.

**Comment by danvick** [comment]
Hi @Spepardy, 
You appeared to have closed this issue and then reopened after. Do we still have it recurring?
