### ISSUE TITLE
Change Map<String, dynamic> to a strongly typed struct

### ISSUE THREAD

**Issue by iscriptology** [danvick/flutter_form_builder#229]
I don't know how easy it is to implement but it would be very much helpful to have a strongly typed version of handling the form input...

Thanks for a great lib.

**Comment by danvick** [comment]
I have considered this from time to time but I feel there's no easy way of doing it since each user may have their own structure and the possibilities and endless.

I'm glad this package was of help to you.

**Comment by dJani97** [comment]
Now that Angular's typed forms are out, maybe you could draw inspiration from them.
