### ISSUE TITLE
Add  form builder  in stepper not working

### ISSUE THREAD

**Issue by zozeei** [danvick/flutter_form_builder#231]

**Comment by danvick** [comment]
Hi @zozeei,
Could you kindly share more infomation about this. StackTrace or otherwise.

**Comment by zozeei** [comment]
![Screenshot_20200214_213341](https://user-images.githubusercontent.com/49703843/74540268-0fe8c300-4f72-11ea-8212-cac862ab322f.jpg)
![Screenshot_20200214_213406](https://user-images.githubusercontent.com/49703843/74540283-15460d80-4f72-11ea-8020-f4c596b59978.jpg)

When clicking on the step two, the value from the step one  is sent to the step two.

**Comment by MaskyS** [comment]
Hmm, are you using the same key for both form builders?

**Comment by danvick** [comment]
Hi @zozeei,
Kindly help us solve your problem by answering the questions asked. If this is no longer a problem kindly close
