### ISSUE TITLE
initialValue for FormBuilderChipsInput

### ISSUE THREAD

**Issue by brizaldi** [danvick/flutter_form_builder#233]
Hi, i have a list of object, how can i set it as initialValue for FormBuilderChipsInput?

**Comment by danvick** [comment]
The initial value of `FormBuilderChipsInput` should be a List<T> of the Objects expected as input.

**Comment by brizaldi** [comment]
does the initial value have to be the same instance as List of the objects in input?
i tried to insert list of object from api as initial value, but it seems FormBuilderChipsInput doesnt see it as their own list

**Comment by danvick** [comment]
Yes. The same object type expected as the output should be used as initial value.
