### ISSUE TITLE
initialValue - timePicker defaults to 12:00

### ISSUE THREAD

**Issue by Paul-Todd** [danvick/flutter_form_builder#234]
When using initialValue the time defaults to 12:00 instead of the time set in initialValue.

this is because at line 378 the order of the selection is wrong

```
 initialTime: widget.initialTime ?? TimeOfDay.fromDateTime(currentValue ?? DateTime.now()));
```

should actually be

```
initialTime: currentValue ? TimeOfDay.fromDateTime(currentValue) : widget.initialTime ? widget.initialTime : TimeOfDay.fromDateTime(DateTime.now());
```

initialTime has a runtime default value so that is getting chosen in preference to the current value.

**Comment by Paul-Todd** [comment]
Or set initialTime: null in the constructor to force the time to come from the initialValue

**Comment by qwertyuiop17u** [comment]
I got the same problem.

And before this bug fixed, I use my own timePicker to fix it.
Just like following.
it works for me. 

```
FormBuilderDateTimePicker(
    ...,
    timePicker: (BuildContext context){
        return showTimePicker(
            context: context, 
            initialTime: initialTime,
        ).then((result){
            return result ?? initialTime;
        });
    },
)
```

**Comment by danvick** [comment]
Hi @Paul-Todd,
Thanks for bringing this to my attention, I'll be sure to fix this ASAP.
