### ISSUE TITLE
Is this package support for iOS?

### ISSUE THREAD

**Issue by Sravankumar28** [danvick/flutter_form_builder#235]
I am using this package for hybrid app but this is not working in iOS.can you please help me out.

**Comment by danvick** [comment]
Hi @Sravankumar28,
Not currently but we're planning for it in future.

**Comment by awhitford** [comment]
I am using Flutter Form Builder in an app that is compiled to iOS and Android.  _What is the issue?_

**Comment by danvick** [comment]
Closed since it's a duplicate of #22. PRs are welcome
