### ISSUE TITLE
Widget's labelText is truncated

### ISSUE THREAD

**Issue by kmusham** [danvick/flutter_form_builder#236]
Hi
I've a requirement to show entire labelText without truncate. 

Example:
_FormBuilderCheckboxList(
     decoration: InputDecoration(
          labelText: 'Occasional forgetfulness and requires reminders and or prompting at times');
     <other properties>
);

Do you have any advices to show entire text in multiple lines without truncating.

Thanks

**Comment by danvick** [comment]
Hi @kmusham,
`InputDecoration` doesn't provide for multiple lines on `labelText`. I'd suggest you use a shorter `labelText` them use `hintText` or `helperText` to provide more information to the user.
