### ISSUE TITLE
Need a subtitle for all the widgets

### ISSUE THREAD

**Issue by kmusham** [danvick/flutter_form_builder#237]
Hi
I've a requirement to show a title and subtitle for all the widgets. I see just the labelText but no a subtitle.

Please advice me to show a subtitle for the widget?

Thanks

**Comment by danvick** [comment]
Hi @kmusham,
Flutter doesn't provide a subtitle on an `InputDecoration`. What comes close to what you may use is `hintText` or `helperText`. The two, however, appear below the input field.
