### ISSUE TITLE
 Error: Type 'RawFloatingCursorPoint' not found

### ISSUE THREAD

**Issue by daniel-lucas-silva** [danvick/flutter_form_builder#24]
When i try to buld apk, i got this error
and I'm not using Chips Input.

flutter --version
Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (3 months ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

command: flutter build apk --release
`Compiler message:
file:///Volumes/files/daniel/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.1.0/lib/src/chips_input.dart:293:29: Error: Type 'RawFloatingCursorPoint' not found.
  void updateFloatingCursor(RawFloatingCursorPoint point) {
                            ^^^^^^^^^^^^^^^^^^^^^^
file:///Volumes/files/daniel/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.1.0/lib/src/chips_input.dart:293:29: Error: 'RawFloatingCursorPoint' isn't a type.
  void updateFloatingCursor(RawFloatingCursorPoint point) {
                            ^^^^^^^^^^^^^^^^^^^^^^
Compiler terminated unexpectedly.`

![screen shot 2019-02-18 at 12 24 14 pm](https://user-images.githubusercontent.com/15893416/52960837-6380fa80-3378-11e9-97a9-51b84f9c21ef.png)

**Comment by danvick** [comment]
I'm trying to figure out why this has started acting up. You can however try adding and explicit dependency of `flutter_chips_input: ^1.1.0` as suggested here: [https://github.com/danvick/flutter_chips_input/issues/3#issuecomment-467304993](https://github.com/danvick/flutter_chips_input/issues/3#issuecomment-467304993)
