### ISSUE TITLE
FormBuilderDateTimePicker validator vs validators

### ISSUE THREAD

**Issue by awhitford** [danvick/flutter_form_builder#240]
This may just be a documentation issue, but...

I have a `FormBuilderDateTimePicker` and needed to add ONE custom validation, so specified `validator` except that it didn't work.  When I moved it to a single element array in `validators` (plural), everything worked as expected.

Is `validator` deprecated?  Or is it doing something else?  I'm a little confused.

**Comment by danvick** [comment]
Kindly use validators, that's what we provide for usage in this package since it allows us to chain more than one validator methods.

I may have forgotten to remove the original provided method - I should remove it. Thanks for bringing this to my attention.
Cheers
