### ISSUE TITLE
Applying themes to the entire formBuilder 

### ISSUE THREAD

**Issue by moda20** [danvick/flutter_form_builder#242]
hey  I am trying to apply a theme, basically a set of textStyles, buttons styles, ...  to the entire formBuilder widget and the items in it. 

I could go on and add InputDecorations like follow to all widgets but that would be non efficient :
```dart
decoration: InputDecoration(
                            labelText: "Stepper",
                            labelStyle: TextStyle(
                                color: Colors.white
                            )
                        )
```

Is applying a global theme possible and how to do it if true.

**Comment by rnvitter** [comment]
I was wondering the same thing

**Comment by sharpsan** [comment]
Theme(
   theme: Theme.of(context).copyWith(
      //Your theme changes
   );
):

**Comment by danvick** [comment]
Hi @moda20 / @rnvitter,
This looks like a sound idea. 

However, are you aware that you can set a system-wide `InputDecoration` theme in your `MaterialApp` like so:

```dart
MaterialApp(
  theme: ThemeData(
    inputDecorationTheme: InputDecorationTheme(
      labelStyle: TextStyle(color: Colors.white),
    ),
  ),
  ...
)
```

**Comment by danvick** [comment]
I'll consider adding a form-wide input decoration theme if this issue gets enough upvotes. In the meantime, my suggestion is to use `InputDecorationTheme` as shown above.

**Comment by sharpsan** [comment]
> I'll consider adding a form-wide input decoration theme if this issue gets enough upvotes. In the meantime, my suggestion is to use `InputDecorationTheme` as shown above.

I think wrapping the form builder in a Theme widget or using the suggestion described above is adequate. 

For further modifications, we can make our own components and directly control the UI through the conponent's renderer.
