### ISSUE TITLE
FormBuilderDateTimePicker gets Focus on route pop

### ISSUE THREAD

**Issue by shashikantleher** [danvick/flutter_form_builder#251]
Reproduce:

- Now on page A
- Open form page  B
- Change date value
- Go back (Pops the screen)
- Date time picker dialog shows in the page B

There is some issue in handling the focus of FormBuilderDateTimePicker. (may be)

**Comment by cuimingqiang** [comment]
if (_formKey.currentState.saveAndValidate()) {
                      FocusScope.of(context).requestFocus(FocusNode());
}

**Comment by shashikantleher** [comment]
Yes thank you, @cuimingqiang . That works.

**Comment by shashikantleher** [comment]
But, when a date is selected, it should automatically unfocus the date field

**Comment by danvick** [comment]
Thank you @shashikantleher, for bringing this to our attention. 

Kindly note that this package makes use of other packages so some bugs or issues may emanate from such.

I will try to have a permanent fix, baked into the package.

@cuimingqiang thanks for your solution.
Cheers!

**Comment by danvick** [comment]
This should be fixed, feel free to reopen if not.
