### ISSUE TITLE
Remove line decoration under every form item

### ISSUE THREAD

**Issue by christianarduino** [danvick/flutter_form_builder#252]
Is there a fast way to remove this blue line that is automatically added under each item on the form?

![image](https://user-images.githubusercontent.com/54827354/78718131-051f2e80-7922-11ea-948e-86d2d3aa28ab.png)

**Comment by danvick** [comment]
Yes! In your `InputDecorator`, set `border` to `InputBorder.none`. 

You can apply this to the whole form by setting the attribute in your `inputDecorationTheme`.

**Comment by christianarduino** [comment]
Maybe I'm the one who puts something wrong?

```
FormBuilderSlider(
  attribute: "slider",
  validators: [FormBuilderValidators.min(6)],
  min: 0.0,
  max: 10.0,
  initialValue: 1.0,
  divisions: 20,
  decoration: InputDecoration(
    labelText: "Number of things",
    border: InputBorder.none,
  ),
),
```

The blue border always remains also for other elements of the form (such as checkboxes).
The widget in the real code is inserted in a FormBuilder obviously

![image](https://user-images.githubusercontent.com/54827354/78722131-26374d80-7929-11ea-89ed-82cebe8bad2c.png)

**Comment by danvick** [comment]
It doesn't seem like it. I'm testing locally and everything seems to be working a-okay - I know classic answer ;-)
Which version of the package are you using?

**Comment by christianarduino** [comment]
I think the latest: `flutter_form_builder: ^3.8.2`

**Comment by christianarduino** [comment]
Okay, I found the solution. I had set inputDecorationTheme enabledBorder and focusedBorder. This way InputBorder.none doesn't work for individual elements of the form
