### ISSUE TITLE
FormBuildRadio should support Direction Parameter

### ISSUE THREAD

**Issue by WilliamCunhaCardoso** [danvick/flutter_form_builder#255]
This List should support direction param so we could define axis.horizontal vs vertical

**Comment by danvick** [comment]
Hi @WilliamCunhaCardoso,
This is a nice idea. But how exactly to implement it would be a bit of an issue. For example how many radios to show in a line, the width of the items, how to handle overflows, etc.

More ideas, suggestions on how to handle this, or better yet a PR will be highly appreciated.

**Comment by robertos95** [comment]
I was about to raise a similar issue as well.
@danvick I think usually when we use the horizontal radio button options, we are already aware that we will only have few and fixed options (e.g. genders - male, female, others). So I think without the overflow handling, this would still be a great feature (maybe can just put some note on the API).

**Comment by danvick** [comment]
Kindly use `FormBuilderRadioGroup` field.
