### ISSUE TITLE
how to get scroll info in FormBuilderTypeAhead widget 

### ISSUE THREAD

**Issue by yazanIbrahim** [danvick/flutter_form_builder#257]
Hello, i need to implement an infinite scroll in the suggestions of FormBuilderTypeAhead widget is there a way to get scroll info from this widget ?

**Comment by danvick** [comment]
Hi @yazanIbrahim,
For more customizations on the `FormBuilderTypeAhead` kindly refer to the [flutter_typeahead package](https://pub.dev/packages/flutter_typeahead) which we are making use of within our package.
