### ISSUE TITLE
FormBuilderTextField initialValue not working when a controller is specified

### ISSUE THREAD

**Issue by awhitford** [danvick/flutter_form_builder#258]
For a `FormBuilderTextField`, I noticed that the `initialValue` does not seem to be used when I specify a `controller`.  I am seeing a blank text field, rather than the initial value.

**Comment by danvick** [comment]
This is the default behavior in `TextFormField` in Flutter. This is because while using a controller you are supposed to specify the value within it.

In fact, there's an assertion in Flutter that doesn't allow you to specify an `initialValue` when the controller is set.

**Comment by awhitford** [comment]
OK, if this is expected behavior, then that's fine.  I didn't see anything documented, and noticed that it wasn't working so wanted to mention it.

Note that I didn't notice an assertion if I specify both for a `FormBuilderTextField`.  Should it?

**Comment by abgrano** [comment]
Use static for your variable etc. For example:

**static** String myText;
