### ISSUE TITLE
minLength validation only when not empty

### ISSUE THREAD

**Issue by awhitford** [danvick/flutter_form_builder#259]
I only want the `minLength` validation when a value is specified; an empty field is fine.

It seems that this is arguably redundant:
```dart
            validators: [
              FormBuilderValidators.required(),
              FormBuilderValidators.minLength(4),
            ],
```

I thought I could simply remove the `required()` validator, but `minLength(4)` still complains that the empty field is not at least 4 characters.

Maybe the `minLength` validator could have an optional flag to say whether it should apply to empty fields?  (That way, backwards compatibility can be maintained.)

**Comment by awhitford** [comment]
My workaround is to do this:
```dart
              validators: [
                (val) => val.isNotEmpty
                    ? FormBuilderValidators.minLength(4).call(val)
                    : null,
              ],
```

This is not awful, but I'm open to a more elegant solution.

**Comment by danvick** [comment]
> I only want the `minLength` validation when a value is specified; an empty field is fine.
> 
> It seems that this is arguably redundant:
> 
> ```dart
>             validators: [
>               FormBuilderValidators.required(),
>               FormBuilderValidators.minLength(4),
>             ],
> ```
> 
> I thought I could simply remove the `required()` validator, but `minLength(4)` still complains that the empty field is not at least 4 characters.
> 
> Maybe the `minLength` validator could have an optional flag to say whether it should apply to empty fields? (That way, backwards compatibility can be maintained.)

This actually sounds like an elegant suggestion.

**Comment by awhitford** [comment]
When the field is truly **required**, adding `FormBuilderValidators.required(),` provides a better user interface experience.  It is better that it says, "_field must not be empty_", rather than just a "_field must be at least 4 characters._"

However, when the field is _not required_, adding the flexibility to `FormBuilderValidators.minLength` would be nice.  Maybe something like:
```dart
validators: [
              FormBuilderValidators.minLength(4, allowEmpty: true),
            ],
```

**Comment by awhitford** [comment]
I just tried using this and it did not work:
```dart
    FormBuilderValidators.minLength(4, allowEmpty: true),
```
Alas, I get a _"Value must have a length greater than or equal to 4."_ message when the field is blank.

The implementation is presently:
```dart
static FormFieldValidator minLength(
  num minLength, {
  bool allowEmpty = false,
  String errorText,
}) {
  return (valueCandidate) {
    if (allowEmpty && (valueCandidate == null || valueCandidate?.length == 0))
      return errorText ??
          "Value must have a length greater than or equal to $minLength";
    if (valueCandidate != null && valueCandidate.length < minLength) {
      return errorText ??
          "Value must have a length greater than or equal to $minLength";
    }
    return null;
  };
}
```

May I recommend this alternative:
```dart
static FormFieldValidator minLength(
  num minLength, {
  bool allowEmpty = false,
  String errorText,
}) {
  return (valueCandidate) {
    final valueLength = valueCandidate?.length ?? 0;
    if (valueLength < minLength && (!allowEmpty || valueLength > 0)) {
      return errorText ??
          "Value must have a length greater than or equal to $minLength";
    }
    return null;
  };
}
```

**Comment by danvick** [comment]
HI @awhitford,
I now see the mistake I made.

Could you be kind enough to submit a PR for this?

**Comment by awhitford** [comment]
Note that I see that you added `allowEmpty` to the `maxLength` validator too, but that is not necessary because an empty value will not trigger a max length validation.

**Comment by awhitford** [comment]
PR has been submitted.  However, please note that I was unable to completely validate it because the build is broken:
```
../lib/src/fields/form_builder_phone_field.dart:181:11: Error: No named parameter with the name 'visualDensity'.
```
I assume that this is _work in progress_.

**Comment by awhitford** [comment]
Confirmed that this now works great with version 3.10.0.  Thank you!
