### ISSUE TITLE
[feature require] add showCheckmark property for FormBuilderFilterChip

### ISSUE THREAD

**Issue by gengzhichen** [danvick/flutter_form_builder#260]
Thank you for your hard working.
For class

> FormBuilderFilterChip

Can you add new setting of `showCheckmark` for the children `FilterChip`.
The checkmark is annoying.
Thanks

**Comment by danvick** [comment]
Hi @gengzhichen,
Thanks for the suggestion I've worked on this issue and will be releasing it in the next release which, I'm hoping, is a few hours away.
