### ISSUE TITLE
Simulator builds fail for both iOS and Android after flutter upgrade - Error: The non-abstract class 'ChipsInputState' is missing implementations for these members: - TextInputClient.currentAutofillScope

### ISSUE THREAD

**Issue by ochmist** [danvick/flutter_form_builder#261]
Hello, I am on the master channel, and I just ran flutter upgrade today and everything broke. I tried downgrading but that did not work. I am using vscode. Here are my tool versions:

`Flutter 1.18.0-6.0.pre.106 • channel master • https://github.com/flutter/flutter.git
Framework • revision 84c84fb249 (15 hours ago) • 2020-04-20 21:35:01 -0400
Engine • revision 2bde4f0ae4
Tools • Dart 2.9.0 (build 2.9.0-1.0.dev a12c36dd97)`

`code build done.                                           19.7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    Compiler message:
    ../../../.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.8.0/lib/src/chips_input.dart:64:7: Error: The non-abstract class 'ChipsInputState' is missing implementations for these members:
     - TextInputClient.currentAutofillScope
    Try to either
     - provide an implementation,
     - inherit an implementation from a superclass or mixin,
     - mark the class as abstract, or
     - provide a 'noSuchMethod' implementation.`

This issue is a build blocker for us. Would appreciate a workaround if one exists.

**Comment by danvick** [comment]
Hi @ochmist,
You could consider adding the latest version of [flutter_chips_input](https://pub.dev/packages/flutter_chips_input/versions/1.9.0-dev.1#-installing-tab-) to your `pubspec.yaml` so that it overrides the one being used by this package.

**Comment by JayPerfetto** [comment]
You can also circumvent this by simply implementing flutter_chips_input directly, which is a very simple change (removing the 'chip' attribute, and changing the class to from FormBuilderChipsInput to just ChipsInput)

**Comment by ochmist** [comment]
> Hi @ochmist,
> You could consider adding the latest version of [flutter_chips_input](https://pub.dev/packages/flutter_chips_input/versions/1.9.0-dev.1#-installing-tab-) to your `pubspec.yaml` so that it overrides the one being used by this package.

This worked for me. Thank you very much.

**Comment by MaskyS** [comment]
@danvick will this package's pubspec.yaml be updated soon to eliminate this issue?

**Comment by joanofdart** [comment]
Hello,

I'm getting this error
![image](https://user-images.githubusercontent.com/43426084/84709580-b8c81e80-af62-11ea-9156-f9fc082bdf4b.png)
Is it related to the same one reported by OP?

**Comment by jaxnz** [comment]
> Hello,
> 
> I'm getting this error
> ![image](https://user-images.githubusercontent.com/43426084/84709580-b8c81e80-af62-11ea-9156-f9fc082bdf4b.png)
> Is it related to the same one reported by OP?

Yes, easiest fix is to manually add `flutter_chips_input: ^1.9.0-dev.3` to your `pubspec.yaml`

**Comment by danvick** [comment]
Yes, it is.

**Comment by rvplauborg** [comment]
I had the same issue, came here and following @jaxnz input helped.
