### ISSUE TITLE
how to change the underline color of FormBuilderDropdown

### ISSUE THREAD

**Issue by jibinjayachandran** [danvick/flutter_form_builder#262]
Hi there,
I'm a beginner in flutter.I couldn't able to change the underline color of the FormBuilderDropdown.
Please help me out.
`FormBuilderDropdown(
          attribute: "item",
          underline: Container(
            height: 1,
            width: MediaQuery.of(context).size.width,
            decoration: BoxDecoration(
                border:
                    Border(bottom: BorderSide(color: Colors.blue, width:MediaQuery.of(context).size.width))),
          ),
          hint: Text(
            "Select Item",
            style: MyStyles.DropDownTextStyle,
          ),
          isExpanded: true,
          validators: [FormBuilderValidators.required()],
          iconSize: 6 * SizeConfig.imageSizeMultiplier,
          icon: Icon(
            Icons.keyboard_arrow_down,
            color: MyColors.primaryColor,
          ),
          items: _itemsDropDownMenuItems,
        )` `

**Comment by danvick** [comment]
Hi @jibinjayachandran,
Kindly set the field's underline with `decoration` property as you would for any of the fields within FormBuilder. Here's how:
```dart
FormBuilderDropdown(
  decoration: InputDecoration(
    enabledBorder: UnderlineInputBorder(
      borderSide: BorderSide(
        color: Colors.blue,
        width: 5.0,
        style: BorderStyle.solid,
      ),
  ),
),
```

**Comment by jibinjayachandran** [comment]
thank you.
