### ISSUE TITLE
FormBuilderDateTimePicker - Can't format Input?

### ISSUE THREAD

**Issue by jobsyNZ** [danvick/flutter_form_builder#264]
Hi, 

I  assume this is  a bug with [datetime_picker_formfield](https://github.com/jifalops/datetime_picker_formfield/)  but I thought ask here first. I am currently using: 

```
      child: FormBuilderDateTimePicker(
        attribute: label,
        inputType: InputType.date,
        format: DateFormat('dd-MM-yyyy'),
        decoration: InputDecoration(
          enabledBorder: OutlineInputBorder(
            borderSide: BorderSide(color: Colors.grey[300]),
          ),
          border: OutlineInputBorder(),
          prefixIcon: Icon(Icons.calendar_today),
          labelText: label,
          hintText: label,
        ),
        onChanged: onChanged,
      ),
```

I am using the format variable with DateFormat('dd-MM-yyyy') - which works well, but if I select input, it shows as MM-dd-yyyy but returns in the correct format.

![image](https://user-images.githubusercontent.com/60025148/80447838-aa9c4f80-896e-11ea-8cd2-75398b934f2c.png)

![image](https://user-images.githubusercontent.com/60025148/80447856-bb4cc580-896e-11ea-81c2-7cb3d1beec68.png)

Also is it possible to resize the text? (this is a web app)

![image](https://user-images.githubusercontent.com/60025148/80447916-e33c2900-896e-11ea-9cbf-45985f723602.png)

**Comment by danvick** [comment]
Hi @jobsyNZ,
Kindly note that the date formating within the `TextField` is different from the formating presented by [showDatePicker()](https://api.flutter.dev/flutter/material/showDatePicker.html) dialog. 

The dialog is presented by Flutter and its formatting is controlled the app's/phone's locale. To override this formating by locale set the `locale` attribute of your `FormBuilderDateTimePicker`.

**Comment by jobsyNZ** [comment]
I have updated the Locale, and still have the same issue.

**Comment by danvick** [comment]
Hi @jobsyNZ, could you kindly update to v3.9.0 and let me know about the status of this issue.

**Comment by jobsyNZ** [comment]
@danvick thanks, the input date now matches the locale :)
