### ISSUE TITLE
How to change rating icon color?

### ISSUE THREAD

**Issue by encikpulasan** [danvick/flutter_form_builder#266]
Hi, how can i change icon color when using FormBuilderRate? 
Hope someone can help.

**Comment by danvick** [comment]
Hi @encikpulasan,
I'm afraid the [rating package we are currently using](https://pub.dev/packages/sy_flutter_widgets) makes use of your Material theme `primaryColor` and doesn't allow changing.

Not to worry though. This is something that I've been aware of and I've been working on changing the rating package to a [new one](https://pub.dev/packages/rating_bar) which comes with that and many more customizations.

I'll be releasing an update in a few hours. Thanks for your patience.

**Comment by danvick** [comment]
Kindly check out v3.9.0 which contains a fix
