### ISSUE TITLE
FormBuilderTextField Password use obscureText

### ISSUE THREAD

**Issue by bunphithak** [danvick/flutter_form_builder#271]
Hi 
i use FormBuilderTextField in crate input password and i use  **obscureText: true** in FormBuilderTextField but error **Failed assertion: line 197 pos 15: '!obscureText || maxLines == 1'**  What should I do?

**Comment by danvick** [comment]
Hi @bunphithak,
Kindly set the attribute `maxLines: 1` for `FormBuilderTextField`. That should solve it

**Comment by bunphithak** [comment]
Thank you it work
