### ISSUE TITLE
FormBuilderDateTimePicker - open keyboard

### ISSUE THREAD

**Issue by serzhikdnepr** [danvick/flutter_form_builder#274]
When you tap on the field for a moment, the keyboard (android) appears and disappears, can I remove the keyboard opening?

**Comment by janKir** [comment]
I have the same problem.

**Comment by nightfire4k** [comment]
Me2

**Comment by danvick** [comment]
Hi @serzhikdnepr et. al
Kindly try out the newly released v3.10.0 of the package which should address  this issue.

Kindly let me know of the status of the issue

**Comment by serzhikdnepr** [comment]
Hi @danvick !
Yes, the latest version solved the problem, thanks!
