### ISSUE TITLE
Change color to DateTimePicker

### ISSUE THREAD

**Issue by christianarduino** [danvick/flutter_form_builder#275]
Is it possible to change the DateTimePicker's color? I'm trying to set Theme, but doesn't work

**Comment by danvick** [comment]
Hi @christianarduino,
The package doesn't allow changing the color of DatePicker or TimePicker since the colors are automatically picked from the Theme of the surrounding context.

If setting Theme colors doesn't work, kindly share your sample code for us to try troubleshoot and isolate the cause of the problem.

**Comment by christianarduino** [comment]
I tried to do this in two ways:
**1.**
This in main.dart
```
theme: ThemeData(
          primaryColor: mainTeal,
          accentColor: mainGreen,
          appBarTheme: AppBarTheme(
            textTheme: TextTheme(
              bodyText2: TextStyle(
                color: mainBlack,
              ),
            ),
          ),
          canvasColor: Color(0xFFD8DBE2),
        ),
```

**2.**
This in FormBuilderDatePicker
```
builder: (context, child) {
                                      return Theme(
                                        data: ThemeData.light().copyWith(
                                          primaryColor: const Color(
                                            0xFF4A5BF6,
                                          ),
                                          accentColor: const Color(
                                            0xFF4A5BF6,
                                          ),
                                        ),
                                        child: child,
                                      );
                                    },
```


**Result**:
![image](https://user-images.githubusercontent.com/54827354/82126983-ba11fa00-97b0-11ea-91e5-590efb789b67.png)

Maybe is there a problem with the new DatePicker?

**Comment by danvick** [comment]
I've been not been able to reproduce this issue. Even directly copying your code to the example project works as intended.

```dart
Theme(
  data: ThemeData.light().copyWith(
    primaryColor: Colors.greenAccent,
    accentColor: Colors.deepOrange,
  ),
  child: FormBuilderDateTimePicker(
    attribute: "date",
    inputType: InputType.time,
    decoration: InputDecoration(
      labelText: "Appointment Time",
    ),
    validator: (val) => null,
    initialTime: TimeOfDay(hour: 8, minute: 0),
  ),
),
```

<img width="293" alt="image" src="https://user-images.githubusercontent.com/7383575/82127538-08c59100-97bd-11ea-9fa9-1245bb50b28b.png">

**Comment by christianarduino** [comment]
You have to try InputType.date and not InputType.time, as in the image. With InputType.time, works

**Comment by danvick** [comment]
<img width="293" alt="image" src="https://user-images.githubusercontent.com/7383575/82128383-7674bb80-97c3-11ea-99ef-49b5b87e84d2.png">

Kindly investigate the probability of the issue originating from elsewhere within your project. 

Which version of the package are you using?

**Comment by toufeeqahamedns** [comment]
Tried evrything said above, but no success.

TimePicker is showing corrent theme but DatePicker shows the default buleAccent color.

Current version 3.10.1
Flutter SDK 1.17.1

**Comment by danvick** [comment]
Noted. 

I haven't tried this package with Flutter 1.17.1 yet and because of fear of introducing breaking changes I wasn't in a hurry to.

I'm aware there are some changes to DatePicker in SDK 1.17.1, maybe this is why. I'll have a look as soon as I can.

**Comment by toufeeqahamedns** [comment]
Adding ColorScheme to ThemeData will solve the issue,

```
theme: ThemeData(
        colorScheme: ColorScheme.light(
          primary: mainTeal, //constant Color(0xFF16A5A6)
        ),
        primaryColor: mainTeal, //constant Color(0xFF16A5A6)
        accentColor: mainGreen, //constant Color(0xFF58AAAC)
        appBarTheme: AppBarTheme(
          textTheme: TextTheme(
            bodyText2: TextStyle(
              color: mainBlack,
            ),
          ),
        ),
        canvasColor: Color(0xFFD8DBE2),
      ),
```

As DatePickerHeader from the DatePickerDialog uses the default  #colorScheme to show the color.

**Comment by christianarduino** [comment]
> Adding ColorScheme to ThemeData will solve the issue,
> 
> ```
> theme: ThemeData(
>         colorScheme: ColorScheme.light(
>           primary: mainTeal, //constant Color(0xFF16A5A6)
>         ),
>         primaryColor: mainTeal, //constant Color(0xFF16A5A6)
>         accentColor: mainGreen, //constant Color(0xFF58AAAC)
>         appBarTheme: AppBarTheme(
>           textTheme: TextTheme(
>             bodyText2: TextStyle(
>               color: mainBlack,
>             ),
>           ),
>         ),
>         canvasColor: Color(0xFFD8DBE2),
>       ),
> ```
> 
> As DatePickerHeader from the DatePickerDialog uses the default #colorScheme to show the color.

It worked for me! I don't think it's a feature that needs to be implemented by the package developers, so I close the issue
