### ISSUE TITLE
Failed to Compile - flutter_chips_input

### ISSUE THREAD

**Issue by jaxnz** [danvick/flutter_form_builder#277]
Looks like an issue with flutter chips input causing my app not to compile as per my issue request:

https://github.com/flutter/flutter/issues/57275

Sorry I posted in this repository but I saw you are the creator of it, and I use form builder rather than chips directly.

**Comment by jaxnz** [comment]
Manually adding [flutter_chips_input 1.9.0-dev.1](https://pub.dev/packages/flutter_chips_input/versions/1.9.0-dev.1) to pubspec has fixed the error,

**Comment by sathishkumarjktech** [comment]
Compiler message: /F:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.8.1/lib/src/chips_input.dart:65:7: Error: The non-abstract class 'ChipsInputState' is missing implementations for these members: - TextInputClient.currentAutofillScope Try to either - provide an implementation, - inherit an implementation from a superclass or mixin, - mark the class as abstract, or - provide a 'noSuchMethod' implementation. class ChipsInputState<T> extends State<ChipsInput<T>> ^^^^^^^^^^^^^^^ /F:/flutter/packages/flutter/lib/src/services/text_input.dart:769:21: Context: 'TextInputClient.currentAutofillScope' is defined here. AutofillScope get currentAutofillScope; ^^^^^^^^^^^^^^^^^^^^ Compiler message: /F:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.8.1/lib/src/chips_input.dart:65:7: Error: The non-abstract class 'ChipsInputState' is missing implementations for these members: - TextInputClient.currentAutofillScope Try to either - provide an implementation, - inherit an implementation from a superclass or mixin, - mark the class as abstract, or - provide a 'noSuchMethod' implementation. class ChipsInputState<T> extends State<ChipsInput<T>> ^^^^^^^^^^^^^^^ /F:/flutter/packages/flutter/lib/src/services/text_input.dart:769:21: Context: 'TextInputClient.currentAutofillScope' is defined here. AutofillScope get currentAutofillScope; ^^^^^^^^^^^^^^^^^^^^ Target kernel_snapshot failed: Exception: Errors during snapshot creation: null build failed. FAILURE: Build failed with an exception. * Where: Script 'F:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896 * What went wrong: Execution failed for task ':app:compileFlutterBuildDebug'. > Process 'command 'F:\flutter\bin\flutter.bat'' finished with non-zero exit value 1 * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. * Get more help at https://help.gradle.org BUILD FAILED in 9m 45s Exception: Gradle task assembleDebug failed with exit code 1 Exited (sigterm)

**Comment by danvick** [comment]
Hi @sathishkumarjktech,
Kindly try out @jaxnz's solution above and let us know if that works for you.

The solution should work for those on Flutter channels ahead of stable.
