### ISSUE TITLE
[FormBuilderImagePicker] How do I change or remove Image after select?

### ISSUE THREAD

**Issue by zahedul** [danvick/flutter_form_builder#278]
hello,
I am using `FormBuilderImagePicker` widget. after selecting an image I want to change or remove the selected image. how can I do it?

**Comment by danvick** [comment]
Hi @zahedul,
As it is currently, the author of the widget put it in such a way that long-pressing the image is the way to remove it.

I'm aware this is a genuine concern and that this is not the best way of handling that. I, therefore, am planning to change it to make il look like FormBuilderFilePicker

**Comment by danvick** [comment]
As of v3.10.1, there's a visible delete icon on the top-right of selected images, which can be used to remove the image;

**Comment by zahedul** [comment]
sounds cool!! possible to implement set specific number of images. For example, I only need one image. if the user selects one image does not need to show image upload placeholder.

**Comment by danvick** [comment]
I'll consider having this feature included. I, however, feel that this could have been a separate issue, so that this is closed.
