### ISSUE TITLE
Change height of items in FormBuilderRadio

### ISSUE THREAD

**Issue by fabiorg74** [danvick/flutter_form_builder#280]
Hi,

it's possible change the height of FormBuilderRadio widget or add row view?

![image](https://user-images.githubusercontent.com/54955968/82121980-308a0a00-9767-11ea-8fe7-25b2f9b46379.png)

Tks :)

**Comment by danvick** [comment]
Hi @fabiorg74,
Kindly have a look at v3.10.1 which introduced an attribute `contentPadding` in Radio field, which can be used for this purpose.

**Comment by fabiorg74** [comment]
Tks Danvick :)
