### ISSUE TITLE
iOS build failed on version 3.10.1

### ISSUE THREAD

**Issue by WecanWang** [danvick/flutter_form_builder#285]
Hello,

I'm using the latest version but every time I tried to open the app in an iOS simulator it's failing. (no problem with Android). The error messages shows as following.

Failed to build iOS app
Error output from Xcode build:
↳
    2020-05-20 14:13:40.277 xcodebuild[25450:3051166] [MT] PluginLoading: Required plug-in compatibility UUID BAB79788-ACEE-4291-826B-EC4667A6BEC5 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/MarmaladeGCC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
    2020-05-20 14:13:40.277 xcodebuild[25450:3051166] Failed to load plugin at: /Users/wayne/Library/Application Support/Developer/Shared/Xcode/Plug-ins/MarmaladeGCC.xcplugin, skipping.  Reason for failure: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/Development/flutter/.pub-cache/hosted/pub.dartlang.org/phone_number-0.6.2+2/ios/Classes/SwiftPhoneNumberPlugin.swift:87:21: warning: immutable value 'error' was never used; consider replacing with '_' or removing it
            } catch let error {
                        ^~~~~
                        _
    /Users/Development/flutter/.pub-cache/hosted/pub.dartlang.org/phone_number-0.6.2+2/ios/Classes/SwiftPhoneNumberPlugin.swift:53:11: warning: 'catch' block is unreachable because no errors are thrown in 'do' block
            } catch {
              ^ 

It only works if I start the app in iOS simulator without the package first, then include the package in later. Is this a known issue?

Thanks,
Wayne.

**Comment by awhitford** [comment]
Hmmm...  That's weird because I am using 3.10.1 with no issues.  `flutter clean` didn't resolve?  It feels like stale pods.  (from `ios` folder, try `pod update`)

**Comment by WecanWang** [comment]
I've tried both of it but it's still the same, here's my flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G103, locale en-TW)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[!] VS Code (version 1.44.2)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (2 available)

**Comment by awhitford** [comment]
I am using a newer flutter, so maybe that is a factor.  Any reason why you don't `flutter upgrade`?

As a comparison, my `flutter doctor`:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)

• No issues found!
```
Note that I am using **CocoaPods version 1.9.2** -- I was using 1.9.1 before today.

Looking at your output, you have 1 error and 2 warnings.  The warnings are not going to break your build -- **the `MarmaladeGCC.xcplugin` error is your real issue**.  I'm pretty sure that has nothing to do with the `flutter_form_builder` package.

You might check this issue out:  https://github.com/pauldemarco/flutter_blue/issues/406

**Comment by WecanWang** [comment]
Thanks @awhitford , I've just upgraded to 1.17.1 and using CocoaPods 1.9.2 but it's still the same. I'm now trying to upgrade my macOS to 10.15 and the latest Xcode version to see if it works, if not I might try to recreate the iOS folder with objective-C version as the issue you reference. Thanks again!

**Comment by WecanWang** [comment]
In the end I have to create a new project and copy everything over to make it works, but it's working now so I'll close the issue.

**Comment by salvador-moreno** [comment]
Creating a new project used to work for me, but not anymore. [This workaround](https://github.com/pauldemarco/flutter_blue/issues/514#issuecomment-616975294) commented in other threads might be of help as it did to me. This is a MUST if you need to use Swift due to other packages (such as sqlite).
