### ISSUE TITLE
Required field error is not disappear after fill

### ISSUE THREAD

**Issue by jasonlaw** [danvick/flutter_form_builder#29]
Hi,
With the autovalidate = false, the required error text will not disappear even after some text are entered. It will on be disappear after hitting the submit button. Can this be improved?
Thanks in advance.

**Comment by danvick** [comment]
Hi @jasonlaw. 

I'll investigate and fix the issue as soon as I can.
Thank you for your contribution.

**Comment by danvick** [comment]
May be based on problems to do with state that I was planning to improve on in the next major version.

**Comment by EcoGames** [comment]
Pretty crucial, also good for checking the state of a form field such as if it's dirty.

**Comment by EcoGames** [comment]
And with `autovalidate: true`, when I enter the page with the form, all of the fields have errors which just doesn't look good but when I type into it, the error goes away which is good, but not how I want it so there are no good alternatives.

**Comment by cmregazzo** [comment]
Good night,

Thank you very much for the prompt reply.

Sorry for the inconvenience, but would you have a forecast for such an improvement?

Thanks.

Cristian Regazzo

**Comment by danvick** [comment]
Fixed in v4.0.0
