### ISSUE TITLE
Limit FormBuilderImagePicker

### ISSUE THREAD

**Issue by khairu-aqsara** [danvick/flutter_form_builder#291]
Ho do we limit FormBuilderImagePicker just for one image ?

**Comment by danvick** [comment]
Noted. We'll consider having a limit to the number of images picked

**Comment by peterd1954** [comment]
Yes please. I wish to allow only 1 image for some instances, other instances will require more.

**Comment by ahmednet0001** [comment]
Yes it is logic for many types of forms. I wait for this update I will use normal image_picker instead until update .

**Comment by awhitford** [comment]
How does _Image Picker_ handle multiple images?  I don't see any kind of support for it in [PickedFile](https://pub.dev/documentation/image_picker_platform_interface/latest/image_picker_platform_interface/PickedFile-class.html).
