### ISSUE TITLE
Build xcode occurred error

### ISSUE THREAD

**Issue by leewonghao** [danvick/flutter_form_builder#293]
I build a source example to device with Xcode. But an error occurred.

<img width="1174" alt="Screen Shot 2020-05-28 at 10 41 21 AM" src="https://user-images.githubusercontent.com/8869627/83096489-feb26500-a0cf-11ea-82d1-c5c5c8105b35.png">

Please help me. Thank you.

**Comment by danvick** [comment]
Hi @leewonghao,
I'm not sure this bug originates directly from this package. I'm also not an iOS expert. 

I'll, therefore, suggest that you:
1. Follow [image_picker plugin setup instructions for iOS](https://pub.dev/packages/image_picker#ios) to make sure that you haven't missed a thing, then,
2. Run `flutter clean` then rebuilding your app.

**Comment by awhitford** [comment]
This does not look like a `flutter_form_builder` issue, so closing it.
