### ISSUE TITLE
I want to pass data from one formfield to other formfield.. How can I do that ?

### ISSUE THREAD

**Issue by avinashpakala** [danvick/flutter_form_builder#296]
How do I change initial value of the formfields  during runtime?

**Comment by avinashpakala** [comment]
How do I change initial value during runtime?

**Comment by danvick** [comment]
TextFields?

**Comment by ramnath30** [comment]
Did you try something like this in the setState()?

I am doing something like below to reset the state code when the country code changes. See the line in bold below:

onChanged: (country) {
                      setState(() {
                        **_fbKey.currentState.fields['state'].currentState.setValue(null);**
                        _currentCountry = country;
                        _setStatesDropdownItems(country);
                      })

**Comment by WilliamCunhaCardoso** [comment]
Looks like it is an abandoned issue
