### ISSUE TITLE
Request: loading or in progress indicator

### ISSUE THREAD

**Issue by jasonlaw** [danvick/flutter_form_builder#30]
Hi,
Can we have a loading or in progress indicator upon submit in case the long process at the back?
Thanks in advance.

**Comment by danvick** [comment]
This is a wonderful idea. However, it may be problematic because one may want to implement the loader in different ways based on their own ideas.

We can discuss on how to have this implemented in an agnostic way, if feasible.

**Comment by jasonlaw** [comment]
May be we can have a default loader built in, with an option to turn off if the developer want to implement in their own way.
