### ISSUE TITLE
[FormBuilderImagePicker] Set Image upload limitation

### ISSUE THREAD

**Issue by zahedul** [danvick/flutter_form_builder#301]
Is it possible to implement set specific number of images?
For example, I only need one image. if the user selects one image does not need to show image upload placeholder. showing placeholder confuses the user.

thanks in advance

**Comment by awhitford** [comment]
[ImagePicker.getImage](https://pub.dev/documentation/image_picker/latest/image_picker/ImagePicker/getImage.html) only seems to be able to handle one image at a time.

**Comment by deandreamatias** [comment]
I guess that this issue is resolved by [this commit](https://github.com/danvick/flutter_form_builder/commit/82e18d1d98f3522b55212a9a5b8b2133add85096), so I it closed
