### ISSUE TITLE
Request: Map input

### ISSUE THREAD

**Issue by jasonlaw** [danvick/flutter_form_builder#31]
Can I request for a map input?
Thanks in advance.

**Comment by danvick** [comment]
I'll see how soon I can be able to implementation. 

Again, great idea. Thanks for the contribution.

**Comment by jasonlaw** [comment]
Thanks for the consideration!

**Comment by pratikpparikh** [comment]
@danvick have you made any progress on this?

**Comment by danvick** [comment]
I've created this in a separate package, have a look at it [here](https://pub.dev/packages/form_builder_map_field)
Kindly note that the package is still work in progress and suggestions and PRs are welcome.

**Comment by pratikpparikh** [comment]
@danvick,  Thank you.  I will look at it and provide updates or feedback.
