### ISSUE TITLE
Pin input

### ISSUE THREAD

**Issue by akoua** [danvick/flutter_form_builder#311]
How can I make pin input like this 
![pin](https://user-images.githubusercontent.com/40893199/84021521-51afd600-a974-11ea-9084-00b5e8a80a43.png)

**Comment by danvick** [comment]
Hello @akoua,
We currently don't have a PIN Input built into the package.

However, we have a [FormBuilderCustomInput](https://github.com/danvick/flutter_form_builder#building-your-own-custom-field) which can be used to implement any type of input that you may need to use with the package.
