### ISSUE TITLE
Initializing SignaturePad a

### ISSUE THREAD

**Issue by vin-fandemand** [danvick/flutter_form_builder#317]
How do you initialize Signature-pad. I tried passing Uint8List.fromList(<int>[]) in the intialValue, but it did not load anything. Can you please show an example ? Also, can you show and example where initial values are displayed in a read only form ?

**Comment by danvick** [comment]
Hi @vin-fandemand,
[According to the author of the signature package](https://github.com/4Q-s-r-o/signature/issues/17#issuecomment-624704979), there's no easy way of converting Uint8List to List<Point>.

To initialize the value of the signature you'd have to use `SignatureController` which only takes in `List<Point>`.

**Comment by vin-fandemand** [comment]
> Hi @vin-fandemand,
> [According to the author of the signature package](https://github.com/4Q-s-r-o/signature/issues/17#issuecomment-624704979), there's no easy way of converting Uint8List to List.
> 
> To initialize the value of the signature you'd have to use `SignatureController` which only takes in `List<Point>`.

Thanks for the reply.  I see that you have depreciated the initialValue for signature.
There is a way around. 
1. On init value show `Image.memory(Uint8List)` instead of the `Signature` widget.
2. When we press **Clear button**, show the `Signature` Widget
3. When the form is saved, show the `Image.memory(Uint8List)` again.

This way the package users don't have to do anything with the `Point` class or even import `signature` package (for the controller).

**Comment by danvick** [comment]
I've thought about doing this. But the problem with that is that users may expect that they could be able to edit the static image shown - and may be reported as unexpected behavior.

**Comment by vin-fandemand** [comment]
Yes. By making it look different when saved and not saved (one is a card with some elevation and one is signature pad, which is an inward facing white rectangle ). May be we can even have different text on the Clear button to show the difference. 
In any case, this feature would make this field inline with other fields.

**Comment by vin-fandemand** [comment]
my suggestion is that we push it and see how your package users respond. I am sure there are any out there who don't want to use Signature Controller (As you rightly described as complex) and would happily welcome this change.

**Comment by vin-fandemand** [comment]
@danvick can you please share your thoughts on it ? I believe that if you don't fix this problem in some way (whether it is my approach or some other approach), it would feel like this feature is kind of dangling

**Comment by MartinHlavna** [comment]
Another way around may be allowing users to store data as ```List<Point> ```. That would allow you to pass points to ```SignatureController```  and edit data.

But since it is signature pad and not a full featured drawing editor I can't think of use case where end user would want to edit Signature instead of making a new one.
