### ISSUE TITLE
Formbuilderslider values

### ISSUE THREAD

**Issue by leidig54** [danvick/flutter_form_builder#318]
Is there an option to remove the mix/max and current values underneath the slider? If there is I can't for the life of me fine it. If there isn't are there plans to implement this option?

Thanks,

G

**Comment by danvick** [comment]
Thanks for your suggestion @leidig54.
We'll consider doing this.

**Comment by danvick** [comment]
@leidig54,
As from v3.11.2, it is possible to select which values to display under Slider and RangeSlider through the `displayValues` attribute. The options available are `DisplayValues.all`, `DisplayValues.current`, `DisplayValues.minMax` and `DisplayValues.none`,

**Comment by leidig54** [comment]
@danvick works perfectly. thank you very much!
