### ISSUE TITLE
FormBuilderTypeAhead: can't seem to grab 'value' via valueTransformer as Object is now String

### ISSUE THREAD

**Issue by FickleLife** [danvick/flutter_form_builder#333]
I have a FormBuilderTypeAhead that is working beautifully, apart from not being able to specify the value to be entered in the actual form. In this instance, it's a list of countries and I want the 2 letter ISO code "AU" to be entered instead of the word "Australia". 

I have tried:
```dart
                    FormBuilderTypeAhead(
                      attribute: 'product.countryAlpha2ProductOf',
                      decoration: const InputDecoration(
                        labelText: 'Made in...',
                      ),
                      validators: [
                        FormBuilderValidators.required(),
                      ],
                      selectionToTextTransformer: (item) {
                        if (item is CountryData$QueryRoot$Country) {
                          return item.name;
                        } else {
                          return item;
                        }
                      },
                      suggestionsCallback: (String pattern) async {
                        //return await CountryService().getSuggestions(pattern);
                        return await model.dropdownGetCountries(pattern);
                      },
                      itemBuilder: (context, suggestion) {
                        return DropdownMenuItem(
                          child: Text(suggestion.name),
                          value: suggestion.alpha2,
                        );
                      },
                    ),
```

but it takes the name of child as the value, not value. If I change selectionToTextTransformer to return alpha2, then "AU" appears in the form (I want "Australia") but then saves as "AU" correctly.

Can anyone bump me in the right direction?

**Comment by awhitford** [comment]
Are you saying that you want the _value_ to be the 2 character ISO Code (like 'AU'), but you want the _name_ (like 'Australia') to appear?  I think you need both the `selectionToTextTransformer` and the `valueTransformer`.

I do recommend adding a _type_ to `FormBuilderTypeAhead`, like:
```dart
                    FormBuilderTypeAhead<Country>(
                      attribute: 'product.countryAlpha2ProductOf',
                      decoration: const InputDecoration(
                        labelText: 'Made in...',
                      ),
                      validators: [
                        FormBuilderValidators.required(),
                      ],
                      selectionToTextTransformer: (item) => item.code,
                      suggestionsCallback: (String pattern) async {
                        return await model.dropdownGetCountries(pattern);
                      },
                      itemBuilder: (context, country) =>
                        ListTile(
                          leading: Text(country.code),
                          title: Text(country.name),
                        ),
                    ),
```
In this example, you are choosing a `Country`, but the `code` is being used as the display text.

Also, ensure that you are using the latest version (3.11.1 or later) because there is a recent bug fix.

BTW...  Have you tried the [FormBuilderCountryPicker](https://pub.dev/documentation/flutter_form_builder/latest/flutter_form_builder/FormBuilderCountryPicker-class.html)?

**Comment by gilthonweapps** [comment]
Hi,

I am having the same issue.
Could you please explain how to use `selectionToTextTransformer` and the `valueTransformer` together?

Here is part of my code:

```
FormBuilderTypeAhead<DirectorySpeciality>(
            attribute: 'speciality',
            hideOnEmpty: true,
            itemBuilder: (context, speciality) => ListTile(title: Text(speciality.name)),
            selectionToTextTransformer: (s) => s?.name,
            suggestionsCallback: (query) async {
              if (_specialities == null) {
                _specialities = await DirectoryProvider().getSpecialities(type);
              }
              if (query.isNotEmpty) {
                return _specialities
                    .where((speciality) => speciality.name.toLowerCase()).contains(query.toLowerCase())
                    .toList(growable: false);
              }
              return _specialities;
            },
          ),
```

`DirectorySpeciality` is a class with `id` and `name`. I want to show the name on the screen but submit the id.

**Comment by FickleLife** [comment]
Thanks @awhitford for your reply (and sorry it took me a very long time to reply). @gilthonweapps the code below may help.

I've typed the `FormBuilderTypeAhead<CountryData$QueryRoot$Country>` (this type was generated by Artemis from a GraphQL schema) and added a valueTransformer but the issue seems to stem that the object is lost after `selectionToTextTransformer` is run, leaving only the string "Australia" for example. 

```
selectionToTextTransformer: (item) { // all good as the object is there
  if (item is CountryData$QueryRoot$Country) {
    return item.name;
  } else {
    return '';
  }
},
valueTransformer: (item) {  // item is a string of "Australia", object is lost
  if (item is CountryData$QueryRoot$Country) {
    return item.alpha2; // since it's a string, there is no alpha2 to reference
  } else {
    return item;
  }
},
```
Any ideas on how to maintain the object?

**Comment by FickleLife** [comment]
Looks like I can see others with this issue https://github.com/danvick/flutter_form_builder/issues/341 and @awhitford I can see your post here to typeadhead plugin https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/209 - Looks like I might have to do another look up here temporarily (at least the record should be in the cache, but yeah, not ideal). Thanks for your help

**Comment by FickleLife** [comment]
@gilthonweapps it's pretty ugly, but I have been able to work around by adding the ID in the string to be displayed and then parsing that with valueTransformer. e.g. Australia (AU) and then extracting what's in between the brackets. Like I said, ugly...

Hope that it is fixed in FlutterTypeAhead soon....

**Comment by gilthonweapps** [comment]
@FickleLife I did the same :)

**Comment by deandreamatias** [comment]
This still a issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
