### ISSUE TITLE
Some strings are not translated using locale 'it'

### ISSUE THREAD

**Issue by mattiagalati** [danvick/flutter_form_builder#334]
In my application I've declared the 'it' locale:

![image](https://user-images.githubusercontent.com/6606297/85020062-0f567800-b170-11ea-8e4f-e914932446a9.png)

and the datepicker is created with this code:

```
FormBuilderDateTimePicker(
  attribute: "date",
  enabled: state.canModifyExpense(),
  readOnly: !state.canModifyExpense(),
  inputType: InputType.date,
  
  format: DateFormat("dd/MM/yyyy"),
  initialDate: widget.modalFormData == null
      ? expense.date
      : widget.modalFormData['date'],
  firstDate: widget.modalFormData == null
      ? expense.date
      : widget.modalFormData['date'],
  lastDate: DateTime.now(),
  decoration: InputDecoration(
    labelText: Translate.getPhrase(
      context,
      "label_expense_date",
    ),
    suffixIcon: Icon(
      Icons.calendar_today,
    ),
  ),
  validators: [
    FormBuilderValidators.required(
      errorText: Translate.getPhrase(
        context,
        "field_cannot_empty",
      ),
    ),
  ],
  onChanged: (val) {
    if (val != null) {
      store.dispatch(SelectSupportingDate(val));
    }
  },
),
```

Everythings looks good but this two strings:

![image](https://user-images.githubusercontent.com/6606297/85020414-999edc00-b170-11ea-97ec-5b7fb1762bf9.png)

I'm missing some configuration?

**Comment by danvick** [comment]
Hi @mattiagalati,
This is interesting. We'll investigate.

In the meantime could you kindly try passing in your Locale through the `locale` attribute on `FormBuilderDateTimePicker` and let us know how that works for you?

**Comment by mattiagalati** [comment]
Hi @danvick ,
thanks for your interest. I've just tried the `locale` attribute without success.

The same behaviour occurs if I try to insert another (eg Russian) locale locale in my `supportedLocales` and change the `locale` attribute in `FormBuilderDateTimePicker`.
As you can see in the following image, the dialog seems to translate correctly everything but the mentioned strings:

![image](https://user-images.githubusercontent.com/6606297/85272417-70d25b80-b47c-11ea-9071-3657b778eca1.png)

**Comment by danvick** [comment]
I'm not sure if this is a `FormBuilder` specific issue or a Flutter issue.

**Comment by fpicoitoj** [comment]
Hello @danvick any news regarding this?

Hello @mattiagalati have you found a workaround in the meantime?

**Comment by deandreamatias** [comment]
This still a issue?
