### ISSUE TITLE
FormBuilderPhoneField

### ISSUE THREAD

**Issue by BigBrosh** [danvick/flutter_form_builder#336]
There are few issues with FormBuilderPhoneField in flutter_form_builder 3.11.2

Code to reproduce:
```
final GlobalKey<FormBuilderState> signIn = GlobalKey<FormBuilderState>();

FormBuilder(
    key: signIn,
    child: Column(
        children: <Widget> [
            FormBuilderPhoneField(
                attribute: 'phone',
                decoration: InputDecoration(labelText: 'Phone', hintText: 'Enter your phone'),
            ),
            FormBuilderTextField(
                attribute: 'password',
                maxLines: 1,
                obscureText: true,
                textInputAction: TextInputAction.done,
                onFieldSubmitted: (_) {},
                decoration: InputDecoration(labelText: 'Password', hintText: 'Enter your password'),
                validators: [
                    FormBuilderValidators.required()
                ]
            )
        ]
    )
),
```

Issues:
1. It allows me to enter more symbols than should be allowed per phone number. It actually doesn't have limits
2. Nothing happens when I click "done" on keyboard (expecting keyboard to be hidden)
3. Focus phone field then focus text field. Focus occurs on both fields. After this you can even click back on phone field, start typing and after first tap focus will come back to text field

**Comment by awhitford** [comment]
I am aware of a Focus issue that was introduced in version 3.11.2.  Until a newer version is released, I recommend reverting to 3.11.1.

**Comment by BigBrosh** [comment]
Unfortunately facing this issue in previous versions as well

**Comment by BigBrosh** [comment]
I just noticed that it breaks FocusScope somehow
In my fields I have logic for `FocusScope.of(context).nextFocus()` if it's not last field
When I submit phone field it stops working and doesn't change the focus on any field

**Comment by xJon** [comment]
This is still an issue with `3.11.3`.

**Comment by BigBrosh** [comment]
@awhitford do you have any updates on this?

**Comment by awhitford** [comment]
The focus issue that I mentioned was resolved.  If you still have an issue with the latest version, then it is a different issue.

I personally have other outstanding focus issues that I need to dig into.  I was hoping that Flutter framework would provide better focus support, but I haven't seen it yet.

**Comment by deandreamatias** [comment]
This still a issue?

**Comment by deandreamatias** [comment]
Without response and because this issue is related to a old version, will close
