### ISSUE TITLE
FormBuilderDropdown does not remove underline

### ISSUE THREAD

**Issue by kleberapsilva** [danvick/flutter_form_builder#338]
FormBuilderDropdown(
                                                attribute: 'player',
                                                controller.initialValuePlayer : null,
                                             
                                                underline: Container(
                                                  height: 0,
                                                  width: 0,
                                                ),

**Comment by danvick** [comment]
Hi @kleberapsilva,
In `FormBuilderDropdown` the underline is ignored - it was an oversight issue to leave the option available.

To make changes to the line under any field consider using InputDecorator border options.
