### ISSUE TITLE
FormBuilderImagePicker bottom sheet does not respect bottom safe area

### ISSUE THREAD

**Issue by OpticNectar** [danvick/flutter_form_builder#339]
The `FormBuilderImagePicker` control when clicked opens up a bottom sheet, but it goes under the gesture bar on iOS. It just needs to use safe area so that it has more padding on the bottom for devices that need it.

**Comment by danvick** [comment]
As of v3.11.5, you can adjust `bottomSheetPadding` so as not to be affected by SafeArea.
