### ISSUE TITLE
Hot reload not work

### ISSUE THREAD

**Issue by ua4ever** [danvick/flutter_form_builder#34]
In the debugging app using hot reload, if i add new formbuilderinput then i reload app using hot reload, it's not working properly. Please fix this, cause this is slow down the time for developer.

I'm sorry my English is bad.

**Comment by danvick** [comment]
I'm working on a solution for this as soon as possible, thanks for your patience.

Thanks for your contribution and sorry for the inconvenience.

**Comment by danvick** [comment]
Hi @ua4ever,
Kindly try out version 3 of the package on pub which solves this issue.
