### ISSUE TITLE
FormBuilderTypeAhead<T> erroneously transforming T to String for Attribute Value

### ISSUE THREAD

**Issue by awhitford** [danvick/flutter_form_builder#341]
The following code illustrates a **bug** with `FormBuilderTypeAhead<T>` when `T` is not a `String`.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FFB TypeAhead Bug',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key key}) : super(key: key);
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

/// This is a Value Class for a Photo.
/// It is a simplification just to illustrate the bug with FormBuilderTypeAhead.
class Photo {
  final String path;
  final int width;
  final int height;

  const Photo({
    this.path,
    this.width,
    this.height,
  });
}

class _MyHomePageState extends State<MyHomePage> {
  final GlobalKey<FormBuilderState> _fbKey = GlobalKey<FormBuilderState>();

  /// Some sample data...
  final allPhotos = [
    Photo(path: 'ABC123.png', width: 300, height: 200),
    Photo(path: 'DEF456.png', width: 400, height: 300),
    Photo(path: 'XYZ789.png', width: 500, height: 500),
  ];

  Widget _buildForm() {
    return FormBuilder(
      key: _fbKey,
      child: Column(
        children: <Widget>[
          // Note that the TYPE for FormBuilderTypeAhead is a Photo!
          FormBuilderTypeAhead<Photo>(
            attribute: 'photo',
            initialValue: allPhotos[1],
            decoration: InputDecoration(
              icon: const Icon(Icons.photo_library),
              labelText: 'Photo',
            ),
            itemBuilder: (BuildContext context, Photo photo) {
              return ListTile(
                leading: const Icon(Icons.photo_camera),
                title: Text(photo.path),
                subtitle: Text('${photo.width} x ${photo.height}'),
              );
            },
            selectionToTextTransformer: (photo) => photo?.path,
            suggestionsCallback: (query) {
              if (query.isNotEmpty) {
                return allPhotos.where((photo) => photo.path.contains(query));
              } else {
                return [];
              }
            },
          ),
          ButtonBar(
            children: <Widget>[
              RaisedButton(
                child: Text('Submit'),
                onPressed: () {
                  if (_fbKey.currentState.saveAndValidate()) {
                    final formValues = _fbKey.currentState.value;
                    // You will see a String instead of a Photo
                    print('photo value: ${formValues['photo']}');
                    final photo = formValues['photo'];
                    // The bug is that this assertion fails because somehow a
                    // Photo is being transformed into a String
                    assert(photo is Photo);
                  }
                },
              ),
            ],
          )
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('FFB TypeAhead Bug'),
      ),
      body: _buildForm(),
    );
  }
}
```

In summary, the _form field value_ should be of type `T`, but the value is somehow being transformed into a `String`.  I know that the `selectionToTextTransformer` will transform a `T` into a `String`, but that should just be for the Text Controller (`_typeAheadController.text`), and not the actual attribute value.

I've traced the source code and I honestly can't find the problem.  Consider [this code](https://github.com/danvick/flutter_form_builder/blob/master/lib/src/fields/form_builder_typeahead.dart#L142):
```dart
      onSaved: (val) {
        var transformed;
        if (widget.valueTransformer != null) {
          transformed = widget.valueTransformer(val);
          _formState?.setAttributeValue(widget.attribute, transformed);
        } else {
          _formState?.setAttributeValue(widget.attribute, val);
        }
        if (widget.onSaved != null) {
          widget.onSaved(transformed ?? val);
        }
      },
```
In my example, `val` is a `Photo`.  You can see that when there is no `valueTransformer`, the `_formState?.setAttributeValue(widget.attribute, val);` should be setting the `photo` attribute to be the selected `Photo` object.  This may be working fine, but then something else is ruining the value by transforming it into a String again.

If I specify an `onSaved` method, [`widget.onSaved(transformed ?? val);`](https://github.com/danvick/flutter_form_builder/blob/master/lib/src/fields/form_builder_typeahead.dart#L145) throws an exception because `type 'String' is not a subtype of type 'Photo'` -- meaning that `onSaved` is being passed a `String` instead of `T`.

So `onSaved` and `formValues` are consistently storing a String, rather than the T type.  However, I don't think that is correct.

🤔  _Am I missing something?_

**Comment by awhitford** [comment]
I am afraid that the underlying `flutter_typeahead` module is insufficient.  See https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/209.

**Comment by awhitford** [comment]
Commit d785b697bc84a33cc77fdf28aa924a5ba9b1608d broke this scenario even further because now the text editing controller value (which is a String) is being used as the `initialValue`. 🤦 

If `T` must be a `String`, then remove `T` and hard-code the `String` type.

**Comment by awhitford** [comment]
Alternatively, if you need to keep [Line 108](https://github.com/danvick/flutter_form_builder/commit/d785b697bc84a33cc77fdf28aa924a5ba9b1608d#diff-e1008108bed18431ca83691c2ea12ee8R108) then we need another function that translates the `_typeAheadController.text` to `T`.  (The `selectionToTextTransformer` translates `T` to `String` -- we need the opposite.)

**Comment by awhitford** [comment]
I just noticed another related bug:  despite passing a non-null `initialValue`, the value (`_formKey.currentState.value['attribute_name'];`) is null -- unless I interact with the field to trigger some kind of population.  😠 I'm pretty sure this was working before.

**Comment by awhitford** [comment]
In my use case, I need an _async_ function to translate `String` to `T`.  This is feeling impossible.

**Comment by awhitford** [comment]
OK, I just figured out why my value was null.  It was because I introduced a hack as a workaround to the [Line 108](https://github.com/danvick/flutter_form_builder/commit/d785b697bc84a33cc77fdf28aa924a5ba9b1608d#diff-e1008108bed18431ca83691c2ea12ee8R108) change.

@danvick Can you please elaborate on why you made that change?
```dart
    _initialValue = widget.initialValue ??
        _typeAheadController.text ??
        ((_formState?.initialValue?.containsKey(widget.attribute) ?? false)
            ? _formState.initialValue[widget.attribute]
            : null);
```
The logic does not seem sound because `_typeAheadController` will be not null (see line 102), and I think text will be an empty string, not a null, so form initialValue will not be read.

Maybe you mean to say `widget.controller?.text` instead?  Because that may be null when the controller is not provided.

**Comment by danvick** [comment]
Noted. Thanks for the keen eye again @awhitford.

**Comment by awhitford** [comment]
@danvick I truly appreciate the fix to `initialValue`, but the original issue raised here remains.

I thought I could solve it by adding a `valueTransformer`, however in my real solution I need an asynchronous version, which seems impossible.

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
