### ISSUE TITLE
Signature To PNG or JPG

### ISSUE THREAD

**Issue by TafadzwaD** [danvick/flutter_form_builder#345]
How do i save the image to JPEG or any other image format?

Thanks you for this wonderful package @danvick

**Comment by danvick** [comment]
Hi @TafadzwaD,
`Image image = Image.memory(data);` will do the trick.

PS: I'm glad you find the package useful.

**Comment by danvick** [comment]
For reference purposes, this is a duplicate of #218

**Comment by TafadzwaD** [comment]
Thank you for the prompt response @danvick . Worked for me!!!👏👏👏👏👏👏👏
