### ISSUE TITLE
CountryPicker

### ISSUE THREAD

**Issue by gilthonweapps** [danvick/flutter_form_builder#346]
Hi,

You should switch to this package for country picker --> https://github.com/imtoori/CountryCodePicker
It allows internationalization :)

**Comment by danvick** [comment]
Thanks for your suggestion @gilthonweapps.

I think this will solve the issue you raised had in #335.

**Comment by danvick** [comment]
Noted. Thanks for the suggestion

**Comment by gilthonweapps** [comment]
In fact, this one is better: https://pub.dev/packages/country_codes

It uses code from Android/iOS to get the list of countries translated into the device language.

**Comment by gilthonweapps** [comment]
The package I gave in my previous post is not really good.
This one is definitely better: https://pub.dev/packages/iso_countries
It will return all the countries in any language.
