### ISSUE TITLE
How to display entire text when using "labelText" attribute

### ISSUE THREAD

**Issue by Clid3** [danvick/flutter_form_builder#349]
"**labelText**" doesn't display the entire text when the text is long. 
Is there any way i can display the entire text?
Here is an example of what i Mean
![question1](https://user-images.githubusercontent.com/30189267/86131235-4d8f5800-badd-11ea-817b-2d86e07f7fb0.png)

**Comment by danvick** [comment]
Hi @Clid3,
This is a Flutter issue because a multiline `labelText` is not provided.

I'd suggest you use a `Text` widget above the field if you have a long `labelText`

**Comment by Clid3** [comment]
Thanks @danvick .
