### ISSUE TITLE
Support interface for state

### ISSUE THREAD

**Issue by danielwalczak** [danvick/flutter_form_builder#352]
Would be great to be able to define state using Class interface instead of having value like `Map<String, dynamic>`.

**Comment by danvick** [comment]
I'm not sure how using a Class interface would work given every user of the package would have their own class implementation and there are those that may not exactly want their data to be in a class.

It would be better for you, if you want to use a class, to have a `fromJson()` and `toJson()` implementation within your class.

If you have figured out how a class interface could be incorporated, kindly raise a PR and we'll review. In the meantime, I'm gonna shelf this.

**Comment by danvick** [comment]
Similar to #276
