### ISSUE TITLE
Selected Color overwrites background and textcolor in FormBuilderChoiceChip

### ISSUE THREAD

**Issue by SchnMar** [danvick/flutter_form_builder#354]
Hey,

first of all: Thank you very much for this great plugin! I'm using it in my app and it works great.

At the moment I'm trying to use a FormBuilderChoiceChip with a selected Color. When I select one FormBuilderFieldOption both, the backgroundColor and the text turn blue. How can I make this work? Is it a bug? I only want the background to be blue.

Thank you!
Marcel

```
 FormBuilderChoiceChip(
          attribute: "someAttribute",
          alignment: WrapAlignment.center, spacing: 6.0,
          selectedColor: Colors.blue,
          decoration: InputDecoration(
            enabledBorder: UnderlineInputBorder(
              borderSide: BorderSide(
                style: BorderStyle.none,
              ),
            ),
          ),
          options: [
            FormBuilderFieldOption(
              child: Text("Yes"),
              value: 'yes',
            ),
            FormBuilderFieldOption(
              child: Text("No"),
              value: LegalActionTakenType.no,
            ),
            FormBuilderFieldOption(
              child: Text("I don't know"),
              value: LegalActionTakenType.unknown,
            ),
          ],
        ),
```

**Comment by danvick** [comment]
Hi @SchnMar,
First of all thanks for the kind words. It makes me happy when people all over the world find this package useful.

You're having the issue because probably your theme's primary color is blue. The label for Flutter's ChoiceChip widget takes your primary color when selected. 
Setting blue as your `selectedColor` means that both the label and the background color are blue in color.

**Comment by danvick** [comment]
There are two possible solutions: you can either change the `selectedColor` to a different shade of blue (e.g. `Colors.blue[100]`) or on your app theme, change the color attribute of `ChipTheme.labelStyle` to change the text color.

**Comment by SchnMar** [comment]
Hey @danvick,

this solved my problem. Thank you!
