### ISSUE TITLE
Error with 'TextTheme'.

### ISSUE THREAD

**Issue by maituongan11zz** [danvick/flutter_form_builder#355]
I cannot use form builder because this error. Anyone has the same problem with me??? Please help. Thanks a lot.
![image](https://user-images.githubusercontent.com/43066513/86534251-457e5080-bf01-11ea-8f70-b7ba6d58172d.png)

**Comment by danvick** [comment]
I think it's because you are using a lower version of Flutter SDK - pre 1.17.*. Consider upgrading to at least the latest stable version.
