### ISSUE TITLE
Request: Camera/photo picker

### ISSUE THREAD

**Issue by jasonlaw** [danvick/flutter_form_builder#36]
Hi @danvick 

Do you think it is possible to put camera/photo picker as part of your todo list?
For the time being, it would helping a lot if there is a custom input widget support, so we can handle any input which is not ready yet in the library. 

Fyi, I am currently working on a forum/discussion like module, which camera/photo upload is one of the common feature. 
The photo/image will be stored in Base64 string, so I guess that is how you could save the value. However, I am displaying the image with the URL reference.

Thank you!

**Comment by awhitford** [comment]
I would be interested in this too -- if it truly makes sense.

**Comment by danvick** [comment]
v3.9.0 contains this feature.
