### ISSUE TITLE
[Sliders] Whole Numbers?

### ISSUE THREAD

**Issue by kg551915** [danvick/flutter_form_builder#361]
How do I get the slider's (FormBuilderRangeSlider & FormBuilderSlider)  to use only whole numbers? such as the range of only: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10.

**Comment by danvick** [comment]
To do this you need to set the `divisions` attribute. For example, if you have your `min` as 1 and `max` as 10, setting divisions as 10 will divide the slider into 10 equal parts.
