### ISSUE TITLE
Error when selecting option from FormBuilderChipsInput

### ISSUE THREAD

**Issue by jasonspick** [danvick/flutter_form_builder#362]
I can't seem to solve this. I am able to render and build no problem, but as soon as I select a suggestion the whole app crashes.

![image](https://user-images.githubusercontent.com/4552494/86944464-6dda9a80-c10d-11ea-8a55-731c04f63a6b.png)
![image](https://user-images.githubusercontent.com/4552494/86944495-76cb6c00-c10d-11ea-8573-235b3e3e2e68.png)

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
