### ISSUE TITLE
FormBuilderDropDown width

### ISSUE THREAD

**Issue by ialameh** [danvick/flutter_form_builder#365]
Hi, 
The formbuilderdropdown size is always taking the available space, I have tried to trace if there is anything stretching it and could not figure it out, here is my tree and how it looks like and the code

```
FormBuilderDropdown(
                  isDense: true,
                  attribute: 'frequency',
                  initialValue:
                  StatementsStrings.kPaymentFrequencies[
                  StatementsStrings.FORTNIGHTLY],
                  onChanged: (value)=>{},
                  decoration: kDropDownInputDecoration(
                      suffix: StatementsStrings.kValuesShownHere),
                  items: StatementsStrings
                      .kPaymentFrequencies.entries
                      .map((e) {
                    print('${e.key}   ${e.value}');
                    return DropdownMenuItem(
                        child: Text(
                          e.key,
                          style: kText14SemiBold101519,
                        ),
                        value: e.value);
                  }).toList(),
                ),
```

Is there a simple way to minimise the width of the dropdown? 
![image](https://user-images.githubusercontent.com/713669/87496980-f28e6100-c697-11ea-8256-78630a85edbd.png)
![image](https://user-images.githubusercontent.com/713669/87497183-6e88a900-c698-11ea-8851-822053ccd862.png)
![image](https://user-images.githubusercontent.com/713669/87497249-8d873b00-c698-11ea-8e30-04a49830ee8d.png)

**Comment by danvick** [comment]
I'd suggest, if you don't want to have it take the whole width, to put your widgets in a `Row`. By default, all `FomField` widgets take the available width.

**Comment by ialameh** [comment]
thank you
