### ISSUE TITLE
The non-abstract class 'ChipsInputState' is missing implementations for these members:  - TextInputClient.currentAutofillScope

### ISSUE THREAD

**Issue by paulowender** [danvick/flutter_form_builder#367]
I changed the flutter channel to beta for use flutter web and have this issue
Compiler message:
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.8.3/lib/src/chips_input.dart:88:7: Error: The non-abstract class 'ChipsInputState' is missing implementations for these members:
 - TextInputClient.currentAutofillScope
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ChipsInputState<T> extends State<ChipsInput<T>>
      ^^^^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/services/text_input.dart:769:21: Context: 'TextInputClient.currentAutofillScope' is defined here.
  AutofillScope get currentAutofillScope;
                    ^^^^^^^^^^^^^^^^^^^^

**Comment by danvick** [comment]
Kindly use the dev version of `flutter_chips_input`. [https://github.com/danvick/flutter_chips_input/issues/37](https://github.com/danvick/flutter_chips_input/issues/37)
