### ISSUE TITLE
[4.0.0-alpha.5] Error when setting the FormBuilderLocalizations.delegate

### ISSUE THREAD

**Issue by jasonlaw** [danvick/flutter_form_builder#369]
Hi,

I hit the error after setting the FormBuilderLocalizations.delegate in MaterialApp.
Am I missing anything?

![image](https://user-images.githubusercontent.com/107820/87865205-0cd08380-c9a5-11ea-8ac1-9648397ff11a.png)

**Comment by danvick** [comment]
Interesting. This would mean that your app's locale couldn't be accessed. Very interesting.

Thanks for bringing this to my attention.

**Comment by danvick** [comment]
Should be fixed in 4.0.0-alpha.6

**Comment by jasonlaw** [comment]
It is working fine now. Well done! Thanks!
