### ISSUE TITLE
[4.0.0-alpha.5] Form fields does not take the initialValues from FormBuilder

### ISSUE THREAD

**Issue by jasonlaw** [danvick/flutter_form_builder#370]
Hi,

Aren't the form fields suppose to take the initialValue from FormBuilder?

I have passed in the initialValues into FormBuilder, but the text field seems not referring to the values.

Here is my code snippet: 

FormBuilder(
        formKey: fkey,
        initialValue: App.auth.data,
        children: <Widget>[
          FormBuilderTextField(
            attribute: App.auth.userName.attribute,
            decoration: InputDecoration(labelText: App.auth.userName.label),
          ),
          FormBuilderTextField(
            attribute: App.auth.displayName.attribute,
            decoration: InputDecoration(labelText: App.auth.displayName.label),
          ),
        ],)

**Comment by jasonlaw** [comment]
Somehow, after several flutter clean, the issue is resolved. Closing the issue now.

**Comment by jasonlaw** [comment]
Somehow, this issue pop out again.
Since I was testing both pre 4 version and alpha version before, to be safe, I clear all the local cache and make sure the environment is clean with only alpha version. 
Could you please take a look into this and confirm it is either a bug or not?
p/s: i am using the alpha 6 now for the testing.

**Comment by danvick** [comment]
The bug seems to be on the TextField only. Could you kindly confirm this?

**Comment by jasonlaw** [comment]
Hi @danvick ,
My form is quite simple, and only contains TextField.
So yes, it could probably only happens on TextField.
I did trace the debug, it seems TextField has overridden all the attributes, could that be the culprit?
Thanks.

**Comment by danvick** [comment]
Should be okay now in v4.0.0-alpha.7. It was only TextField.

It wasn't because of the overrides.

**Comment by jasonlaw** [comment]
Thanks. :)
