### ISSUE TITLE
Renaming attribute to name in v4.0.0

### ISSUE THREAD

**Issue by danvick** [danvick/flutter_form_builder#374]
It's my plan to rename the attribute named `attribute` in form fields to `name` in v4.

Any thoughts or objections? 

@jasonlaw? @awhitford? @VOIDCRUSHER? Anyone?

**Comment by jasonlaw** [comment]
I am fine with that. :)

**Comment by VOIDCRUSHER** [comment]
While I'm onboard for renaming the field, I feel that "name" could get confused with "label" terminology when more than a name, this parameter is really being used as a key for the field under the form in scope. So maybe something like "fieldKey" would be more appropriate?

**Comment by danvick** [comment]
I get your point @VOIDCRUSHER. I, however, think that including the term `key` in the name is still not the best idea since Flutter has its own Keys and may still bring confusion.

You'll notice that with this library my aim was to make Flutter forms as easy as HTML forms, hence most concepts and naming is either borrowed from HTML or [Angular's Reactive Forms](https://angular.io/guide/reactive-forms) - mostly since a good number of Flutter users have a web background. 

The idea of naming it `name` is will actually be borrowed from HTML inputs, where there doesn't seem to be a lot of confusion between the `name` attribute within the `<input>` element and the `<label>` element.

**Comment by awhitford** [comment]
Sorry, this ended up in my spam folder, but I also prefer `name`. 👍 

(Using `key` could get confusing since Flutter has fleshed _Key_ concepts already and it has nothing to do with that.)
