### ISSUE TITLE
FormBuilderFieldOption child does not work

### ISSUE THREAD

**Issue by josoma03** [danvick/flutter_form_builder#376]
Hi,
FormBuilderFieldOption inside FormBuilderRadioGroup, does not work as expected.

```dart
return FormBuilderRadioGroup(
          decoration: InputDecoration(labelText: 'Accept the terms'),
          attribute: "answer",
          initialValue: '',
          onChanged: _onChanged,
          options: [
            FormBuilderFieldOption(value: '0', child: Text('No')),
            FormBuilderFieldOption(value: '1', child: Text('Yes')),
          ]);
```
'child' don't work:

![Screen Shot 07-23-20 at 09 07 AM](https://user-images.githubusercontent.com/8276103/88296187-fa678a00-ccc3-11ea-9f0a-a28c8bfebcb0.PNG)

Thanks

**Comment by Shiba-Kar** [comment]
> Hi,
> FormBuilderFieldOption inside FormBuilderRadioGroup, does not work as expected.
> 
> ```dart
> return FormBuilderRadioGroup(
>           decoration: InputDecoration(labelText: 'Accept the terms'),
>           attribute: "answer",
>           initialValue: '',
>           onChanged: _onChanged,
>           options: [
>             FormBuilderFieldOption(value: '0', child: Text('No')),
>             FormBuilderFieldOption(value: '1', child: Text('Yes')),
>           ]);
> ```
> 
> 'child' don't work:
> 
> ![Screen Shot 07-23-20 at 09 07 AM](https://user-images.githubusercontent.com/8276103/88296187-fa678a00-ccc3-11ea-9f0a-a28c8bfebcb0.PNG)
> 
> Thanks

It Works perfectly Fine here !!! try doing a clean ```flutter clean```

**Comment by marceloreis13** [comment]
I'm facing the same error, but with FormBuilderFieldOption
