### ISSUE TITLE
FormBuilderDateTimePicker format input AM/PM

### ISSUE THREAD

**Issue by josoma03** [danvick/flutter_form_builder#377]
Hi, FormBuilderDateTimePicker set format "h:mm a", 
Formatted date works fine.
Graphic control does not display the correct format.

```dart
return FormBuilderDateTimePicker(
      alwaysUse24HourFormat: false,
      attribute: 'date',
      onChanged: (value) {
        print(value);
      },
      format: DateFormat("h:mm a"),
      inputType: InputType.time,
      initialTime: TimeOfDay(hour: 8, minute: 0),
    );
```

![Screen Shot 07-23-20 at 11 03 AM](https://user-images.githubusercontent.com/8276103/88309806-7964be80-ccd4-11ea-9cd5-a76b735d095b.PNG)
![Screen Shot 07-23-20 at 11 04 AM](https://user-images.githubusercontent.com/8276103/88309811-7b2e8200-ccd4-11ea-89d7-8818d48a900c.PNG)

**Comment by danvick** [comment]
To switch between 12 and 24-hour modes in TimePicker, all you need to do is toggle `alwaysUse24HourFormat` attribute. The `format` attribute is used only within the TextField.
