### ISSUE TITLE
Error: No named parameter with the name 'focusNode'.

### ISSUE THREAD

**Issue by zenkog** [danvick/flutter_form_builder#385]
I got this error when building the Flutter app:

```
../../../../Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_form_builder-3.12.0/lib/s
rc/fields/form_builder_chips_input.dart:138:11: Error: No named parameter with the name 'focusNode'.
[        ]           focusNode: widget.focusNode,
[        ]           ^^^^^^^^^
[        ]
../../../../Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_chips_input-1.9.0-dev.1/l
ib/src/chips_input.dart:13:3: Context: Found this candidate, but the arguments don't match.
[        ]   ChipsInput({
[        ]   ^^^^^^^^^^
[  +66 ms]
../../../../Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_form_builder-3.12.0/lib/s
rc/fields/form_builder_range_slider.dart:21:9: Error: 'RangeSemanticFormatterCallback' isn't a type.
[        ]   final RangeSemanticFormatterCallback semanticFormatterCallback;
```

I'm using `flutter_form_builder: ^3.12.0`

And here is my flutter doctor:
```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.37, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.21.0-6.0.pre.37 at /Applications/flutter
    • Framework revision 35e7005184 (3 days ago), 2020-07-25 09:44:17 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Applications/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Applications/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2-dev.3
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.0

[✓] Connected device (3 available)
    • iPhone SE (2nd generation) (mobile) •  • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • Web Server (web)                    • web-server                           • web-javascript •
      Flutter Tools
    • Chrome (web)                        • chrome                               • web-javascript •
      Google Chrome 84.0.4147.89

• No issues found!
```

**Comment by danvick** [comment]
Kindly use the latest pre-release version of flutter_chips_input which at this time is [1.9.0-dev.3](https://pub.dev/packages/flutter_chips_input/versions/1.9.0-dev.3)

**Comment by zenkog** [comment]
Thanks for the answer. But I’m not even using the flutter_chips_input  dependency in my pubspec.yaml. Isn’t it managed by the package as a whole?

**Comment by danvick** [comment]
Because you are using a version of Flutter above 1.17, kindly use `^3.13.0` of this package.

**Comment by zenkog** [comment]
Hi, I followed your suggestions to change the version to `^3.13.0` but then I got this error message in XCode 
```
/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_form_builder-3.13.1/lib/src/fields/form_builder_range_slider.dart:21:9: Error: Type 'RangeSemanticFormatterCallback' not found.
      final RangeSemanticFormatterCallback semanticFormatterCallback;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  /development/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_form_builder-3.13.1/lib/src/fields/form_builder_range_slider.dart:21:9: Error: 'RangeSemanticFormatterCallback' isn't a type.
      final RangeSemanticFormatterCallback semanticFormatterCallback;
```

**Comment by zenkog** [comment]
> Hi, I followed your suggestions to change the version to `^3.13.0` but then I got this error message in XCode
> 
> ```
> /development/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_form_builder-3.13.1/lib/src/fields/form_builder_range_slider.dart:21:9: Error: Type 'RangeSemanticFormatterCallback' not found.
>       final RangeSemanticFormatterCallback semanticFormatterCallback;
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   /development/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_form_builder-3.13.1/lib/src/fields/form_builder_range_slider.dart:21:9: Error: 'RangeSemanticFormatterCallback' isn't a type.
>       final RangeSemanticFormatterCallback semanticFormatterCallback;
> ```
> 
> Moreover, previously I have commented out the `focusNode` and two other properties then it worked. But now since I upgraded flutter to latest version it breaks with the above error message.
> 
> ```
> [✓] Flutter (Channel dev, 1.21.0-7.0.pre, on Mac OS X 10.15.6 19G73, locale en-US)
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.6)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 4.0)
> [✓] VS Code (version 1.47.3)
> [✓] Connected device (3 available)
> ```

I solved the issue by going to the file `/flutter_form_builder-3.13.1/lib/src/fields/form_builder_range_slider.dart`
and change `RangeSemanticFormatterCallback` to `SemanticFormatterCallback`

And this happened because flutter upgrade changed it. It is a material class.

It must be a headache to keep up with all the breaking changes caused by flutter upgrades. Keep up the good work @danvick !
