### ISSUE TITLE
Cannot set value to FormBuilderTextField at runtime

### ISSUE THREAD

**Issue by kvbogdanov** [danvick/flutter_form_builder#386]
There is a form with a text field:
```
FormBuilder(
 key: _fbKey,
 child: 

....

     FormBuilderTextField(
       attribute: "diameter",
       keyboardType: TextInputType.number, 
       initialValue: '10',
       validators: [
          FormBuilderValidators.numeric(),
          FormBuilderValidators.max(1000),
      ],                                              
   ),
....
)
```

Trying to set value in this field in such way:

`_fbKey.currentState.fields['diameter'].currentState.didChange("22");`

Expected that value in text filed changed from "10" to "22", but nothing happens. This works fine for other inputs like checkboxes, sliders etc. but not for simple text input.

**Comment by danvick** [comment]
Hi @kvbogdanov,
Unfortunately, this isn't how `FormField.didChange()` works in Flutter. The function is called when the field value is changed on UI and its purpose is to set the value internally - it, however, doesn't work the other way around.

I'd suggest that you use a `TextEditingController` for that purpose.

**Comment by danvick** [comment]
Sorry for the misinformation, `FormField.didChange()` should work for most other fields, but not all. The exceptions should include `FormBuilderTextField` and `FormBuilderSignature`
