### ISSUE TITLE
FormBuilderRadio vs FormBuilderRadioGroup

### ISSUE THREAD

**Issue by awhitford** [danvick/flutter_form_builder#389]
From the [README](https://github.com/danvick/flutter_form_builder/blob/master/README.md):
> FormBuilderRadio - Used to select one value from a list of Radio Widgets
FormBuilderRadioGroup - Used to select one value from a list of Radio Widgets

😕 What's the difference?

**Comment by awhitford** [comment]
`FormBuilderRadio` lists the options **vertically** (column), vs `FormBuilderRadioGroup` lists the option **horizontally** (row).

**Comment by danvick** [comment]
`FormBuilderRadio` was the initial control that uses a ListView underneath therefore the options are shown vertically. Due to the need for more layout options, we included `FormBuilderRadioGroup` which was initially based on the package [group_radio_button](https://pub.dev/packages/group_radio_button) which also had a different API than the initial Radio field.

The package, however, proved insufficient for our purpose and we retired it and built our own implementation. 

Note that `FormBuilderRadioGroup` allows for both orientations using the `orientation` attribute. 

I agree we need to make the distinction clear in README. 

I think we should also deprecate `FormBuilderRadio`.

**Comment by danvick** [comment]
Same applies to `FormBuilderCheckboxList` and `FormBuilderCheckboxGroup`

**Comment by awhitford** [comment]
I support deprecating to avoid confusion.

Unfortunately, I'm running into a problem when my `FormBuilderFieldOption` `child` is a `ListTile`.

> BoxConstraints forces an infinite width.

One day, I will figure this out... 😕

**Comment by awhitford** [comment]
I resorted to [StackOverflow](https://stackoverflow.com/questions/63236286/how-to-constrain-listtile-in-widget-hierarchy) for some advice, but I'm still not happy...  😩 

When I replaced my `FormBuilderRadio` with `FormBuilderRadioGroup` (and specified the `orientation: GroupedRadioOrientation.vertical`), my render blows up because (in this case) my `FormBuilderFieldOption` `child` is a `ListTile`.  Normally, I simply wrap the offending infinite width widget in an `Expanded`, but that is not working here.

I _can_ solve the layout problem if the [`GestureDetector`](https://github.com/danvick/flutter_form_builder/blob/master/lib/src/widgets/grouped_radio.dart#L276) was wrapped in `Expanded`.

_Should we add a flag to optionally wrap the `GestureDetector` in an `Expanded`?_ 🤔

**Comment by awhitford** [comment]
BTW...  I have to admit that I prefer the look of the deprecated `FormBuilderRadio` instead of the `FormBuilderRadioGroup`:

**Old** FormBuilderRadio:
![image](https://user-images.githubusercontent.com/123887/89282569-94063400-d600-11ea-823f-c6a2c4db188a.png)

**New** FormBuilderRadioGroup:
![image](https://user-images.githubusercontent.com/123887/89282389-4b4e7b00-d600-11ea-90b9-ab1fdae49d12.png)

**Comment by slavap** [comment]
@awhitford It is possible to get the same layout with FormBuilderRadioGroup as it was for FormBuilderRadio, but currently I have to specify exact Container width manually, which is absolutely awful. Please fix vertical mode, or remove deprecation from FormBuilderRadio.

![image](https://user-images.githubusercontent.com/4129763/89356479-c81a3d00-d672-11ea-869e-34321349cc1b.png)

```dart
final radio = FormBuilderRadioGroup(
      orientation: GroupedRadioOrientation.vertical,
      controlAffinity: ControlAffinity.trailing,

FormBuilderFieldOption(
      value: v,
      child: Container(width: 400, 
```

**Comment by awhitford** [comment]
Yes, I know that I can adjust the control affinity.  However, I am now further convinced that `FormBuilderCheckboxGroup` is buggy:
![image](https://user-images.githubusercontent.com/123887/89474437-7937da80-d73a-11ea-80db-8bb25b61f73b.png)

_Why isn't this wrapping?_  (`FormBuilderFieldOption.child` is a `Text`.) 🤔

**Comment by slavap** [comment]
@awhitford It is the same story - you have to specify container width, then it will be possible to get wrapping with Flexible and Text.

**Comment by awhitford** [comment]
I see that the old deprecated versions use `ListTile`, and I think it was changed so that the horizontal and wrap layouts could be implemented.  Unfortunately, it has a side effect of not being a _drop in replacement_.  I think I finally have an idea on how to fix this...

**Comment by FickleLife** [comment]
Just wondering if there's a solution to the overflow wrapping?

**Comment by oodavid** [comment]
Bumping into this too, decided to use the deprecated `FormBuilderCheckboxList`

**Comment by pawangjain** [comment]
@awhitford how did you fix this?
It will be helpful if you can share it.

**Comment by awhitford** [comment]
@pawangjain Sadly, I don't think I tackled this yet.  For my original issue, I ended up using the deprecated control.  However, a **version 4** migration is in the future, so...

**Comment by danvick** [comment]
I think I solved this issue in v4 but forgot to port it to v3. I'll do that as soon as I can and release an update.

**Comment by mgav** [comment]
Using `orientation: OptionsOrientation.vertical,` with `flutter_form_builder: ^4.0.2` I was able or orient each radio option vertically.

Here's the whole block of code:

`FormBuilderRadioGroup(
                      name: 'formerly_an_attribute',
                      decoration: const InputDecoration(
                        border: InputBorder.none,
                        labelStyle: TextStyle(fontStyle: FontStyle.italic),
                      ),
                      wrapVerticalDirection: VerticalDirection.down,
                      // doesn't work in 4.0 (use below) orientation: GroupedRadioOrientation.vertical,
                      orientation: OptionsOrientation.vertical,`

And here's a screenshot:

<img width="420" alt="image" src="https://user-images.githubusercontent.com/2406851/102813184-5aa74880-4396-11eb-8902-6cb3fa739a41.png">

**Comment by ayaanpathan** [comment]
> @awhitford It is possible to get the same layout with FormBuilderRadioGroup as it was for FormBuilderRadio, but currently I have to specify exact Container width manually, which is absolutely awful.
> @danvick Please fix vertical mode, or remove deprecation from FormBuilderRadio.
> 
> ![image](https://user-images.githubusercontent.com/4129763/89356479-c81a3d00-d672-11ea-869e-34321349cc1b.png)
> 
> ```dart
> final radio = FormBuilderRadioGroup(
>       orientation: GroupedRadioOrientation.vertical,
>       controlAffinity: ControlAffinity.trailing,
> 
> FormBuilderFieldOption(
>       value: v,
>       child: Container(width: 400, 
> ```

How do i make the radio button list like this? can you please share the snippet? Also how do I keep the title on the left and the radio button to the right, like spacebetween?

**Comment by ayaanpathan** [comment]
> @awhitford It is possible to get the same layout with FormBuilderRadioGroup as it was for FormBuilderRadio, but currently I have to specify exact Container width manually, which is absolutely awful.
> @danvick Please fix vertical mode, or remove deprecation from FormBuilderRadio.
> 
> ![image](https://user-images.githubusercontent.com/4129763/89356479-c81a3d00-d672-11ea-869e-34321349cc1b.png)
> 
> ```dart
> final radio = FormBuilderRadioGroup(
>       orientation: GroupedRadioOrientation.vertical,
>       controlAffinity: ControlAffinity.trailing,
> 
> FormBuilderFieldOption(
>       value: v,
>       child: Container(width: 400, 
> ```

Hi, How do i customize the shape and size of the radio button

**Comment by Natan-hub** [comment]
Currently in this FormBuilderRadioGroup I can select the options by clicking exactly on the Radio button. Isn't there a way to select the options by clicking on the options label as well?
