### ISSUE TITLE
Provide abstract FormBuilderInput class that can be fully override and compatible with FormBuilder

### ISSUE THREAD

**Issue by magillus** [danvick/flutter_form_builder#39]
Having this abstract "interface" that works with FormBuilder would allow to have custom UI for some form functions:
- map (as other issues mentioned)
- CC information (that interests me and I willing to help PR it)
- slider pickers, etc. 
- would allow plugins with custom functionality.

**Comment by jasonlaw** [comment]
+1

**Comment by danvick** [comment]
Planned for Version 3 - which will be a complete rewrite of the plugin structure.

**Comment by danvick** [comment]
Hi @magillus, @jasonlaw 
Kindly try out version 3.0.0-beta.1 which has `FormBuilderField` which will allow you to define your own custom formField. Tell me what you think.

Thanks in advance for your much awaited contrubutions

**Comment by jasonlaw** [comment]
@danvick , I have made a custom image picker field, with reference to https://github.com/rapido-mobile/rapido-flutter. 

[form_builder_image_field.zip](https://github.com/danvick/flutter_form_builder/files/3088235/form_builder_image_field.zip)

**Comment by danvick** [comment]
Hi @jasonlaw,
I've had a chance to look at your implementation and I'm almost done implementing an ImagePicker. I however saw that your implementation allows one to select one image so I'm working on one that will pick several at a time.

One problem of depending on an image picker is that you'd be required to configure Android and/or iOS permissions for this package even when you're not necessarily gonna use an image picker. Same applies to other inputs such as Maps etc.
