### ISSUE TITLE
FormBuilderRadioGroup doesn't set a value

### ISSUE THREAD

**Issue by Talor-A** [danvick/flutter_form_builder#390]
on `flutter_form_builder: v3.12.0`,
this code:

```
          FormBuilderRadio(
            attribute: 'testValue',
            initialValue: null,
            options: [
              FormBuilderFieldOption(value: true, child: Text('Yes')),
              FormBuilderFieldOption(value: false, child: Text('No')),
            ],
            decoration: InputDecoration(border: InputBorder.none),
            validators: [],
          ),
```

will never set a value as true or false, it always remains null. I see there was a rework of this component recently, is it related?

**Comment by rishisaraf11** [comment]
Same issue... problem is below piece of code in generateItems which reset the value to original value. Selection on label work because of  one extra call widget.onChanged?.call(selectedValue);

```
    if (widget.value != null) {
      selectedValue = widget.value;
    }
```

**Comment by danvick** [comment]
Thanks @rishisaraf11 for the keen eye and highlighting the problem.
