### ISSUE TITLE
how to handle multiple FormBuilderDropdown onchange

### ISSUE THREAD

**Issue by Lukaalishi** [danvick/flutter_form_builder#391]
There should be exactly one item with [DropdownButton]'s value: 28. 
Either zero or 2 or more [DropdownMenuItem]s were detected with the same value
'package:flutter/src/material/dropdown.dart':
Failed assertion: line 827 pos 15: 'items == null || items.isEmpty || value == null ||
              items.where((DropdownMenuItem<T> item) {
                return item.value == value;
              }).length == 1'

**Comment by danvick** [comment]
Duplicate of #220. Kindly refer
