### ISSUE TITLE
Confirm password validator missing

### ISSUE THREAD

**Issue by yurikong** [danvick/flutter_form_builder#397]
cant find a validator that exactly match some string to another string

**Comment by danvick** [comment]
Hi @yurikong,
Remember that you can [include your own custom validator](https://pub.dev/packages/flutter_form_builder#custom-validator-function).

You can also make use of [conditional validation](https://pub.dev/packages/flutter_form_builder#conditional-validation) in the case of password confirmation scenario.

**Comment by danvick** [comment]
I will, however, consider adding an exact match in-built validation in later versions.

**Comment by yurikong** [comment]
oh that's right, exactly what I needed! I thought I saw it somewhere, but couldn't find it. Perfecto. Thank you

> Hi @yurikong,
> Remember that you can [include your own custom validator](https://pub.dev/packages/flutter_form_builder#custom-validator-function).
> 
> You can also make use of [conditional validation](https://pub.dev/packages/flutter_form_builder#conditional-validation) in the case of password confirmation scenario.

**Comment by yurikong** [comment]
Thanks for the consideration. It will be very handy 👍 

> I will, however, consider adding an exact match in-built validation in later versions.
