### ISSUE TITLE
Exception thrown when using timepicker in FormBuilderDateTimePicker

### ISSUE THREAD

**Issue by beatc1234** [danvick/flutter_form_builder#403]
I have the latest version of both this extension and flutter. Date picker works fine but when I set to InputType. time in FormBuilderDateTimePicker i got an error as in the picture.

![image](https://user-images.githubusercontent.com/63736950/89704278-16864f00-d985-11ea-91a2-c78e6543d6f6.png)

**Comment by danvick** [comment]
Closed by v3.13.1
