### ISSUE TITLE
[4.0.0.beta.1] Error: Type 'DiagnosticableMixin' not found

### ISSUE THREAD

**Issue by jasonlaw** [danvick/flutter_form_builder#406]
Hi @danvick ,

flutter form version: **4.0 beta 1**
flutter version: **1.20.1**

After upgrading to 4.0 beta 1, it hits the following error:

![image](https://user-images.githubusercontent.com/107820/89745416-4bf67e00-dae6-11ea-9b1b-b021f940b6ff.png)

**Comment by danvick** [comment]
This error comes from `flutter_datetime_picker` package which is yet to be updated for the current Flutter version. 

There's a PR in the pipeline but in the meantime, you can use [this solution](https://github.com/Realank/flutter_datetime_picker/issues/155#issuecomment-664443209)

**Comment by jasonlaw** [comment]
Hi @danvick , thanks for the clarification.
I believe the fixed version had been released now, the latest is 1.4.0.

**Comment by danvick** [comment]
Thanks for the update. I had already included, an update is coming out soon with a fix.
