### ISSUE TITLE
Feature Request: Section for a group of related fields

### ISSUE THREAD

**Issue by yokiran** [danvick/flutter_form_builder#41]
If the form has a lot of fields, it will be nice to be able to group them logically and present them in labeled sections. For example: Personal Information Section has Name, Address etc., Company Information has Name of Company, Billing Address etc.,

**Comment by danvick** [comment]
This is a feature that's in development and we'll have it soon.

Thank you for your contribution

**Comment by danvick** [comment]
Hi @yokiran,
I've decided that from version 3.0.0 which is in beta right now I would not place the fields in a Column but allow developers to compose the UI the way they like it, using sections, groups and panels if they like; arrange the fields the way you please etc. You can quite literally go crazy with it ;-)

You can pull the beta from pub and have a go at it, I'd appreciate your feedback.

**Comment by danvick** [comment]
That being said, 'sections' won't be developed, which I think would be better since one will have freedom to implement them as they like.

Thanks for your continued contributions.
