### ISSUE TITLE
I couldn't write in the FormBuilderTextField

### ISSUE THREAD

**Issue by AymanYassinn** [danvick/flutter_form_builder#411]
I can't write in the FormBuilderTextField when I start writing the keyboard goes down ...

layout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x1 surface={valid=true 533332074496} changed=false

**Comment by danvick** [comment]
We weren't able to reproduce this. What's the result of `flutter doctor` on your PC?

**Comment by AymanYassinn** [comment]
nothing
