### ISSUE TITLE
Compiler message: ../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.1/lib/src/fields/form_builder_checkbox.dart:28:9: Error: Type 'MouseCursor' not found.   final MouseCursor mouseCursor;

### ISSUE THREAD

**Issue by Lukaalishi** [danvick/flutter_form_builder#412]
Compiler message:
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.1/lib/src/fields/form_builder_checkbox.dart:28:9: Error: Type 'MouseCursor' not found.
  final MouseCursor mouseCursor;

**Comment by danvick** [comment]
Duplicate of #399. Kindly refer.
