### ISSUE TITLE
FormBuilderDateTimePicker - Problems with firstDate & lastDate

### ISSUE THREAD

**Issue by amoslai5128** [danvick/flutter_form_builder#417]
Thank you for your form_builder, you've done a very great job.

However, I've faced some problems. the FormBuilderDateTimePicker doesn't update in the picker TextContoller when the state of firstDate or lastDate was changed.

For example, picker initial lastDate was at 2020/12/13,  and the state deadline now changed into 12/10, picker doesn't update.
Therefore, it will throw an error !initialDate.isAfter(lastDate)
![Screenshot 2020-08-14 at 12 05 02 AM](https://user-images.githubusercontent.com/30002046/90158619-ce6e8e80-ddc1-11ea-8b94-73a5e2ea8a52.png)

Could you write extra code for this, for example, throw an error snack bar and change to the updated lastDate / reset() its value before opening picker dialog?

**Comment by deandreamatias** [comment]
This still a issue?
