### ISSUE TITLE
[FormBuilderImagePicker] Add option to sort Images

### ISSUE THREAD

**Issue by guenth39** [danvick/flutter_form_builder#419]
I would love to have the functionality to sort the selected Images via Drag and Drop. I think it could be solved by an [ReorderableListView](https://api.flutter.dev/flutter/material/ReorderableListView-class.html) relative easily.

**Comment by parth181195** [comment]
we can also add options to center do center alignment of images by warping it in center and shrink wrapping the list view

**Comment by parth181195** [comment]
sure why not
