### ISSUE TITLE
Form Builder 2.0.3 is not working 

### ISSUE THREAD

**Issue by netwiser** [danvick/flutter_form_builder#42]
Hi I checkout the master brand and it is successfully running in iPhone XR emulator. However I copy the sample code into one of my page, run it again, it crash.

I use redux to handle the data but I have removed all redux stuff from this page. This page is a pure clone from the sample page. 

flutter: External FormValidation failed
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: setState() called after dispose(): _DateTimePickerTextFormFieldState#e142e(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback. The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
#0      State.setState.<anonymous closure> (package:flutter/<…>
flutter: External FormValidation failed   

Reloaded 6 of 943 libraries in 1,175ms.
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building Builder(dirty):
flutter: Looking up a deactivated widget's ancestor is unsafe.
flutter: At this point the state of the widget's element tree is no longer stable. To safely refer to a
flutter: widget's ancestor in its dispose() method, save a reference to the ancestor by calling
flutter: inheritFromWidgetOfExactType() in the widget's didChangeDependencies() method.
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3252:9)
flutter: #1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3261:6)
flutter: #2      Element.inheritFromWidgetOfExactType (package:flutter/src/widgets/framework.dart:3276:12)
flutter: #3      Theme.of (package:flutter/src/material/theme.dart:128:52)
flutter: #4      showDialog.<anonymous closure> (package:flutter/src/material/dialog.dart:705:37)
flutter: #5      _DialogRoute.buildPage (package:flutter/src/widgets/routes.dart:1484:14)
flutter: #6      _ModalScopeState.build.<anonymous closure> (package:flutter/src/widgets/routes.dart:655:43)
flutter: #7      Builder.build (package:flutter/src/widgets/basic.dart:6035:41)
flutter: #8      StatelessElement.build (package:flutter/src/widgets/framework.dart:3789:28)
flutter: #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3736:15)
flutter: #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #11     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #21     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #27     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #29     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #33     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #37     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #43     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #47     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
flutter: #48     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
flutter: #49     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
flutter: #50     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
flutter: #51     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
flutter: #52     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
flutter: #56     _invoke (dart:ui/hooks.dart:209:10)
flutter: #57     _drawFrame (dart:ui/hooks.dart:168:3)
flutter: (elided 3 frames from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by netwiser** [comment]
After I disable the virtual keyboard in iOS and Android, and move the FormBuilder to another statefulwidget, it is working now.

**Comment by danvick** [comment]
Current version has issues managing statefulness, but I'm making amends in version 3. Feel free to test out the beta from [pub](https://pub.dartlang.org/packages/flutter_form_builder/versions/3.0.0-beta.4).

**Comment by danvick** [comment]
Kindly migrate to version 3 now released. Feel free to reopen the issue if it persists.
