### ISSUE TITLE
Compile error on channel beta: 1.21.0-9.1.pre

### ISSUE THREAD

**Issue by slavap** [danvick/flutter_form_builder#426]
/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_range_slider.dart:21:9: Error: Type 'RangeSemanticFormatterCallback' not found.
  final RangeSemanticFormatterCallback semanticFormatterCallback;

**Comment by Hikaru-Otaki** [comment]
me too

**Comment by evdinursan** [comment]
I got it also.

**Comment by Windol** [comment]
Same problem

**Comment by Windol** [comment]
Pull request #422 proposes a solution.

**Comment by evdinursan** [comment]
Either I'm doing something wrong or this issue has been fixed in the latest beta flutter release.

This is what I have in pubspec.yaml:

`flutter_form_builder: ^3.13.4`

And my current version of flutter on beta channel is: `Flutter 1.21.0-9.2.pre • channel beta`

**Comment by deandreamatias** [comment]
Closed because now don't apply this Flutter versions
