### ISSUE TITLE
suffixIcon for FormBuilderTextField?

### ISSUE THREAD

**Issue by joshuakoh1** [danvick/flutter_form_builder#428]
Would like to add a suffix icon to toggle editability of a field. Tap once to make it editable, press another to cancel changes. Would appreciate if suffixIcon could be passed to the TextField.

**Comment by devnullpointer** [comment]
I think his question was how do you make the suffixIcon "touchable" or react to press?

**Comment by realshovanshah** [comment]
@danvick does this mean it's not possible to add an onTap property to the suffix icon?

**Comment by mdeandrea-mrmilu** [comment]
Can be close this issue?
