### ISSUE TITLE
3.0.0-beta.1 : Error: No named parameter with the name 'strutStyle'.

### ISSUE THREAD

**Issue by benoitverstraete** [danvick/flutter_form_builder#43]
Hi @danvick ,

I try the new version of your package and with the given example at https://pub.dartlang.org/packages/flutter_form_builder/versions/3.0.0-beta.1#-readme-tab- , it doesn't compile :

```
Compiler message:
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.0.0-beta.1/lib/src/inputs/form_builder_text_field.dart:127:7: Error: No named parameter with the name 'strutStyle'.
      strutStyle: widget.strutStyle,
      ^^^^^^^^^^
file:///C:/src/flutter/packages/flutter/lib/src/material/text_form_field.dart:73:3: Context: Found this candidate, but the arguments don't match.
  TextFormField({
  ^
```

Thanks a lot for your time !

**Comment by danvick** [comment]
I see. Looks like I'm building the package on a later version of Flutter. Seems like I'll have to switch to stable channel and build for it, my bad.

**Comment by danvick** [comment]
@benoitverstraete Kindly upgrade to `^3.0.0-beta.2`, it's been fixed.

Thanks for being my kinda beta tester. I'm sure you'll find some very cool features (and less bugs) and more coming soon.

**Comment by benoitverstraete** [comment]
@danvick it works, thanks !
