### ISSUE TITLE
How to specify date format for DatePickerEntryMode.input?

### ISSUE THREAD

**Issue by bloodnwine** [danvick/flutter_form_builder#433]
I have successfully set the `format` attribute for date field as `format: DateFormat('dd/MM/yyyy')`.

But, I don't know how to set the same for Date Picker (input mode), its format is still `MM/dd/yyyy`.

<img width="403" alt="Screen Shot 2020-08-25 at 7 17 33 PM" src="https://user-images.githubusercontent.com/69716726/91173230-ae1aca00-e707-11ea-8162-3d7a45e40ed3.png">

```
  Widget _buildBirthdayField() {
    return FormBuilderDateTimePicker(
      attribute: 'date',
      inputType: InputType.date,
      format: DateFormat('dd/MM/yyyy'),
      initialEntryMode: DatePickerEntryMode.input,
      decoration: const InputDecoration(
        filled: true,
        labelText: 'Birthday',
      ),
    );
  }
```

**Comment by danvick** [comment]
Hi @bloodnwine,
Kindly note that the `format` attribute refers to the display format (what's displayed on the TextField) and not the entry format. 

Flutter's `showDatePicker` uses your application's Locale to set the input format, you can override this by setting the `locale` attribute of `FormBuilderDateTimePicker`
