### ISSUE TITLE
OnChanged with Length

### ISSUE THREAD

**Issue by NiranjanShah** [danvick/flutter_form_builder#437]
onChanged: (val) {
                            if (val != null && val.length == 4){
                              _focusAadhar1.unfocus();
                              FocusScope.of(context).requestFocus(_focusAadhar2);
                            }
}

the above code is working as expected when the value is entered for first time, however when a user need to modify/alter the data and if backspace(Delete) character key is pressed i/o deleting the character it jumps to next column.

Expected Behaviour: if backspace is pressed it must remove the character i/o firing the unfocus code.

**Comment by danvick** [comment]
Hi @NiranjanShah,
Unless I haven't understood your question, your expected behavior doesn't seem to match with the code written. 

Because if you already have 4 characters and backspace is pressed, the `if` condition wouldn't hold any longer, thus unfocus wouldn't fire.

**Comment by NiranjanShah** [comment]
Unfortunately the if condition is firing….

Will record a video for better understanding….

**Comment by NiranjanShah** [comment]
The issue is resolved, testing process was wrong, no code change required
