### ISSUE TITLE
failed to compile: issue with flutter chips input

### ISSUE THREAD

**Issue by anastasiamela** [danvick/flutter_form_builder#438]
Looks like an issue with flutter chips input  causing my app not to compile..

Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.9.0-dev.1/lib/src/chips_input.dart:421:3: Error: Type 'AutofillScope' not found.
  AutofillScope get currentAutofillScope => null;
  ^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.12.1/lib/src/fields/form_builder_chips_input.dart:136:11: Error: No named parameter with the name 'focusNode'.
          focusNode: widget.focusNode,
          ^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.9.0-dev.1/lib/src/chips_input.dart:13:3: Context: Found this candidate, but the arguments don't match.
  ChipsInput({
  ^^^^^^^^^^

Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.9.0-dev.1/lib/src/chips_input.dart:421:3: Error: Type 'AutofillScope' not found.
  AutofillScope get currentAutofillScope => null;
  ^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.12.1/lib/src/fields/form_builder_chips_input.dart:136:11: Error: No named parameter with the name 'focusNode'.
          focusNode: widget.focusNode,
          ^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.9.0-dev.1/lib/src/chips_input.dart:13:3: Context: Found this candidate, but the arguments don't match.
  ChipsInput({
  ^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

How could i fix this? I really want to use this package!

**Comment by danvick** [comment]
Kindly show your `flutter doctor` result and `pubspec.yaml` contents

**Comment by anastasiamela** [comment]
flutter doctor -v
[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.17.0 at C:\src\flutter
    • Framework revision e6b34c2b5c (4 months ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1        


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at c:\Users\anast\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Program Files\Android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.48.2)
    • VS Code at C:\Users\anast\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 2 categories.

**Comment by anastasiamela** [comment]
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+1
  intl: ^0.16.1
  sticky_grouped_list: ^0.3.0
  table_calendar: ^2.2.3
  toggle_switch: ^0.1.8
  flutter_form_builder: ^3.12.1
  flutter_chips_input: ^1.9.0-dev.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

**Comment by anastasiamela** [comment]
![image](https://user-images.githubusercontent.com/45273374/91485456-908a6380-e8b3-11ea-9f93-872bae45ad67.png)
pubspec.yaml

**Comment by danvick** [comment]
Try removing: flutter_chips_input: ^1.9.0-dev.1 from pubspec

**Comment by danvick** [comment]
flutter_chips_input is already included in this package

**Comment by anastasiamela** [comment]
![image](https://user-images.githubusercontent.com/45273374/91485920-3d64e080-e8b4-11ea-8884-761a222aa653.png)
![image](https://user-images.githubusercontent.com/45273374/91486021-5a99af00-e8b4-11ea-9366-4f102d7f4ef0.png)
![image](https://user-images.githubusercontent.com/45273374/91486065-6f764280-e8b4-11ea-94fe-84472bf8fb40.png)

**Comment by anastasiamela** [comment]
there is still problem..

**Comment by anastasiamela** [comment]
there is still problem..

![image](https://user-images.githubusercontent.com/45273374/91488186-97b37080-e8b7-11ea-95e6-4b4cb018e58a.png)

**Comment by chubzchoc** [comment]
try to clear your pub cache, or upgrade flutter version.
i got this issue to and fixed it by upgrade my flutter version

**Comment by deandreamatias** [comment]
Close because this old Flutter versions is not applied now
