### ISSUE TITLE
Is this package still alive and supported 

### ISSUE THREAD

**Issue by AlmogRnD** [danvick/flutter_form_builder#439]
Wanted to know if this package is still alive and supported were getting a number of errors on flutter run 
![IMG_20200827_191140_846](https://user-images.githubusercontent.com/169507/91566341-2d004480-e94c-11ea-90cf-4b37c58b6a62.jpg)

**Comment by taniket15** [comment]
from `README`

- For Flutter 1.17.x, use version 3.12.x
- For Flutter 1.20.x, use version 3.13.x
- For Flutter channel > stable (beta, dev, master), use version 3.14.0-alpha.x

**Comment by danvick** [comment]
Hi @AlmogRnD,
Kindly follow the instructions in README as suggested by @taniket15.

**Comment by maurobotta** [comment]
I have downloaded 4.0 Beta 5, zip, but the example don't compile 

[√] Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Versione 10.0.18363.1082], locale it-IT)

error:

Target of URI doesn't exist: '../data.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.

**Comment by mdeandrea-mrmilu** [comment]
Can be close this issue?
