### ISSUE TITLE
Version 3, is customized validation supported? 

### ISSUE THREAD

**Issue by jasonlaw** [danvick/flutter_form_builder#44]
Hi @danvick , does version 3 still support for custom validator? 
Suppose I have a text field with some customize validation, can it still be done now?

**Comment by danvick** [comment]
Ooh yeah. The fields have an attribute named `validators` which takes a list of `FormFieldValidator`s. That makes validators composable and reusable. There is a class named `FormBuilderValidators` with all the common validators. Checkout the v3 example. 
Sample Usage:
```dart
FormBuilderTextField(
    attribute: "age",
    decoration: InputDecoration(labelText: "Age"),
    validators: [
        FormBuilderValidators.numeric(),
        FormBuilderValidators.max(70)
        FormBuilderValidators.min(18, errorText: "You can't be under 18.")
    ],
),
```
P.S. I'm currently working on comprehensive documentation.

**Comment by jasonlaw** [comment]
That means we can create our own customized FormBuilderValidator right?

**Comment by danvick** [comment]
Sure. Or alternatively just stick in your validator function inside the list of validators, like so: 
```dart
FormBuilderTextField(
    attribute: "over_18",
    decoration: InputDecoration(labelText: "Are you over 18?"),
    validators: [
        FormBuilderValidators.required(),
        (val){
            if(val != "Yes")
                return "The answer must be Yes";
        },
    ],
),
```

**Comment by danvick** [comment]
The validator function just has to be Flutter's `FormFieldValidator`. The reason for making it this way - in a list - is to allow you to define your custom validator once and just use it in different fields or even across multiple forms / pages.

**Comment by jasonlaw** [comment]
I see, that's cool....great job! Thank you very much!

**Comment by danvick** [comment]
I'm glad you appreciate it.
