### ISSUE TITLE
How to set hint for FormBuilderTextField?

### ISSUE THREAD

**Issue by bloodnwine** [danvick/flutter_form_builder#441]
The hintText attribute in InputDecoration seems doesn't work!

```
  FormBuilderTextField(
      name: 'name',
      decoration: const InputDecoration(
        labelText: 'Name',
        border: InputBorder.none,
        hintText: 'hint text',
        filled: true,
      ),
      validator: FormBuilderValidators.compose([
        FormBuilderValidators.max(context, 8),
        FormBuilderValidators.max(context, 24),
      ]),
    );
```

**Comment by danvick** [comment]
Hi @bloodnwine,
Kindly note that `hintText` will only show when: 
a. the `labelText` is floating
b. the field is empty.

If you need the `hintText` to always show, consider setting `floatingLabelBehavior` to `FloatingLabelBehavior.always`
