### ISSUE TITLE
How to disable text edit in the FormBuilderTextField but enable suffix icon click?

### ISSUE THREAD

**Issue by arnzuk** [danvick/flutter_form_builder#442]
Hi,

How to disable text edit in the FormBuilderTextField but enable suffix icon click?

Arnoldas

**Comment by danvick** [comment]
There seems not to be a way of doing this in Flutter's `TextFormField`. When `enabled` is set to `false`, `suffix` and `suffixIcon` are disabled.
You may consider having your suffix icon as a separate widget instead of being part of the FormBuilderTextField's decoration

**Comment by arnzuk** [comment]
Thanks for the answer. Will create separate icon widget.

**Comment by arnzuk** [comment]
Container(
                            child: Stack(
                              alignment: Alignment.centerRight,
                              children: [
                                FormBuilderTextField(
                                  readOnly: true,
                                  controller: _codeController,
                                  attribute: 'qq',
                                ),
                                IconButton(
                                  icon: Icon(Icons.traffic),
                                  onPressed: () {
                                    print('qq');
                                  },
                                )
                              ],
                            ),
                          ),

**Comment by mdeandrea-mrmilu** [comment]
Can be close this issue?

**Comment by arnzuk** [comment]
> Can be close this issue?

Yes, you can close. Thanks.

**Comment by mdeandrea-mrmilu** [comment]
Hi @danvick. I don't have time all days, but I can contribute in my free time. Please add my personal account [@deandreamatias](https://github.com/deandreamatias/)

**Comment by danvick** [comment]
Neither do I, that's why some issues take time before they are solved. 😌

Glad to have you on board 🥳
