### ISSUE TITLE
FormBuilderSwitch has default margin

### ISSUE THREAD

**Issue by avinashk369** [danvick/flutter_form_builder#443]
`Container(
                                padding: EdgeInsets.all(0),
                                decoration: BoxDecoration(
                                    border: Border.all(color: kred)),
                                child: FormBuilderSwitch(
                                  decoration: InputDecoration(
                                      border: OutlineInputBorder(
                                          borderSide: BorderSide.none)),
                                  label: Text('Text Reminder'),
                                  attribute: "text_reminder_switch",
                                  initialValue: true,
                                ),
                              ),`

this switch widget has default margin and don't know how to change that margin.

**Comment by danvick** [comment]
There's an attribute named `contentPadding`, does that help?

**Comment by avinashk369** [comment]
> There's an attribute named `contentPadding`, does that help?

i tried that too but couldn't help

**Comment by danvick** [comment]
Can we have a screenshot to better understand what you want to achieve

**Comment by avinashk369** [comment]
contentPadding attribute worked inside inputdecoration. i was trying the same attribute outside the inputDecoration.
i really appreciate your promptness.
much thanks
