### ISSUE TITLE
labelText doens't turn red when validating in some Form Builder fields

### ISSUE THREAD

**Issue by bloodnwine** [danvick/flutter_form_builder#446]
In my case, they are `Nickname` labelText and `Birthday` labelText.

```
      decoration: InputDecoration(
        labelText: 'Nickname',
        border: InputBorder.none,
        hintText: 'Choose a nickname',
        filled: true,
        floatingLabelBehavior: FloatingLabelBehavior.always,
      ),
```

<img width="300" src="https://user-images.githubusercontent.com/69716726/91796601-c7ad9b80-ec4a-11ea-9ade-290d38c945dd.gif">

**Comment by deandreamatias** [comment]
This still a issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
