### ISSUE TITLE
[3.14.0-alpha.1] FormBuilderTextField initialValue does not change after build

### ISSUE THREAD

**Issue by gppam** [danvick/flutter_form_builder#447]
I have this widget that will change when it receives an object data and reflects it in the form. And while it works for the first change because it's the first data, when it receives a new object (a second object) it will just leave the first data in the form and not change. I was able to confirm that my data change work when I checked the `_detailGlobalKey.currentState.value.toString();` but the FormBuilderTextField textbox didn't. I've tried using controllers but that didn't do it too. Is this a bug?

<details>
<summary>Code</summary>

```dart
class DetailPage extends StatefulWidget {
  final User user;

  DetailPage({@required this.user});

  @override
  _DetailPageState createState() => _DetailPageState();
}

class _DetailPageState extends State<DetailPage> {
  final GlobalKey<FormBuilderState> _detailGlobalKey = GlobalKey<
      FormBuilderState>();
  User u;

  @override
  Widget build(BuildContext context) {
    u = widget.user;
    return Scaffold(
        body: Card(
                    child: Container(
                      margin: const EdgeInsets.all(16.0),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Container(
                              margin: const EdgeInsets.symmetric(vertical: 8.0),
                              child: Text('Details'),
                          FormBuilder(
                            key: _detailGlobalKey,
                            initialValue: {   // <---- not changing when User object changes
                              'firstName': u.firstName,
                              'lastName': u.lastName
                            },
                            child: Column(
                              mainAxisSize: MainAxisSize.min,
                              children: _getForm(),
                            ),
                          ),
                        ]
                      ),
                    ),
                  ),
      );
  }

  List<Widget> _getForm() {
    return [
      FormBuilderTextField(
        textCapitalization: TextCapitalization.words,
        attribute: "firstName",
        decoration: InputDecoration(
            border: UnderlineInputBorder(),
            filled: true,
            labelText: "First Name"),
        maxLines: 1,
        validators: [
          FormBuilderValidators.required(),
        ],
      ),
      .
      .
      .
      ];
    }

}
```

</details>

**Comment by bloodnwine** [comment]
There's also an initialValue attribute of FormBuilderTextField. In my case, it will cause a null exception. Could you try it?

**Comment by shkatulo** [comment]
Addidg ValueKey to `FormBuilderTextField` worked for me:

``` dart
FormBuilderTextField(
  key: ValueKey('contactPhone-$contactPhone'),
  name: 'contactPhone',
  initialValue: contactPhone ?? '',
  // ...
),
```

**Comment by YouSour** [comment]
> final TextEditingController _textController = TextEditingController();



> I'm using version `4.0.0-beta.3`. But, I hope I can help you! There's also an `initialValue` attribute of `FormBuilderTextField`. Could you try it? I had a look at the codes. `FormBuilderTextField` prefers `initialValue` to be set by a `TextEditingController`, I believe.
> 
> ```
> final TextEditingController _textController = TextEditingController();
> _textController.name = 'init value here';
> ```

it works as expected , thank you

**Comment by deandreamatias** [comment]
This still a issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
