### ISSUE TITLE
FormField.autovalidate not found

### ISSUE THREAD

**Issue by ryanhz** [danvick/flutter_form_builder#449]
In the latest flutter version 1.22.0-10.0.pre.79,  FormField.autovalidate does not exist anymore

**Comment by AbdulRafaySiddiqui** [comment]
Yeah, it seems to be replaced with [AutovalidationMode.](https://github.com/flutter/flutter/commit/7fdd9218b0b9af2c1115c633fa79319eeb83949d)

**Comment by pulstar** [comment]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.14.0-alpha.2/lib/src/form_builder_custom_field.dart:96:40: Error: The getter 'autovalidate' isn't defined for the class 'FormField<T>'.
 - 'FormField' is from 'package:flutter/src/widgets/form.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/form.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'autovalidate'.
        autovalidate: widget.formField.autovalidate,
                                       ^^^^^^^^^^^^

FAILURE: Build failed with an exception.

**Comment by buraky84** [comment]
I have the same issue.
What is the fix for this?

**Comment by pulstar** [comment]
> I have the same issue.
> What is the fix for this?

I switched to Flutter stable channel (there Flutter version is 1.20) and I am using Form Builder version 3.13.5
I will stay using the stable channel until a fix be available.

**Comment by buraky84** [comment]
ok thanks. while i posted here i also tried some workaround.
`flutter version 1.22.0-9.0.pre`

i am on master channel and switched to some pre-release of flutter not far from latest with above command.
this fixed my issue for the moment.

**Comment by danvick** [comment]
Kindly  use `^3.14.0`
