### ISSUE TITLE
3.0.0-beta.2 : Feature request FormBuilder inputs onChanged

### ISSUE THREAD

**Issue by benoitverstraete** [danvick/flutter_form_builder#45]
Hi @danvick,

Do you plan to implement an "onChanged" event on each inputs (FormBuilderDateTimePicker, FormBuilderSegmentedControl, ..) ? I would like to do an action when the user change only one element in the form.

I would like to avoid to handle the general onChanged (Map<String, dynamic>) in the FormBuilder.

Thanks a lot for the new beta version, it seems less buggy :)

**Comment by danvick** [comment]
Yes, this is a planned feature before release of version 3.

Thanks for contributing...

**Comment by danvick** [comment]
The feature has been added to the just released v3.0.0-beta.3.

Kindly help me test out this feature. Thanks in advance.

**Comment by benoitverstraete** [comment]
It works, thanks !
