### ISSUE TITLE
how i can get List<DateTime> from FormBuilderDateRangePicker

### ISSUE THREAD

**Issue by saleh-aleid** [danvick/flutter_form_builder#451]
I am using FormBuilderDateRangePicker i want calculate total days between first date and last date

**Comment by deandreamatias** [comment]
This still a issue?

**Comment by deandreamatias** [comment]
With new type `DateTimeRange`, this issue is resolved?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
