### ISSUE TITLE
[3.14.0-alpha.2] onChanged will break the signature pad

### ISSUE THREAD

**Issue by bensonwong** [danvick/flutter_form_builder#457]
The `onChanged` in combination with a `FormBuilderSignaturePad`. While using the signature pad, onChanged triggers a `_forceRebuild()` which basically makes the signature pad unusable. 

Easy workaround is to not use `onChanged` in combination with `FormBuilderSignaturePad` but ideally `onChanged` can check if the field is a signature and prevent any rebuild.

**Comment by syky27** [comment]
This is still happening in stable version  3.14.0

**Comment by nipunasudha** [comment]
Having the same issue on v3.14 stable.

**Comment by nipunasudha** [comment]
any news on this one?

**Comment by awhitford** [comment]
Is this still a problem with Version 4?  (Because I think this has been fixed.)

**Comment by nipunasudha** [comment]
> Is this still a problem with Version 4? (Because I think this has been fixed.)

just saw the migration guide to version 4 and i wont be able to migrate anytime soon due to so many breaking changes.

**Comment by deandreamatias** [comment]
This still a issue?

**Comment by syky27** [comment]
Dont know dont care.. :)

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
