### ISSUE TITLE
patchValue don't works - bug?

### ISSUE THREAD

**Issue by fehernyul** [danvick/flutter_form_builder#464]
Hi, I try the 4.0.0-beta.5 version.

I put a "FormBuilderTextField" to a "FormBuilder" named: "test".
I put a button to make run code which is patchValue the field, and immediately read it.
I write to the field: "123456789", but after I read is, there is "null".
Is is a bug?

BTW, in the Text field in the screen there is seen the correct value (123456789). 
But how can I read from it?

If I put some value to this field with my hand, by touching the screen, the problem is nowhere. That way is everything is fine.
Only problem with patchValue.

test code:

      body: Padding(
        padding: const EdgeInsets.symmetric(vertical: 8.0, horizontal: 20),
        child: SingleChildScrollView(
          child: FormBuilder(
            key: _fbKey,
            autovalidate: true,
            child: Column(
              children: <Widget>[
                // !!! patchValue begin **********************************************************************
                RaisedButton(
                  child: Text('test patchValue'),
                  onPressed: () async {
                    _fbKey.currentState.fields['test'].patchValue('123456789'); // = write value toFormBuilderField field !
                    _fbKey.currentState.save();
                    String ssss = _fbKey.currentState.value['test'];
                    print('patched value is: "$ssss"');
                  },
                ),

                FormBuilderTextField(
                  name: 'test',
                  minLines: 1,
                  maxLines: 1,
                  decoration: InputDecoration(
                    labelText: 'patchValue test',
                  ),
                ),
                // !!! patchValue end **********************************************************************

**Comment by jans-y** [comment]
I think I am facing the same bug, where `_fbKey.currentState.value` always returns empty Map {}.

Therefore I am using `_fbKey.currentState.fields` but then must append "?.value" to get the raw value.

In your case that would be:
`_fbKey.currentState.fields['test']?.value;`

**Comment by fehernyul** [comment]
> Azt hiszem, ugyanazzal a hibával nézek szembe, ahol `_fbKey.currentState.value`mindig üres Map {} jelenik meg.
> 
> Ezért használom, `_fbKey.currentState.fields`de akkor hozzá kell adnom a "? .Value" értéket a nyers érték megszerzéséhez.
> 
> Az Ön esetében ez a következő lenne:
> `_fbKey.currentState.fields['test']?.value;`

Thank you for your response.
My side it has the same result. So the "_fbKey.currentState.fields['test']?.value" is still "null" value, not the "123456789".
The field "_fbKey.currentState.fields['test']" is exists, but the value property is "null".

I think, for getting the good resolution is not only the patchValue('1234'), but 

**patchValue('1234')** +
**didChange('1234')**

So, I run this
                    _fbKey.currentState.fields['test'].patchValue('I was setting new value'); // only showing in form
                    _fbKey.currentState.fields['test'].didChange('I was setting new value'); // this set the value in "fields" array
                    ssss = _fbKey.currentState.fields['test']?.value;
                    print('changed value: "$ssss"'); // printed: changed value: "I was setting new value"

It will be good, if I can do this result with one command (not two).

**Comment by mdeandrea-mrmilu** [comment]
Can be close this issue?
