### ISSUE TITLE
How to force rebuild FormBuilderDropdown widget?

### ISSUE THREAD

**Issue by serpentarius-hollow** [danvick/flutter_form_builder#466]
Let's say I have 2 dropdowns called dropdown A and dropdown B. when I fired the onChanged event of dropdown A I want to also change the value of dropdown B. I tried to use setState but it seems that the initialValue parameter only set once and the widget dropdown B never rebuild. This doesn't happen with the default dropdownbutton widget because when the selected parameter changed the widget gets rebuilded.

**Comment by danielweil** [comment]
I need help with this; Any comments? @awhitford @danvick 

I am trying to rebuild if the value filled is empty string, so It doesn't fire the assertion error, but it is not possible.

**Comment by awhitford** [comment]
A trick is to specify a key for the B widget based on the A selection.  This will force Flutter to rebuild the B widget.

**Comment by awhitford** [comment]
Here is an article that explains:
* https://medium.com/analytics-vidhya/how-to-force-widget-to-redraw-in-flutter-2eec703bc024

> Well, this is actually how Flutter works - **tries to keep Stateful Widget’s State.**

**Comment by awhitford** [comment]
Closing this because this is more of a Flutter issue than a Flutter Form Builder issue, and it is _by design_.
