### ISSUE TITLE
FormBuilderCheckboxGroup value set to widget.initialValue

### ISSUE THREAD

**Issue by malain96** [danvick/flutter_form_builder#467]
Hello!

I think I found a mistake in the FormBuilderCheckboxGroup widget. 
While I was taking a look at your code, I noticed that in most widget you were setting the value of the field using `field.value`. However, for the FormBuilderCheckboxGroup widget, you are not using `field.value` but `widget.initialValue`.
The mistake is located [here](https://github.com/danvick/flutter_form_builder/blob/286a2ff744e96f6a9a4f85c7aa5a123427fa8dfe/lib/src/fields/form_builder_checkbox_group.dart#L136).

I hope this helped and thank you for your work.

**Comment by danvick** [comment]
Thanks for bringing this to my attention. I'm glad you find the package useful
