### ISSUE TITLE
Country code is empty in some country

### ISSUE THREAD

**Issue by saypadith** [danvick/flutter_form_builder#468]
I have used FormBuilderPhoneField as a phone field.
My default country in the field is "Laos" - "la". But the country code does not appear. 
The country code of "Laos" - "la" is +856

**Comment by danvick** [comment]
Hello @vathlala,
Sorry for the inconvenience. Kindly note however that the country picker we are using in the package comes from the package [country_pickers](https://pub.dev/packages/country_pickers). The issue, therefore, comes from a dependency of this package.

Kindly consider raising the issue on the [library repo](https://github.com/figengungor/country_pickers) or if possible submitting a PR fixing the issue.
