### ISSUE TITLE
duration form input

### ISSUE THREAD

**Issue by pasblin** [danvick/flutter_form_builder#469]
Hi, 
Would it be possible to add a duration field similar to this?.
https://pub.dev/packages/flutter_duration_picker.

Thx for this awesome library and regards.

**Comment by danvick** [comment]
Hi @pasblin. Thanks for your suggestion. I'm glad you find the package useful.

We may consider adding the field in future versions of the package. Kindly note, however, that you can use FormBuilderCustomField to build any type of field out of what's been provided by the package.

**Comment by pasblin** [comment]
ok , thx! 👍

**Comment by baptistesx** [comment]
I was also looking for a Duration input field :)

I'll use a custom field then. Is it on the roadmap or not at all? 

Thank you !
