### ISSUE TITLE
App crashes when select the second image with FormBuilderImagePicker()

### ISSUE THREAD

**Issue by andersondn** [danvick/flutter_form_builder#476]
When i click to slecte the second image, the app crashes on iOS leaving no information on debug console.
Debugging with xcode I got this error: 

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.'
terminating with uncaught exception of type NSException
CoreSimulator 732.17 - Device: iPhone 11 (88C2B28E-CBE3-4968-BA1F-8A8300282058) - Runtime: iOS 14.0 (18A372) - DeviceType: iPhone 11

**Comment by knaeckeKami** [comment]
See https://github.com/flutter/flutter/issues/65995 for the tracking issue in Flutter
