### ISSUE TITLE
[FormBuilderTextField] how to maintain the cursor position after patchValue

### ISSUE THREAD

**Issue by jasonlaw** [danvick/flutter_form_builder#477]
version: 4.0.0-beta.5
flutter: 1.20.4

I want to do a profanity filter, which to replace the profanity words to * when user is entering the text.
I do it in onChanged callback, the problem is, after patching the value, the cursor will be reset to the beginning position.
May I know how to maintain the cursor position at the back?

~~~dart
      onChanged: (val) {
                        if (Get.find<ProfanityFilter>()
                            .checkStringForProfanity(val)) {
                          val = Get.find<ProfanityFilter>().censorString(val);
                          print(val);
                          c.formKey.currentState.fields[c.request.loginId.name]
                              .patchValue(val);
                        }
                      },
~~~

![cursor](https://user-images.githubusercontent.com/107820/94331610-705bda80-0000-11eb-8fc5-00509ec5e88b.gif)

**Comment by danvick** [comment]
We'll consider placing the cursor after patchValue has been called. 

In the meantime consider using [this solution from StackOverflow](https://stackoverflow.com/questions/56851701/how-to-set-cursor-position-at-the-end-of-the-value-in-flutter-in-textfield)

**Comment by jasonlaw** [comment]
Thanks, I use the following code and it works well.

~~~dart
  var offset = this.selection.base.offset;
      formKey.currentState.fields[fieldName].patchValue(censoredValue);
      this.selection = TextSelection.collapsed(offset: offset);
~~~

**Comment by jasonlaw** [comment]
After I upgraded to flutter v1.22, the above code is no longer working.
It will hang at patchValue, some breaking changes?

**Comment by jasonlaw** [comment]
Looks like using patchValue in the OnChanged callback causing the infinite loop. :(
Hoping to have this enhancement implemented as soon as possible.
Thank you very much!
