### ISSUE TITLE
How can I get the event after field edit is finished? (OnEditingComplete) 

### ISSUE THREAD

**Issue by danielweil** [danvick/flutter_form_builder#478]
Hello,

Is there a way to get the event after the field is finished edited? I was using onChanged, but that triggers every time the user types.
I want an event that triggers when the user stops editing that certain field. Is it possible?

Thanks!

**Comment by danvick** [comment]
A TextField has an `onEditingComplete` attribute which fires when editing is done but only if the `TextInputtAction` is tapped.

A better alternative is to use a `FocusNode` have a focus handler that fires when the input loses focus
