### ISSUE TITLE
Incompatible with json_serializable >= 3.5.0

### ISSUE THREAD

**Issue by Ali-hd** [danvick/flutter_form_builder#481]
Hi, I having issues when running pub get after adding json_serilizable. 
This is my output:
` Because json_serializable >=3.5.0 depends on json_annotation >=3.1.0 <3.2.0 and basic_utils >=2.4.4 depends on json_annotation >=2.0.0 <=3.0.1, json_serializable >=3.5.0 is incompatible with basic_utils >=2.4.4.

And because vin_decoder 0.1.2 depends on basic_utils ^2.5.4, json_serializable >=3.5.0 is incompatible with vin_decoder 0.1.2.

And because no versions of vin_decoder match >0.1.2 <0.2.0 and validators 2.0.1 depends on vin_decoder ^0.1.2, json_serializable >=3.5.0 is incompatible with validators 2.0.1.

Because flutter_form_builder >=3.11.6 <4.0.0-alpha.1 depends on validators ^2.0.1 and no versions of validators match >2.0.1 <3.0.0, flutter_form_builder >=3.11.6 <4.0.0-alpha.1 requires validators 2.0.1.

Thus, json_serializable >=3.5.0 is incompatible with flutter_form_builder >=3.11.6 <4.0.0-alpha.1. `

flutter version: 1.22.0-10.0.pre.433 • channel master

**Comment by Ali-hd** [comment]
flutter version: 1.22.0-10.0.pre.433 • channel master

**Comment by danvick** [comment]
Please use `dependency_overrides` to make sure your dependencies play nice with each other.

**Comment by Ali-hd** [comment]
Thanks please close issue.
