### ISSUE TITLE
Form Widget color

### ISSUE THREAD

**Issue by reidlai** [danvick/flutter_form_builder#482]
Hi there, i am now trying to plug form builder with dark theme.  Is there any way I can change widget color , e.g. raido button, checkbox, to white color?  I know I can use decoration to change underline color etc but still have no clue how to change checkbox and radio button.  Thanks for any help

**Comment by danvick** [comment]
Checkboxes and radio buttons have options to change colors such as `activeColor`, `checkColor`, `focusColor`, `hoverColor`; use these attributes to adjust colors as required.

**Comment by mdeandrea-mrmilu** [comment]
Can be close this issue?
