### ISSUE TITLE
4.0.0-pre.3 error

### ISSUE THREAD

**Issue by jasonlaw** [danvick/flutter_form_builder#484]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_checkbox.dart:79:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_checkbox_group.dart:39:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_chips_input.dart:38:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_choice_chips.dart:253:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_color_picker.dart:71:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_date_range_picker.dart:62:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_date_time_picker.dart:159:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_dropdown.dart:194:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_filter_chips.dart:45:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_image_picker.dart:53:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_location_field.dart:55:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_phone_field.dart:67:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_radio_group.dart:38:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_range_slider.dart:118:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_rating.dart:47:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_searchable_dropdown.dart:115:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_segmented_control.dart:50:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_signature_pad.dart:41:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_slider.dart:142:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_switch.dart:95:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_text_field.dart:304:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_touch_spin.dart:57:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_typeahead.dart:270:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/form_builder_field.dart:53:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/form_builder_field.dart:90:3: Error: Type 'AutovalidateMode' not found.
  AutovalidateMode get autovalidateMode => widget.autovalidateMode;
  ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_checkbox.dart:79:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_checkbox.dart:79:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_checkbox_group.dart:39:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_checkbox_group.dart:39:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_chips_input.dart:38:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_chips_input.dart:38:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_choice_chips.dart:253:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_choice_chips.dart:253:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_color_picker.dart:71:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_color_picker.dart:71:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_date_range_picker.dart:62:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_date_range_picker.dart:62:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_date_time_picker.dart:159:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_date_time_picker.dart:159:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_date_time_picker.dart:243:49: Error: The getter 'AutovalidateMode' isn't defined for the class 'FormBuilderDateTimePicker'.
 - 'FormBuilderDateTimePicker' is from 'package:flutter_form_builder/src/fields/form_builder_date_time_picker.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_date_time_picker.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'AutovalidateMode'.
              autovalidate: autovalidateMode != AutovalidateMode.disabled &&
                                                ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_dropdown.dart:194:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_dropdown.dart:194:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_filter_chips.dart:45:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_filter_chips.dart:45:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_image_picker.dart:53:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_image_picker.dart:53:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_location_field.dart:55:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_location_field.dart:55:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_phone_field.dart:67:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_phone_field.dart:67:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_radio_group.dart:38:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_radio_group.dart:38:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_range_slider.dart:118:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_range_slider.dart:118:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_range_slider.dart:172:52: Error: The argument type 'String Function(double)' can't be assigned to the parameter type 'String Function(RangeValues)'.
 - 'RangeValues' is from 'package:flutter/src/material/slider_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/slider_theme.dart').
                        semanticFormatterCallback: semanticFormatterCallback,
                                                   ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_rating.dart:47:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_rating.dart:47:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_searchable_dropdown.dart:115:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_searchable_dropdown.dart:115:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_segmented_control.dart:50:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_segmented_control.dart:50:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_signature_pad.dart:41:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_signature_pad.dart:41:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_slider.dart:142:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_slider.dart:142:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_switch.dart:95:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_switch.dart:95:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_text_field.dart:304:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_text_field.dart:304:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_touch_spin.dart:57:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_touch_spin.dart:57:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_typeahead.dart:270:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/fields/form_builder_typeahead.dart:270:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/form_builder_field.dart:53:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/form_builder_field.dart:53:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/form_builder_field.dart:68:11: Error: No named parameter with the name 'autovalidateMode'.
          autovalidateMode: autovalidateMode,
          ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/form_builder_field.dart:90:51: Error: The getter 'autovalidateMode' isn't defined for the class 'FormBuilderField<T>'.
 - 'FormBuilderField' is from 'package:flutter_form_builder/src/form_builder_field.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-pre.3/lib/src/form_builder_field.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'autovalidateMode'.
  AutovalidateMode get autovalidateMode => widget.autovalidateMode;
                                                  ^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
BUILD FAILED in 1m 31s
Picked up _JAVA_OPTIONS: -Xmx2g
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by danvick** [comment]
Kindly note that thes `-pre.*` tag supports the newly released Flutter v1.22  onwards.

**Comment by jasonlaw** [comment]
Thanks for the clarification.
Upgrade flutter to v1.22 fixed the issue. :)
