### ISSUE TITLE
[FormBuilderTextField] Filter profanity, advice needed.

### ISSUE THREAD

**Issue by jasonlaw** [danvick/flutter_form_builder#485]
Hi @danvick ,

I would like to censor bad words to * when user is keying into the FormBuilderTextField.
Eg, "this is a bad word" will become "this is a ********".

I have tried to change it in OnChanged callback, but that will cause the infinite loop.

May I know where is the best place to handle that? I am expecting something like OnChanging callback, which give us a chance to rewrite the value.

Looking forward your advice.

Thanks.

**Comment by jasonlaw** [comment]
Looks like the using TextEditingController with OnChanged will cause the infinite looping.
I have tried to remove the TextEditingController, but it behave very strange.

What I am trying to do is handle OnChanged callback, if the input text has bad words, replace it with *, and use patchValue for the new censor text.

Strange is, if without debug breakpoint, the input text is not updated, but with breakpoint, it will be updated. *Pls refer to the video below.

My expectation is: the text field will be updated with new censor text, and the cursor remain at the last position.

![patchValue issue](https://user-images.githubusercontent.com/107820/94991319-f5249680-05b4-11eb-9298-f6663408546f.gif)

**Comment by danvick** [comment]
As I’m working on this, instead of using patchValue, you could make use of a TextEditingController to update the value.

A TextEditingController would allow you to set the text as well as position the cursor at the end of the entered text

**Comment by danvick** [comment]
FYI I have a fix for this in the pipeline already just awaiting release along with other issues. You could use the above mentioned solution if this is urgent. 

Thanks for your patience
