### ISSUE TITLE
For loop list resets

### ISSUE THREAD

**Issue by Slugman1983** [danvick/flutter_form_builder#489]
Hi,
is this an issue or am I approaching it wrong?
https://stackoverflow.com/questions/64251656/list-keeps-reseting-in-flutter

**Comment by danvick** [comment]
Kindly be keen while using FutureBuilder inside a stateful widget as the future builder will reebuild every time there's change in state i.e. when  `setState()`  is called. This is a [common issue with FutureBuilder](https://stackoverflow.com/questions/61282715/flutters-futurebuilder-rebuilding-multiple-times).

That said, I don't think this is necessarily an issue with this package.
