### ISSUE TITLE
Json_annotation update?

### ISSUE THREAD

**Issue by kthecoder** [danvick/flutter_form_builder#490]
Will you be updating Json_annotation to 3.1.0 anytime soon?

````
Because no versions of validators match >2.0.1 <3.0.0 and flutter_form_builder 3.14.0 depends on validators ^2.0.1, 
flutter_form_builder 3.14.0 requires validators 2.0.1.

And because validators 2.0.1 depends on vin_decoder ^0.1.2 and no versions of vin_decoder match >0.1.2 <0.2.0, 
flutter_form_builder 3.14.0 requires vin_decoder 0.1.2.

And because vin_decoder 0.1.2 depends on basic_utils ^2.5.4 which depends on json_annotation >=2.0.0 <=3.0.1, 
flutter_form_builder 3.14.0 requires json_annotation >=2.0.0 <=3.0.1.

**Comment by DylanMsK** [comment]
I solved the issue with adding 'dependency_overrides' like this.

dependencies:
  json_serializable: ^3.5.0 # https://pub.dev/packages/json_serializable/install
  flutter_form_builder: ^3.14.0 # https://pub.dev/packages/flutter_form_builder
dependency_overrides:
  flutter_form_builder: ^3.14.0 # https://pub.dev/packages/flutter_form_builder
  json_annotation: ^3.0.1

It's just quick solving..
please upgrade the dependency packages.

**Comment by cedvdb** [comment]
is this a real fix or this package deps need to be updated?

**Comment by danvick** [comment]
That's a real fix!

We are not even using `json_annotation` directly in this package - it's a transitive dependency.
