### ISSUE TITLE
How to build custom data on dropdown picker ??

### ISSUE THREAD

**Issue by sokunsamnang** [danvick/flutter_form_builder#495]
I want my data like in picture, instead of country !!!

![photo_2020-10-13_14-49-56](https://user-images.githubusercontent.com/46617484/95832953-32cbb100-0d65-11eb-8baa-a1f41e302def.jpg)

**Comment by danvick** [comment]
Hi @sokunsamnang,
Since we don't have a similar-looking input and we can't have all possible input field configurations, the package provides a way to build your own custom inputs.

Kindly consider using this option. The instrctions on how to are contained in the README
