### ISSUE TITLE
FormBuilderDateTimePicker broken after 4.0.0-pre.3

### ISSUE THREAD

**Issue by jans-y** [danvick/flutter_form_builder#496]
Hi,

I noticed that after updating to pre.3, changing the date it is not visually "changed" to the new value.

On the logic side, it's being changed but the input is not reflecting the change, therefore it's broken from the user's point of view.

Thank you.

**Comment by tstrg** [comment]
I'm facing the same issue after updating flutter_form_builder from 4.0.0-beta.5 to 4.0.0-pre.4
Flutter (Channel beta, 1.22.1, on Microsoft Windows [Version 10.0.18362.1082]

The console log:
```
Exception caught by foundation library
setState() or markNeedsBuild() called during build.
```

**Comment by danielweil** [comment]
Yes. I am also having this issue! Waiting for the solution, and while it isnt out, I downgraded back.

**Comment by danielweil** [comment]
Any updates??

**Comment by stact** [comment]
same issue here; `setState() or markNeedsBuild() called during build.`

**Comment by danvick** [comment]
I'll be publishing an update to fix this ASAP.

**Comment by danvick** [comment]
v4.0.0-pre.5 should have a fix for this.

**Comment by danvick** [comment]
Feel free to reopen if not
