### ISSUE TITLE
Error message customization

### ISSUE THREAD

**Issue by pavankumarkatakam** [danvick/flutter_form_builder#50]
As of now, the error message is creating automatically with attribute value, but it should be customizible in some cases we need to show error message differently.

**Comment by danvick** [comment]
Thanks for your helpful feedback @pavankumarkatakam.
This too has been addressed in the upcoming version.

**Comment by pavankumarkatakam** [comment]
Ok, Thanks for the reply. For now, I'm using plain Flutter in built forms, but this package will solve many problems and less boilerplate code.
