### ISSUE TITLE
Prevent readOnly attribute and its value being passed

### ISSUE THREAD

**Issue by yasirraku** [danvick/flutter_form_builder#501]
Hi all,

I have some fields that are readOnly and their values are loaded from API requests. I don't want these values to be passed. Is there any way we can prevent readOnly attribute and its value from being passed?

Tried changing the key and valueTransformer,onSaved,onSubmitted to return null. But nothing worked.

Thanks!

**Comment by danvick** [comment]
Hi @yasirraku,

Thanks for the suggestion.

We may consider maybe setting a flag that will be used to decide on whether values from read-only fields should be returned.
What do you think @awhitford?

**Comment by awhitford** [comment]
@danvick Are you thinking of adding a flag to the `saveAndValidate()` call?  (If `skipReadyOnly` is `true` then it could filter out the `readOnly` widgets when saving?) I think I could see that work.

Did you have another idea?

**Comment by danvick** [comment]
Yes! That pretty much sums up the idea. 

Same way HTML doesn't send back values for `readonly` inputs - but ours would be optional.

**Comment by yasirraku** [comment]
Thank you so much @danvick @awhitford :)

**Comment by awhitford** [comment]
@danvick In retrospect, rather than adding a `skipReadOnly` flag to the `saveAndValidate` method, I think an easier approach will be to override the `onSave` method to be a no-op, controlled by a `FormBuilder` property.  (Once my `FormBuilderField` class is a base class, this is easy to do.)

**Comment by danvick** [comment]
Ooh. Yeah, I was thinking `skipReadOnly` to be an attribute of `FormBuilder` rather than a param for `saveAndValidate()` method.
