### ISSUE TITLE
FormBuilderChoiceChip missing padding param

### ISSUE THREAD

**Issue by WilliamCunhaCardoso** [danvick/flutter_form_builder#504]
FormBuilderChoiceChip does not provide _padding_ param, only _labelPadding_.

**Comment by danvick** [comment]
Hi @WilliamCunhaCardoso,
Could you kindly elaborate on what you'd like to achieve with padding?

**Comment by danvick** [comment]
Hi @WilliamCunhaCardoso,
Which version of FormBuilder are you on?

**Comment by WilliamCunhaCardoso** [comment]
> Hi @WilliamCunhaCardoso,
> Which version of FormBuilder are you on?

3.14.0

**Comment by danvick** [comment]
Thanks for letting us know, we'll include the option as soon as we can.
