### ISSUE TITLE
Patch Value in date fields don't work

### ISSUE THREAD

**Issue by danielweil** [danvick/flutter_form_builder#505]
Can someone help me patch date fields and have their value changes?

I can't make it work. I tried it all,

Thanks for the help

**Comment by danielweil** [comment]
Was able to make it work with TextEditingControllers.

**Comment by danvick** [comment]
Thanks for bringing this to our attention @danielweil. 

The fix will be published shortly.

**Comment by danielweil** [comment]
Thank you very much for the quick fix. One of the best packages out there!
