### ISSUE TITLE
two bugs in FormBuilderRating

### ISSUE THREAD

**Issue by gdo** [danvick/flutter_form_builder#506]
Hello,

1/ I think line 7 must be 
class FormBuilderRating extends FormBuilderField< double > {
I add < double >

2/ And line 40 
double initialValue = 1.0,
must be
double initialValue,

Thanks for your great lib.
Best regards

**Comment by danvick** [comment]
Thanks for your suggestions @gdo,
About the `double initialValue = 1.0,` the underlying package which renders the stars requires an value and doesn't accept null, that's why we have initialized the value to 1.0.

P.S: I'm glad you find the package useful.

**Comment by awhitford** [comment]
**Version 4** is much for type safe, and addresses the first issue.
