### ISSUE TITLE
Dynamic country code for FormBuilderPhoneField

### ISSUE THREAD

**Issue by sijas** [danvick/flutter_form_builder#509]
Is it possible to make the country code for the phone field dynamic?

Imagine I have a country picker at the to and I have a few FormBuilderPhoneField following it. I want to make the country selection to change the country code of all phone fields.

**Comment by awhitford** [comment]
The Phone Field has a `defaultSelectedCountryIsoCode` property.
You can easily engineer the form to pass the Country Code selection to subsequent Phone fields.

**Comment by sijas** [comment]
@awhitford The field defaultSelectedCountryIsoCode is final. If I am not wrong, it can only take the value once at the runtime.

**Comment by awhitford** [comment]
I am imagining code like this:
```dart
            FormBuilder(
              child: Column(
                children: [
                  FormBuilderCountryPicker(
                    attribute: 'country',
                    onChanged: (value) {
                      final Country country = value;
                      setState(() {
                        _selectedCountryIsoCode = country.isoCode;
                      });
                    },
                  ),
                  FormBuilderPhoneField(
                    key: ValueKey('Phone1_$_selectedCountryIsoCode'),
                    attribute: 'phone1',
                    defaultSelectedCountryIsoCode: _selectedCountryIsoCode,
                    decoration: InputDecoration(labelText: 'Phone 1'),
                  ),
                  FormBuilderPhoneField(
                    key: ValueKey('Phone2_$_selectedCountryIsoCode'),
                    attribute: 'phone2',
                    defaultSelectedCountryIsoCode: _selectedCountryIsoCode,
                    decoration: InputDecoration(labelText: 'Phone 2'),
                  ),
                ],
              ),
            ),
```

Note that the `key` hack is important for the state change to trigger a rebuild of the `FormBuilderPhoneField` widgets.

_Does this help?_

It is likely not perfect for you.  Play around with it, and when you have a more precise request, we can ponder further opportunities to improve the widgets.  I'm thinking that maybe you want a flag to hard-code the country selection, not just default it?

**Comment by sijas** [comment]
@awhitford Yes. Think looks promising, It is a moonlighting project and I work on it in my free time. I will give a try, I didn't use the key hack. It is something new for me. Thank you so much!!

**Comment by awhitford** [comment]
#466 has a similar issue.

Here is an article that explains:
* https://medium.com/analytics-vidhya/how-to-force-widget-to-redraw-in-flutter-2eec703bc024

> Well, this is actually how Flutter works - **tries to keep Stateful Widget’s State.**
