### ISSUE TITLE
Access FormBuilderChipsInput suggestionsBoxController 

### ISSUE THREAD

**Issue by castanonrodrigo** [danvick/flutter_form_builder#510]
Hello, awesome package!

I'm trying to control the opening of the suggestions box in the FormBuilderChipsWidget.
When I focus on the input field, I want the suggestions box to open instantly, without the need to press any keys.
Do you know if it can be done? I already looked through the documentation and source code, and think maybe exposing the _suggestionBoxController object from ChipsInput class could solve it.
If it's not possible, do you think it could be added?

Another issue I'm having is that after an option is selected, the input doesn't work properly, I type and the text doesn't appear.

Thanks!

**Comment by danielweil** [comment]
Any updates on this issue? @danvick

**Comment by deandreamatias** [comment]
This still a issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
