### ISSUE TITLE
Keyboard option in FormBuilderTouchSpin

### ISSUE THREAD

**Issue by danielweil** [danvick/flutter_form_builder#512]
Is there a way to include a numeric keyboard when touching the field in the middle? If I still want to use the spinner but I have to type a big number.

Thanks! Love your package!

**Comment by danvick** [comment]
Hi @danielweil,
I'm glad you find this package useful.

The TouchSpin functionality comes from a separate package.
I would appreciate it if you could report the issue on the package repo and we'll will try to work on it over there then include the feature here when done.

**Comment by danielweil** [comment]
Any luck?

**Comment by deandreamatias** [comment]
This still a issue?

**Comment by deandreamatias** [comment]
Closed because no response and is not primarily applicable in this repository
