### ISSUE TITLE
readOnly changes are not applied.

### ISSUE THREAD

**Issue by LefebvreIlyas** [danvick/flutter_form_builder#515]
Hello @danvick,

Thank you very much for this package 🎉.

Here is a small example to illustrate the problem.

I use: `flutter_form_builder: ^4.0.0-pre.5`

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';

void main() {
  runApp(MyApp());
}

enum Number {
  zero,
  one,
  two,
  three,
  four,
  five,
  six,
  seven,
  eight,
  nine,
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  bool _readOnly;

  @override
  void initState() {
    super.initState();
    _readOnly = false;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: FormBuilder(
        readOnly: _readOnly,
        child: Column(
          children: <Widget>[
            SwitchListTile(
              value: _readOnly,
              title: Text('Read only'),
              onChanged: (value) => setState(
                () => _readOnly = value,
              ),
            ),
            FormBuilderDropdown<Number>(
              name: 'number',
              decoration: InputDecoration(labelText: 'Number'),
              items: Number.values
                  .map(
                    (number) => DropdownMenuItem(
                      child: Text(number.toString()),
                      value: number,
                    ),
                  )
                  .toList(),
            ),
            FormBuilderTextField(
              name: 'name',
            ),
          ],
        ),
      ),
    );
  }
}
```
</details

**Comment by LefebvreIlyas** [comment]
Thank you very much 🎉.

**Comment by LefebvreIlyas** [comment]
It now works perfectly with `FormBuilderDropdown` but not yet with `FormBuilderTextField`.

**Comment by awhitford** [comment]
@LefebvreIlyas Are you able to test the latest **version 4 pre-release**?  Note that there was a significant `readOnly` flag overhaul because it was generally confusing with Flutter's established `enabled` flag.  As a result, you may need to tweak some code accordingly.

**Comment by LefebvreIlyas** [comment]
Hello @awhitford 

But it is now no longer possible to disable the whole form by setting true to readOnly (or enabled to avoid confusion) to FormBuilder ?

Now FormBuilderField has become abstract, which means you have to inherit it, but Flutter prefers composition over inheritance, and with inheritance it creates a problem when you want to pass validators, because it requires context. What do you think about it?

**Comment by awhitford** [comment]
Perhaps you'd like to join the [Gitter on Version 4](https://gitter.im/flutter_form_builder/version_4).

You are right about disabling the whole form.  That idea might have been caught in the crossfire over cleaning up `enabled` and `readOnly` because these two flags were used in inconsistent and contradictory ways.  (There was an intentional attempt to simplify the interface by keeping the controls discrete and not complicating things with a dependent relationship.)

I am surprised that `FormBuilderField` being abstract is posing an issue.  Every _Form Builder Field_ extends `FormBuilderField`.  Were you using it _as is_?  (I guess the `abstract` keyword could be dropped -- I was thinking that it was a signal to folks to subclass.)

I'm not following the validator problem.  Validators are functions where `context` is a parameter.  If you have some sample source code, I might be able to make suggestions.

**Comment by LefebvreIlyas** [comment]
Thanks for the link!

> You are right about disabling the whole form. That idea might have been caught in the crossfire over cleaning up enabled and readOnly because these two flags were used in inconsistent and contradictory ways. (There was an intentional attempt to simplify the interface by keeping the controls discrete and not complicating things with a dependent relationship.)

I understand, I think it would be a good thing to restore this functionality.

> I am surprised that FormBuilderField being abstract is posing an issue. Every Form Builder Field extends FormBuilderField. Were you using it as is? (I guess the abstract keyword could be dropped -- I was thinking that it was a signal to folks to subclass.)

> I'm not following the validator problem. Validators are functions where context is a parameter. If you have some sample source code, I might be able to make suggestions.

<details>
<summary>Old solution</summary>

```dart
class MyCustomObjectFormField extends StatelessWidget {
  const MyCustomObjectFormField({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return FormBuilderField<Object>(
      name: 'object_field',
      builder: (FormFieldState<Object> field) {
        final initialValue = field.value ?? Object();

        // ignore: invalid_use_of_protected_member
        if (field.value == null) field.setValue(initialValue);

        return MyCustomObjectWidget(
          object: initialValue,
          onChanged: (object) => field.didChange(object),
        );
      },
      validator: FormBuilderValidators.compose(
        <FormFieldValidator>[
          FormBuilderValidators.required(
            context,
            errorText: "Object is required",
          ),
        ],
      ),
    );
  }
}
```
</details>

<details>
<summary>New solution</summary>

```dart
class MyCustomObjectFormField extends FormBuilderField<Object> {
  MyCustomObjectFormField({
    Key key,
  }) : super(
    key: key,
    name: 'object_field',
    builder: (FormFieldState<Object> field) {
      final initialValue = field.value ?? Object();

      // ignore: invalid_use_of_protected_member
      if (field.value == null) field.setValue(initialValue);

      return MyCustomObjectWidget(
        object: initialValue,
        onChanged: (object) => field.didChange(object),
      );
    },
    validator: FormBuilderValidators.compose(
      <FormFieldValidator>[
        FormBuilderValidators.required(
        context, // <------------------------------------------------ NOT AVAILABLE
        errorText: "Object is required",
        ),
      ],
    ),
  );

  @override
  _MyCustomObjectFormFieldState<Object> createState() => _MyCustomObjectFormFieldState<Object>();
}

class _MyCustomObjectFormFieldState<Object> extends FormBuilderFieldState<MyCustomObjectFormField, Object> {}
```

Here are two examples of code, maybe I'm using the package wrong.

</details>

**Comment by awhitford** [comment]
Thanks for the code sample...  I'd like to mention a few things with your old example:

1. Extending `StatefulWidget` instead of `FormBuilderField` loses some common _Form Field_ properties like `enabled` and `autovalidateMode`.  This is inconsistent with expectations.
2. ` field.setValue(initialValue);` should not be called during `build` -- that would be something best done during `initState`, or specifying a default constructor value.
3. Hard-coding values like `name` make the custom form field less flexible.  (You can only ever have _one_ per form?)

Hard-coding the `validator` is unexpected and highly restrictive like hard-coding `name`.  The typical scenario is declaring the form field in a widget's `build` method, which has access to `context`:
```dart
                FormBuilderTextField(
                  name: 'full_name',
                  decoration: InputDecoration(labelText: 'Full Name'),
                  validator: FormBuilderValidators.compose([
                    FormBuilderValidators.required(context),
                  ]),
                ),
```
However, by trying to create the `validator` during the `FormBuilderField` constructor, `context` is clearly missing.  The solution is to refactor so that the `validator` declaration is done during the `build` method with a `BuildContext`.

Also, the `<Object>` for `createState`/`State` is unnecessary -- the code would be like this:
```dart
  @override
  _MyCustomObjectFormFieldState createState() =>
      _MyCustomObjectFormFieldState();
}

class _MyCustomObjectFormFieldState
    extends FormBuilderFieldState<MyCustomObjectFormField, Object> {}
```

**Comment by awhitford** [comment]
@LefebvreIlyas Consider an approach like this:

```dart
class MyCustomObjectFormField extends FormBuilderField<Object> {
  MyCustomObjectFormField({
    Key key,
    @required String name,
    Object initialValue,
    AutovalidateMode autovalidateMode = AutovalidateMode.onUserInteraction,
    bool enabled = true,
    FormFieldSetter<Object> onSaved,
    FormFieldValidator<Object> validator,
    ValueTransformer<Object> valueTransformer,
    ValueChanged<Object> onChanged,
    InputDecoration decoration = const InputDecoration(),
    VoidCallback onReset,
    FocusNode focusNode,
  }) : super(
          key: key,
          name: name,
          initialValue: initialValue ?? Object(),
          autovalidateMode: autovalidateMode,
          enabled: enabled,
          onSaved: onSaved,
          validator: validator,
          valueTransformer: valueTransformer,
          onChanged: onChanged,
          decoration: decoration,
          onReset: onReset,
          focusNode: focusNode,
          builder: (FormFieldState<Object> field) {
            final state = field as _MyCustomObjectFormFieldState;
            return MyCustomObjectWidget(
              object: state.initialValue,
              onChanged: (object) => field.didChange(object),
            );
          },
        );

  factory MyCustomObjectFormField.typical(BuildContext context, {Key key}) {
    return MyCustomObjectFormField(
      key: key,
      name: 'object_field',
      validator: FormBuilderValidators.compose(
        <FormFieldValidator>[
          FormBuilderValidators.required(
            context,
            errorText: 'Object is required',
          ),
        ],
      ),
    );
  }

  @override
  _MyCustomObjectFormFieldState createState() =>
      _MyCustomObjectFormFieldState();
}

class _MyCustomObjectFormFieldState
    extends FormBuilderFieldState<MyCustomObjectFormField, Object> {}
```

This creates a flexible `MyCustomObjectFormField` widget, but then also provides a _factory_ for creating a _typical_ case with hard-coded values.  So you could call that factory from the `build` method.

_Does this help?_

**Comment by LefebvreIlyas** [comment]
Thank you for all these precisions!

In my application I use different custom widgets in the forms such as ToggleButtons (which can be generalized to be reused), and a table to configure user permissions that cannot and does not need to be generalized, and which has a hard-coded validator. 

The sample code is focused for the case of the configuration table.

You're right, but it's intentional to simplify the code examples, in my project the name is passed as an argument.

Your code helps me but have some shadows still.
