### ISSUE TITLE
[version 3] Error when wrap the form field with Row

### ISSUE THREAD

**Issue by jasonlaw** [danvick/flutter_form_builder#52]
Hi @danvick ,

When we wrap any field with Row, it will hit the error:

![image](https://user-images.githubusercontent.com/107820/56649138-26f2b780-66b7-11e9-8401-020378f5392f.png)

**Comment by danvick** [comment]
Refer [here](https://github.com/danvick/flutter_form_builder/issues/46#issuecomment-480284848).
