### ISSUE TITLE
Form with table having multiple columns and multiple rows

### ISSUE THREAD

**Issue by SachinTanpure** [danvick/flutter_form_builder#521]
I need to create form which has table with multiple columns and multiple rows.
Each column may contain different types of form element like Textbox, Checkbox, Radio etc.
Basically i have to arrange existing form elements in table's columns and rows format instead of vertical.
Please help me.
For reference please use below image
![70133668-951b4600-16ac-11ea-9af1-5a96c1883cca](https://user-images.githubusercontent.com/6615247/97853480-2b714500-1d1e-11eb-81cf-5b29248cf904.jpeg)

**Comment by LefebvreIlyas** [comment]
Hello @SachinTanpure, what is your problem ?

**Comment by SachinTanpure** [comment]
@LefebvreIlyas i just need to know how to make above ui with form builder.

**Comment by SachinTanpure** [comment]
Okay i have achieved this result through my own R&D

**Comment by DoomTaper** [comment]
@SachinTanpure Can you share how did you achieve it ?
