### ISSUE TITLE
Rich Text widget

### ISSUE THREAD

**Issue by SachinTanpure** [danvick/flutter_form_builder#522]
Need rich text form widget, in which user can to different rich text operations like make text bold, italic, underline, change text color, change text size etc. When form data save, it will save as html text

**Comment by danvick** [comment]
Hello @SachinTanpure,
There's currently no widget for this function within the library. You can howver build your own custom widget to use within FormBuilder as indicated in the documentation.

**Comment by SachinTanpure** [comment]
Yes. Thanks. Made custom widget.
