### ISSUE TITLE
FocusNode in TextFormField not working

### ISSUE THREAD

**Issue by Tyxz** [danvick/flutter_form_builder#53]
I wanted to give it a try, but it is neccessary for me to get an notice, when the focus of the ```TextFormField``` changes. For that I work with a ```FocusNode``` and a listener. 
When I use your form builder and give the text field my global focus node, the listener of it is never called.

**Comment by danvick** [comment]
Hi @Tyxz,
Thanks very much for your contribution. 
This issue has been fixed in the just released v3.0.1.

Thanks again.
