### ISSUE TITLE
Dropdown Field with Editable New Values

### ISSUE THREAD

**Issue by danielweil** [danvick/flutter_form_builder#530]
Hey Dan, 

Is there any way to create a dropdown list field with the option of the user type new values besides the possible values in the field's items?

Thanks! Your package is the main one in my app and I love it. Need to figure out how to do this.

Sincerely,
Daniel

**Comment by mdeandrea-mrmilu** [comment]
Maybe method `registerField` can be help.
If this issue is resolved, please close it
