### ISSUE TITLE
Discrepancy between onImageSelected and onImage

### ISSUE THREAD

**Issue by awhitford** [danvick/flutter_form_builder#536]
These two handlers are basically doing the same thing, but they are suspiciously different.
https://github.com/danvick/flutter_form_builder/blob/db1b4c10ec84ecdbc6339feb8ae45b333b65297e/lib/src/fields/form_builder_image_picker.dart#L177-L186

I'm concerned that this may be a bug. 🐞 This is on the `version_4` branch.

**Comment by deandreamatias** [comment]
This widget is moved to [form_builder_image_picker](https://github.com/danvick/form_builder_image_picker)
