### ISSUE TITLE
FormBuilderDateTimePicker onCancel and onReset not working

### ISSUE THREAD

**Issue by danielweil** [danvick/flutter_form_builder#548]
Hey!

When I clear the date present in the field, clicking in the reset Icon, and after this try to fill the field again, but this time cancel, the value present in the onChange event is still the previous value before the clear.

My issue is that i need to execute code when the date field is cleared, but there is no event triggering it. I tried overwriting the inputDecoration suffixIcon, but I am not being able to clear the state for the field, emptying it.

Do you imagine any way to handle this bug?

Thanks!

**Comment by danielweil** [comment]
![image](https://user-images.githubusercontent.com/44274213/98419792-91363780-2064-11eb-8053-b1c94c9fae82.png)
![image](https://user-images.githubusercontent.com/44274213/98420193-64ceeb00-2065-11eb-8677-32464cbb4821.png)
![image](https://user-images.githubusercontent.com/44274213/98420158-54b70b80-2065-11eb-9d8a-46f80067c7bf.png)

The internal widget ignores my onReset calls.

**Comment by danielweil** [comment]
Guess it is not your widget's fault. Anything you can do?
I checked the datetime_picker_formfield github but he ignored the issues regarding this problem.

**Comment by awhitford** [comment]
`clear` is not the same as `reset`
* `onReset` is called as part of `reset()` where it restores the `initialValue`
* `clear` should empty (or _clear_) the field

Also, rather than calling `_effectiveController.clear()`, try calling `patchValue(null)`.

**Comment by awhitford** [comment]
I think the issue may be a discrepancy between `didChange` and `patchValue` in `FormBuilderDateTimePicker`.

(I'm unclear on why there are 2 methods that essentially do the same thing.)

**Comment by awhitford** [comment]
I think I was able to reproduce this bug and resolve it with PR #551.
There was no `onChange` being wired, and then there was another bug where a null value from a cancelation put the widget in a bad state.

**Comment by danielweil** [comment]
Nice, I was able to handle my issue, doing a couple of things:

![image](https://user-images.githubusercontent.com/44274213/98446493-80390500-20fc-11eb-8563-161746e1e19d.png)

But I think it is a hack.

**Comment by awhitford** [comment]
@danielweil If you are able to test the latest `version_4` branch? It would be great to get feedback.

**Comment by danielweil** [comment]
Not yet! Will try it next week and I will let you know here. Is that ok?

**Comment by awhitford** [comment]
That'd be great.  I will warn you that the latest v4 introduced some breaking changes, but it shouldn't be too bad.

**Comment by danielweil** [comment]
Hey @awhitford, 

Just tested the changes. The onChange is now being called correctly.
The onCancel event is still not triggering for me. But I won't need it.

Thanks for your help!

**Comment by danielweil** [comment]
I know you have a lot in your hands, but I have interest in two opened issues. Is there a way you can have a quick look at it?
Numbers 510 and 530.
