### ISSUE TITLE
l10n - Version 4.0 - French Translations

### ISSUE THREAD

**Issue by cedricDevWP** [danvick/flutter_form_builder#561]
I tried to put the error messages in French but I always get the error in English.

For example when the field is empty when it is required (FormBuilderValidators.required (context)), I have the message "This field cannot be empty".

```dart
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: DotEnv().env['DEBUG'] == 'true',
      theme: CTheme().generateTheme(),
      home: LoginScreen(),
      supportedLocales: [
        Locale('fr'),
      ],
      localizationsDelegates: [
        FormBuilderLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
    );
  }
}
```

i follow this : https://pub.dev/packages/flutter_form_builder/versions/4.0.0-pre.5#l10n but without success...

Do you have an idea of the problem?

thank you in advance,
Cédric

**Comment by danvick** [comment]
Hi @cedricDevWP,
We currently don't have all translations and would actually [appreciate PRs for more language translations](https://pub.dev/packages/flutter_form_builder/versions/4.0.0-pre.5#issues-and-prs).

**Comment by cedricDevWP** [comment]
Ok, I'll try to translate the sentences into French.

On the other hand I tried to follow the steps of the link which you transmitted to me, but the orders fail ...

Do you need to have special packages in addition?

**Comment by cedricDevWP** [comment]
I could translate the sentences into French if someone provided me with the documentation to be able to do so.

I tried the various commands from this link https://pub.dev/packages/flutter_form_builder/versions/4.0.0-pre.6 but without success.

Example : 
e.g. To generate for French run: flutter pub run intl_translation:generate_from_arb --output-dir=lib/l10n --no-use-deferred-loading lib/localization/form_builder_localizations.dart lib/l10n/intl_fr.arb lib/l10n/intl_messages.arb

**Comment by cedricDevWP** [comment]
I found how translate, i was not on the right branch ....

[https://github.com/danvick/flutter_form_builder/tree/version_4](https://github.com/danvick/flutter_form_builder/tree/version_4
)

Step for translate : 

1 - In you project create file : lib/localization/form_builder_localizations.dart and paste [code](https://github.com/danvick/flutter_form_builder/blob/version_4/lib/localization/form_builder_localizations.dart)

2 - In your project create file : lib/l10n/intl_messages.arb and paste [code](https://github.com/danvick/flutter_form_builder/blob/version_4/lib/l10n/intl_messages.arb) 

3 - In your project create file : lib/l10n/intl_**xx**.arb and translate code from 2

4 - Run : flutter pub run intl_translation:generate_from_arb --output-dir=lib/l10n --no-use-deferred-loading lib/localization/form_builder_localizations.dart lib/l10n/intl_**xx**.arb lib/l10n/intl_messages.arb

++

**Comment by cedricDevWP** [comment]
I close when i do a PR

**Comment by cedricDevWP** [comment]
pr #573

**Comment by cedricDevWP** [comment]
you're welcome :)

**Comment by cedricDevWP** [comment]
@danvick,

i have create the translation french, on the other hand it was not added like the supported languages:

[File](https://github.com/danvick/flutter_form_builder/blob/master/lib/localization/form_builder_localizations.dart) : 

```dart
class _FormBuilderLocalizationsDelegate
    extends LocalizationsDelegate<FormBuilderLocalizations> {
  const _FormBuilderLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'es'].contains(locale.languageCode);
  }

  @override
  Future<FormBuilderLocalizations> load(Locale locale) {
    return FormBuilderLocalizations.load(locale);
  }

  @override
  bool shouldReload(_FormBuilderLocalizationsDelegate old) {
    return false;
  }
}
```
