### ISSUE TITLE
Is it possible to remove/hide the black line divider/separator after each field?

### ISSUE THREAD

**Issue by sarbogast** [danvick/flutter_form_builder#562]
I would like to control padding and display my own separators in the Column under FormBuilder.

**Comment by danvick** [comment]
FormBuilder's main purpose is to just provide form  stuff. The rest of how you express your UI wouldn't be restricted by the library, so feel  free to compose your UI the way you want.
The way we have set up the example project with a Column and no padding isn't the only  way.

**Comment by sarbogast** [comment]
OK, but I don't see how

**Comment by sarbogast** [comment]
I just figured out that this black line came from the InputDecorator, so I can remove it or customize it with the decoration field.

**Comment by danvick** [comment]
@Alkabann You know you could just disable input border application-wide from your theme, right?
