### ISSUE TITLE
FormBuilder(Text)Field: enabled and readonly ambiguity

### ISSUE THREAD

**Issue by Wouter12** [danvick/flutter_form_builder#564]
I seem to have an issue with the `readOnly` and `enabled` properties of a FormBuilderTextField (and other fields as well)
What those properties mean to me: 

- enabled: you cannot interact with the field. Taps on the field, and suffixicons get ignored.

- readonly: you cannot change the text, but taps on the field, and suffixicons are not ignored.

What i get from the code of the FormBuilderTextField is that the `enabled` property of the field is based on the `_readOnly` property of the state.

If i put all my formfields on enabled = false (after submitting a form while waiting for the backend call to succeed), I can still tap the fields and enter data. 
If i put readOnly on true, but pass an onTap function to the widget, this function does not get called (for example: to show a search dialog and pass the chosen value to the field).

**Comment by awhitford** [comment]
@Wouter12 **Version 4** dramatically fixes the ambiguity of `enabled` vs `readOnly` and makes things more consistent with Flutter.  I recommend trying the v4 pre-release.

Related to #511.

**Comment by Wouter12** [comment]
Yeah that issue explains it a lot better than I did. Thanks and I will check out the v4 pre-release.
