### ISSUE TITLE
Add max lines property in FormBuilderFilterChip

### ISSUE THREAD

**Issue by IsmailAlamKhan** [danvick/flutter_form_builder#567]
Please add the max lines property in FormBuilderFilterChip as if I have a list with a length of like a hundred the input area's height will be too big. By max lines property, I mean like the text field where you set the max lines property to something like 3 the text field won't be larger than 3 lines but the text inside it will be scrollable.

**Comment by VOIDCRUSHER** [comment]
Typically, it is good design practice to keep information in manageable chunks for the user to digest. Filter chips and chips in general are a great alternative to vertical lists to present information in a vertically compact manner, precisely to avoid having to scroll down a long list of chips. If your use case for FormBuilderFilterChip is to present a wide range of options from which the user will most likely select a much smaller subset of them, (selecting several countries from the set of all countries for example), then I would strongly suggest using FormBuilderChoiceChip instead. If this is not applicable, then I would strongly suggest reconsidering whether all the items are essential or whether you can categorize your original list of options into more refined slices of 30 or fewer items. For these reasons, I would not recommend adding this functionality into the package proper.

However, I believe you can still implement the functionality you seek by wrapping FormBuilderFilterChip with a SingleChildScrollView nested in some bounded widget, such as  SizedBox.

**Comment by IsmailAlamKhan** [comment]
@VOIDCRUSHER thanks for your suggestion. I tried to use the FormBuilderChipsInput but it does not work well with Web, as it cannot be cleared with backspace, also without writing anything the menu does not appear it should show the menu when the field is focused. Thank you.

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by IsmailAlamKhan** [comment]
after 2 years you are asking this question? That's nice. No idea about this issue anymore I will just close it.
