### ISSUE TITLE
SingleChildScrollView scrolling bottom after patchValue 

### ISSUE THREAD

**Issue by cedricDevWP** [danvick/flutter_form_builder#574]
Hello,

I have a SingleChildScrollView in which there is a FormBuilder containing multiple inputs.

In initState of my StateFulWidget I will retrieve data from an API to dynamically fill in the various inputs present in my form.

So the problem is when I fill the last input with a patchValue, this scrolls my SingleChildScrollView down.

```dart
_formKey.currentState.patchValue({
            inputLastname: currentUser.lastname,
            inputFirtsname: currentUser.firstname,
            inputEmail: currentUser.email,
            inputPhone: currentUser.phone,
            inputAddress: currentUser.address,
            inputCity: currentUser.city,
            inputZip: currentUser.zip,
            inputDepartment: currentUser.department,
            inputCountry: currentUser.country,
});
```

Has anyone ever had cares?

**Comment by cedricDevWP** [comment]
I found a workaround while waiting, after my call on my API, i use a ```Future.delayed```  : 

```dart
@override
  void initState() {
    super.initState();
    loadDataUser();
  }

  loadDataUser() async {
    await _con.loadDataUser();

    if (_con.needToLogin) {
      Navigator.of(context).pushReplacementNamed(Config.routeLogin);
    } else {
      Future.delayed(Duration(milliseconds: 1), () {
        setState(() {
          _scrollController.animateTo(0, duration: Duration(milliseconds: 1000), curve: Curves.ease);
        });
      });
    }
  }
```

If i add a delay of : 
- 1 milliseconds => KO (no march)
- 10 millieseconds => OK (march)

**Comment by awhitford** [comment]
I am surprised to hear that `patchValue` would trigger a scroll.  There might be a Focus issue.

You might try a workaround like @cedricDevWP suggests.  Rather than adding a delay, try using [addPostFrameCallback](https://api.flutter.dev/flutter/scheduler/SchedulerBinding/addPostFrameCallback.html) to do the scroll after calling `patchValue`.

**Comment by awhitford** [comment]
We can investigate more if you can provide code that reproduces this behavior.  Thanks!

**Comment by cedricDevWP** [comment]
i will using a adding delay.
