### ISSUE TITLE
Date and Time picker issue

### ISSUE THREAD

**Issue by SachinTanpure** [danvick/flutter_form_builder#575]
In Date Time picker selection color and text color of Hour, Minutes, AM/PM is not visible when selected. Also Okay cancel button is not shown
![WhatsApp Image 2020-11-19 at 1 22 09 PM](https://user-images.githubusercontent.com/6615247/99637230-8a4af400-2a6a-11eb-814b-a126f8775042.jpeg)

This is my code
<pre>
//TIME PICKER  WIDGET
  Widget makeTimePickerWidget(FormElement element){
    return Visibility(
      visible: !element.isHidden,
      maintainState: true,
      child: FormBuilderDateTimePicker(
        attribute: element.id.toString(),
        inputType: InputType.time,
        initialTime:null,
        format: DateFormat("hh:mm a"),
        alwaysUse24HourFormat: false,
        style: Theme.of(context).textTheme.bodyText2,
        readOnly:  element.isDisabled,cancelText: "Cancel",confirmText: "Okay",fieldLabelText: "sdkfslfjskdfj",helpText: "aaaaa",
        decoration: InputDecoration(
            isDense: true,
            hintStyle: Theme.of(context).textTheme.bodyText1.copyWith(color: Colors.grey),
            contentPadding: EdgeInsets.fromLTRB(Sizes.PADDING_5, Sizes.PADDING_10, Sizes.PADDING_5, Sizes.PADDING_10),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(CommonConstants.CORNER_RADIUS),
              borderSide: BorderSide(color: CommonConstants.APP_IS_IN_DARK_MODE ? Colors.black.withOpacity(0.7) : Colors.grey, width: 0.8),
            ),
          focusedErrorBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(CommonConstants.CORNER_RADIUS),
            borderSide: BorderSide(color: Colors.red, width: 0.8),
          ),
          errorBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(CommonConstants.CORNER_RADIUS),
            borderSide: BorderSide(color: Colors.red, width: 0.8),
          ),
          disabledBorder:OutlineInputBorder(
            borderRadius: BorderRadius.circular(CommonConstants.CORNER_RADIUS),
            borderSide: BorderSide(color: CommonConstants.APP_IS_IN_DARK_MODE ? Colors.black : Colors.grey, width: 0.8),
          ),
        ),
        validators: getValidation(element),
        valueTransformer: (value){
          if(value != null)
            return CommonUtils.convertStringDate(date: value.toString(),toFormat: CommonConstants.SERVER_TIME_FORMAT);
          else return value;
        },
        initialValue: element.value != null ? CommonUtils.convertStringToDate(date: element.value,fromFormat: CommonConstants.SERVER_TIME_FORMAT):
        element.defaultValue != null ?
        CommonUtils.convertStringToDate(date: element.defaultValue,fromFormat: CommonConstants.SERVER_TIME_FORMAT):
        null,

      ),
    );
  }

//App Theme 

static final ThemeData lightTheme = ThemeData(
    scaffoldBackgroundColor: _lightPrimaryVariantColor,
    appBarTheme: AppBarTheme(
      brightness: Brightness.dark,
      color: _lightPrimaryVariantColor,
      iconTheme: IconThemeData(color: _lightOnPrimaryColor),
      elevation: Sizes.APP_BAR_ELEVATION,
    ),
    colorScheme: ColorScheme.light(
      primary: _lightPrimaryColor,
      primaryVariant: _lightPrimaryVariantColor,
      secondary: _lightSecondaryColor,
      onPrimary: _lightOnPrimaryColor,
    ),
    iconTheme: IconThemeData(
      color: _iconColor,
    ),
    textTheme: _lightTextTheme,
    cardTheme: _cardThemeLight,
    dividerTheme: _dividerThemeLight,
    hintColor: _lightTextFieldHintColor,
    cardColor: _lightPrimaryColor
  );

  static final ThemeData darkTheme = ThemeData(
    scaffoldBackgroundColor: _darkPrimaryVariantColor,
    appBarTheme: AppBarTheme(
      brightness: Brightness.light,
      color: _darkPrimaryVariantColor,
      iconTheme: IconThemeData(color: _darkOnPrimaryColor),
      elevation: Sizes.APP_BAR_ELEVATION,
    ),
    colorScheme: ColorScheme.dark(
      primary: _darkPrimaryColor,
      primaryVariant: _darkPrimaryVariantColor,
      secondary: _darkSecondaryColor,
      onPrimary: _darkOnPrimaryColor,
    ),
    iconTheme: IconThemeData(
      color: _iconColor,
    ),
    textTheme: _darkTextTheme,
    cardTheme: _cardThemeDark,
    dividerTheme: _dividerThemeDark,
    hintColor: _darkTextFieldHintColor,
    cardColor: _darkPrimaryColor
  );
</pre>

**Comment by SachinTanpure** [comment]
Any solution for this issue?

**Comment by SachinTanpure** [comment]
I have tried example with the custom theme and issue repeat in example also. Looks like form builder date and time picker does not support custom theme.

**Comment by SachinTanpure** [comment]
Any update on this issue?

**Comment by deandreamatias** [comment]
This is related to Flutter theme config. flutter_form_builder uses default components from Flutter
