### ISSUE TITLE
Example typo

### ISSUE THREAD

**Issue by stocksp** [danvick/flutter_form_builder#58]
You are using 'errorMessage' in the requireTrue for the FormBuilderValidatore for the FormBuilderCheckBox

it should be 'errorText';

You might also include in the Readme that the example code requires the 'intl' package.

The example on the pub.dev (not the READMe.md) must be for an older version as it has fundamental problems in the 3.0 environment

**Comment by danvick** [comment]
Hi @stocksp,
Thanks for the heads-up. I also just recently noticed this and will be fixing this as soon as I can.

**Comment by danvick** [comment]
This issue has been fixed. Thanks for bringing it up.
