### ISSUE TITLE
FormBuilderDateTimePicker validators

### ISSUE THREAD

**Issue by frendcarlo** [danvick/flutter_form_builder#581]
using 3.14.1, i got this error from DateTimePicker when i add validators: [
                                    FormBuilderValidators.date(
                                        errorText: 'Date is required'),
                                  ],

error i get is : 

Class 'DateTime' has no instance getter 'isNotEmpty'.
Receiver: Instance of 'DateTime'
Tried calling: isNotEmpty

here's my code 

FormBuilderDateTimePicker(
                                  attribute: 'birthDate',
                                  inputType: InputType.both,
                                  onChanged: (value) => print(value),
                                  initialEntryMode:
                                      DatePickerEntryMode.calendar,
                                  initialValue: DateTime(1960),
                                  firstDate: DateTime(1960),
                                  format: DateFormat('yyyy-MM-dd'),
                                  onSaved: (value) {
                                    if (value != null) print(value);
                                    // save to model
                                  },
                                  validator: (value) {
                                    if (value == null)
                                      return 'Birth of date is required';
                                    return null;
                                  },
                                  validators: [
                                    FormBuilderValidators.date(
                                        errorText: 'Date is required'),
                                  ],
                                ),

looks like it fails here 
// package:flutter_form_builder/src/form_builder_validators.dart:196
/// [FormFieldValidator] that requires the field's value to be a valid date string.
  static FormFieldValidator date({
    String errorText = 'This field requires a valid date string.',
  }) {
    return (valueCandidate) {
      if (valueCandidate != null && valueCandidate.isNotEmpty) {
        if (!isDate(valueCandidate)) return errorText;
      }
      return null;
    };
  }

is there a correct way to implement validators in datetimepicker?

**Comment by danvick** [comment]
Kindly note that the `FormBuilderValidators.date()` is used to check whether a string is a valid date string. Since DateTimePicker always yields a `DateTime`, it's not needed in that context. 

This confusion has been corrected in version 4 by renaming the validator `FormBuilderValidators.dateString()`

**Comment by awhitford** [comment]
Closing since this does not appear to be an FFB issue.
