### ISSUE TITLE
Version 4.0.0 : Not able to create custom form fields

### ISSUE THREAD

**Issue by SachinTanpure** [danvick/flutter_form_builder#588]
Error: The class 'FormBuilderField' is abstract and can't be instantiated.

**Form builder version: 4.0.0**

Here is my code

FormBuilderField(

        name: element.id.toString(),
        validator: getValidation(element),
        initialValue: element.value != null ? _getDefaultValueForFormSearchWidget(element.value):null,
        builder: (FormFieldState<dynamic> field) {
        return InputDecorator(
          decoration: InputDecoration(
            contentPadding: const EdgeInsets.only(top: 0.0,bottom: 0.0,),
            border: InputBorder.none,
            errorText: field.errorText,
          ),
          child: FormSearchFormWidget(label: element.label,formId:element.properties.metaData.formID != null ? element.properties.metaData.formID.toString():"",
            formRepository: _formRepository,
            formFieldState: field,
            readOnly: (_readOnlyForm || element.isDisabled),
            formElementMetaData: element.properties.metaData,
            fbKey: _fbKey,
            getFormWidgetValueFromLabel: (String label){
              return _getFormWidgetValueFromLabel(label);
            },
          ),
        );
        },
      ),

Flutter doctor
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.14.6 18G3020, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!

**Comment by danvick** [comment]
This issue has been noted and is [being worked on](https://github.com/danvick/flutter_form_builder/pull/587).

**Comment by danvick** [comment]
This should be fixed in 4.0.1
