### ISSUE TITLE
Any options to pull data from custom component(From external color picker widget)

### ISSUE THREAD

**Issue by nipunravisara** [danvick/flutter_form_builder#594]
I'm having a external color picker package and It's also a part of the form so i needs to get data from that also. Is there any options to pull data from custom component on currentstatus.save();

**Comment by danvick** [comment]
Hi @RavisaraDev,
With Formbuilder, you could [build your own custom inputs](https://github.com/danvick/flutter_form_builder#building-your-own-custom-field) if you wanna

You could achieve it like so:

```dart
FormBuilderField(
  name: "name",
  builder: (FormFieldState<Color> field) {
    return InputDecorator(
      decoration: InputDecoration(
        labelText: "Pick Color",
        errorText: field.errorText,
      ),
      child: YourColorPicker(
          onChanged: (value) {
            field.didChange(value);
          },
      ),
    );
  },
),
```

**Comment by RavisaraDev** [comment]
Ups I'm new to flutter, i missed it. Anyway thanks @danvick  it worked.

**Comment by RavisaraDev** [comment]
I'm using [flex_color_picker](https://github.com/rydmike/flex_color_picker) as a custom field using **FormBuilderField**. But It's not able to read the picker value and always fail validation. but in the picker side it's clearly shows the color is selected. Am I missing something here.

This is how my widget looks like.
```
class ColorPicker extends StatefulWidget {
  final name;
  final label;

  ColorPicker({
    this.name,
    this.label,
    Key key,
  }) : super(key: key);

  @override
  _ColorPickerState createState() => _ColorPickerState();
}

class _ColorPickerState extends State<ColorPicker> {
  Color screenPickerColor;

  @override
  void initState() {
    super.initState();
    screenPickerColor = Colors.orange;
  }

  @override
  Widget build(BuildContext context) {
    return FormBuilderField(
      name: widget.name,
      validator: FormBuilderValidators.compose([
        FormBuilderValidators.required(context),
      ]),
      builder: (FormFieldState<Color> field) {
        return InputDecorator(
          decoration: InputDecoration(
            border: InputBorder.none,
            errorText: field.errorText,
          ),
          child: flexColorPicker.ColorPicker(
            width: 28.2,
            height: 28.2,
            spacing: 12,
            runSpacing: 12,
            borderRadius: 8,
            crossAxisAlignment: CrossAxisAlignment.start,
            color: screenPickerColor,
            padding: EdgeInsets.zero,
            enableShadesSelection: false,
            onColorChanged: (Color color) =>
                setState(() => screenPickerColor = color),
          ),
        );
      },
    );
  }
}
```

**Comment by danvick** [comment]
Hi @RavisaraDev,
I see you've made good progress, the only thing remaining was to notify the field that the value has changed. 

Like so:

```dart
onColorChanged: (Color color){
    setState(() => screenPickerColor = color);
    field.didChange(color)l
}
```

**Comment by RavisaraDev** [comment]
> Hi @RavisaraDev,
> I see you've made good progress, the only thing remaining was to notify the field that the value has changed.
> 
> Like so:
> 
> ```dart
> onColorChanged: (Color color){
>     setState(() => screenPickerColor = color);
>     field.didChange(color)l
> }
> ```

This worked @danvick again thanks for the awesome work,  package and the help 💪
