### ISSUE TITLE
Color picker type MaterialPicker visibility problem

### ISSUE THREAD

**Issue by BoHellgren** [danvick/flutter_form_builder#597]
This is a very nice picker, but it has a problem. Many users complain that they cannot see which color they have chosen. If you look closely, the selected color is surrounded by very faint lines in the same color. They are almost invisible. If the lines were black, there would be no problem to see what you have chosen.

**Comment by danvick** [comment]
Hi @BoHellgren,
The color picker comes from another library which this package is making use of.

Kindly raise the issue on the [flutter_colorpicker repo](https://github.com/mchome/flutter_colorpicker)

**Comment by deandreamatias** [comment]
Closed because don't apply to this package
