### ISSUE TITLE
flutter_datetime_picker.dart:215:48: Error: No named parameter with the name 'shadowThemeOnly'

### ISSUE THREAD

**Issue by BayzedHossain** [danvick/flutter_form_builder#600]
Launching lib/main.dart on Chrome in debug mode...
../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.4.0/lib/flutter_datetime_picker.dart:215:48: Error: No named parameter with the
name 'shadowThemeOnly'.
    ThemeData inheritTheme = Theme.of(context, shadowThemeOnly: true);  
                                               ^^^^^^^^^^^^^^^          
../../../../snap/flutter/common/flutter/packages/flutter/lib/src/material/theme.dart:119:20: Context: Found this candidate, but the arguments don't match.
  static ThemeData of(BuildContext context) {                           
                   ^^

**Comment by suhfangmbeng** [comment]
Yes, I experience the same issue. Any solution you got for this @BayzedHossain ?

**Comment by RavisaraDev** [comment]
I'm having the same issue.

**Comment by slavap** [comment]
@suhfangmbeng 
The only solution I've found is copying both folders with sources:
flutter_form_builder
flutter_datetime_picker

to my project, fixing them, and using relative import in pubspec.yaml, like:
```
flutter_form_builder:
    path: ../flutter_form_builder
```

**Comment by danvick** [comment]
Hi @BayzedHossain / all,
Which Flutter channel are you on?

**Comment by slavap** [comment]
@danvick Beta channel, Flutter 1.24.0-10.2.pre

**Comment by angwandi** [comment]
flutter_datetime_picker-1.4.0/lib/flutter_datetime_picker.dart:215:48: Error: No named parameter with the name 'shadowThemeOnly'.

Same issue

**Comment by awhitford** [comment]
Related to https://github.com/Realank/flutter_datetime_picker/issues/206 too.

**Comment by gaboreyes** [comment]
I'm having the same issue, anybody has a solution other than @slavap workaround ??

**Comment by awhitford** [comment]
Please add a 👍 to https://github.com/Realank/flutter_datetime_picker/issues/206 and https://github.com/Realank/flutter_datetime_picker/issues/197.  We need to get that project's attention.

**Comment by deandreamatias** [comment]
This still a issue?
