### ISSUE TITLE
Beta & Dev channels are broken - ChoiceChip shape

### ISSUE THREAD

**Issue by awhitford** [danvick/flutter_form_builder#602]
I just enabled matrix builds to test this library across Flutter channels (`stable`, `beta`, `dev`).  This exposed that there is a breaking change with `beta` and `dev`.  I recorded the issue here:  https://github.com/flutter/flutter/issues/71352

> It appears that `shape` was changed from `ShapeBorder` to `OutlinedBorder` for `ChoiceChip`

I am curious if they end up reverting it because they could introduce the change with a deprecation phase first.

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
