### ISSUE TITLE
FormBuilderChoiceChip Add border color on FormBuilderFieldOption

### ISSUE THREAD

**Issue by cedricDevWP** [danvick/flutter_form_builder#608]
Hello,

I tried in vain to add a color on the border but without success.

I would like to set up this visual:

<img width="338" alt="Capture d’écran 2020-12-01 à 14 44 16" src="https://user-images.githubusercontent.com/12508260/100748510-b1e37a00-33e3-11eb-8d08-56beb30fdfc6.png">

Would it be possible to add this functionality?

**Comment by VOIDCRUSHER** [comment]
FormBuilderChoiceChip and FormBuilderFilterChip both expose all parameters from core Flutter ChoiceChip and FilterChip. If you would like to customize your chips, I would recommend looking into the official Flutter documentation. In your case for example you might want to pass in a ShapeBorder to the the shape parameter, a StadiumBorder with a custom color from the looks of it.
