### ISSUE TITLE
Cannot upgrade  json_annotation because of flutter_form_builder reference to vin_decoder 

### ISSUE THREAD

**Issue by slavap** [danvick/flutter_form_builder#619]
vin_decoder is kind of "abandoned", probably should be excluded from flutter_form_builder.
Related issue: https://github.com/adaptant-labs/vin-decoder-dart/issues/2

```
Because every version of flutter_form_builder from path depends on validators ^2.0.1 and no versions of validators match >2.0.1 <3.0.0, every version of flutter_form_builder from path requires validators 2.0.1.


And because validators 2.0.1 depends on vin_decoder ^0.1.2, every version of flutter_form_builder from path requires vin_decoder ^0.1.2.
And because no versions of vin_decoder match >0.1.2 <0.2.0 and vin_decoder 0.1.2 depends on basic_utils ^2.5.4, every version of flutter_form_builder from path requires basic_utils ^2.5.4.

Because basic_utils >=2.4.4 <2.7.0-rc.1 depends on json_annotation >=2.0.0 <=3.0.1 and basic_utils >=2.7.0-rc.1 depends on json_annotation >=2.0.0 <=3.1.0, basic_utils >=2.4.4 requires json_annotation >=2.0.0 <=3.1.0.

Thus, every version of flutter_form_builder from path requires json_annotation >=2.0.0 <=3.1.0.

So, because swtouch depends on both json_annotation ^3.1.1 and flutter_form_builder from path, version solving failed.
```

**Comment by awhitford** [comment]
As far as _Flutter Form Builder_ is concerned, `vin_decoder` is an _unused transitive_ dependency from `validators`:
https://github.com/danvick/flutter_form_builder/blob/c2b63433778187cd9258499f1bf5f53781fa3ffa/pubspec.yaml#L34

**There is nothing that this library can do.**

Besides the [issue](https://github.com/adaptant-labs/vin-decoder-dart/issues/2) for `vin_decoder`, there is already an [issue](https://github.com/dart-league/validators/issues/20) for `validators`: https://github.com/dart-league/validators/issues/20

I submitted a [PR](https://github.com/adaptant-labs/vin-decoder-dart/pull/4), but the maintainers will need to accept it.

In the meantime, try using `dependency_overrides`.

**Comment by awhitford** [comment]
`vin_decoder` Version 0.1.3 was released:  https://pub.dev/packages/vin_decoder/changelog

Hopefully that helps.
