### ISSUE TITLE
How to Load images back into form.. for editing

### ISSUE THREAD

**Issue by prakash-indorkar** [danvick/flutter_form_builder#622]
Hi. It might be a silly question. But I couldn't find any example which shows how to load back images to from. New images are picked from device or camera is fine. But how to assign initialValue for Images in editing form?
I tried to assign list of MemoryImages it didn't work. Initialise it with list of network image path.. it dint work. 
Please share the example.
Thanks in advance, Prakash.

**Comment by haliknihudas666** [comment]
I've also encountered this issue right now on the flutter_form_builder: 4.0.2
I just recently upgraded to 4.0.2 from 3.14.0
on 3.14.0 you don't need to reassign the picked image and imagepicker should do its job replacing your placeholder image if you have one but when i upgraded to 4.0.2 it doesn't replace the placeholder image

**Comment by deandreamatias** [comment]
Closed because this widget is moved to https://github.com/danvick/form_builder_image_picker
