### ISSUE TITLE
How to fix flutter_datetime_picker.dart after add flutter_form_builder 4.0.2 (My flutter sdk 1.25)

### ISSUE THREAD

**Issue by chanthavong** [danvick/flutter_form_builder#629]
.pub-cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.4.0/lib/flutter_datetime_picker.dart:215:48: Error: No named parameter with the name 'shadowThemeOnly'.
    ThemeData inheritTheme = Theme.of(context, shadowThemeOnly: true);

                                               ^^^^^^^^^^^^^^^
../../../development/flutter/packages/flutter/lib/src/material/theme.dart:107:20: Context: Found this candidate, but the arguments don't match.
  static ThemeData of(BuildContext context) {

**Comment by zsoerenm** [comment]
This error occurs in the flutter dev channel.
I recommend going back to the stable channel with:
```
flutter channel stable
```

**Comment by joeyyy688** [comment]
https://stackoverflow.com/questions/64706160/flutter-not-able-to-run-get-navigation-theme-error

check this link for the solution
