### ISSUE TITLE
FormBuilderCheckbox Exception

### ISSUE THREAD

**Issue by supermnemonic** [danvick/flutter_form_builder#636]
I followed the example to create FormBuilderCheckbox, but `Exception` occurred. 

> ════════ Exception caught by scheduler library ═════════════════════════════════
> 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2632 pos 14: 'node.parent?._dirty != true': is not true.
> 

flutter_form_builder: ^4.0.2

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.51.1)

<hr>

**Update**

It works properly, but it keep logs the Exception. And I think it only happened in iOS. Here is my code.

```
FormBuilderCheckbox(
  name: 'accept_terms',
  initialValue: false,
  onChanged: _onChanged,
  // leadingInput: true,
  title: RichText(
    text: TextSpan(
      children: [
        TextSpan(
            text: 'I have read and agree to the ',
            style: TextStyle(color: Colors.black)),
        TextSpan(
          text: 'Terms and Conditions',
          style: TextStyle(color: Colors.blue),
          recognizer: TapGestureRecognizer()
            ..onTap = () {
              print('launch url');
            },
        ),
      ],
    ),
  ),
  validator: FormBuilderValidators.compose([
    FormBuilderValidators.required(context,
        errorText:
            'You must accept terms and conditions to continue'),
  ]),
)
```

**Comment by awhitford** [comment]
@supermnemonic We will need more information than this, but I will warn you that the README is a little out of date -- and we should definitely fix that.

This is a working example from the `example` app:
```dart
                  FormBuilderCheckbox(
                    name: 'accept_terms',
                    initialValue: false,
                    onChanged: _onChanged,
                    title: RichText(
                      text: TextSpan(
                        children: [
                          TextSpan(
                            text: 'I have read and agree to the ',
                            style: TextStyle(color: Colors.black),
                          ),
                          TextSpan(
                            text: 'Terms and Conditions',
                            style: TextStyle(color: Colors.blue),
                            // Flutter doesn't allow a button inside a button
                            // https://github.com/flutter/flutter/issues/31437#issuecomment-492411086
                            /*
                            recognizer: TapGestureRecognizer()
                              ..onTap = () {
                                print('launch url');
                              },
                            */
                          ),
                        ],
                      ),
                    ),
                    validator: FormBuilderValidators.compose([
                      FormBuilderValidators.equal(
                        context,
                        true,
                        errorText:
                            'You must accept terms and conditions to continue',
                      ),
                    ]),
                  ),
```

Note:
* The `TapGestureRecognizer` is invalid because _Flutter doesn't allow a button inside a button_
* `FormBuilderValidators.requiredTrue` was deprecated in favor of `FormBuilderValidators.equal`

If you are still having a problem, please share your code fragment so that we can reproduce.

**Comment by supermnemonic** [comment]
@awhitford I updated with code.

**Comment by supermnemonic** [comment]
@awhitford I am sorry. I think I missed your notice "Flutter doesn't allow a button inside a button". I did remove TapGestureRecognizer inside, and now Exception gone. I think this can be closed.

Thank you for your help.
