### ISSUE TITLE
FormBuilderSearchableDropdown getting the value

### ISSUE THREAD

**Issue by angwandi** [danvick/flutter_form_builder#642]
_formKey.currentState.fields['name'].currentState.value  : not working

**Comment by andrewzakhartchouk** [comment]
Did you try this?
 `_formKey.currentState.value['name']`

**Comment by angwandi** [comment]
I just tried it but not achieving what I am trying to do here: Change the item list on the second formbuilder based on the value of the first one. The code below

> FormBuilderSearchableDropdown(
          name: 'Category',
          items: EventItemsList.category,
          initialValue: 'Choose',
        ),
        FormBuilderSearchableDropdown(
          initialValue: 'Music',
          name: 'Subcategory',
          items: _formKey.currentState.value['Category'] == 'Music'
              ? EventItemsList.music_sub_category
              : [],
        ),

**Comment by andrewzakhartchouk** [comment]
How about using the onChanged property to create a new list with values that match the category?

**Comment by angwandi** [comment]
@andrewzakhartchouk example code please

**Comment by andrewzakhartchouk** [comment]
Can't really come up with a solution, but I would suggest to try using `setState()` and/or `Provider` to change the items of the 'Subcategory' field.

**Comment by angwandi** [comment]
Thanks @andrewzakhartchouk. Works like a charm

**Comment by mdeandrea-mrmilu** [comment]
This issue is resolved? If yes, close please

**Comment by mdeandrea-mrmilu** [comment]
Can be close this issue?
