### ISSUE TITLE
Support for Flutter Web in 4.x.x

### ISSUE THREAD

**Issue by MichaelDark** [danvick/flutter_form_builder#645]
`flutter_form_builder` is not compatible with Flutter Web. Projects, that have been using version flutter_form_builder 3.x.x cannot migrate to 4.x.x because there are 3 transitive dependencies that are not compatible with Flutter Web.

`image_picker` is maintained by Flutter, no support for Web yet.
Analog: `file_picker_cross`
https://pub.dev/packages/image_picker
https://pub.dev/packages/file_picker_cross

No analogs for `permission_handler`, still is under the question if it is really needed in `flutter_form_builder`.
https://pub.dev/packages/permission_handler

No analogs for `phone_number`, still is under the question if it is really needed in `flutter_form_builder`.
https://pub.dev/packages/phone_number

Perhaps, the best ide would be to move it to:
- `flutter_form_builder_permissions` or 
- `flutter_form_builder_${name of specific functionality provided by this package in addition to flutter_form_builder}`. 

Divide and conquer 🥇

**Comment by danvick** [comment]
Thanks for the suggestion @MichaelDark. This is something we've been considering and we'll have them separated from the main package as we've done for [form_builder_file_picker](https://pub.dev/packages/form_builder_file_picker) and [form_builder_map_field](https://pub.dev/packages/form_builder_map_field)
