### ISSUE TITLE
How to only show validation errors on change

### ISSUE THREAD

**Issue by stocksp** [danvick/flutter_form_builder#65]
If autovalidate is true on the FormBuilder:
All validation errors are shown for the whole form as soon as one control is edited.

If autovalidate is false on the FormBuilder but true on the FormBuilderXX widgets
all validation errors are show as soon as the form loads.

Both of these are wrong.
Validation errors should only be show when the widget is changed.  So the user is only shown one error at a time at the moment they make the edit.
Submit should not be enabled if the form is not valid.

Can this be achieved in Flutter (I hope) ?

**Comment by zhousheng1114** [comment]
+1

**Comment by Pannkaaka** [comment]
Is there a solution to this since the issue was closed?

**Comment by ChristBKK** [comment]
I have the same problem?

**Comment by stocksp** [comment]
Forms processing in Flutter is probably it’s weakest.  This package will not help you.  Some day someone will write a Formik or Finalform like the JavaScript world has.  It’s very hard and tedious in Flutter.  For modest (a few simple controls) forms it’s doable.  You must  create and manage the focusNodes for each control to generate an ‘onBlur’ and ‘isDirty’ etc and then hook these into your validation logic.  For serious business form processing ... forget it

**Comment by ChristBKK** [comment]
@stocksp  thanks for that input. I agree with your points, focusNodes is also quite complicated for that simple logic.

@danvick  thanks for your good work with this package. Can you check on this topic again? It feels like the biggest problem for me right now using your validations.
Or where do I find the duplicated issue for this one?
