### ISSUE TITLE
[FormBuilderDateTimePicker] rename `theme` property to `cupertinoTheme`

### ISSUE THREAD

**Issue by torbenkeller** [danvick/flutter_form_builder#652]
The theme property will not apply to the standard material DateTimePickerDialog. It will be only applied when the `pickerType` property is set to `PickerType.cupertino`. This actually costs me 2 hours to figure out why the Dialog is not styled as I want and there is no Documentation about this. So please change the property name to make it more clear or add at least some documentation for this field.

**Comment by deandreamatias** [comment]
This isn't apply because PickerType is deprecated
