### ISSUE TITLE
Exception: The plugin file_picker could not be built due to the issue above.

### ISSUE THREAD

**Issue by Kalyanb447-github** [danvick/flutter_form_builder#654]
The built failed likely due to AndroidX incompatibilities in a plugin.
Building plugin file_picker...

**Comment by andrewzakhartchouk** [comment]
Perhaps [#508](https://github.com/danvick/flutter_form_builder/issues/508#issuecomment-716872989) or [#637](https://github.com/danvick/flutter_form_builder/issues/508#issuecomment-716872989) could help you?

**Comment by Sor0** [comment]
Thanks it works

**Comment by deandreamatias** [comment]
Duplicated
