### ISSUE TITLE
FormBuilderCheckboxGroup and initialValue

### ISSUE THREAD

**Issue by nlfiedler** [danvick/flutter_form_builder#657]
Seems like the `FormBuilderCheckboxGroup` passes the widget's `initialValue` to the `GroupedCheckbox` instead of passing the `_initialValue` private field. That is, when I'm building a `FormBuilderCheckboxGroup` the checkboxes are not initially selected as expected, unless I pass in `initialValue` in the constructor. For example:

```dart
        FormBuilderState formState = FormBuilder.of(context);
        FormBuilderCheckboxGroup<bool>(
          attribute: 'stores',
          options: packStoreOptions,
          initialValue: formState.initialValue['stores'],
          decoration: InputDecoration(
            icon: Icon(Icons.archive),
            labelText: 'Pack Store(s)',
          ),
          // require at least one pack store is selected
          validators: [FormBuilderValidators.required()],
        ),
```
 Is this expected behavior? I don't need to do the same with any of the other widgets. If I'm right and this is in fact not the desired behavior, please give me a sign and I'll be happy to submit a PR. Thanks.

**Comment by danvick** [comment]
This is for version 3.*, right?

**Comment by Iccr** [comment]
Hi, any update on this. I am using` flutter_form_builder: ^4.2.0`, An I cannot set the initial value.
I have widget like this.
```
FormBuilderCheckboxGroup<Parking>(
        initialValue: initialValue,
        focusNode: focusNode,
        key: parkingKey,
        validator: (value) {
          return value == null ? "This field cannot be empty" : null;
        },
        decoration: ChautariDecoration().outlinedBorderTextField(
          labelText: "parkings",
          helperText: "Select all availabe options",
        ),
        name: "parking",
        options: options,
        onSaved: (newValue) => onSaved(newValue),
      ),
```

And I am using this like this,

```
RoomParkingCheckBoxWidget(
                        initialValue: controller.room.parkings,
                        parkingKey: controller.formKeys.parkingKey,
                        focusNode: controller.focusNodes.parkingFocusNode,
                        options: controller.appInfoService.appInfo.parkings
                            .map(
                              (element) => FormBuilderFieldOption(
                                value: element,
                                child: Text(element.name.capitalize),
                              ),
                            )
                            .toList(),
                        onSaved: (value) => controller.room.parkings = value,
                      ),

```

But it does not set checked to the initially selected values.

**Comment by Iccr** [comment]
I found out that  `value: selectedListItems.contains(optionValue),` this line was causing the trouble inside `GroupedCheckbox`. even  selectedListItems's element and optionValue belongs to same class, They are not equal.  I override == operator for the Parking class and it is now working like a charm.

```
class Parking {
...
bool operator ==(Object other) =>
      identical(this, other) ||
      other is Parking && runtimeType == other.runtimeType && tag == other.tag;

  @override
  int get hashCode => tag.hashCode;
  }
```

**Comment by deandreamatias** [comment]
This still a issue?

**Comment by nlfiedler** [comment]
It was less of an issue and more of question.

**Comment by deandreamatias** [comment]
This is a unsolved question?

**Comment by nlfiedler** [comment]
I am referring to my question in the original report. If that does not make sense, then feel free to close this, as I must be misunderstanding and you can ignore me.
