### ISSUE TITLE
Appstore rejected because of Required Permissions

### ISSUE THREAD

**Issue by scrombie** [danvick/flutter_form_builder#659]
Hello, 

Very awesome stuff you guys have done here.

I ran into an issue recently while trying to deploy my flutter app to the app store.

The app got rejected cause certain permissions that were required were not included in the Info.plist file. 

Here are the permissions in question:

```
NSAppleMusicUsageDescription
NSSpeechRecognitionUsageDescription
NSCalendarsUsageDescription
NSMotionUsageDescription
NSLocationAlwaysUsageDescription
NSLocationWhenInUseUsageDescription
```
They recommend adding descriptions to the Info.plist for each of these permissions, but I don't require any of these permissions in my app, so its sort of weird (and unsafe) having to grant access to these guys.

I did some digging and it turns out its being caused by a dependency in your package: permission_handler

Please, Any ideas on how to resolve this?

**Comment by danvick** [comment]
Hi @scrombie,
Thanks for bringing this to our attention. This is related to #645, and  we are working to fix it
