### ISSUE TITLE
_fbKey.currentState.value is always empty even after changing a field.

### ISSUE THREAD

**Issue by MachariaK** [danvick/flutter_form_builder#663]
I updated to version 4 then downgraded to version 3 and now the values are not being saved. When I change a field ad print _fbKey.currentState.value, I am getting an empty map.

**Comment by diegoaces** [comment]
Hello, have you called the _fbKey.currentState.validate function? the values ​​change after calling that function.

**Comment by WilliamCunhaCardoso** [comment]
you can use save() too, don'þ you?

**Comment by awhitford** [comment]
@MachariaK Please include some sample code that reproduces the issue.

**Comment by deandreamatias** [comment]
Closed for no feedback
