### ISSUE TITLE
In v4 FormBuilderImagePicker link for package is down. 

### ISSUE THREAD

**Issue by Shiba-Kar** [danvick/flutter_form_builder#664]

**Comment by WingCH** [comment]
same problem
in `4.20` release note : https://pub.dev/packages/flutter_form_builder/changelog#420---29-dec-2020
[form_builder_image_picker](https://pub.dev/packages/form_builder_image_picker) link cannot find any Additional plugin

![image](https://user-images.githubusercontent.com/19588517/103405683-de311880-4b92-11eb-9c65-aaa3474f7420.png)

**Comment by amoslai5128** [comment]
Same issues same, I cannot run the project

**Comment by danvick** [comment]
Sorry for the delay guys, this should be fixed now.
