### ISSUE TITLE
How to validate Email and Phone number on same field... (Question) (Either One Validation is True)

### ISSUE THREAD

**Issue by rmControls** [danvick/flutter_form_builder#669]
First of all thanks for developing this great package....

I have a requirement to validate the field for either phone number or email.... if any one of them is true then it should allow them to submit the form... 

that means => isNotEmpty &&  (isPhone || isEmail)

I read your document and found compose option will server the purpose of multiple validation... but I am not sure how to use it for "or" condition...

Sorry to post my question here... didn't found the right place to post it....

**Comment by rmControls** [comment]
Hello,

Is this feature available or do I need to make a custom one... if 'Yes' then how do I make to work??

**Comment by WilliamCunhaCardoso** [comment]
Inside compose, you may add custom validators, like:

```dart
FormBuilderValidators.compose([
                    (value) => customValidatorMethod(value)
                  ])
```

And, creating a method like

```dart
// You should type the value according the field you use.
String? customValidatorMethod(dynamic value) {
if(!someLogicThatVerifyIfIsPhone && !someLogicThatVerifyIfIsEmail){
return not a valid phone neither email.
}

return null;
}
```

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
