### ISSUE TITLE
FormBuilder cause exception in rotation for duplicate attribute

### ISSUE THREAD

**Issue by shariful2011** [danvick/flutter_form_builder#67]
During rotation got an exception as follows:
I/flutter (28924): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (28924): The following assertion was thrown building MyDropDown:
I/flutter (28924): Field with attribute 'attribute' already exists. Make sure that two or more fields don't have the same
I/flutter (28924): attribute name.
I/flutter (28924): 'package:flutter_form_builder/src/form_builder.dart': Failed assertion: line 64 pos 12:
I/flutter (28924): '_fieldKeys.containsKey(attribute) == false'

**Comment by danvick** [comment]
Kindly make sure that no two fields have the same `attribute` name

**Comment by shariful2011** [comment]
All of my fields are a unique attribute. It perfectly works with Portrait mode but not in Landscape mode.

**Comment by danvick** [comment]
Thanks for bringing this issue to my attention. I'll have a look into it and try to fix it as soon as I can.

Meanwhile, as I had earlier noted, an assertion failure is not necessarily an error, you can therefore ignore this assertion failure as it won't affect your app in production.

**Comment by shariful2011** [comment]
If I can't do anything in development phase what can I have in production? Please solve it, it's making crazy on every rotation.

**Comment by danvick** [comment]
The assertion was removed in later versions of the package.
