### ISSUE TITLE
How do I create TextArea field??

### ISSUE THREAD

**Issue by rmControls** [danvick/flutter_form_builder#670]
I was trying to build form with TextArea field  but I am not able to find that field in the package....

I only see FormBuilderTextField...

am I missing something?

**Comment by andrewzakhartchouk** [comment]
You can use the `maxLines` property in the FormBuilderTextField widget to set the height (number of lines).

**Comment by emri99** [comment]
Also you can use `minLines: X` and `maxLines: null` for dynamic height textarea upon content, take care of scrolling in this case ;)

**Comment by rmControls** [comment]
Thanks for the help it works...
