### ISSUE TITLE
Because flutter_form_builder 4.0.2 depends on intl ^0.16.1 and no versions of flutter_form_builder match >4.0.2 <5.0.0, flutter_form_builder ^4.0.2 requires intl ^0.16.1.

### ISSUE THREAD

**Issue by joeyyy688** [danvick/flutter_form_builder#673]
Because flutter_form_builder 4.0.2 depends on intl ^0.16.1 and no versions of flutter_form_builder match >4.0.2 <5.0.0, flutter_form_builder ^4.0.2 requires intl ^0.16.1.

Can someone help me fix this error please?

dependency_overrides:
intl: ^0.17.0-nullsafety.2

I later did this but the error is still coming as:

Because myapp depends on dependency_overrides from unknown source "intl", version solving failed.
pub get failed (1; Because myapp depends on dependency_overrides from unknown source "intl", version solving failed.)

**Comment by awhitford** [comment]
Duplicates #634

**Comment by joeyyy688** [comment]
@awhitford  I don't get you
can you explain further ?
