### ISSUE TITLE
[4.2.0] Hit error when running debug

### ISSUE THREAD

**Issue by jasonlaw** [danvick/flutter_form_builder#674]
Hi @danvick ,

I am getting error when running debug. 
It seems something to do with the flutter_typehead package, could you please take a look?
Many Thanks.

~~~dart
Launching lib\main.dart on Android SDK built for x86 in debug mode...
 lib\main.dart
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.2.0/lib/src/fields/form_builder_typeahead.dart:184:9: Error: Expected 0 type arguments.
  final TextFieldConfiguration<T> textFieldConfiguration;
        ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.2.0/lib/src/fields/form_builder_typeahead.dart:328:20: Error: Expected 0 type arguments.
              ) as TextFieldConfiguration<dynamic>,
                   ^^^^^^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 43s
Picked up _JAVA_OPTIONS: -Xmx2g
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

~~~

**Comment by jasonlaw** [comment]
Looks like here is the culprit.

![image](https://user-images.githubusercontent.com/107820/103868562-02957380-5104-11eb-810e-33d5c017d08a.png)

**Comment by gooljim** [comment]
Yes,I also ,please fix it

**Comment by Silfalion** [comment]
just got this as well

**Comment by Silfalion** [comment]
Found the issue. It was weird since everything was working fine yesterday and not anymore this morning. Turns out the flutter typehead dev pushed an update yesterday/this morning which causes the problem because flutter form builder is depended on it.

Long story short, in the meantime that the dev of typehead fixes the issue, add this to your pubspec.yaml and everything should work:

flutter_typeahead: "<=1.9.1"


Opened an issue as well on their repo if anyone's interested: https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/270#issue-781183747

**Comment by jasonlaw** [comment]
> Found the issue. It was weird since everything was working fine yesterday and not anymore this morning. Turns out the flutter typehead dev pushed an update yesterday/this morning which causes the problem because flutter form builder is depended on it.
> 
> Long story short, in the meantime that the dev of typehead fixes the issue, add this to your pubspec.yaml and everything should work:
> 
> flutter_typeahead: "<=1.9.1"
> 
> Opened an issue as well on their repo if anyone's interested: [AbdulRahmanAlHamali/flutter_typeahead#270 (comment)](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/270#issue-781183747)

Thanks @Silfalion for the update.
I believe the error is not within the flutter_typehead package, but rather in this package.
flutter_typehead has made some changes that causing some breaking changes here.
I removed the generic type <dynamic> from TextFieldConfiguation<dynamic> and it works.
Anyway, I will leave it to @danvick for the correct fixes.

**Comment by Silfalion** [comment]
my please @jasonlaw.
I see, so it's a matter of incompatibility.
Thank you for the notice and explanation.

**Comment by devnullpointer** [comment]
I also received this error when running a flutter run command, but I don't make any use of TypeAhead. I just added one FormBuilderTextField and now I got a whole slew of warnings along with those errors which I never had before.

**Comment by danjenson** [comment]
Same, also getting this error in my automated builds.

**Comment by devnullpointer** [comment]
I'm gettitng frustrated because no matter what version of form_builder I use in pubspec it causes my compilation errors in my app.

**Comment by devnullpointer** [comment]
Quick fix for those who can't wait is top remove generics type-safety on the declaration and usage of TextFieldConfiguration lines 184 and 328 in the file form_builder_typeahead.dart
