### ISSUE TITLE
Version solving error on flutter beta channel

### ISSUE THREAD

**Issue by mattf80** [danvick/flutter_form_builder#676]
Getting the following version conflict when installing form builder into a brand new flutter app on the beta channel:

```
Because flutter_form_builder >=4.0.0-alpha.3 depends on flutter_localizations any from sdk which depends on intl 0.17.0-nullsafety.2, flutter_form_builder >=4.0.0-alpha.3 requires intl 0.17.0-nullsafety.2.

So, because <app-name> depends on flutter_form_builder ^4.2.0 which depends on intl ^0.16.1, version solving failed.
```

Is this expected or should it work on the beta channel?

**Comment by dsvignesh** [comment]
add the below lines in pubspec.yaml
dependency_overrides:
  intl: ^0.17.0-nullsafety.2

**Comment by pinterhuang** [comment]
> add the below lines in pubspec.yaml
> dependency_overrides:
> intl: ^0.17.0-nullsafety.2

No, It doesn't work. You will get
Because <app-name> depends on flutter_form_builder ^4.2.0 which depends on intl ^0.16.1, intl ^0.16.1 is required.

So, because <app-name> depends on intl ^0.17.0-nullsafety.2, version solving failed.

**Comment by franco-brusca** [comment]
> > add the below lines in pubspec.yaml
> > dependency_overrides:
> > intl: ^0.17.0-nullsafety.2
> 
> No, It doesn't work. You will get
> Because depends on flutter_form_builder ^4.2.0 which depends on intl ^0.16.1, intl ^0.16.1 is required.
> 
> So, because depends on intl ^0.17.0-nullsafety.2, version solving failed.

I had the same error you posted and with that change it worked for me. What error does it show you now?

**Comment by niktob560** [comment]
> > > add the below lines in pubspec.yaml
> > > dependency_overrides:
> > > intl: ^0.17.0-nullsafety.2
> > 
> > 
> > No, It doesn't work. You will get
> > Because depends on flutter_form_builder ^4.2.0 which depends on intl ^0.16.1, intl ^0.16.1 is required.
> > So, because depends on intl ^0.17.0-nullsafety.2, version solving failed.
> 
> I had the same error you posted and with that change it worked for me. What error does it show you now?

Same issue  
Does not worked for me  
With no ``intl`` deps:  
```
Because flutter_form_builder >=4.0.0-alpha.3 depends on flutter_localizations any from sdk which depends on intl 0.17.0-nullsafety.2, flutter_form_builder >=4.0.0-alpha.3 requires intl 0.17.0-nullsafety.2.
So, because project_name depends on flutter_form_builder ^4.2.0 which depends on intl ^0.16.1, version solving failed.
```

And with ``intl: ^0.17.0-nullsafety.2`` deps:  
```
Because project_name on flutter_form_builder ^4.2.0 which depends on intl ^0.16.1, intl ^0.16.1 is required.
So, because project_name depends on intl ^0.17.0-nullsafety.2, version solving failed.
pub get failed (1; So, because project_name depends on intl ^0.17.0-nullsafety.2, version solving failed.)
```
```
$ flutter --version
Flutter 1.25.0-8.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5d36f2e7f5 (3 недели назад) • 2021-01-14 15:57:49 -0800
Engine • revision 7a8f8ca02c
Tools • Dart 2.12.0 (build 2.12.0-133.7.beta)
```

**Comment by mattf80** [comment]
@dsvignesh 's solution worked for me, so closing issue.

**Comment by wildtv** [comment]
Because flutter_form_builder >=4.0.0-alpha.3 depends on flutter_localizations any from sdk which depends on intl 0.17.0-nullsafety.2, flutter_form_builder >=4.0.0-alpha.3 requires intl 0.17.0-nullsafety.2.
So, because clubcard depends on flutter_form_builder ^4.2.0 which depends on intl ^0.16.1, version solving failed.

**Comment by gluons** [comment]
Similar problem. Unable to install this on stable channel.

```
Because flutter_form_builder >=4.0.0-alpha.3 depends on flutter_localizations any from sdk which depends on intl 0.17.0, flutter_form_builder >=4.0.0-alpha.3 requires intl 0.17.0.

So, because <app name> depends on both flutter_form_builder ^4.2.0 and intl ^0.16.1, version solving failed.
pub get failed (1; So, because <app name> depends on both flutter_form_builder ^4.2.0 and intl ^0.16.1, version solving failed.)
```

**Comment by holy-dev** [comment]
> Because flutter_form_builder >=4.0.0-alpha.3 depends on flutter_localizations any from sdk which depends on intl 0.17.0-nullsafety.2, flutter_form_builder >=4.0.0-alpha.3 requires intl 0.17.0-nullsafety.2.
> So, because clubcard depends on flutter_form_builder ^4.2.0 which depends on intl ^0.16.1, version solving failed.
> 
> -- Had a pending upgrade, upgraded flutter and now seems to work with the above lines.
> 
> Just reports:
> 
> ```
> Warning: You are using these overridden dependencies:
> ! intl 0.17.0
> ```

Use the solution ultil they push update. It's just a warning so chill.

**Comment by AhmedAlzahrani** [comment]
It has removed the error. However, when I try to run the in the simulator it did not run.

it runs the 'Gradle task' assembler but the app didn't show up in the simulator

**Comment by AhmedAlzahrani** [comment]
it show this error:

Because flutter_form_builder >=4.0.0-alpha.3 depends on flutter_localizations any from sdk which depends on intl 0.17.0, flutter_form_builder >=4.0.0-alpha.3 requires intl 0.17.0.

**Comment by iNVISIBLExtanx** [comment]
I added 

```
dependency_overrides:
  intl: ^0.17.0-nullsafety.2
```
but still it displays the problem, 

```
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/gradient_app_bar-0.1.3/lib/gradient_app_bar.dart:407:57: Error: No named parameter with the name 'nullOk'.
    final ScaffoldState scaffold = Scaffold.of(context, nullOk: true);
                                                        ^^^^^^
../../snap/flutter/common/flutter/packages/flutter/lib/src/material/scaffold.dart:1944:24: Context: Found this candidate, but the arguments don't match.
  static ScaffoldState of(BuildContext context) {
                       ^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/gradient_app_bar-0.1.3/lib/gradient_app_bar.dart:636:20: Error: The method 'ancestorRenderObjectOfType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../snap/flutter/common/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ancestorRenderObjectOfType'.
    return context.ancestorRenderObjectOfType(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script '/home/invisible/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/invisible/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
Exception: Gradle task assembleDebug failed with exit code 1

```
can someone explain the issue?

**Comment by NightCrawler33** [comment]
Try upgrading your flutter SDK. If you're still running into this issue, you should be able to upgrade the relevant packages themselves now, as they now include null-safety.
