### ISSUE TITLE
FormBuilderSwitch broken on Version 4.1.0+

### ISSUE THREAD

**Issue by mhabashy** [danvick/flutter_form_builder#681]
Hello All, Thanks for taking the time and reading my issue. 

Flutter Docker
-----------------
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)
    ! Device emulator-5554 is offline.

```
FormBuilderSwitch(
     title: Text('Name'),
     name: "Name",
),
```
Error log
When the exception was thrown, this was the stack: 
#2      new SwitchListTile (package:flutter/src/material/switch_list_tile.dart:279:15)
#3      new FormBuilderSwitch.<anonymous closure> (package:flutter_form_builder/src/fields/form_builder_switch.dart:130:22)
#4      FormFieldState.build (package:flutter/src/widgets/form.dart:528:26)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)

Can't add value on the FormBuilderSwitch widget.

**Comment by ShadyZekry** [comment]
`FormBuilderSwitch` has an attribute called `value` shouldn't be null at any time, so you should assign a value to it by giving a value to `initialValue` attribute in the widget constructor.

So I think your code should be like that.
```
FormBuilderSwitch(
     title: Text('Name'),
     name: "Name",
     initialValue: true,
),
```

**Comment by mhabashy** [comment]
Okay, thank you for actually tried that and field earlier. Thank you so much. works now.

**Comment by dessonchan** [comment]
@ShadyZekry I have the same issue, and this workaround will override the initialValue set on the FormBuilder.

> `FormBuilderSwitch` has an attribute called `value` shouldn't be null at any time, so you should assign a value to it by giving a value to `initialValue` attribute in the widget constructor.
> 
> So I think your code should be like that.
> 
> ```
> FormBuilderSwitch(
>      title: Text('Name'),
>      name: "Name",
>      initialValue: true,
> ),
> ```

**Comment by ShadyZekry** [comment]
@dessonchan  You have to set a value to `initialValue` attribute, it is not a workaround. 
I was just trying to explain why the error is related to that value.
