### ISSUE TITLE
get value from List<dynamic>FormBuilderTypeAhead

### ISSUE THREAD

**Issue by YouSour** [danvick/flutter_form_builder#684]
hi , i got some problem , i have List\<dynamic> from backend service that return on FormBuilderTypeAhead (ex : data = [{label:"camera",value:001 , label:"iphone",value:002}] , i want to get label show for user and value insert to database , how can i do that ?

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by YouSour** [comment]
@deandreamatias yes , solved.
