### ISSUE TITLE
FormBuilderValidator.compose not working with null safe

### ISSUE THREAD

**Issue by prakash-indorkar** [danvick/flutter_form_builder#688]
Hi, The normal validator function is not working with the null safe version of flutter. 

Currently using FlutterFormBuilder with (// ignore: import_of_legacy_library_into_null_safe) 
But the validation function producing an error.

```
validator: FormBuilderValidators.compose([
              (val) {
                     if (formKey?.currentState?.fields['category']?.value == 'ED' && (val == null || val.isEmpty)) {
                            return 'Please enter some text!'; }
                      return null;
                      },
 ]),
```

"Error message": "The element type 'String? Function(String)' can't be assigned to the list type 'String Function(String)'."

for DateTime field

"Error message": "The element type 'String? Function(DateTime)' can't be assigned to the list type 'String Function(DateTime)'.",

**Comment by WilliamCunhaCardoso** [comment]
Is it still occurring?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
