### ISSUE TITLE
Alignment issue

### ISSUE THREAD

**Issue by jeffoowz** [danvick/flutter_form_builder#692]
After several times of redoing the code, I am still not able to align the form as what I expected. Both the imagepicker and the radio button should be in the center. But the text `Basic Information` is in the centre. Can anyone give me a hand here? Thank you very much!!!

![image](https://user-images.githubusercontent.com/30382960/105321273-355e6200-5c02-11eb-85bf-141dddd48c0f.png)

The code I wrote is as follow

```
      body: FormBuilder(
        key: _formKey,
        child: Padding(
          padding: const EdgeInsets.all(8.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.center,
              children: <Widget>[
                Text(
                  'Basic Information',
                  style: TextStyle(color: Colors.black, fontSize: 20),
                ),
                FormBuilderImagePicker(
                  name: 'profile_pic',
                  maxImages: 1,
                ),
                SizedBox(height: 20,),
                FormBuilderRadioGroup(
                  name: 'gender',
                  initialValue: 'Male',
                  validator: FormBuilderValidators.compose(
                      [FormBuilderValidators.required(context)]),
                  options: ['Male', 'Female']
                      .map((gender) => FormBuilderFieldOption(
                            value: gender,
                            child: Text('$gender'),
                          ))
                      .toList(growable: false),
                ),

                SizedBox(height: 20,),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: <Widget>[
                    RaisedButton(
                      child: Text("Continue"),
                      onPressed: () {
                        _formKey.currentState.save();
                        if (_formKey.currentState.validate()) {
                          print(_formKey.currentState.value);
                          Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) => JoinedPlan()));
                        } else {
                          print("validation failed");
                        }
                      },
                    ),

                    RaisedButton(
                      child: Text("Reset"),
                      onPressed: () {
                        _formKey.currentState.reset();

                      },
                    ),
                  ],
                ),
              ],
            ),
          ),
      ),
```

**Comment by andrewzakhartchouk** [comment]
Wouldn't `crossAxisAlignment: CrossAxisAlignment.center` in the column widget be the cause of the centring?
You can set the property to `CrossAxisAlignment.start`

**Comment by jeffoowz** [comment]
Thanks for the reply. After changing `center `to `start`. The layout remains unchanged. I guess it is the issue of Form Builder since the traditional `flutter/material.dart` does not have this issue.

**Comment by ShadyZekry** [comment]
For the radio buttons, you can use `wrapAlignment` to set the place for the buttons, and it should be like that
```
wrapAlignment: WrapAlignment.center,
```
<br>
For the  image picker, it is designed to be a row of multiple chosen images,  so the widget should take the entire screen size.
You can see that from dart dev tools.

![photo_2021-01-22_16-46-11](https://user-images.githubusercontent.com/42680354/105505274-6f4a6980-5cd1-11eb-9bca-20ddd905e83a.jpg)

So using `crossAxisAlignment: CrossAxisAlignment.center` wont work, because the widget is not just the camera box.
I hope in the future the *image picker package* could solve that problem

**Comment by jeffoowz** [comment]
Ok, I will try to use another tool for the image instead!

Thank you very much for your help!!
