### ISSUE TITLE
implement stepper with flutter form builder 

### ISSUE THREAD

**Issue by YouSour** [danvick/flutter_form_builder#699]
hi , anyone here using stepper with flutter form builder , i would like to see an example code how to implement it and with validation , thank in advance 😄 

![Flutter-Stepper-Widget-Example4](https://user-images.githubusercontent.com/9318106/106435178-1df66300-64a5-11eb-961a-393057684ed6.jpg)

**Comment by andrewzakhartchouk** [comment]
Perhaps this repository by [AseemWangoo](https://github.com/AseemWangoo) can help you? 
[StepperWithForm.dart](https://github.com/AseemWangoo/flutter_programs/blob/master/StepperWithForm.dart)

If you just replace the basic Flutter form stuff with FlutterFormBuilder, it should work the same way.
Don't forget to declare a form key.

**Comment by YouSour** [comment]
thank you so much @andrewzakhartchouk

**Comment by devwebapps** [comment]
Can we reopen this issue.
I have the same problem. I want to use Stepper with FormBuilder and for example the validation of FormBuilder isnt working if i click on the "Next" Stepper Button.

I would also like to know whether it is correct that I have to create a separate formKey variable per step, i.e. per FormBuilder?

Will the form data that I have entered per step be saved automatically?

Actually, an example of how to use the FormBuilder with the stepper would be really helpful.
