### ISSUE TITLE
Dynamic FormBuilderTextField delete method always unsubscribe last added

### ISSUE THREAD

**Issue by acorn371** [danvick/flutter_form_builder#706]
Hi,
I have a simple form with 5 rows made by a FormBuilderTextField with a "remove" button each, as in the code below.
When I push the "remove" button on the first row, the Field object is correctly removed from field list, FormBuilderState.unregisterField unregisters always the last added TextField and assert(_fields.containsKey(name)) fails with the following error lines:

`======== Exception caught by widgets library =====================================================
The following assertion was thrown while finalizing the widget tree:
'package:flutter_form_builder/src/form_builder.dart': Failed assertion: line 135 pos 12: '_fields.containsKey(name)': is not true.

When the exception was thrown, this was the stack: 
#2      FormBuilderState.unregisterField (package:flutter_form_builder/src/form_builder.dart:135:12)
#3      FormBuilderFieldState.dispose (package:flutter_form_builder/src/form_builder_field.dart:134:24)
#4      _FormBuilderTextFieldState.dispose (package:flutter_form_builder/src/fields/form_builder_text_field.dart:475:11)
#5      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4854:12)
#6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1998:13)
...
====================================================================================================`

I'm using **flutter 1.22.6 stable channel** and **flutter_form_builder 4.2.0**. 

```
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';

void main() => runApp(MyFormExample());

class MyFormExample extends StatefulWidget {
  @override
  _MyFormExampleState createState() => _MyFormExampleState();
}

class Field {
  final String name;
  String value;
  Field(this.name, [this.value]);
}

class _MyFormExampleState extends State<MyFormExample> {
  final GlobalKey<FormBuilderState> _formKey = GlobalKey<FormBuilderState>();
  List<Field> fields = List.generate(5, (index) => Field(index.toString()));
  List<TextEditingController> controllers;

  @override
  void initState() {
    super.initState();
    controllers = List.generate(5, (index) {
      TextEditingController controller = TextEditingController();
      controller.text="";
      return controller;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('MyForm Example'),
        ),
        body: FormBuilder(
          key: _formKey,
          child: ListView.builder(
            itemCount: fields.length,
              itemBuilder: (BuildContext context, int position) {
                return Row(
                  children: [
                    Expanded(
                      child: FormBuilderTextField(
                        name: fields[position].name,
                        controller: controllers[position],
                        // focusNode: _focusNodes[position],
                        decoration: InputDecoration(labelText: "Field ${fields[position].name}"),
                      ),
                    ),
                    MaterialButton(
                      child: Icon(Icons.remove_circle_outline),
                      onPressed: () => setState( () => fields.removeAt(position)),
                    )
                  ],
                );
              }
          ),
        ),
      ),
    );
  }
}
```

**Comment by lyuscott** [comment]
encountered  the same problem, can anybody help?

**Comment by bannarisoftwares** [comment]
Any updates?

**Comment by rexyness** [comment]
Add a key to the FormBuilderTextField as follows
`FormBuilderTextField(
                                key: UniqueKey(),
// rest of the attributes
)`

as well as a key for Scaffold

`
final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();
Scaffold(
          key: _scaffoldKey,)
`

so in total you should have 3 different keys declared , one for Scaffold , one for the FormBuilder and UniqueKey() for FormBuilderTextField

**Comment by acorn371** [comment]
> Add a key to the FormBuilderTextField as follows `FormBuilderTextField( key: UniqueKey(), // rest of the attributes )`
> 
> as well as a key for Scaffold
> 
> `final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();` `Scaffold( key: _scaffoldKey,)`
> 
> so in total you should have 3 different keys declared , one for Scaffold , one for the FormBuilder and UniqueKey() for FormBuilderTextField

Great, this seems to works fine!
There is only an annoying warning saying:

_I/flutter ( 4034): Warning! Replacing duplicate Field for 1 -- this is OK to ignore as long as the field was intentionally replaced_

Thanks!

**Comment by acorn371** [comment]
`FormBuilderTextField( key: UniqueKey(), // rest of the attributes )` is, maybe, the right way to use FormBuilderTextField or just a workaround.
Anyway, it works
