### ISSUE TITLE
 Not compatible with latest release of intl: ^0.17.0

### ISSUE THREAD

**Issue by m-j-g** [danvick/flutter_form_builder#721]

**Comment by RaymondAtivie** [comment]
This is important . Can't run my app on web cause of this on Flutter 2

**Comment by alexmarkley** [comment]
Due to this issue, `flutter pub get` depsolving fails using latest flutter stable (2.0.0).

```
$ flutter pub get
Because no versions of flutter_form_builder match >4.2.0 <5.0.0 and flutter_form_builder 4.2.0 depends on flutter_localizations any from sdk, flutter_form_builder ^4.2.0 requires flutter_localizations any from sdk.
And because every version of flutter_localizations from sdk depends on intl 0.17.0, flutter_form_builder ^4.2.0 requires intl 0.17.0.
So, because myProject depends on both intl ^0.16.1 and flutter_form_builder ^4.2.0, version solving failed.
Running "flutter pub get" in myProject...
pub get failed (1; So, because myProject depends on both intl ^0.16.1 and flutter_form_builder ^4.2.0, version solving failed.)
$
```

Flutter doctor output:

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.0.0, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 2.0.0 at /Users/alex/Development/Flutter/flutter
    • Framework revision 60bd88df91 (3 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/alex/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/alex/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • macOS 11.1 20C69 darwin-x64

• No issues found!
```

**Comment by Dhi13man** [comment]
While the Flutter Team works to fix intl 0.16.x being used instead of 0.17.0 in Stable branch now, a temporary solution for you all to get this fixed right now is to add
```
    
dependency_overrides:
  intl: ^0.17.0
  
```

after dependencies and dev_dependencies section in pubspec.yaml. Also set flutter_form_builder to ^4.2.0 after doing this.

**Comment by ingmferrer** [comment]
Although overriding intl dependency works it won't solve other dependencies that flutter_form_builder relies on

date_range_picker seems to be outdated for flutter 2.0.

`Warning: You are using these overridden dependencies:                   
! intl 0.17.0                                                           
Running "flutter pub get" in matchmaking_flutter...                833ms

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/date_range_picker-1.0.6/lib/date_range_picker.dart:1152:44: Error: Method not found: 'ButtonTheme.bar'.
    final Widget actions = new ButtonTheme.bar(                         
                                           ^^^                          
                                                                        
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/home/ingmferrer/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 991
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildRelease'.            
> Process 'command '/home/ingmferrer/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 23s                                                     
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      24.0s
Gradle task assembleRelease failed with exit code 1`

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.0, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.`

and looking for date_range_picker it seems it is unmaintained now, last update was march 2019, so I guess this is more complicated than overriding.

anyways, any help would be appreciated.

**Comment by ingmferrer** [comment]
I went ahead, cloned date_range_pciker and made a quick fix for flutter 2.0. If you face the same problem of my previous post this will solve:

override not only intl package but date_rage_picker

```
dependency_overrides:
  intl: ^0.17.0
  date_range_picker:
    git:
      url: https://github.com/ingmferrer/date_range_picker.git
```

I tested the widget and it works.

P.D: do `flutter clean` before `flutter pub get` and `flutter pub upgrade`

**Comment by eliandrosn** [comment]
I did everything you instructed and works fine! @ingmferrer thank you so much.

But I got an issue when I add firebase dependence:

> Because no versions of firebase match >9.0.0 <10.0.0 and firebase 9.0.0 depends on http ^0.13.0, firebase ^9.0.0 requires http ^0.13.0.
> Because vin_decoder >=0.1.3 <0.2.0-nullsafety depends on http ^0.12.2 and vin_decoder >=0.1.2 <0.1.3 depends on http ^0.12.1, vin_decoder >=0.1.2 <0.2.0-nullsafety requires http ^0.12.1.
> Thus, firebase ^9.0.0 is incompatible with vin_decoder >=0.1.2 <0.2.0-nullsafety.
> And because flutter_form_builder >=4.0.0-alpha.3 depends on validators ^2.0.1 which depends on vin_decoder ^0.1.2, firebase ^9.0.0 is incompatible with flutter_form_builder >=4.0.0-alpha.3.

**Comment by ingmferrer** [comment]
> I did everything you instructed and works fine! @ingmferrer thank you so much.
> 
> But I got an issue when I add firebase dependence:
> 
> > Because no versions of firebase match >9.0.0 <10.0.0 and firebase 9.0.0 depends on http ^0.13.0, firebase ^9.0.0 requires http ^0.13.0.
> > Because vin_decoder >=0.1.3 <0.2.0-nullsafety depends on http ^0.12.2 and vin_decoder >=0.1.2 <0.1.3 depends on http ^0.12.1, vin_decoder >=0.1.2 <0.2.0-nullsafety requires http ^0.12.1.
> > Thus, firebase ^9.0.0 is incompatible with vin_decoder >=0.1.2 <0.2.0-nullsafety.
> > And because flutter_form_builder >=4.0.0-alpha.3 depends on validators ^2.0.1 which depends on vin_decoder ^0.1.2, firebase ^9.0.0 is incompatible with flutter_form_builder >=4.0.0-alpha.3.

I'm guessing it's because the environment sdk constraint in your pubspect.yaml, try to set it like this and test again:
```
environment:
  sdk: ">=2.10.0 <3.0.0"
```

**Comment by eliandrosn** [comment]
Works fine now, thank you again!

But it will be even more interesting if add null safety or some upgrades to this useful package.

**Comment by AlBlanc** [comment]
https://github.com/danvick/flutter_form_builder/issues/729#issuecomment-791328663

**Comment by alexmarkley** [comment]
I just donated to the developer @danvick with a request to prioritize Flutter 2.0.0 support. I would encourage anyone depending on this package to do the same! https://www.buymeacoffee.com/wb5M9y2Sz/c/1126129

**Comment by bawa-ra** [comment]
I don't know what kind of fix is this may be bad , but it worked for me

change sdk environment  
```
environment:
  sdk: ">=2.10.0 <3.0.0"        // 2.6.0 ( was previous ) -> 2.10.0

```

```
dependencies
  flutter_form_builder: any

```

```
dependency_overrides:
  intl: ^0.17.0
```

**Comment by deandreamatias** [comment]
Actual version has compatibility with intl 0.17.0
![Screenshot 2022-06-10 at 09 46 46](https://user-images.githubusercontent.com/21011641/173016901-110e4503-f9bb-4c24-bc92-a17d87167c32.png)
