### ISSUE TITLE
very low performance on physical devices...

### ISSUE THREAD

**Issue by nirbar89** [danvick/flutter_form_builder#733]
hello, 

i'm trying to implement signature field and slider fields,

both are very not responsive to user drag
the slider and the signature as a delay 

i did search in all issues but i didn't find any information related to this.
its happing on android and ios...

**Comment by nirbar89** [comment]
Hello @danvick!
first thanks for your comment i know that this days is very busy for you since Flutter 2 is here.

i will try to do my best on improving signature and if ill improve we consider PR also ill will help you with Hebrew support.

i have a general question.

in my product i'm trying to implement this package but since my form should be created on run time due unknown number of fields and types (data from backend) some time it can be a Form with 100+ fields and different types.
 i'm using ListView.builder. BUT i cant use GlobalKey its pumping my RAM, i want to use Bloc to save fields data and manage the Form state.
there is any chance i can use this package in my project to fit my needs?

**Comment by deandreamatias** [comment]
This apply to external repository
