### ISSUE TITLE
flutter_form_builder >=3.7.3 <5.0.0-alpha.1 depends on intl ^0.16.1 

### ISSUE THREAD

**Issue by faisalmushtaq007** [danvick/flutter_form_builder#735]
Help needed here!!!

**Comment by nstrelow** [comment]
```
dependency_overrides:
  intl: 0.17.0
```

**Comment by faisalmushtaq007** [comment]
@nstrelow I tried to migrate my project to null safety, but as i try to upgrade package dependencies, error like these occur

**Comment by danvick** [comment]
Kindly note that the package depends on `intl_translation: ^0.17.10+1` which depends on `intl ^0.16.1` that's why we have  to use `intl ^0.16.1`. 

It's also not possible to override dependencies in a package so - at least for now (until `intl_translation` is updated) - you'll have to override intl in your app.

**Comment by faisalmushtaq007** [comment]
@danvick Could you upgrade to new packages, and also daterange_picker needs to be replaced

**Comment by pumuckelo** [comment]
yes, that would be very helpful

**Comment by nstrelow** [comment]
daterange_picker got an update today. So we might be good for a while now :D

**Comment by faisalmushtaq007** [comment]
@danvick  you need to use different daterange_picker from git, as the repo you are using isnt being looked by the owner. so for the betterment of everybody change it. We are getting issues because of this.

**Comment by nstrelow** [comment]
@faisalmushtaq007 DateRangePicker was updated and is compiling for me.

What's the problem?

**Comment by deandreamatias** [comment]
This bug exists and is tracked here #721 . There have a discussion about this
