### ISSUE TITLE
Pub points are very low

### ISSUE THREAD

**Issue by RishabJaiswal** [danvick/flutter_form_builder#736]
It is a really good package, yet the pub points are really low. Can something be done to boost those pub points, so developers have more confidence in using this package, apart from referring to the code coverage.
[](https://pub.dev/packages/flutter_form_builder/score)

![image](https://user-images.githubusercontent.com/10057450/110915698-fadd8f80-833d-11eb-83cb-ebb9906ef9b0.png)

**Comment by YuenEsc** [comment]
I was thinking maybe help with the documentation of the package, some documentation will seem redundant or exactly the same as the ones available on flutter but that could help to raise the points of the library.

**Comment by deandreamatias** [comment]
Solved!
![Screenshot 2022-06-10 at 10 17 31](https://user-images.githubusercontent.com/21011641/173022563-5409903e-f7a4-48b7-a505-384874dcb9f6.png)
