### ISSUE TITLE
flutter_form_builder >=4.0.0-alpha.3 requires http ^0.12.1.

### ISSUE THREAD

**Issue by eliabieri** [danvick/flutter_form_builder#742]
I'm using the latest beta version of Flutter (2.0.2).
I added flutter_form_builder: ^5.0.0-alpha.1 to my pubfile but it seems incompatible with the latest version of http.
Any ideas how I could circumvent this?

```
Because flutter_form_builder >=4.0.0-alpha.3 depends on validators ^2.0.1 which depends on vin_decoder ^0.1.2, flutter_form_builder >=4.0.0-alpha.3 requires vin_decoder ^0.1.2.

Because vin_decoder >=0.1.3 <0.2.0-nullsafety depends on http ^0.12.2 and vin_decoder >=0.1.2 <0.1.3 depends on http ^0.12.1, vin_decoder >=0.1.2 <0.2.0-nullsafety requires http ^0.12.1.

Thus, flutter_form_builder >=4.0.0-alpha.3 requires http ^0.12.1.
```

**Comment by danvick** [comment]
Since the package doesn't directly depend on HTTP. Please feel free to use dependency overrides to solve this problem while we work on this issue.

**Comment by deandreamatias** [comment]
Solved with dependencies updates
