### ISSUE TITLE
flutter_form_builder 5.0.0-alpha.1 depends on flutter_typeahead ^2.0.0

### ISSUE THREAD

**Issue by pumuckelo** [danvick/flutter_form_builder#743]
Hello

I hope it's not too annoying getting all the dependency update requests:

Please update package to use **flutter_typeahead 3.0.0-nullsafety.0**

It currently uses **flutter_typeahead ^2.0.0**

Thank you!

**Comment by deandreamatias** [comment]
Solved with new versions https://pub.dev/packages/form_builder_extra_fields/score
