### ISSUE TITLE
Could anyone please help me with this issue 

### ISSUE THREAD

**Issue by joeyyy688** [danvick/flutter_form_builder#748]
Running "flutter pub get" in my_project...                           
Because no versions of flutter_form_builder match >4.2.0 <5.0.0 and flutter_form_builder 4.2.0 depends on flutter_localizations any from sdk, flutter_form_builder ^4.2.0 requires flutter_localizations any from sdk.

And because every version of flutter_localizations from sdk depends on intl 0.17.0, flutter_form_builder ^4.2.0 requires intl 0.17.0.

So, because my_project depends on both intl ^0.16.1 and flutter_form_builder ^4.2.0, version solving failed.
pub get failed (1; So, because my_project depends on both intl ^0.16.1 and flutter_form_builder ^4.2.0, version solving failed.)
exit code 1

So, I just upgraded my flutter sdk to 2.0.3 and this issue came

**Comment by anthonycuervo23** [comment]
this will fix it:

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

**Comment by joeyyy688** [comment]
yeah Thanks It worked
