### ISSUE TITLE
TextField readonly does not work when referencing a variable defined by a checkbox

### ISSUE THREAD

**Issue by Tibasa** [danvick/flutter_form_builder#75]
TextField readonly does not work when referencing a variable defined by a checkbox.
Example:

Expanded(
&nbsp;&nbsp;child: FormBuilderTextField(
&nbsp;&nbsp;&nbsp;&nbsp;attribute: 'textField',
&nbsp;&nbsp;&nbsp;&nbsp;controller: textFieldController,
&nbsp;&nbsp;&nbsp;&nbsp;readonly: _disableTextField,  // This does not work
&nbsp;&nbsp;&nbsp;&nbsp;decoration: InputDecoration(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;labelText: _disableTextField ? 'Disabled' : 'Enabled', // This works
&nbsp;&nbsp;&nbsp;&nbsp;),
&nbsp;&nbsp;)
),
Expanded(
&nbsp;&nbsp;child: FormBuilderCheckbox(
&nbsp;&nbsp;&nbsp;&nbsp;attribute: 'checkBox',
&nbsp;&nbsp;&nbsp;&nbsp;initialValue: false,
&nbsp;&nbsp;&nbsp;&nbsp;onChanged: (val) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;setState(() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (val) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;textFieldController.clear();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_disableTextField= true;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;} else {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_disableTextField= false;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;});
&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;)
)

In the example above, label switching works, but deactivation of the field does not work

Need help. Thanks in advance

**Comment by dhaalves** [comment]
Same applies for FormBuilderRadio

**Comment by dhaalves** [comment]
I being trying to debug the problem, and moving the line:
`    _readonly = (_formState?.readonly == true) ? true : widget.readonly;`
from method initState() to the first line of build fix the issue

**Comment by danvick** [comment]
Hi @Tibasa.
Try out version `3.2.3` of the plugin which works as expected thanks to the good work by @dhaalves

**Comment by Tibasa** [comment]
Thanks very much!!!
