### ISSUE TITLE
 Unhandled Exception: Unsupported operation: Cannot modify unmodifiable map

### ISSUE THREAD

**Issue by Shiba-Kar** [danvick/flutter_form_builder#754]
`` 
Map<String, dynamic> values;
``
``
values = _formKey.currentState.value; 
``

getting this error !!

**Comment by romater0** [comment]
Got the same error too 
I/flutter (14615): #0      _UnmodifiableMapMixin.[]= (dart:collection/maps.dart:269:5)
[log] Unsupported operation: Cannot modify unmodifiable map

**Comment by santoshnaagula** [comment]
me too same error, please help.

**Comment by dannycortesv** [comment]
Same error here....

**Comment by YouSour** [comment]
got the same error , anyone got a solution ?

**Comment by santoshnaagula** [comment]
> just got an answer from here : https://stackoverflow.com/questions/58855894/flutter-setting-property-in-map-causes-unsupportederror-unsupported-operation
> 
> **Solution :**
> 
> ```
> final newUser = {
>   ..._user,
>   'imageOne': downloadLink
> };
> ```
> 
> or
> 
> ```
> final newUser = Map.of(_user);
> newUser['imageOne'] = downloadLink;
> ```

Thank you so much...

**Comment by YouSour** [comment]
@santoshnaagula never mind , happy coding 😄

**Comment by deandreamatias** [comment]
Solved
