### ISSUE TITLE
FormBuilderDateTimePicker on 6.0.0-nullsafety.1

### ISSUE THREAD

**Issue by milazmidza** [danvick/flutter_form_builder#755]
The method 'FormBuilderDateTimePicker' isn't defined for the type 'AddBatches'.  Try correcting the name to the name of an existing method, or defining a method named 'FormBuilderDateTimePicker'.

Trying to use datetime picker but it's saying The error above off which FormBuilderDateRangePicker is working very well

**Comment by ozz-rjq** [comment]
having the same issue

**Comment by nicks258** [comment]
Same issue..

**Comment by janataanfor** [comment]
the team make comment on the date and time picker class, the question when they upgrade the code since its dependencies are already upgraded to null safety

**Comment by jaxnz** [comment]
Fixed with latest release ef2892d9d70423677484d64579f195b2ccbdb28c

**Comment by deandreamatias** [comment]
Solved
