### ISSUE TITLE
Form builder dependancy conflict

### ISSUE THREAD

**Issue by LLTIGER** [danvick/flutter_form_builder#756]
Because flutter_form_builder >=4.0.0-alpha.3 <6.0.0-nullsafety.0 depends on validators ^2.0.1 which depends on vin_decoder ^0.1.2, flutter_form_builder >=4.0.0-alpha.3 <6.0.0-nullsafety.0 requires vin_decoder ^0.1.2.

Because vin_decoder >=0.1.3 <0.2.0-nullsafety depends on http ^0.12.2 and vin_decoder >=0.1.2 <0.1.3 depends on http ^0.12.1, vin_decoder >=0.1.2 <0.2.0-nullsafety requires http ^0.12.1.

**Comment by deandreamatias** [comment]
Solved with new versions
