### ISSUE TITLE
FormValidators extension to validate length on arrays

### ISSUE THREAD

**Issue by YuenEsc** [danvick/flutter_form_builder#757]
Hi Danvick, I open this issue because there is validators for String length but there arent validators that check the length on the array of options. This could be very helpful on the multiselectors fields on this package. I could add this functionality myselft because the implementation is very straightforward. Anyway this issue is more related with
Do you think they could be added to the package?
Which name do you think will be better given the existing validators on the package?

**Comment by deandreamatias** [comment]
This still an issue?
