### ISSUE TITLE
FormBuilderTextField does not respect the constructor parameter "enabled"

### ISSUE THREAD

**Issue by jrnelson333** [danvick/flutter_form_builder#76]
FormBuilderTextField has a constructor parameter `enabled`, but it is not used. `readonly` is used instead. This can be seen [here](https://github.com/danvick/flutter_form_builder/blob/master/lib/src/fields/form_builder_text_field.dart#L126). This is inconsistent with the Flutter API for [TextField](https://api.flutter.dev/flutter/material/TextField-class.html).

Solution: Support `enabled` to be consistent with the Flutter API for TextField. Deprecate `readonly` but continue to support it for backwards compatibility.

**Comment by danvick** [comment]
This is a great idea! It will definitely be considered going forward.

Your positive contribution is greatly appreciated.

**Comment by danvick** [comment]
Hi @jrnelson333,
I was working on changing the `readonly` property to `enabled` but it seems Flutter have in the latest versions [included `readOnly` property](https://api.flutter.dev/flutter/material/TextField/readOnly.html) in the API for `TextField`.

What we may need to do therefore is to change `readonly` to `readOnly`.

I'm therefore going ahead to close this issue.
