### ISSUE TITLE
FormBuilderTypeAhead is permanently removed from version 6.0.0?

### ISSUE THREAD

**Issue by rgb1380** [danvick/flutter_form_builder#762]
Is FormBuilderTypeAhead permanently removed? I have quite a few of these in my code and staying with version 5.0.0 is no longer an option due to package conflicts. A bit stuck right now.

**Comment by sumitbhanushali** [comment]
@rgb1380 you can use https://api.flutter.dev/flutter/material/Autocomplete-class.html which was introduced in flutter 2, I guess this is the reason FormBuilderTypeAhead was removed.
would appreciate FormField version of this though

**Comment by rgb1380** [comment]
> would appreciate FormField version of this though
exactly, they are not the same thing without the additional validation that used to be provided through FormBuilderTypeAhead.

**Comment by deandreamatias** [comment]
[FormBuilderTypeAhead](https://github.com/danvick/flutter_form_builder/blob/master/packages/form_builder_extra_fields/lib/src/fields/form_builder_typeahead.dart) exists in another package but same repository
