### ISSUE TITLE
why FormBuilderDateTimePicker has been commented out on null_safety branch?

### ISSUE THREAD

**Issue by prakash-indorkar** [danvick/flutter_form_builder#764]
https://github.com/danvick/flutter_form_builder/blob/null_safety/lib/src/fields/form_builder_date_time_picker.dart

**Comment by prakash-indorkar** [comment]
Guys any has an alternate repo url to use date_time_picker?

**Comment by ivan0930** [comment]
https://github.com/danvick/flutter_form_builder/commit/a46f9956a94556da01144297629c6625908b00f1#diff-9e79d5effe9e88e322e3f029da9c843cbefedd2a0095b4c4776b4f4c975f7d8b
They are working on the null safe version.
I uncomment those code and import the FormBuilderDateTimePicker widget to my project, it's working. 
I do not suggest you to use this approach but at least you can use the widget temporary.

**Comment by deandreamatias** [comment]
This widget exist in master
https://github.com/danvick/flutter_form_builder/blob/master/packages/flutter_form_builder/lib/src/fields/form_builder_date_time_picker.dart
