### ISSUE TITLE
Signature Pad Null Safety

### ISSUE THREAD

**Issue by Malikazz** [danvick/flutter_form_builder#768]
Hello hope your doing well I noticed that in the current null safe build of the library that `Signature Pad` is out. I understand by looking at issues that this was due to dependencies not being null safe. I took at look at the dependencies and they are marked null safe at this point. I was wondering if we have any idea when signatures will be coming to null safe version of form builder. 

If no one is currently working on it maybe I can scope the problem and put some time into it. Let me know.

**Comment by marko-mlinarevic** [comment]
Were you able to look at signature safety?

**Comment by deandreamatias** [comment]
[Signature](https://pub.dev/packages/signature) now is null safety
