### ISSUE TITLE
Is there a way to show/hide a form field according to value of another field?

### ISSUE THREAD

**Issue by wyxcoder** [danvick/flutter_form_builder#769]
thanks

**Comment by yathu** [comment]
you can do this using check _formkey current state and _formkey should not be as final.

  `var  _formKey = GlobalKey<FormBuilderState>();`

`bool canShow = _formKey.currentState.fields['gender'].value.toString() == 'male';` 

if this boolean true you can show your component.

**Comment by deandreamatias** [comment]
This comments help to solve problem @wyxcoder ? If yes, can close this issue

**Comment by deandreamatias** [comment]
Due to lack of response, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
