### ISSUE TITLE
FormBuilderSearchableDropdown error when inputing text

### ISSUE THREAD

**Issue by iulian0512** [danvick/flutter_form_builder#777]
![form_builder_crash](https://user-images.githubusercontent.com/16035099/115433107-d5cb1f00-a20f-11eb-8b21-115d1fd7cbe7.gif)

No changes were made to the example code pulled from the master branch.
I am running on flutter 2.0.3 
LOG:

I/flutter ( 9745): Italy

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Builder(dirty, dependencies: [MediaQuery]):
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

The relevant error-causing widget was
MaterialApp
lib\main.dart:13
When the exception was thrown, this was the stack
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure>
package:flutter/…/widgets/framework.dart:3864
#1      Element._debugCheckStateIsActiveForAncestorLookup
package:flutter/…/widgets/framework.dart:3878
#2      Element.visitAncestorElements
package:flutter/…/widgets/framework.dart:3964
#3      InheritedTheme.capture
package:flutter/…/widgets/inherited_theme.dart:158
#4      InheritedTheme.captureAll
package:flutter/…/widgets/inherited_theme.dart:126
...
═══════════════════════════════════════════════════════════════════════════════

**Comment by iulian0512** [comment]
i pulled the new version and turns out i had an old version.

**Comment by nicks258** [comment]
Still facing the same issue. Any fix?
