### ISSUE TITLE
FormBuilderSearchableDropdown not define 

### ISSUE THREAD

**Issue by angwandi** [danvick/flutter_form_builder#778]
FormBuilderSearchableDropdown is not part of the library version 6.0.0.

**Comment by kilroy05** [comment]
Yes, the one field I really need :D

**Comment by vivian-ng** [comment]
I really hope a version of this gets implemented in version 6.0.x because I cannot compile a snap right now due to the breaking change... sigh...

**Comment by deandreamatias** [comment]
This widget exists in [another package](https://pub.dev/packages/form_builder_extra_fields) in this same repository
