### ISSUE TITLE
FormBuilderRadio Not Working Properly

### ISSUE THREAD

**Issue by kidwiz** [danvick/flutter_form_builder#78]
List<FormBuilderFieldOption> options = List();

List<dynamic> answers = data["questions_answers"];
   
answers.forEach((a) {
      options.add(FormBuilderFieldOption(value: a["answer"].toString()));
});

------------------------------------------------------------
FormBuilderRadio(
            attribute: "question_" + data["question_id"].toString(),
            options: options,
),

Output 

![IMG-20190614-WA0014](https://user-images.githubusercontent.com/4988463/59506736-b5163d80-8eb1-11e9-85b8-a7081cd46ade.jpg)

Please assist why i get all selected

**Comment by danvick** [comment]
Hi,
It looks like your options are all similar.

**Comment by danvick** [comment]
We may have to add an assertion to ensure that the radio option values are not the same.

**Comment by kidwiz** [comment]
Thanks! for your support!! now i understand why was not working!!!
