### ISSUE TITLE
Cannot change FormBuilderRadioGroup value

### ISSUE THREAD

**Issue by oxyii** [danvick/flutter_form_builder#782]
error when tap on radio:

```bash
The following _TypeError was thrown while handling a gesture:
type '(String) => void' is not a subtype of type '(String?) => void'

When the exception was thrown, this was the stack: 
#0      _GroupedRadioState.item.<anonymous closure> (package:flutter_form_builder/src/widgets/grouped_radio.dart:257:22)
...
```

Looks like argument must be optional (`final ValueChanged<T?> onChanged;`) here:
https://github.com/danvick/flutter_form_builder/blob/860f79593bb61b11f1c08ba511cb5a3a831b818f/lib/src/widgets/grouped_radio.dart#L20

**Comment by edwin0401** [comment]
Same here, after upgraded to null safety.


════════ Exception caught by gesture ═══════════════════════════════════════════
Expected a value of type '(String?) => void', but got one of type '(String) => void'

**Comment by lchaglla** [comment]
Try with this:

`FormBuilderRadioGroup<String?>(
...
)`

**Comment by oxyii** [comment]
@lchaglla Thank you, it's works. But I will not close this issue. i'm sure this should be the default in null-safety env

**Comment by WilliamCunhaCardoso** [comment]
Could you please confirm if it still happens in the latest versions?

**Comment by deandreamatias** [comment]
This issues is fixed in this line
https://github.com/danvick/flutter_form_builder/blob/8b9c68e8d166779de34d8e1ad34302e49bdc89e8/packages/flutter_form_builder/lib/src/widgets/grouped_radio.dart#L21
