### ISSUE TITLE
form_builder_phone_field dependency issue

### ISSUE THREAD

**Issue by Hussein-Kamareddine** [danvick/flutter_form_builder#785]
**when trying to upgrade to flutter_form_builder6.0.0 i get the below error:**

Because form_builder_phone_field 0.2.0 depends on flutter_form_builder ^5.0.0-alpha.1 and no versions of form_builder_phone_field match >0.2.0 <0.3.0, form_builder_phone_field ^0.2.0 requires flutter_form_builder ^5.0.0-alpha.1.

So, because money_pos depends on both flutter_form_builder ^6.0.0 and form_builder_phone_field ^0.2.0, version solving failed.
pub get failed (1; So, because money_pos depends on both flutter_form_builder ^6.0.0 and form_builder_phone_field ^0.2.0, version solving failed.)
exit code 1

**Comment by Clid3** [comment]
same issue here

**Comment by Faaatman** [comment]
I created a pull request for[form_builder](https://github.com/danvick/form_builder_phone_field/pull/5) put the maintainer isn't replying to anything right now I don't know why.
So I used my pull request until the maintainer merges it.
Done it as follows:
```
form_builder_phone_field:
    git:
      url: https://github.com/Faaatman/form_builder_phone_field.git
      ref: 4f1a827
```

**Comment by rainerlonau** [comment]
> I created a pull request for [form_builder_phone_field](https://github.com/danvick/form_builder_phone_field/pull/5) but the maintainer isn't replying to anything right now I don't know why.
> So I used my pull request until the maintainer merges it.
> Done it as follows:
> 
> ```
> form_builder_phone_field:
>     git:
>       url: https://github.com/Faaatman/form_builder_phone_field.git
>       ref: 4f1a827
> ```
> 
> edit: typo

I get this error here: 
```
C:/_Dev/Flutter/.pub-cache/git/form_builder_phone_field-4f1a827daed80efd8ff762e436459e3c27c874e5/lib/src/form_builder_phone_field.dart:117:22: Error: The argument type 'void Function(String)?' can't be assigned to the parameter type 'void Function(String?)?' because 'String?' is nullable and 'String' isn't.
          onChanged: onChanged,
                     ^
```
                     
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.985], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (3 available)

• No issues found!

**Comment by Faaatman** [comment]
@rainerlonau  Oh yeah, that problem happened when he upgraded flutter_form_builder to 6.0.1. I used flutter_form_builder 6.0.0 for this to work.
Use the following in your pubspec for the phone field to work.
`
flutter_form_builder: 6.0.0
`

**Comment by rainerlonau** [comment]
@Faaatman wow, thanks for this fast reply! It works with your pubspec entry.

**Comment by YouSour** [comment]
can you guy run your project ios emulator when use this package ? i got an error on xcode like this , any one got this problem too ?
`
Could not find module 'PhoneNumberKit' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator
`

**Comment by YouSour** [comment]
i solved it by using Rosetta , lol
and in pubspec
```
 flutter_form_builder: 6.0.0
 form_builder_phone_field:
    git:
      url: https://github.com/Faaatman/form_builder_phone_field.git
      ref: 4f1a827
``` 
<img width="275" alt="BtLNu" src="https://user-images.githubusercontent.com/9318106/124353795-e1d15500-dc32-11eb-80d5-1f73ddaba555.png">

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by deandreamatias** [comment]
Due to lack, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
