### ISSUE TITLE
FormBuilderDropdown allowClear 

### ISSUE THREAD

**Issue by ATmare** [danvick/flutter_form_builder#787]
I would like to give users the opportunity to clear a DateTime field by clicking a cross icon inside the form field. Is this possible at the moment, because I can't find it? If not, this post can be considered as a feature request.
It would be great if you could add **allowClear** functionality, which is already implemented in FormBuilderDropdown to the **FormBuilderDateTimePicker** widget too. 

![grafik](https://user-images.githubusercontent.com/51372743/116436933-2e706c80-a84d-11eb-967a-c7b3b848a178.png)

**Comment by deandreamatias** [comment]
This is implemented [here](https://github.com/danvick/flutter_form_builder/blob/604a9d7674eb20d8bbe0902ca2ad257bf763422d/packages/flutter_form_builder/lib/src/fields/form_builder_dropdown.dart#L339) for FormBuilderDropdown and [here](https://github.com/danvick/flutter_form_builder/blob/604a9d7674eb20d8bbe0902ca2ad257bf763422d/packages/flutter_form_builder/lib/src/fields/form_builder_date_time_picker.dart#L221) for FormBuilderDateTimePicker.

If isn't enogh, please feel free to open another Feature request
