### ISSUE TITLE
Is there a way to make date picker be cupertino everywhere?

### ISSUE THREAD

**Issue by caseyryan** [danvick/flutter_form_builder#789]
Before null-safety FormBuilderDateTimePicker could be used as cupertino even on android. 
Now its look and feel is material which is very very ugly. I hate material date picker but I couldn't find a way to make it look like cupertino. I took a look at the source and found that PickerType has now been commented out. But why? 
Is there any replacement?

**Comment by danvick** [comment]
Hi @caseyryan,
With the coming of null-safety, most of the users of this package demanded that we support null-safety. However, most packages - including the one offering Cupertino date picker - were not null-safe and were not being updated fast enough.

As a trade-off, we decided to have the package decided to remove the fields that depended on external packages from the package and have only those derived from Flutter itself - such as TextField, Material Datepicker, Checkboxes etc - to achieve null-safety.

The plan is to have a separate package for these fields. This is what I'm working on right now - it's only that my schedule doesn't allow me to do that fast enough.

Thanks for your patience.

**Comment by danvick** [comment]
In the meantime, feel free to copy the code of said field from the old version. It should work - as there isn't much incompatibility in code.

**Comment by caseyryan** [comment]
What do you mean by saying that cupertino date picker is supported by external package? It's definitely supported by flutter itself and I have made my own form field with cupertino picker already. It's 100% null-safe. That's really sad that such a great package loses really needed functionality

**Comment by danvick** [comment]
What I mean is that we had initially used an external package to achieve the functionality.

**Comment by danvick** [comment]
If you've been able to build your own without using an external package kindly feel free to submit a PR for review.

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by caseyryan** [comment]
> This still an issue?

Not for me. I've made a custom one
