### ISSUE TITLE
get error text from form builder validation 

### ISSUE THREAD

**Issue by YouSour** [danvick/flutter_form_builder#791]
hi , i'm using form builder , everything is ok , but i don't know how can i get error text from form builder validation and show it somewhere else i want , i don't want to show it under the textfield , example i want to show it on **SnackBar** , or **Alert** , how can i do it ? thank in advance 😅 

example image : 

![1dQdc](https://user-images.githubusercontent.com/9318106/117093673-d7f2b900-ad8b-11eb-9a15-df816c2ccfe3.gif)

**Comment by YouSour** [comment]
solved

**Comment by mayank-meragi** [comment]
> solved
How did you solve this?

**Comment by mayank-meragi** [comment]
> solved

@YouSour  how did you solve this?
