### ISSUE TITLE
Disable error message showing

### ISSUE THREAD

**Issue by MattiaEffendi** [danvick/flutter_form_builder#792]
Hello!

I would like to completely remove the error message showing when a field is invalid. This is because i am using some custom logic and so when it is invalid i just want to color the container wrapping the textfield.

Right now, i am using `validator: FormBuilderValidators.email(context, errorText: '')` as my validator, but the result is this one, because the error text doesn't get completely removed.
![image](https://user-images.githubusercontent.com/17389697/117196969-7bbd8280-ade7-11eb-99e4-a480d10c6508.png)

Is there a way to disable the error message popping up?

Thanks!

**Comment by YouSour** [comment]
i got the same problem 😞

**Comment by YouSour** [comment]
@MattiaEffendi  here my solution : 
```
InputDecoration(
    errorStyle:
        TextStyle(height: double.negativeInfinity, 
       color: Colors.transparent,)
)

**Comment by MattiaEffendi** [comment]
@YouSour just managed to fix mine by changing height to 0 instead of your solution, since it was giving me an error!

Thanks! 🎉
