### ISSUE TITLE
Question: Standard TextFormField with FormBuilder

### ISSUE THREAD

**Issue by S-ecki** [danvick/flutter_form_builder#807]
I am trying to emulate the typeahead field (which was deleted on the null-safe version) with Flutter´s Autocomplete + a standard TextFormField
I am wondering whether I can use integrate this field into my ForumBuilder and eg save it. If not, what would be the best practise for doing this? Wrapping the Autocomplete field with an own Form and always handling both forms on a save etc?

Another question: is the TypeAhead field planned to get migrated to null safety? I really enjoyed using it!

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by S-ecki** [comment]
nope, thanks
