### ISSUE TITLE
Text Field not able to expand 

### ISSUE THREAD

**Issue by S-ecki** [danvick/flutter_form_builder#809]
Before null-safety, you could make the FormBuilderTextField expand vertically based on the input when setting `maxLines: null`.

Because `maxLines` is now (version 6.0.1) of type `int` and not `int?`, null cannot be assigned anymore. However, I did not find a reason why maxLines could not be nullable.

This also breaks the `expands` property, because for it not to throw an error, both `minLines` and `maxLines` must be null.

**Comment by tahesse** [comment]
This patch is badly needed on my side. Please let me know if I can assist with this.
