### ISSUE TITLE
currentState.setAttributeValue doesn't work

### ISSUE THREAD

**Issue by benoitverstraete** [danvick/flutter_form_builder#81]
Hi @danvick ,

I try to set a value of an input but the target attribute's value doesn't change.

Here is an example of code (based on yours) :

```
              FormBuilder(
                key: _fbKey,
                autovalidate: true,
                child: Column(
                  children: <Widget>[
                    FormBuilderDateTimePicker(
                      attribute: "date",
                      onChanged: (value) {
                        _fbKey.currentState.setAttributeValue('age', 50);
                      },
                      inputType: InputType.date,
                      format: DateFormat("yyyy-MM-dd"),
                      decoration: InputDecoration(labelText: "Appointment Time"),
                    ),
                    FormBuilderTextField(
                      attribute: "age",
                      decoration: InputDecoration(labelText: "Age"),
                    ),
                  ],
                ),
              )
```

Could you please guide me how to change an input value from another one (or outside of the form) ?

Thanks a lot !

**Comment by danvick** [comment]
Hi @benoitverstraete,
Hope you're doing well.
The `setAttributeValue` API doesn't currently work as expected - as cool as it sounds in prospect - I wasn't even aware I had accidentally published it.
The problem with `setAttributeValue` as it is currently is that it will change the underlying value for the `FormField` without changing it on the UI.

With your current problem, the solution would be to use a `TextEditingController` on the `FormBuilderTextField` by setting the `controller` attribute.

**Comment by benoitverstraete** [comment]
Thank you for your replay and your workaround, it works. 
`setAttributeValue` will be a nice feature if it is available in a future relase.

**Comment by NickCullen** [comment]
I have just run into this issue - it's all well and good using a controller for it, but when you're dealing with form values that are not strings (i.e. datetimes) it would make more sense to use the form.setAttributeValue. 

The underlying form builder input (FormBuilderDateTimePicker for example) knows how to convert the complex type to a string (i.e. the correct format of a date) and should set the text controller value accordingly.

As an example use case, I have wrote a mixin helper class

```
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';

@optionalTypeArgs
mixin FormPageHelper<T extends StatefulWidget> on State<T> {
  dynamic getFormValue(GlobalKey<FormBuilderState> form, String field) {
    if(form == null || form.currentState.fields.containsKey(field) == false) 
      return null;

    return form.currentState.fields[field].currentState.value;
  }

  void setFormValue(GlobalKey<FormBuilderState> form, String field, dynamic value) {
    if(form == null || form.currentState.fields.containsKey(field) == false) 
      return;

    setState(() {
      form.currentState.setAttributeValue(field, value);
    });
  }
}
```

And I can simply use as follows in my view:

```
class _LoginPageState extends State<LoginPage> with FormPageHelper {
  
  final _formState = GlobalKey<FormBuilderState>();

  String get email => getFormValue(_formState, "email");
  set email(String value) => setFormValue(_formState, "email", value);
  
  String get password => getFormValue(_formState, "password");
}
```

**Comment by danielwalczak** [comment]
I wonder why this is closed when `setAttributeValue` api is provided but its not working as expected. It should be reopened as a bug.

**Comment by danvick** [comment]
Hi @danielwalczak,
`setAttribute` was supposed to be a private function to be used within the package and not consumed by the user.

**Comment by papmodern** [comment]
It is an absolute necessary feature for this lib. These type of abilities are the main reason that force us to use external libs. 
I know you though about it differently. But when we are facing a clear demand, it is a wise decision to rethink the strategies.

**Comment by danvick** [comment]
Thanks for sharing your concerns @papmodern. However, is discussed earlier `setAttributeValue` was being used for the unintended purpose and thus the complaints.

I'm sure that you'll be glad to note that I am trying to [make this feature possible in the next version of the package](https://pub.dev/packages/flutter_form_builder/versions/4.0.0-beta.3#programmatically-changing-field-value) which is planned for release soon.

**Comment by papmodern** [comment]
That's a wonderful news. Glad yo hear. Thank you for your great work @danvick

**Comment by akreienbring** [comment]
Had the same problem. I need to set the value of various formfields (e.g. Dropdown, TypeAhead..) programmatically AND manually. That's why a TextEditingController is not an option. But it seems (I'm not totally sure about this...) that once the initialValue is set, the value can only be changed by manual interaction. 

For the time being I found a funny workaround: Triggering the Visibility of the Fields in question seems to do the trick for me. 
That means:
Step 1. Page loaded -> Set the initial value programmatically = works!
Do Step 1. then -> User changes the values -> State changes -> Set the initial value programmatically = Doesn't work!
Do Step 1. then -> User changes the values -> make fields invisible -> State changes -> Set the initial values programmatically and make fields visible = works!
