### ISSUE TITLE
FormBuilderDateTimePicker - resetIcon

### ISSUE THREAD

**Issue by Aerofluxx** [danvick/flutter_form_builder#818]
Maybe someone can help me with the `resetIcon` parameter in FormBuilderDateTimePicker.

I'm not able to get a `resetIcon` with my code below:

```
FormBuilderDateTimePicker(
    name: 'date',
    locale: context.locale,
    lastDate: DateTime.now(),
    firstDate: DateTime(1900),
    confirmText: 'general.submit'.tr(),
    cancelText: 'general.cancel'.tr(),
    fieldLabelText: 'general.date.title'.tr(),
    resetIcon: const Icon(Icons.delete),
    inputType: InputType.date,
    decoration: InputDecoration(
        contentPadding: const EdgeInsets.symmetric(vertical: 5.0, horizontal: 5.0),
        labelText: 'tests.birthDate'.tr(),
        disabledBorder: OutlineInputBorder(
        borderSide: BorderSide(color: Theme.of(context).primaryColor),
        ),
        focusedBorder: OutlineInputBorder(
        borderSide: BorderSide(color: Theme.of(context).primaryColor),
        ),
        enabledBorder: OutlineInputBorder(
        borderSide: BorderSide(color: Theme.of(context).primaryColor),
        ),
    ),
    format: kDateEUFormat,
),
```

Any hints what I'm doing wrong? 
Thanks a ton!

**Comment by nlfiedler** [comment]
I suspect that `resetIcon` is not actually hooked in anywhere. Searching the code base reveals the property in `form_builder_date_time_picker.dart` and nothing else. Probably something got removed at some point and now the property does nothing. It's a shame, because I would love for a "reset" on just the date picker (not the entire form).

**Comment by supermnemonic** [comment]
i have experienced the same. eventually i downgraded to ^5.0.0-alpha.1.

**Comment by santhavathi** [comment]
Will this be fixed anytime soon?
