### ISSUE TITLE
FormBuilderCheckboxGroup and didChange issue

### ISSUE THREAD

**Issue by kvbogdanov** [danvick/flutter_form_builder#829]
**FormBuilderCheckboxGroup** does not reacting on setting values with **didChange** 

                                        FormBuilderCheckboxGroup(
                                          key: UniqueKey(),
                                          name: "condition",
                                          initialValue: [],
                                          options: [
                                            FormBuilderFieldOption(child: Text("Desc 1"), value: "1"),
                                            FormBuilderFieldOption(child: Text("Desc 2"), value: "2"),
                                            FormBuilderFieldOption(child: Text("Desc 3"), value: "3"),
                                            FormBuilderFieldOption(child: Text("Other"), value: "99"),
                                          ],
                                        ),

Invoke **_fbKey.currentState.fields['condition'].didChange([1,2])** for this code does not affect anything in ver 5.* and 6.* (but in 4.* it worked well)

**Comment by mdeandrea-mrmilu** [comment]
Do you use what version? In [6.2.0 fix](https://github.com/danvick/flutter_form_builder/blob/master/packages/flutter_form_builder/CHANGELOG.md#620---21-oct-2021) this behaviour
