### ISSUE TITLE
Change part of a text field style

### ISSUE THREAD

**Issue by eliezerp3** [danvick/flutter_form_builder#830]
Hi. Absolutely love this framework and thank you to all who contributed. I have a text field that i want if someone types in '@username' then that part should turn blue but the rest should stay black. Is there any way to change the style of part of an input programmatically?

**Comment by ShadyZekry** [comment]
Hi, @eliezerp3,
Unfortunately, Flutter's  `Textfield` doesn't have this feature, but you can:
* Follow this gist https://gist.github.com/pulyaevskiy/d7af7217c2e71f31dfb78699f91dfbb5, and implement it yourself in your app.
OR
*  Just use this Package https://pub.dev/packages/rich_text_controller.

<br>

And if you need to request this feature in the package, you can mention **_Danvic_** to discuss if the package should include such feature or not.

Have a great day, eliezerp3 .

**Comment by deandreamatias** [comment]
> Hi, @eliezerp3, Unfortunately, Flutter's `Textfield` doesn't have this feature, but you can:
> 
> * Follow this gist https://gist.github.com/pulyaevskiy/d7af7217c2e71f31dfb78699f91dfbb5, and implement it yourself in your app.
>   OR
> * Just use this Package https://pub.dev/packages/rich_text_controller.
> 
> 
> And if you need to request this feature in the package, you can mention **_Danvic_** to discuss if the package should include such feature or not.
> 
> Have a great day, eliezerp3 .

If this answer solve your problem, please @eliezerp3 close this issue.
If not, feel free to open a new issue with this Feature request
