### ISSUE TITLE
initialValue from arguments & TextEditingController

### ISSUE THREAD

**Issue by Mohdx** [danvick/flutter_form_builder#834]
Hi. 
Need the initialValue to view old value text from previous page (I'm passing that by arguments)
Then after editing the textformfield, get the edited value text from TextEditingController 

is this possible? 
I found it confusing to do in flutter_form_builder
Because if there's a TextEditingController , The initialValue won't show in the textformfield

**Comment by ShadyZekry** [comment]
Hi @Mohdx ,
You can pass the initial _string-value_ to your `TextEditingController` Constructor. You shouldn't be using the `initialValue` named-parameter of the `FormBuilderTextField` with a text controller, this assertion will be false:
```Dart
assert(initialValue == null || controller == null),
```

<br>

**An example of what you are trying to do:**
```Dart
class MyForm extends StatelessWidget {
  final _formKey = GlobalKey<FormBuilderState>();
  final TextEditingController controller;

  MyForm(String? initString)
      : controller = TextEditingController(text: initString);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        child: FormBuilder(
          key: _formKey,
          child: FormBuilderTextField(
            name: 'Testing Field',
            controller: controller,
            decoration: InputDecoration(labelText: 'Testing Field'),
          ),
        ),
      ),
    );
  }
}

```

**Comment by deandreamatias** [comment]
> Hi @Mohdx , You can pass the initial _string-value_ to your `TextEditingController` Constructor. You shouldn't be using the `initialValue` named-parameter of the `FormBuilderTextField` with a text controller, this assertion will be false:
> 
> ```dart
> assert(initialValue == null || controller == null),
> ```
> 
> 
> **An example of what you are trying to do:**
> 
> ```dart
> class MyForm extends StatelessWidget {
>   final _formKey = GlobalKey<FormBuilderState>();
>   final TextEditingController controller;
> 
>   MyForm(String? initString)
>       : controller = TextEditingController(text: initString);
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: SingleChildScrollView(
>         child: FormBuilder(
>           key: _formKey,
>           child: FormBuilderTextField(
>             name: 'Testing Field',
>             controller: controller,
>             decoration: InputDecoration(labelText: 'Testing Field'),
>           ),
>         ),
>       ),
>     );
>   }
> }
> ```

Hi @Mohdx, this answer solve your question? If yes, please close this issue. Thanks

**Comment by javarava** [comment]
I have the same issue. Hi @deandreamatias how do we solve it in a stateful widget?

**Comment by javarava** [comment]
I was able to solve it with the code below:

```
class _MyFormState extends State<MyForm> {
  TextEditingController controller = TextEditingController();
  
  @override
  void initState() {
    controller.value = TextEditingValue(text: 'initializedValue');
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        child: FormBuilder(
          key: _formKey,
          child: FormBuilderTextField(
            name: 'Testing Field',
            controller: controller,
            decoration: InputDecoration(labelText: 'Testing Field'),
          ),
        ),
      ),
    );
  }
}
```
