### ISSUE TITLE
get clicked checkbox

### ISSUE THREAD

**Issue by evanholt1** [danvick/flutter_form_builder#835]
Hello!
In my app, i will have an item additions screen, with multiple _FormBuilderCheckboxGroups_, each indicating a specific category of additions.
In that screen there will be a total item price as well, reflecting the changes in the item's price as additions are selected and 
un-selected.

Due to this, I want that on the click on any checkbox to immediately add it's price (in an ItemExtra model class) to the total, if that checkbox's new status is True, and deduct from the item's price if the new checkbox status is false. 

_**Can (& How) this be achieved in this package?**_ . I know there's an onChanged property, but as it only gets the new list, and the amount of lists will be dynamic, it will be unfeasible to do such a calculation on every checkbox click.

**Comment by ShadyZekry** [comment]
Hi @evanholt1,

I suggest that you use this trick:

- You can initialize a Map object in your screen with the types `String`, `List<dynamic>` as the group `name`, and selected values list respectively.
```Dart
Map<String, List<dynamic>> resultMap = {};
```

- Then you can use `onChanged` parameter in every `FormBuilderCheckboxGroup` widget that you use. And in it, you assign the result of the selected `List` with the group widget `name`.
```Dart
FormBuilderCheckboxGroup(
  name: 'myList1'
  onChanged: (List<Object?>? value) {
    resultMap['myList1'] = value ?? [];
    print(resultMap);
  },
// other parameters
)
```

- And you can get your results from the `Map`.
---

Excuse me if I'm not fully understanding your issue. Have a great day.

**Comment by evanholt1** [comment]
Hello again!
thanks for your reply.

  I am sorry, i must have clarified more in the question:
  I have an _**ItemExtra**_ model which has a property _**Map<ItemExtra, Null> extras**_ (it should be a Set, but wrote it a Map because of Hive-Flutter's constraints),
and an **_Item_** model whose **_price_** property  changes based on the _**ItemExtras**_ chosen. 
  _**Map<ItemExtra, Null> extras**_ is used all over the place in our app for business logic, so it would be hard to change it everywhere.
 
  Thus far(before learning about this package and handling validations) I have on each checkbox click updated the item's price directly. 
  I am asking if there is similar functionality in the CheckboxGroup widget, or something comparably fast, as i really liked the validations & less boilerplate of this package.

**Comment by evanholt1** [comment]
### UPDATE:
I found out the most performant way to do this was to add 2 properties to _**FormBuilderCheckboxGroup**_,
one is of type _**Function**_(I called _**onCheckboxChanged**_), and is the custom function which will be executed on clicking any checkbox in that group,
and the other is of type _**T**_ (I called _**identifiers**_), and is the argument to the custom function above which will help identify exactly which checkbox was selected.

  As an example, i added in the widget tree:
```   
 FormBuilderCheckboxGroup<List<ItemExtra>> (
     identifiers: categoryItemExtrasList, // list of itemExtras
     onCheckboxChanged: (bool selected, ItemExtra itemExtra) {
         updateItemPrice(selected, itemExtra) // adds or removes the itemExtra depending on the boolean 
     },
    // other options 
)
```

and i passed those 2 new parameters down to **_GroupedCheckbox_**, where i changed:
```
final control = Checkbox(
      // ...previous options
      onChanged: isOptionDisabled
          ? null
          : (selected) {
              if (widget.onCheckboxChanged != null) 
                  widget.onCheckboxChanged(selected, widget.identifiers[index]); 
             // rest of code...
            },
    );
```
And this now sends the new state of the checkbox, along which checkbox was clicked (_**identifiers[index]**_), 
to the value of **onCheckboxChanged**_ defined in `FormBuilderCheckboxGroup<List<ItemExtra>>`.

While this is a bit of a niche case, i do think that sometimes it would be useful to be able to define a custom callback when a checkbox is clicked. So i think this feature (the 2 parameters) would be nice to have as optional in _**FormBuilderCheckboxGroup**_.

**Comment by WilliamCunhaCardoso** [comment]
I am not sure about it, but using a `Typed` `FormBuilderFieldOption` does not satisfy you? Also, if you want the exactly item clicked, you may use its return (as I mentioned, it can be typed, so you can pass any value), and compares it with any other data. Considering that, you can use or Equatable, or override Equality, so you can compare two objects
