### ISSUE TITLE
min-max list length validation

### ISSUE THREAD

**Issue by evanholt1** [danvick/flutter_form_builder#837]
Currently, there is no _**FormFieldValidator**_ to validate if a list's length has a minimum amount of elements, or a max amount of elements. 

  An example of this usage would be to make a _min-max_ selection of elements in a **_FormBuilderCheckboxGroup_** for example, where a user must select between min and max elements checkboxes.

  There is a '**_minLength_**' validator and a '**_maxLength_**' validator, but they only work on **Strings**.
   A simple modification to allow _**both**_ Strings and Lists to use this validator (as both have the length property),
or a new validator for min-max list length,
instead of creating custom validators would be great.

**Comment by deandreamatias** [comment]
This actually is implemented https://github.com/danvick/flutter_form_builder/blob/bf5a5914232ca106cfad60e8d531b8f8405d03e8/packages/form_builder_validators/lib/src/form_builder_validators.dart#L120
