### ISSUE TITLE
Example doesn't work anymore

### ISSUE THREAD

**Issue by benoitverstraete** [danvick/flutter_form_builder#84]
Hi @danvick, 

Apparently, the example at [example/lib/main.dart](example/lib/main.dart) doesn't work anymore.

There are a lot of print messages and the values are not correctly saved in the GlobalKey (even after save() and validate()).

I experienced the same behavior in another project.

Could you please check ?

Thanks a lot

**Comment by jocelyngirard** [comment]
Hi, 

Same behavior on my side: the values map are empty from `globalKey.currentState.value` (even after save() and validate()).

I've upgraded the Flutter version to 1.7.8, seems related ?

```
/opt/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-GB)
    • Flutter version 1.7.8+hotfix.3 at /opt/flutter
    • Framework revision b712a172f9 (13 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0
```

Thanks.

**Comment by danvick** [comment]
Hi,
Which version of the package are you using?

**Comment by danvick** [comment]
This issue will be closed due to inactivity
