### ISSUE TITLE
maxLine not nullable

### ISSUE THREAD

**Issue by cakaltepe** [danvick/flutter_form_builder#842]
In the previous version, maxLines:null was enough to stretch the FormBuilderTextField object downwards. But right now the maxLine property is not nullable.

**Comment by agallo97** [comment]
Yeah this is breaking for existing app that use this feature. Please give it at look

**Comment by cakaltepe** [comment]
> Yeah this is breaking for existing app that use this feature. Please give it at look

I guess you wanted to give a link? Because you said "Please give it at look".

**Comment by agallo97** [comment]
> > Yeah this is breaking for existing app that use this feature. Please give it at look
> 
> I guess you wanted to give a link? Because you said "Please give it at look".

Sorry, there was a typo. I was referring to the devs, I meant "give it a look"

**Comment by blackchineykh** [comment]
Any update on this one?

**Comment by cakaltepe** [comment]
Unfortunately :(

**Comment by deandreamatias** [comment]
Hi!
I seen that maxLine now support null values. I will close this issue, but if still happens can open again
https://github.com/danvick/flutter_form_builder/blob/881879b45b3df4c7434e933ac4bfb09f4fed2e10/packages/flutter_form_builder/lib/src/fields/form_builder_text_field.dart#L68
