### ISSUE TITLE
Form Reset Not Working [ver 6.0.1]

### ISSUE THREAD

**Issue by Shiba-Kar** [danvick/flutter_form_builder#848]
I have a form most of them is textFields i have passed a initialvalue. when i reset the from  using foemkey nothing happens.

**Comment by edwin0401** [comment]
I got the same. Do you have idea to fix it?

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by markfili** [comment]
I can't even click on the reset icon, it always opens the input dialog

**Comment by deandreamatias** [comment]
@markfili Can provide details please

- **Platform:** 
- **Device information:**  
- Simple code smaple

**Comment by markfili** [comment]
oh, I forgot, I think OP meant that calling `_formKey.currentState!.fields['date']?.reset();` does not reset the field which is what I found, too. you can replace `.didChange(null)` with `reset()` in `resetIcon`'s `onPressed` method in the above example to test it out

**Comment by deandreamatias** [comment]
@markfili This happens only with `FormBuilderDateTimePicker`?

**Comment by deandreamatias** [comment]
@markfili I think that this situation is duplicated from #859

**Comment by markfili** [comment]
> @markfili This happens only with `FormBuilderDateTimePicker`?

yes! just tried the example app from the master branch, only DateTimePicker has this issue, DateRangePicker and TextField work as intended.

**Comment by deandreamatias** [comment]
I think that this is because you use initialValue and initialTime at same time. These generate conflict.
I will close this issue and move all to #859
