### ISSUE TITLE
Getter of values not working

### ISSUE THREAD

**Issue by cacianokroth** [danvick/flutter_form_builder#85]
When I give a `_fbKey.current State.value` the value is empty!
I noticed that the values ​​of the `_value` variable are never changed.

```
  void setAttributeValue(String attribute, dynamic value) {
    if (_fieldKeys[attribute] != null) {
      print("Trying to change value for $attribute to $value");
      _fieldKeys[attribute].currentState.didChange(value);
      print(_fieldKeys[attribute].currentState.value);
    }
  }

```

***** **Looks like this line is missing** ********
> _value[attribute] = _fieldKeys[attribute].currentState.value;

**Comment by jasonlaw** [comment]
I am encountering the same problem here!

**Comment by frediustcDev** [comment]
Me too I had to downgrade to version **flutter_form_builder: 3.2.0**. I have deleted the build folder and android/.gradle too and sync data using android studio

**Comment by eltonmorais** [comment]
Sent a pull request to solve that. Was with the same issue here.

**Comment by danvick** [comment]
Sorry guys - been having quite a hectic couple of days.
Thanks @eltonmorais for the PR, I'm just gonna merge and publish without looking. 
I trust you ;-)
