### ISSUE TITLE
Validator weird behaviour with multiple form fields

### ISSUE THREAD

**Issue by SalahAdDin** [danvick/flutter_form_builder#850]
Hi,

Thanks for this package, a easy way to handle forms.

However, we are having the next error  when using multiple fields: It validates every fields even if it is not required.
![image](https://user-images.githubusercontent.com/5034215/125091675-4c720d00-e0d9-11eb-92de-2b2cab8b950b.png)
All four form fields are not required actually, if you interact with them and you leave then blank, the validatos are triggered too.

Now, we tried changing the validation mode to `OnUserInteraction` and it is worst: At any user interaction not just one but all fields are validated at time, why?
![image](https://user-images.githubusercontent.com/5034215/125094395-e3d85f80-e0db-11eb-9e44-a47bedf7f2e6.png)

It should validate unrequired fields and also it should validate fields one by one when auto validate mode is `OnUserInteraction`.

Thanks.

**Comment by danvick** [comment]
Setting `autovalidateMode` on the Form sets the mode on the whole form. Therefore, if the user has interacted with any field then the whole form has been interacted with and validation will run for the whole form.

Prefer having the `autovalidateMode` set on the specific fields of interest. This may cause repetition but it's the default behavior for Flutter forms.

**Comment by SalahAdDin** [comment]
> Setting `autovalidateMode` on the Form sets the mode on the whole form. Therefore, if the user has interacted with any field then the whole form has been interacted with and validation will run for the whole form.
> 
> Prefer having the `autovalidateMode` set on the specific fields of interest. This may cause repetition but it's the default behavior for Flutter forms.

There is no any `autovalidateMode` on the whole form.

**Comment by ristiisa** [comment]
@SalahAdDin did you found a solution?

**Comment by leojfrancis** [comment]
I am facing the same issue it would be great if some one can tell me what wrong and what the fix
