### ISSUE TITLE
Localization with Flutter Intl IntelliJ Plugin not working

### ISSUE THREAD

**Issue by simonsymhoven** [danvick/flutter_form_builder#851]
I've added the Flutter Intl IntelliJ Plugin and added three new languages (de_DE, en_US and fr_FR). 

![Bildschirmfoto 2021-07-14 um 14 46 43](https://user-images.githubusercontent.com/26878018/125625567-a1fc9073-ef64-499f-b54d-b8955cfba399.png)

I also installed the flutter_form_builder plugin and added the delegate to the MaterialApp:

```
supportedLocales: S.delegate.supportedLocales,
localizationsDelegates: const [
  S.delegate,
  FormBuilderLocalizations.delegate,
  GlobalMaterialLocalizations.delegate,
  GlobalWidgetsLocalizations.delegate,
  GlobalCupertinoLocalizations.delegate,
],
```

 S.delegate.supportedLocales:
```
List<Locale> get supportedLocales {
  return const <Locale>[
    Locale.fromSubtags(languageCode: 'en', countryCode: 'US'),
    Locale.fromSubtags(languageCode: 'de', countryCode: 'DE'),
    Locale.fromSubtags(languageCode: 'fr', countryCode: 'FR'),
  ];
}
```

but the localization of the form_builder_plugin is not working. If I replace the `S.delegate.supportedLocals` with 

```
[
   Locale('de')
]
```
 its working, but my own localization no longer works. So what am I doing wrong or is this an issue in the `flutter_form_builder`? 

Thanks in advanced!

**Comment by simonsymhoven** [comment]
If I swap the two delegates

```
FormBuilderLocalizations.delegate,
S.delegate,
```

the correct language is set for the form_builder but my own delegate does not work anymore.

**Comment by p02diada** [comment]
Hi @simonsymhoven , did you solved it?

**Comment by simonsymhoven** [comment]
> Hi @simonsymhoven , did you solved it?

Hi, no not yet

**Comment by mstfkhazaal** [comment]
please solve this problem

**Comment by mstfkhazaal** [comment]
multiple_localization: ^0.2.2 
i found this package and it work with me @simonsymhoven
