### ISSUE TITLE
Checking whether form statatus changes or not

### ISSUE THREAD

**Issue by SalahAdDin** [danvick/flutter_form_builder#852]
Hello,

We are using this package to build a simple form with four inputs.

We need to check whether the inputs was changed or not to send an **API** only when the form was changed.

For doing this we decided to compare the current state values with the initial value:
`if (isValid && formKey.currentState!.initialValue != formKey.currentState!.value)`
But it is always true; debbuging this we get `initialValue` is always `{}`, a empty object always; hence, the initial value and the current value are always different.

How should we handle this?

Thanks

**Comment by SalahAdDin** [comment]
> In Case someone else faces this issue, i offer a solution which worked for me: `FormBuilder` has a parameter, called `initialValue`. setting this will fill the `initialValue` Map. then below `FormBuilder`, make a `Builder`, then below it the widget which will depend on the initialValue of the form's current state.
> 
> Even more interesting is setting `initialValue`via a variable. this allows you not only to set an `initialValue`, but to also change it (consider updating an item. after saving the update, the newly saved values have become the initialValues). updating initialValue's variable can be done with a setState() or any state management library.
> 
> final example: (note the code is not optimized and is just for example)
> 
> ```
> class _CategoryFormScreenState extends State<CategoryFormScreen> {
>   late final GlobalKey<FormBuilderState> _formKey;
>   late final TextEditingController englishNameController;
>   late Map<String, dynamic> initialValues;
> 
>   @override
>   void initState() {
>     super.initState();
>     _formKey = GlobalKey<FormBuilderState>();
>     englishNameController = TextEditingController(
>         text: widget.category != null ? widget.category!.name.en : null);
>     initialValues = widget.category == null
>         ? const {}
>         : {
>             "name.en": widget.category!.name.en
>           };
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     print(englishNameController.value.text);
>     return Scaffold(
>       body: SingleChildScrollView(
>         child: FormBuilder(
>           initialValue: this.initialValues,
>           key: _formKey,
>           child: Builder(
>             builder: (context) => Column(
>               children: [
>                 Row(
>                   children: [
>                     Expanded(
>                       child: Container(
>                         decoration: BoxDecoration(
>                           borderRadius: BorderRadius.circular(5),
>                           border: Border.all(
>                             color: () {
>                               return _formKey.currentState
>                                           ?.initialValue['name.en'] ==
>                                       englishNameController.value.text
>                                   ? Colors.black
>                                   : Colors.orange;
>                             }(),
>                           ),
>                         ),
>                         child: FormBuilderTextField(
>                           name: "name.en",
>                           onChanged: (newVal) {
>                             setState(() {});
>                           },
>                           controller: englishNameController,
>                           decoration: InputDecoration(
>                             border: InputBorder.none,
>                             labelText: "Name - English",
>                           ),
>                         ),
>                       ),
>                     ),
>                     OutlinedButton(
>                         onPressed: () {
>                           englishNameController.text =
>                               _formKey.currentState?.initialValue['name.en'];
>                         },
>                         child: Text("Reset")),
>                   ],
>                 ),
>                 
>               ],
>             ),
>           ),
>         ),
>       ),
>     );
>   }
> }
> ```

It is not exactly what I need but you gave me an idea.

**Comment by SalahAdDin** [comment]
Thanks @evanholt1, you gave me an idea about it.

And my terrible solution is:
```dart
Future<void> _onSubmit({
    required GlobalKey<FormBuilderState> formKey,
    required Future<void> Function(Map<String, Object?>) onSubmitCallback,
    required void Function() onEmptyChangesCallback,
  }) async {
    formKey.currentState!.save();

    final Profile _userProfileInitialValues = user.profile ?? Profile.empty;
    final Map<String, dynamic> _profileInitialValuesMap =
        _userProfileInitialValues.toJson()
          ..removeWhere(
            (String key, _) =>
                formKey.currentState!.value.containsKey(key) == false,
          );

    if (mapEquals(
          <String, dynamic>{
            ...formKey.currentState!.value,
            ..._profileInitialValuesMap
          },
          formKey.currentState!.value,
        ) ==
        false) {
      final bool isValid = formKey.currentState!.validate();
      if (isValid) {
        final Map<String, dynamic> updatedFields = formKey.currentState!.value;
        onSubmitCallback(updatedFields);
      } else {
        // raise and error (snack bar way)
        // return false;
      }
    } else {
      onEmptyChangesCallback();
    }
  }
```

It would be awesome if the  package itself incorporates a variable to know if the form changed or not(`isDirty` is common in **Javascript** libraries) @danvick. 

Thank you!

**Comment by thedonatic** [comment]
+1 Is there any update on this feature. I would really like to see that
