### ISSUE TITLE
maxLines should be null able

### ISSUE THREAD

**Issue by hashirshoaeb** [danvick/flutter_form_builder#869]
FormBuilderTextField.maxLines should be nullable, 

Because,
>Input whose height grows from one line up to as many lines as needed for the text that was entered. If a height limit is imposed by its parent, it will scroll vertically when its height reaches that limit.
TextField(maxLines: null)

**Comment by deandreamatias** [comment]
This bug exists and is tracked here #842. There have a discussion about this and possible solutions
