### ISSUE TITLE
How to set value of FormBuilderDropdown

### ISSUE THREAD

**Issue by shariful2011** [danvick/flutter_form_builder#87]
How can I set the value of FormBuilderDropdown? I need FormBuilderDropdown to initialize with my database's table's data as per it's items.

**Comment by jicasa03** [comment]
> ¿Cómo puedo establecer el valor de FormBuilderDropdown? Necesito FormBuilderDropdown para inicializar con los datos de la tabla de mi base de datos según sus elementos.

**Comment by danvick** [comment]
Hi @shariful2011 / @jicasa03,
I'd suggest putting your `FormBuilderDropdown` inside a `FutureBuilder` - since you can't change the Dropdown's items after initialization.

**Comment by cntoss** [comment]
that means we can not set the value ?? how can i get id of user by selecting user's name using FormBuilderDropDown

**Comment by wyxcoder** [comment]
seems you can use didChange like

_formKey.currentState.fields['product'].currentState.didChange(val)

**Comment by jicasa03** [comment]
_fbKey.currentState.fields["cuenta_abono"].currentState.didChange(val);
