### ISSUE TITLE
disable auto-scroll to first error

### ISSUE THREAD

**Issue by evanholt1** [danvick/flutter_form_builder#872]
How can we disable auto-scrolling to the first error?
in my current design, it looks jarring when it auto-scrolls, and i would in a certain FormBuilder that it would not autoscroll to the first error.
Can such an option be added to FormBuilder?

**Comment by huylethanh** [comment]
> How can we disable auto-scrolling to the first error?
> in my current design, it looks jarring when it auto-scrolls, and i would in a certain FormBuilder that it would not autoscroll to the first error.
> Can such an option be added to FormBuilder?

That thing make my application ruined and I get the "Once you have called dispose() on a FocusNode, it can no longer be used" all of the time.
