### ISSUE TITLE
Example using forms builder with mobx

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [danvick/flutter_form_builder#873]
Hello,

This package is quite impressive. But it would be super cool if you can add example how to use this package with mobx (https://pub.dev/packages/flutter_mobx). I wonder if this packages suffers from same issues as flutter forms (initialValue vs controller when using with mobx).

Thanks

**Comment by WilliamCunhaCardoso** [comment]
I understand that it would be better as an article. It will demand too much effort to support examples for different state managers. Also, it is out of scope of the project. So, articles would be better for it. 

@danvick
