### ISSUE TITLE
Feat: Make radio group focus request optional

### ISSUE THREAD

**Issue by hazzo** [danvick/flutter_form_builder#880]
Hi, thanks for the great library!

Could be possible to turn off `requestFocus` with a parameter? The reason is to avoid scrolling to selected radio on change as this might be a desired behaviour. Maybe something like that?

```dart
  onChanged: (val) {
   if(requestFocusOnChange) {
       state.requestFocus();
    }
    state.didChange(val);
  },
```

Thanks again!

**Comment by WilliamCunhaCardoso** [comment]
Not only for radio group but also to chips form. This mandatory request focus embarrass with forms which are able to scroll. I've implemented an optional attribute, so we can decide whether an option should request focus.

**Comment by zzzaJ** [comment]
This should also be implemented for Dropdowns, as I am having a similar issue. Dropdown, when changed, requests focus and moves to the top of the screen and moving the scroll view. This is annoying for users, and not good practice if you aren't completing a form in the same order (top form component to bottom form component) each time.

**Comment by WilliamCunhaCardoso** [comment]
On free time I will check it and maybe implement on https://github.com/danvick/flutter_form_builder/pull/881 if on moment it is not merged yet

**Comment by deandreamatias** [comment]
With @hazzo we found a temporary solution for this problem (that also happens with `FormBuilderDateTimePicker`).
We use `FocusScope.of(context).requestFocus(FocusNode())` after focus action

**Comment by WilliamCunhaCardoso** [comment]
Check if https://github.com/danvick/flutter_form_builder/pull/881 solvs

**Comment by WilliamCunhaCardoso** [comment]
Can you please confirm if `flutter_form_builder: ^7.1.0` solves it?

**Comment by WilliamCunhaCardoso** [comment]
Closing this issue because it seems to be resolved. In case not, feel free to open again/create a new one.

Thanks for contributing.
