### ISSUE TITLE
Disable scroll down on changing form builder fields

### ISSUE THREAD

**Issue by andrewjallenuoft** [danvick/flutter_form_builder#882]
As of 6.1.0, when some FormBuilder fields are changed, it forces the page to scroll down to the point where the changed field is at the top of the page. This is quite a jarring experience for the user as it jumps the page down unnaturally. I have not found a way to disable this behaviour, but downgrading to 6.0.1 solves this problem.

This occurs with FormBuilderSwitch and FormBuilderFilterChip on Flutter web.

**Comment by zzzaJ** [comment]
Also having this issue, but with FormBuilderDropdowns.

**Comment by lehnen** [comment]
Downgrading to 6.0.1 leads to the same problem in my case. But only with FormBuilderSwitch. FormBuilderDropdowns seemed to be ok in 6.0.1.

**Comment by cedricDevWP** [comment]
Same with FormBuilderChoiceChip

**Comment by lionnel8** [comment]
I'm also facing this issue with multiple input types. I've found it's caused by calling Scrollable.ensureVisible(context) in requestFocus method, which was added in this commit: https://github.com/danvick/flutter_form_builder/commit/96ac54f2f4573f9f497df56a3fd8187c9022ff63
Not sure what's the exact purpose of calling this method. When user interacts with some field, I would expect it's also in the visible area at that time.

**Comment by zzzaJ** [comment]
Is there any update on this, or any timeline for the fix to be made to the relevant FormBuilder components?

**Comment by WilliamCunhaCardoso** [comment]
Please check if this pr solves https://github.com/danvick/flutter_form_builder/pull/881

**Comment by T1960CT** [comment]
Any updates? It's been a while.. I'm having the issue with an android UI of scrollbars, every one of them scrolls the page down

**Comment by WilliamCunhaCardoso** [comment]
> Any updates? It's been a while.. I'm having the issue with an android UI of sliders and switches, every one of them scrolls the page down

I am waiting for some owner of this repo to cheeck my pr :/

**Comment by T1960CT** [comment]
> > Any updates? It's been a while.. I'm having the issue with an android UI of sliders and switches, every one of them scrolls the page down
> 
> I am waiting for some owner of this repo to check my pr :/

I've been following your PR comments as well. Thanks for trying, haha, hopefully it gets fixed soon.

**Comment by WilliamCunhaCardoso** [comment]
Closing this issue because it seems to be resolved. In case not, feel free to open again/create a new one.

Thanks for contributing.

**Comment by ervindobri** [comment]
Seems like this issue still persists with FormBuilderDropdown.

**Comment by deandreamatias** [comment]
Hi @ervindobri 
If you can, please open a new bug issue with all details posible.
Thanks
