### ISSUE TITLE
How to watch value change

### ISSUE THREAD

**Issue by socramm9** [danvick/flutter_form_builder#895]
I need to update my UI Based changes on a FormBuilderField. I can't use the onChange of this widget because the field is rendered dynamically. 

So I was thinking to read the value I need from the GlobalKey. Maybe I am missing something but the only way to read from the GlobalKey is to first call the `save()` and `validate()` functions. 

But it is to soon to run the validation in my case.

```
FormBuilder(
  key: _fbKey,
  onChanged: () {

     _fbKey.currentState?.save();
     print(_fbKey.currentState?.value); // Is Empty
       if (_fbKey.currentState?.validate() ?? false) {
         print(_fbKey.currentState?.value);  // Is not Empty
       } else {
          print("validation failed");
       }
        setState(() {});
      },
  child: ...
);
```

**Comment by WilliamCunhaCardoso** [comment]
Do you want to watch values to validate it while the field is being manipulated? For example, validate a text field while the user is typing on it, right? If so, declaring the field `validators` and setting its validate mode as `AutovalidateMode.onUserInteraction` can solve your problem?

**Comment by socramm9** [comment]
I had to come up with an other solution. I needed to validate outside of the Textfield.
I am Using the FormBuilder onChange event 

```
FormBuilder(
    key: _fbKey,
    onChanged: () {...}
)
```

**Comment by WilliamCunhaCardoso** [comment]
Thanks. Sorry for the delay :(
