### ISSUE TITLE
   FormBuilderInput.datePicker

### ISSUE THREAD

**Issue by HAL68000** [danvick/flutter_form_builder#9]
HI I'm trying to use the date picker, even if I set the firstDate parameter I can't, go further Sun, Aug 4 1991 (up to sun may 6th 2046). I'm trying on Huawei and nexus 5 (through emulation) with the same results.  Am I doing something wrong? 

            FormBuilderInput.datePicker(
              label: "Date of Birth",
              firstDate: DateTime(1900),
              attribute: "dob",
            ),

![image](https://user-images.githubusercontent.com/40710379/50208853-a6911280-03b5-11e9-8348-3f98c13e8c09.png)

Thank you for your time :)

**Comment by danvick** [comment]
Hello @HAL68000
My bad. Oversight issue on my part, forgot to plug-in the functionality of setting min and max dates.
Kindly update to version 1.3.2  - which I've just published - contains the fix.

Cheers

**Comment by HAL68000** [comment]
Thank you so much for your support, now it works. If I find other issues I will notify you.
Cheers

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Il giovedì 20 dicembre 2018 02:52, Danvick Miller <notifications@github.com> ha scritto:

**Comment by HAL68000** [comment]
Maybe you should add an initialDate parameter too to to avoid this error.

'package:flutter/src/material/date_picker.dart': Failed assertion: line 1081 pos 10: '!initialDate.isAfter(lastDate)': initialDate mustbe on or before lastDate

FormBuilderInput.datePicker(
label:"Date of Birth",
firstDate:DateTime(1900),
lastDate:DateTime(2018),

attribute:"dob",
),

But it's not so important right now . Keep it in mind for the next update.  :P

Cheers
