### ISSUE TITLE
FormBuilderTextField calls extra validation when its initialValue and controller are not set

### ISSUE THREAD

**Issue by yfakariya** [danvick/flutter_form_builder#904]
`FormBuilderTextField` calls its validator twice if it mets following conditions:

* Its `initialValue` is not set (or set to `null`).
* Its `controller` is not set.
* Its `autovalidateMode` is set other than `AutovalidateMode.disabled`.

In this situation, validation with an empty string (`''`) is called before "actual" validation for the input value. It causes some confusion in widget testing which tends to measure validation logic precisely.

As far as I investigated, although [the _controller is initialized with null](https://github.com/danvick/flutter_form_builder/blob/4609e5c895ac0db04905472b5fe1227cb7f6e56a/packages/flutter_form_builder/lib/src/fields/form_builder_text_field.dart#L441), the relevant `TextEditingController` is [initialized as empty string](https://github.com/flutter/flutter/blob/0b0b21ecb5244c51d2cebc5f9a97530825cc95e6/packages/flutter/lib/src/widgets/editable_text.dart#L112), so any input throughs [the condition](https://github.com/danvick/flutter_form_builder/blob/4609e5c895ac0db04905472b5fe1227cb7f6e56a/packages/flutter_form_builder/lib/src/fields/form_builder_text_field.dart#L480) because `_effectiveController!.text!` (empty) is not equal to `value` (`null`), and then `didChange()` is called before actual validation.

I think there are options to fix this issue:

* Coalesce `initialValue` to empty for `null` like [TextFormField does](https://github.com/flutter/flutter/blob/0b0b21ecb5244c51d2cebc5f9a97530825cc95e6/packages/flutter/lib/src/material/text_form_field.dart#L185). It also improves compatibility between `FormBuilderTextField` and `TextFormField`, but it introduce a little breaking change.
* Change [suppression logic](https://github.com/danvick/flutter_form_builder/blob/4609e5c895ac0db04905472b5fe1227cb7f6e56a/packages/flutter_form_builder/lib/src/fields/form_builder_text_field.dart#L480) to consider `null` as empty string (such as `if (_effectiveController!.text != value ?? '')`).

**Comment by deandreamatias** [comment]
The pull request #1019 solve this issue?

**Comment by yfakariya** [comment]
Yes, I've tested with a3510a4152e9a665e74fc313969f51ee20d07397 and confirm that the extra validation was not called anymore.
I will wait for next release.  Thank you!
