### ISSUE TITLE
right way check validation between 2 fields

### ISSUE THREAD

**Issue by YouSour** [danvick/flutter_form_builder#917]
hi , i got some problem , i don't know how can i check validation between 2 fields , example i have field **amount** and field **minimizeAmount** then i need to check  field **minimizeAmount** must be less than or equal field **amount** , can you show me how can i check it ? thank in advance 😄

**Comment by danvick** [comment]
Hi @YouSour,

Kindly check out [conditional validation](https://pub.dev/packages/flutter_form_builder#conditional-validation) on the package documentation
