### ISSUE TITLE
form builder widget updates scroll state on tab

### ISSUE THREAD

**Issue by thedonatic** [danvick/flutter_form_builder#921]
Hello,

im using the flutter_form_builder widgets in a flutter app. Whenever i click on a form builder widget, my singlechildscrollview change its scroll state and tries to put the tapped form widget on top of the screen.

This happends with widgets in forms, that are splitted in multiple stateful/ stateless widgets.

For example

- Stateful Widget -> FormBuilder
   -  Stateless Widget (contains form widgets in column)
   -  Stateless Widget (container form widgets in column)

Thank you for any help or ideas.

**Comment by WilliamCunhaCardoso** [comment]
What fields does this behavior occur?

**Comment by thedonatic** [comment]
@WilliamCunhaCardoso I described this problem in detail on this stackoverflow thread: https://stackoverflow.com/questions/70250898/flutter-input-widgets-unintentional-movements-and-refocus-after-input

**Comment by WilliamCunhaCardoso** [comment]
> @WilliamCunhaCardoso I described this problem in detail on this stackoverflow thread: https://stackoverflow.com/questions/70250898/flutter-input-widgets-unintentional-movements-and-refocus-after-input

Yeah I faced this error. you can try my pr. I solved it by adding a shouldRequest on onChanged

**Comment by thedonatic** [comment]
Much thanks. Hope it will get merged anytime soon.
