### ISSUE TITLE
Focus when change value in dropdown field 

### ISSUE THREAD

**Issue by phucgotecq** [danvick/flutter_form_builder#927]
![image](https://user-images.githubusercontent.com/88519540/147221802-6cb18041-fd46-4363-b2b4-e54990fbdf9e.png)
can you allow to disable/enable the focus action when change value ? now it force field to focus after change value => state.requestFocus()

**Comment by AZKZero** [comment]
@phucgotecq can you check #931 ? The checkbox had the same issue, check if you need something like that.

**Comment by zzzaJ** [comment]
Also having the same issue. The fix used in #931 for checkboxes is exactly what would fix it for me as well.

**Comment by AZKZero** [comment]
@danvick can you merge and replicate these changes across other clickable elements?

**Comment by WilliamCunhaCardoso** [comment]
Check if https://github.com/danvick/flutter_form_builder/pull/881 solves it

**Comment by WilliamCunhaCardoso** [comment]
Can you please confirm if `flutter_form_builder: ^7.1.0` solves it?

**Comment by WilliamCunhaCardoso** [comment]
Closing this issue because it seems to be resolved. In case not, feel free to open again/create a new one.

Thanks for contributing.
