### ISSUE TITLE
FormBuilderValidators no exist

### ISSUE THREAD

**Issue by koby9779** [danvick/flutter_form_builder#932]
hey, in the new version 7.0.0 FormBuilderValidators is no exist

**Comment by Najib90** [comment]
they exist, can you please show what your code looks like ?

**Comment by koby9779** [comment]
![image](https://user-images.githubusercontent.com/78863592/147471316-e97bc90d-dd2d-4b54-99b1-643c95b3a55a.png)
thanks

**Comment by Najib90** [comment]
> 

Thanks. You probably haven't installed the validators yet I guess, so just do:

1. flutter pub add flutter form_builder_validators
2. import 'package:form_builder_validators/form_builder_validators.dart';

Let me know if that works

**Comment by ShadyZekry** [comment]
Hey, @koby9779,

Did you try to import it manually ? 
Try importing it at the start of your file.
```dart
import 'package:form_builder_validators/form_builder_validators.dart';
```

I guess it is a linting issue in your vscode, so let's try and make sure first.

**Comment by koby9779** [comment]
> > 
> 
> Thanks. You probably haven't installed the validators yet I guess, so just do:
> 
> 1. flutter pub add flutter form_builder_validators (or add it to your pubspec.yaml)
> 2. import 'package:form_builder_validators/form_builder_validators.dart';
> 
> Let me know if that works

Thanks its help, I just think the flutter_form_builder include that

**Comment by AirborneEagle** [comment]
@Najib90 's solution was what I needed. Thank you Sir!

Is there any place in the readme or documentation that states the validators are a seperate package? if so, My bad for missing it. If not, It may be a good idea to put it in some place.

**Comment by koby9779** [comment]
In old version (3.14.1) its was.
Thank anyway you help me a lot

**Comment by Najib90** [comment]
> @Najib90 's solution was what I needed. Thank you Sir!
> 
> Is there any place in the readme or documentation that states the validators are a seperate package? if so, My bad for missing it. If not, It may be a good idea to put it in some place.

Not sure in documentation per se, but in the 'Example' on pub.dev you can see that they import it separately (last import):
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:form_builder_validators/form_builder_validators.dart';
```

Source: https://pub.dev/packages/flutter_form_builder/example
