### ISSUE TITLE
FormBuilderDropdown shows options in wrong place when keyboard is active

### ISSUE THREAD

**Issue by uaumateus** [danvick/flutter_form_builder#940]
Hi guys, I'm having a layout problem with FormBuilderDropdown. When the keyboard is enabled and I click on the FormBuilderDropdown, it dismisses the keyboard but shows the dropdown options in the place where it was when the keyboard was enabled. It is worth mentioning that the following example is inside a bottom sheet.

https://user-images.githubusercontent.com/33528161/149532343-4bd6ea2e-2b63-4ba4-9087-593ee5114b7a.mp4

**Comment by WilliamCunhaCardoso** [comment]
So far I managed to solve it by this workaround https://github.com/flutter/flutter/issues/22075#issuecomment-567836464

**Comment by deandreamatias** [comment]
This issue is related to this package or to flutter?

**Comment by WilliamCunhaCardoso** [comment]
Since it seems to be a flutter core problem, I am closing it here. Just check comments on https://github.com/flutter/flutter/issues/22075#issuecomment-567836464
