### ISSUE TITLE
FormBuilderCheckbox required != "not equal to false" example

### ISSUE THREAD

**Issue by alarmatwork** [danvick/flutter_form_builder#945]
Please consider adding FormBuilderCheckbox validation example to documentation for case like "Accept T&C" checkbox, where we require user to check the checkbox. Probably many others will try to solve it with this:

```

                FormBuilderCheckbox(
                  name: 'acceptTermsAndPrivacy',
                  initialValue: false,
                  validator: FormBuilderValidators.compose([
                    FormBuilderValidators.required(context,
                        errorText: 'You must accept terms and conditions to continue'),
                  ]),
                  ...
```

And spend a lot of time wondering why error message is not popping up on validate.
And a bit later hopefully will understand that they ment

```
                  validator: FormBuilderValidators.compose([
                    FormBuilderValidators.notEqual(context, false,
                        errorText: 'You must accept terms and conditions to continue'),
                  ]),
```
as checkbox was available all the time, but it was not just checked. Maybe even remove option to add required validator, as this is super confusing and useless for FormBuilderCheckbox type.

**Comment by danvick** [comment]
I believe this is already in the example app.

**Comment by alarmatwork** [comment]
Unfortunately it is not in the sample code where everybody will probably get their first code
[](https://pub.dev/packages/flutter_form_builder)
