### ISSUE TITLE
FormBuilderDateTimePicker error

### ISSUE THREAD

**Issue by LucaGabi** [danvick/flutter_form_builder#95]
"The method 'DateFormat' isn't defined for the class" 
```
FormBuilderDateTimePicker(
                attribute: "date",
                inputType: InputType.date,
                format: DateFormat("yyyy-MM-dd"),
                decoration: InputDecoration(labelText: "Appointment Time"),
              ),
```
![image](https://user-images.githubusercontent.com/37976898/61656810-3ab7b500-acca-11e9-8369-cd8e72a9ba21.png)

Please help..

**Comment by danvick** [comment]
Hi,
`DateFormat` is in the `intl` package. Kindly import it as shown below: 

`import 'package:intl/intl.dart';`

also import `InputType` from `datetime_picker_formfield` which is a dependecy of `flutter_form_builder`:

`import 'package:datetime_picker_formfield/datetime_picker_formfield.dart';`
