### ISSUE TITLE
Buyme Coffe link in README is not working

### ISSUE THREAD

**Issue by alarmatwork** [danvick/flutter_form_builder#950]
I'm really grateful for this massive helper! Keep on doing good work and fix the link please, so you can enjoy some coffee too!

**Comment by yokiran** [comment]
@danvick , the URL you currently have "https://www.buymeacoffee.com/wb5M9y2Sz" shows a page not found.
You may want to update it, here is the help page to do that https://help.buymeacoffee.com/en/articles/5885219-how-to-change-your-username-page-url 

Great work on Flutter Form Builder, thanks

**Comment by danvick** [comment]
Thanks for letting me know. I haven't visited the site in a while and it seems things. Some new requirements were added and needed updating - that's why my link was down. 

I'll be updating the link as I merge the latest PRs and release a new version of the package(s)
