### ISSUE TITLE
 No instance of FormBuilderLocalizations present in the widget tree. Did you add FormBuilderLocalizations.delegate in localizationsDelegates?

### ISSUE THREAD

**Issue by alexaung** [danvick/flutter_form_builder#951]
I got this error message when I click submit button. 

`Exception has occurred.
_AssertionError ('package:form_builder_validators/localization/l10n.dart': Failed assertion: line 44 pos 12: 'instance != null': No instance of FormBuilderLocalizations present in the widget tree. Did you add FormBuilderLocalizations.delegate in localizationsDelegates?)`

Here is my form

`Widget _favouriteForm(SocialMode socialMode) {
    
    return FormBuilder(
      key: formKey,
      autovalidateMode: AutovalidateMode.disabled,
      child: Center(
        child: SingleChildScrollView(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const SizedBox(
                height: 20,
              ),
              SizedBox(
                width: MediaQuery.of(context).size.width * 0.9,
                child: FormBuilderTextField(
                  textInputAction: TextInputAction.next,
                  name: "kName",
                  validator: FormBuilderValidators.compose([
                    FormBuilderValidators.required(context),
                    FormBuilderValidators.match(
                        context, r"^[A-Za-z\s]{1,}[\.]{0,1}[A-Za-z\s]{0,}$",
                        errorText: "Name can only be alphabets!"),
                  ]),
                  decoration: InputDecoration(
                    contentPadding: const EdgeInsets.all(8),
                    prefixIcon: const Icon(Icons.favorite_outline),
                    hintText: "Enter playlist name",
                    hintStyle: kHintStyle,
                    fillColor: Colors.grey[200],
                    filled: true,
                    enabledBorder: kOutlineBorder,
                    focusedBorder: kOutlineBorder,
                    errorBorder: kOutlineErrorBorder,
                    focusedErrorBorder: kOutlineErrorBorder,
                  ),
                ),
              ),
              const SizedBox(
                height: 20,
              ),
              CustomButton(
                onPressed: () async {
                  if (formKey.currentState!.validate()) {
                    create(socialMode, widget.currentMediaItem);
                  }
                },
                child: const Text("Create"),
              )
            ],
          ),
        ),
      ),
    );
     }`

**Comment by LukasDoesDev** [comment]
https://github.com/danvick/flutter_form_builder/blob/master/packages/form_builder_validators/README.md#l10n

**Comment by rmControls** [comment]
Hello I am getting the same error... the above link doesn't work... can you please share the link again...?
