### ISSUE TITLE
Alternative to FormBuilderLocalizations or just don't use FormBuilderValidators

### ISSUE THREAD

**Issue by gslender** [danvick/flutter_form_builder#952]
Assuming I'm not wanting to use the error text wording, or use my own way of dealing with i18n in Flutter, what support is there for using FormBuilderValidators, but my own delegate for all the error messages etc? What's the best/easiest way to plug in my own delegate into the FormBuilderValidators?

Is this possible, or would it be easier to use my own set of Validators with error txt etc... ??

**Comment by danvick** [comment]
I'm afraid that's gonna cost you a bit in terms of lines of code. `form_builder_validators` will allow you to write your own error message instead of the default.

You'll however have to do this for every validator you use:

```dart
....
validator: FormBuilderValidators.compose([
    FormBuilderValidators.required(context, errorText: <YourCustomLocalizations>.of(context).requiredErrorText)),
    FormBuilderValidators.numeric(context, errorText: <YourCustomLocalizations>.of(context).numericErrorText),
    FormBuilderValidators.max(context, 70, errorText: <YourCustomLocalizations>.of(context).maxErrorText)),
])
```

**Comment by gslender** [comment]
No that's actually perfect and exactly what I'm looking for. I don't use the code-generator way of i18n support in my apps, and having a way to just inject my i18n strings is perfect :-)

PS - your readme examples on the websites are all wrong and don't compile without several code updates (e.g. not null safe etc, field names have changed etc)
