### ISSUE TITLE
Why there is a file script for tests?

### ISSUE THREAD

**Issue by WilliamCunhaCardoso** [danvick/flutter_form_builder#954]
I was looking in the package and saw a file named `run_tests.sh`. I believe it may is not necessary since melos can already perform those tests.

**Comment by danvick** [comment]
I think someone added it as part of their PR and I was too lazy to remove and advise them.

Hey @WilliamCunhaCardoso, would you like for me to add you as an admin of this repo. I could use some help reviewing PRs and thinking about some ideas.

**Comment by WilliamCunhaCardoso** [comment]
> I think someone added it as part of their PR and I was too lazy to remove and advise them.
> 
> Hey @WilliamCunhaCardoso, would you like for me to add you as an admin of this repo. I could use some help reviewing PRs and thinking about some ideas. This project is quickly becoming bigger than me

I would love it. Really happy for your suggest.

Also, about test file, I already am making a pr for it, removing the additional file and updating the one in melos file
