### ISSUE TITLE
bug with validators or form-fields when adding/removing from Build tree

### ISSUE THREAD

**Issue by gslender** [danvick/flutter_form_builder#959]
Hard to describe but easy to see with the included example source showing the problem. 

Essentially, when you switch between the fields as part of the form during a rebuild (via setState) the error validations get mixed up and stay sticky to the incorrect fields. I don't understand the underlying method of attaching fields to validators and error text etc, but it would seem there is a list with no specific ID to tie everything together. So when you remove/add child form widgets during a build, the Form's validation is broken and needs resetting or something !?

Please try the example below and just toggle between one and two and note that the required error text for Two.1 text is actually showing the error text from One.1 (and vice versa).

There is a) no reason for the required error txt to show, and even if it did b) it shouldn't show the prior fields error txt !?

```
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';
import 'package:form_builder_validators/form_builder_validators.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _formKey = GlobalKey<FormBuilderState>();

  final choiceOptions = ['One', 'Two'];
  String choice = '';

  @override
  Widget build(BuildContext context) {
    List<Widget> formWidgets = [];
    switch (choice) {
      case 'One':
        formWidgets = _oneFormWidget();
        break;
      case 'Two':
        formWidgets = _twoFormWidget();
        break;
      default:
        formWidgets = [];
    }
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Center(
          child: FormBuilder(
            key: _formKey,
            autovalidateMode: AutovalidateMode.onUserInteraction,
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                FormBuilderDropdown<String>(
                  name: 'gender',
                  decoration: const InputDecoration(
                    labelText: 'Form Widgets',
                  ),
                  // initialValue: 'Male',
                  allowClear: true,
                  hint: const Text('Select Choice'),
                  onChanged: (value) {
                    setState(() {
                      choice = value ?? '';
                    });
                  },
                  validator: FormBuilderValidators.required(context,
                      errorText: 'This is required'),
                  items: choiceOptions
                      .map((name) => DropdownMenuItem(
                            value: name,
                            child: Text(name),
                          ))
                      .toList(),
                ),
                ...formWidgets,
              ],
            ),
          ),
        ));
  }

  List<Widget> _oneFormWidget() {
    return [
      FormBuilderTextField(
        name: 'one1',
        decoration: const InputDecoration(
          labelText: 'One.1 text',
        ),
        validator: FormBuilderValidators.required(context,
            errorText: 'This One.1 is required'),
        keyboardType: TextInputType.number,
      ),
    ];
  }

  List<Widget> _twoFormWidget() {
    return [
      FormBuilderTextField(
        name: 'two1',
        decoration: const InputDecoration(
          labelText: 'Two.1 text',
        ),
        validator: FormBuilderValidators.required(context,
            errorText: 'This Two.1 is required'),
        keyboardType: TextInputType.number,
      ),
      FormBuilderTextField(
        name: 'two2',
        decoration: const InputDecoration(
          labelText: 'Two.2 text',
        ),
        validator: FormBuilderValidators.required(context,
            errorText: 'This Two.2 is required'),
        keyboardType: TextInputType.number,
      ),
    ];
  }
}

```

**Comment by gslender** [comment]
Any chance someone can confirm (or otherwise) the bug? As if its not supposed to be used that way (ie form widgets being removed/added to the build tree) then I'd like to know now so that I can re-engineer my app to avoid using it this way

**Comment by gslender** [comment]
Maybe I'm seeing an issue that is fixed by https://github.com/danvick/flutter_form_builder/pull/811

**Comment by gslender** [comment]
Also tried with v6.1.0 of flutter_form_builder and the problem still exists.

**Comment by gslender** [comment]
I believe the issue is due to the way custom error text is managed... I haven't got the time to invest further troubleshooting, especially it seems I'm talking to myself 🤣🤣

**Comment by gslender** [comment]
Tried it with Flutter's Form and TextFormField and found that the issue exists too. BUT, I can call _formKey.currentState.reset() when changing between dropdown options and it works fine. So the issue, is now that I cannot call the same .reset() with FormBuilderState as it crashes. There is some behaviours that differ between Flutter and FormBuilder that make it not compatible or possible to do widget changes on re-build

**Comment by WilliamCunhaCardoso** [comment]
Thanks for your information. I will try to check it on free time. Please keep us updated with new infos if you mind.

**Comment by gslender** [comment]
I've removed FormBuilder from my project because I can't continue using it with zero information back ... sorry but I don't mind helping if there's interest to help too.

**Comment by WilliamCunhaCardoso** [comment]
Sorry I could not help you before :( even though thanks for reporting it :)

**Comment by WilliamCunhaCardoso** [comment]
`registerField` and `removeInternalFieldValue` from `formKey` `currentState` does not satisfy your situation?

**Comment by WilliamCunhaCardoso** [comment]
As the author is no longer using the package, the issue can't be helped. Also, other issues related to this behavior are already on track. Thanks for the report.

**Comment by gslender** [comment]
Maybe take the example code I've provided, and add that to your test case and show how you'd use your FormBuilder package and accomodate building a form that can change upon dropdown or button (whatever). The point is that you'd think that building the form dynamically would have the validations and everything work as expected. It doesn't and there is something fundamentally wrong with either the FormBuilder, or Flutter's Form / Field that doesn't make this approach work... happy to circle back here if you're happy to provide some guidance around how you think it should work. I don't follow how using registerField and removeInternalFieldValue from formKey currentState helps?

**Comment by dev-thinks** [comment]
> `registerField` and `removeInternalFieldValue` from `formKey` `currentState` does not satisfy your situation?

@WilliamCunhaCardoso is there any documentation on these anywhere?!!
