### ISSUE TITLE
Selected year selector view is partially  clipped

### ISSUE THREAD

**Issue by krishnakirana** [danvick/flutter_form_builder#97]
![Simulator Screen Shot - iPhone XS Max - 2019-07-23 at 09 53 16](https://user-images.githubusercontent.com/20473095/61682597-dfb8a900-ad2f-11e9-926e-f05991cf0d1d.png)

**Comment by knaeckeKami** [comment]
Did you define you own theme and set a custom value for "headline"?

**Comment by krishnakirana** [comment]
Yes

**Comment by knaeckeKami** [comment]
The documentation for the "headline" field is:
Used for large text in dialogs (e.g., the month and year in the dialog
shown by [showDatePicker]).

You can either use another field of TextTheme for your big texts (such as display1, display2...) and leave headline as is,
or you can provide a custom theme for the subtree that shows the date dialog.
Example:
```
 Theme(
                          data: Theme.of(context).copyWith(textTheme: TextTheme(headline: TextStyle(fontSize: 16))),
                          child:  <your child widget that shows the dialog>
```

**Comment by krishnakirana** [comment]
Thanks, This solved my issue
