### ISSUE TITLE
please!!

### ISSUE THREAD

**Issue by gustavobrian** [danvick/flutter_form_builder#970]
A query! There are more than 100 developers in this library. But every time I want to update it, it becomes the most expensive part of the project because of the changes that break the code and the changes in the criteria of the interfaces... what is the update strategy? I really want to understand it.... thank you

**Comment by WilliamCunhaCardoso** [comment]
Sorry for this :/

The package seems to follow `major`, `minor` and `patch` update. Since the last one was a minor, you may expect some breaking changes.

Also, I suggest you to abstract components in your own project, Like

`class OwnTextField extends FormBuilderTextField {}`

**Comment by WilliamCunhaCardoso** [comment]
Since there is a long time without any new information, I am closing it
