### ISSUE TITLE
FormBuilderValidators.email accepts whitespace

### ISSUE THREAD

**Issue by brunodmn** [danvick/flutter_form_builder#979]
I've just had I problem when sending e-mails to a client who has filled a form.
I am using bellow validator on TextField:
```
validator: FormBuilderValidators.compose([
          FormBuilderValidators.email(context)
        ]),
```
I checked the code and email validator use `trim()` on the value to check whether its an email or not. But I think it should NOT use trim(), as Form Builder will accept and save the value WITH the whitespace (which would not be a valid email).

I could do a PR if you agree, but it's so simple issue that any contributor could only remove the trim and publish on next package upgrade.

**Comment by danvick** [comment]
Thanks @brunodmn for catching this. 

It may have been introduced by a contributor by error
