### ISSUE TITLE
stuck with this issue

### ISSUE THREAD

**Issue by kketanssharma** [danvick/flutter_form_builder#986]
[/Users/ksd/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.10.0/lib/src/chips_input.dart:87:7](): Error: The non-abstract class 'ChipsInputState' is missing implementations for these members:
 - TextInputClient.insertTextPlaceholder
 - TextInputClient.removeTextPlaceholder
 - TextInputClient.showToolbar
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ChipsInputState<T> extends State<ChipsInput<T>>
      ^^^^^^^^^^^^^^^

**Comment by davebound** [comment]
[This](https://github.com/danvick/flutter_chips_input/issues/107) might be of use?
