### ISSUE TITLE
FormBuilderCheckboxGroup and FormBuilderRadioGroup multi line in question not working properly 

### ISSUE THREAD

**Issue by kader46** [danvick/flutter_form_builder#996]
I've been trying to use FormBuilderCheckboxGroup and FormBuilderRadioGroup on my form, but whenever a long question is set the multi line is not leaving enough space between the question (label) and the options . 
I tried to wrap it with a SingleChildScrollView so it's a single line but scrollable but it didn't scroll ! 
here's the code :
```
 FormBuilderCheckboxGroup(
          //separator: Text('test'),
          wrapSpacing: 0,
          materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
          controlAffinity: ControlAffinity.leading,
          initialValue: questionnaire.optionIds,
          onChanged: (value) => questionnaireController.addQuestionnaireToDB(
              context, clientModel, questionnaireModel, question, value),
          validator: (value) {
            if ((question.mandatory == 1 && value.last == 0)) {
              return 'Cette question est obligatoire!';
            } else {
              return null;
            }
          },
          orientation: OptionsOrientation.vertical,
          name: 'Change',
          decoration: InputDecoration(
            isDense: true,

            border: InputBorder.none,
            label: Container(
              child: Text(
                (question.mandatory == 1)
                    ? question.title + " *"
                    : question.title,
                
                style: TextStyle(
                  fontWeight: FontWeight.bold,
                  fontFamily: 'Montserrat',
                  fontSize: 22,
                  color: AppThemes.color9,
                ),
              ),
            ),

            // labelText: (question.mandatory == 1)
            //     ? question.title + " *"
            //     : question.title,
            // labelStyle: TextStyle(
            //   fontWeight: FontWeight.bold,
            //   fontFamily: 'Montserrat',
            //   fontSize: 20,
            //   color: AppThemes.color9,
            // ),
          ),
          checkColor: Colors.white,
          options: question.options.map((option) {
            return FormBuilderFieldOption(
                value: option.value,
                child: QuestionnaireItemTextWidget(
                  itemtext: option.title,
                ));
          }).toList()),
```
here's the  preview :
![screen error](https://user-images.githubusercontent.com/29239669/161971024-5c82bb38-3592-42b4-8787-e2b16dce8662.png)

**Comment by danvick** [comment]
This may be more of a problem with Flutter's InputDecoration in general, than something to do with the package.

**Comment by kader46** [comment]
> This may be more of a problem with Flutter's InputDecoration in general, than something to do with the package.

Hello @danvick, So what's the solution to use multi line on this package ?

**Comment by foxmedo** [comment]
Hi @danvick  we are facing to the same issue, get a solution to this issue will really help us and other people 
i'm adding my voice to  @kader46

**Comment by danvick** [comment]
As I had said before this is not an issue for this repo, but a [well-known issue in Flutter](https://github.com/flutter/flutter/issues/30439) so it cannot be solved for this package in isolation.

That being said, what I do in my own projects when I face this issue is not to have the label in the `InputDecoration` but to have a separate Text widget for the label. It may not be as pretty as labels are intended to be but it works for me:

```Dart
Column(
    children: [
        Text('My very very veeeeeeeery long label'),
        FormBuilderCheckboxGroup(
               decoration: InputDecoration(
                    isDense: true,
                    border: InputBorder.none,
                    // No label
                ),
        ),
    ]
),
```

**Comment by kader46** [comment]
> As I had said before this is not an issue for this repo, but a [well-known issue in Flutter](https://github.com/flutter/flutter/issues/30439) so it cannot be solved for this package in isolation.
> 
> That being said, what I do in my own projects when I face this issue is not to have the label in the `InputDecoration` but to have a separate Text widget for the label. It may not be as pretty as labels are intended to be but it works for me:
> 
> ```dart
> Column(
>     children: [
>         Text('My very very veeeeeeeery long label'),
>         FormBuilderCheckboxGroup(
>                decoration: InputDecoration(
>                     isDense: true,
>                     border: InputBorder.none,
>                     // No label
>                 ),
>         ),
>     ]
> ),
> ```

Worked fine for me, Thank you @danvick
